DROP DIRECTORY XXD_GL_ACCT_CONTROL_ARC_DIR;

--
-- XXD_GL_ACCT_CONTROL_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_ACCT_CONTROL_ARC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/GL/NatAccount/Archive';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_GL_ACCT_CONTROL_ARC_DIR TO APPS WITH GRANT OPTION;
