DROP DIRECTORY XXD_O9_OUT_TRANSACTIONAL_DATA;

--
-- XXD_O9_OUT_TRANSACTIONAL_DATA  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_O9_OUT_TRANSACTIONAL_DATA AS 
'/f01/EBSPROD/Outbound/Integrations/O9/transactional_data';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_O9_OUT_TRANSACTIONAL_DATA TO APPS WITH GRANT OPTION;
