DROP DIRECTORY XXD_AR_CONS_INV_GE_DIR;

--
-- XXD_AR_CONS_INV_GE_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AR_CONS_INV_GE_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/GlobalE';


GRANT READ, WRITE ON DIRECTORY XXD_AR_CONS_INV_GE_DIR TO APPS;
