DROP DIRECTORY XXD_PROJECT_INVOICES;

--
-- XXD_PROJECT_INVOICES  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_PROJECT_INVOICES AS 
'/f01/EBSPROD/Outbound/Integrations/Project_Invoices';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_PROJECT_INVOICES TO APPS;
