DROP DIRECTORY XXD_ONT_DXLAB_INV_DIR;

--
-- XXD_ONT_DXLAB_INV_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_ONT_DXLAB_INV_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/DXLAB/InventoryFeed';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_ONT_DXLAB_INV_DIR TO APPS WITH GRANT OPTION;
