DROP DIRECTORY XXD_CST_DUTY_ELE_REP_DIR;

--
-- XXD_CST_DUTY_ELE_REP_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_CST_DUTY_ELE_REP_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Report';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_CST_DUTY_ELE_REP_DIR TO APPS WITH GRANT OPTION;
