DROP DIRECTORY XXDO_COST_UPLOAD_DIR;

--
-- XXDO_COST_UPLOAD_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_COST_UPLOAD_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Costing';


GRANT READ, WRITE ON DIRECTORY XXDO_COST_UPLOAD_DIR TO APPS;
