DROP DIRECTORY XXD_AP_INV_UPLOAD_EXC_DIR;

--
-- XXD_AP_INV_UPLOAD_EXC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AP_INV_UPLOAD_EXC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Pagero/AP/Archive';
