DROP DIRECTORY XXD_HYP_FORECAST_INB_DIR;

--
-- XXD_HYP_FORECAST_INB_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_HYP_FORECAST_INB_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Inbound/Hyperion';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_HYP_FORECAST_INB_DIR TO APPS WITH GRANT OPTION;
