DROP DIRECTORY XXD_AR_RCPT_RECON_BL;

--
-- XXD_AR_RCPT_RECON_BL  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AR_RCPT_RECON_BL AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/RcptRecon';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_AR_RCPT_RECON_BL TO APPS WITH GRANT OPTION;
