DROP DIRECTORY XXD_HYPERION_INTG;

--
-- XXD_HYPERION_INTG  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_HYPERION_INTG AS 
'/f01/EBSPROD/Outbound/Integrations/Hyperion';


GRANT READ, WRITE ON DIRECTORY XXD_HYPERION_INTG TO APPS;
