DROP DIRECTORY XXDO_C2B_OUT_DIR;

--
-- XXDO_C2B_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_C2B_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/C2B';


GRANT READ, WRITE ON DIRECTORY XXDO_C2B_OUT_DIR TO APPS;
