DROP DIRECTORY XXD_OE_LOYALTY_ARC_DIR;

--
-- XXD_OE_LOYALTY_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_OE_LOYALTY_ARC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Reports/Loyalty/Archive';
