DROP DIRECTORY XXD_HYP_FORECAST_EXC_DIR;

--
-- XXD_HYP_FORECAST_EXC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_HYP_FORECAST_EXC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Inbound/Hyperion/Exception';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_HYP_FORECAST_EXC_DIR TO APPS WITH GRANT OPTION;
