DROP DIRECTORY XXD_AP_INV_UPLOAD_ATTACH_DIR;

--
-- XXD_AP_INV_UPLOAD_ATTACH_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AP_INV_UPLOAD_ATTACH_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Pagero/AP/Archive/Attachment';
