DROP DIRECTORY XXDOAR_MICRFILE_UPLOAD;

--
-- XXDOAR_MICRFILE_UPLOAD  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDOAR_MICRFILE_UPLOAD AS 
'/f01/EBSPROD/Inbound/Integrations/Lockbox';


GRANT READ, WRITE ON DIRECTORY XXDOAR_MICRFILE_UPLOAD TO PUBLIC;
