DROP DIRECTORY XXD_AP_INV_UPLOAD_INB_DIR;

--
-- XXD_AP_INV_UPLOAD_INB_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AP_INV_UPLOAD_INB_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Pagero/AP';
