DROP DIRECTORY XXD_OM_OU_ALIGN_INB_ARC_DIR;

--
-- XXD_OM_OU_ALIGN_INB_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_OM_OU_ALIGN_INB_ARC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/OM/OU_ALIGN/Archive';
