DROP DIRECTORY XXD_GL_CCID_UPLOAD_ARC_DIR;

--
-- XXD_GL_CCID_UPLOAD_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_CCID_UPLOAD_ARC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/GL/CCID/Archive';
