DROP DIRECTORY XXD_CST_DUTY_CORR_ARC_DIR;

--
-- XXD_CST_DUTY_CORR_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_CST_DUTY_CORR_ARC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Inbound/CostUpdate/Archive';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_CST_DUTY_CORR_ARC_DIR TO APPS WITH GRANT OPTION;
