DROP DIRECTORY XXD_OE_CAN_LOYALTY_COUPON_DIR;

--
-- XXD_OE_CAN_LOYALTY_COUPON_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_OE_CAN_LOYALTY_COUPON_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Reports/Loyalty/Coupon/Can';
