DROP DIRECTORY XXDO_GL_MAN_REFUND_OUT_DIR;

--
-- XXDO_GL_MAN_REFUND_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_GL_MAN_REFUND_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/GLManualRefunds';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDO_GL_MAN_REFUND_OUT_DIR TO APPS WITH GRANT OPTION;
