DROP DIRECTORY XXDO_ONT_SHIP_CONF_FILE_DIR;

--
-- XXDO_ONT_SHIP_CONF_FILE_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_ONT_SHIP_CONF_FILE_DIR AS 
'/f01/EBSPROD/highjump/shipconfirm';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDO_ONT_SHIP_CONF_FILE_DIR TO APPS WITH GRANT OPTION;
