DROP DIRECTORY XXDOAR_B2B_STMT_OUTBOUND;

--
-- XXDOAR_B2B_STMT_OUTBOUND  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDOAR_B2B_STMT_OUTBOUND AS 
'/f01/EBSPROD/Outbound/Integrations/BillTrust/Statements';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDOAR_B2B_STMT_OUTBOUND TO APPS WITH GRANT OPTION;
