DROP DIRECTORY XXD_CST_DUTY_ELE_EXC_DIR;

--
-- XXD_CST_DUTY_ELE_EXC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_CST_DUTY_ELE_EXC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Exception';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_CST_DUTY_ELE_EXC_DIR TO APPS WITH GRANT OPTION;
