DROP DIRECTORY XXD_PGR_APP_RESP_INB_DIR;

--
-- XXD_PGR_APP_RESP_INB_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_PGR_APP_RESP_INB_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Pagero/APP_RESP';
