DROP DIRECTORY XXD_FND_DOCUMENTS;

--
-- XXD_FND_DOCUMENTS  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_FND_DOCUMENTS AS 
'/f01/EBSPROD/Outbound/Integrations/FND_Documents';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_FND_DOCUMENTS TO APPS;
