DROP DIRECTORY XXD_GL_AAR_SL_DIR;

--
-- XXD_GL_AAR_SL_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_AAR_SL_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/Subledgers';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_GL_AAR_SL_DIR TO APPS WITH GRANT OPTION;
