DROP DIRECTORY XXD_PO_PAST_DUE_DIR;

--
-- XXD_PO_PAST_DUE_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_PO_PAST_DUE_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/PastDue';


GRANT READ, WRITE ON DIRECTORY XXD_PO_PAST_DUE_DIR TO APPS;

GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_PO_PAST_DUE_DIR TO SYSTEM WITH GRANT OPTION;
