DROP DIRECTORY XXD_CONCURACC_BL_ARC_DIR;

--
-- XXD_CONCURACC_BL_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_CONCURACC_BL_ARC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Reports/Concur/Archive';
