DROP DIRECTORY XXD_ONT_REPORT_OUT_DIR;

--
-- XXD_ONT_REPORT_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_ONT_REPORT_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/ONT';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_ONT_REPORT_OUT_DIR TO APPS WITH GRANT OPTION;
