DROP DIRECTORY XXD_GL_ACCT_BALANCE_DIR;

--
-- XXD_GL_ACCT_BALANCE_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_ACCT_BALANCE_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/GLAccountBal';
