DROP DIRECTORY XXD_OM_OU_ALIGN_INB_DIR;

--
-- XXD_OM_OU_ALIGN_INB_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_OM_OU_ALIGN_INB_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/OM/OU_ALIGN';
