DROP DIRECTORY XXDO_ONT_RA_RECEIPT_FILE_DIR;

--
-- XXDO_ONT_RA_RECEIPT_FILE_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_ONT_RA_RECEIPT_FILE_DIR AS 
'/f01/EBSPROD/highjump/rareceipt';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDO_ONT_RA_RECEIPT_FILE_DIR TO APPS WITH GRANT OPTION;
