DROP DIRECTORY XXD_GL_ACCT_CONTROL_EXC_DIR;

--
-- XXD_GL_ACCT_CONTROL_EXC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_ACCT_CONTROL_EXC_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/GL/NatAccount/Exception';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_GL_ACCT_CONTROL_EXC_DIR TO APPS WITH GRANT OPTION;
