DROP DIRECTORY XXD_PO_FORECAST_REP_DIR;

--
-- XXD_PO_FORECAST_REP_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_PO_FORECAST_REP_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Report/POForeCast';
