DROP DIRECTORY XXDO_EDI846_INC_EXU_SPS;

--
-- XXDO_EDI846_INC_EXU_SPS  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_EDI846_INC_EXU_SPS AS 
'/f01/EBSPROD/Outbound/Integrations/SPS/EDI846';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDO_EDI846_INC_EXU_SPS TO APPS WITH GRANT OPTION;
