DROP DIRECTORY XXD_GL_ACCT_CONTROL_INB_DIR;

--
-- XXD_GL_ACCT_CONTROL_INB_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_ACCT_CONTROL_INB_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/GL/NatAccount';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_GL_ACCT_CONTROL_INB_DIR TO APPS WITH GRANT OPTION;
