DROP DIRECTORY XXD_CE_CF_STATEMENTS_DIR;

--
-- XXD_CE_CF_STATEMENTS_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_CE_CF_STATEMENTS_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/Cashflow_Statements';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_CE_CF_STATEMENTS_DIR TO APPS WITH GRANT OPTION;
