DROP DIRECTORY XXD_GL_LX_REPORTS;

--
-- XXD_GL_LX_REPORTS  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_GL_LX_REPORTS AS 
'/f01/EBSPROD/Inbound/Integrations/GL/LX_REPORTS';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_GL_LX_REPORTS TO APPS WITH GRANT OPTION;

GRANT READ, WRITE ON DIRECTORY XXD_GL_LX_REPORTS TO PUBLIC;
