DROP DIRECTORY XXD_O9_OUT_MASTER_DATA;

--
-- XXD_O9_OUT_MASTER_DATA  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_O9_OUT_MASTER_DATA AS 
'/f01/EBSPROD/Outbound/Integrations/O9/master_data';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_O9_OUT_MASTER_DATA TO APPS WITH GRANT OPTION;
