DROP DIRECTORY XXD_HYP_FORECAST_REP_DIR;

--
-- XXD_HYP_FORECAST_REP_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_HYP_FORECAST_REP_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Duty/Inbound/Hyperion/Report';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXD_HYP_FORECAST_REP_DIR TO APPS WITH GRANT OPTION;
