DROP DIRECTORY XXD_AP_MTD_REPORT_OUT_DIR;

--
-- XXD_AP_MTD_REPORT_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AP_MTD_REPORT_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/VAT/EMEA/AP';
