DROP DIRECTORY XXDO_PO_ASN_RECEIPT_FILE_DIR;

--
-- XXDO_PO_ASN_RECEIPT_FILE_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_PO_ASN_RECEIPT_FILE_DIR AS 
'/f01/EBSPROD/highjump/asnreceipt';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDO_PO_ASN_RECEIPT_FILE_DIR TO APPS WITH GRANT OPTION;
