DROP DIRECTORY XXDO_REPORTS_CB_OUT_DIR;

--
-- XXDO_REPORTS_CB_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_REPORTS_CB_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/Chargeback';


GRANT READ, WRITE ON DIRECTORY XXDO_REPORTS_CB_OUT_DIR TO APPS;
