DROP DIRECTORY XXD_AP_SDI_CB_OUT_ARC_DIR;

--
-- XXD_AP_SDI_CB_OUT_ARC_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_AP_SDI_CB_OUT_ARC_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Pagero/AP/CB/Archive';
