DROP DIRECTORY XXDO_AR_ECOMM_RCT_REP_OUT_DIR;

--
-- XXDO_AR_ECOMM_RCT_REP_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXDO_AR_ECOMM_RCT_REP_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/eCommReceipts';


GRANT EXECUTE, READ, WRITE ON DIRECTORY XXDO_AR_ECOMM_RCT_REP_OUT_DIR TO APPS WITH GRANT OPTION;
