DROP DIRECTORY XXD_VT_CONSOL_REPORT_OUT_DIR;

--
-- XXD_VT_CONSOL_REPORT_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_VT_CONSOL_REPORT_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/VAT/EMEA/CONSOLIDATED';
