DROP DIRECTORY XXD_INTRA_MTD_REPORT_OUT_DIR;

--
-- XXD_INTRA_MTD_REPORT_OUT_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_INTRA_MTD_REPORT_OUT_DIR AS 
'/f01/EBSPROD/Outbound/Integrations/Reports/VAT/EMEA/INTRASTAT';
