DROP DIRECTORY XXD_CONCURACC_BL_INB_DIR;

--
-- XXD_CONCURACC_BL_INB_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_CONCURACC_BL_INB_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Reports/Concur';
