DROP DIRECTORY XXD_OE_US_LOYALTY_PTS_DIR;

--
-- XXD_OE_US_LOYALTY_PTS_DIR  (Directory) 
--
CREATE OR REPLACE DIRECTORY 
XXD_OE_US_LOYALTY_PTS_DIR AS 
'/f01/EBSPROD/Inbound/Integrations/Reports/Loyalty/Points/US';
