--
-- XXDOCST_ITEM_COST  (Table) 
--
CREATE TABLE XXDO.XXDOCST_ITEM_COST
(
  INVENTORY_ITEM_ID      NUMBER,
  CONCATENATED_SEGMENTS  VARCHAR2(122 BYTE),
  STYLE                  VARCHAR2(40 BYTE),
  COLOR                  VARCHAR2(40 BYTE),
  SZE                    VARCHAR2(40 BYTE),
  BRAND                  VARCHAR2(40 BYTE),
  INTRO_SEASON           VARCHAR2(40 BYTE),
  ORGANIZATION_ID        NUMBER,
  MAT_COST               NUMBER,
  FIRST_COST_DUTY        NUMBER,
  DUTY_COST              NUMBER,
  DUTY_RATE              NUMBER,
  FREIGHT_COST           NUMBER,
  MATERIAL_OH            NUMBER,
  LANDED_COST            NUMBER,
  UK2_MAT_COST           NUMBER,
  OLDMATERIALCOST        NUMBER,
  OLD_DUTY_COST          NUMBER,
  OLD_DUTY_RATE          NUMBER,
  OLD_FREIGHT_COST       NUMBER,
  MACAU_COST             NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
