--
-- XXDO_CIT_INBND_AR_ACT_DTL_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_CIT_INBND_AR_ACT_DTL_STG
(
  CLIENT_GROUP_NUMBER     VARCHAR2(250 BYTE),
  EXTRACT_DATE            VARCHAR2(50 BYTE),
  CLIENT_NUMBER           VARCHAR2(250 BYTE),
  CIT_CUSTOMER_NUMBER     VARCHAR2(250 BYTE),
  CLIENT_CUSTOMER_NUMBER  VARCHAR2(250 BYTE),
  CUSTOMER_NAME           VARCHAR2(250 BYTE),
  CUSTOMER_ADDRESS1       VARCHAR2(250 BYTE),
  CUSTOMER_ADDRESS2       VARCHAR2(250 BYTE),
  CUSTOMER_CITY           VARCHAR2(50 BYTE),
  CUSTOMER_STATE          VARCHAR2(50 BYTE),
  CUSTOMER_ZIP            VARCHAR2(50 BYTE),
  CUSTOMER_COUNTRY        VARCHAR2(50 BYTE),
  ACTIVITY_INDICATOR      VARCHAR2(50 BYTE),
  ACTIVITY_DATE           VARCHAR2(50 BYTE),
  CHECK_NUMBER            VARCHAR2(50 BYTE),
  CHECK_AMOUNT            NUMBER,
  CUST_DM_DATE            VARCHAR2(50 BYTE),
  CUST_DM_NUM             VARCHAR2(50 BYTE),
  CUST_STORE_NUM          VARCHAR2(50 BYTE),
  AR_REASON_CODE          VARCHAR2(50 BYTE),
  AR_TRANSACTION_CODE     VARCHAR2(50 BYTE),
  ITEM_REFERENCE          VARCHAR2(50 BYTE),
  ORIG_ITEM_REF           VARCHAR2(50 BYTE),
  TRX_DATE                VARCHAR2(50 BYTE),
  GROSS_AMOUNT            NUMBER,
  DB_CR_IND               VARCHAR2(50 BYTE),
  DUE_DATE                VARCHAR2(50 BYTE),
  DISCOUNT_AMOUNT         NUMBER,
  NET_ITEM_AMOUNT         NUMBER,
  ERROR_MESSAGE           VARCHAR2(2000 BYTE),
  STATUS                  VARCHAR2(10 BYTE),
  CREATION_DATE           DATE,
  CREATED_BY              NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATED_BY         NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_CIT_INBND_AR_ACT_DTL_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_CIT_INBND_AR_ACT_DTL_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_CIT_INBND_AR_ACT_DTL_STG FOR XXDO.XXDO_CIT_INBND_AR_ACT_DTL_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_CIT_INBND_AR_ACT_DTL_STG TO APPS
/
