--
-- XXD_AR_VAT_RPT_T  (Table) 
--
CREATE TABLE XXDO.XXD_AR_VAT_RPT_T
(
  SOURCE_TRXN              VARCHAR2(60 BYTE),
  TRANSACTION_TYPE         VARCHAR2(60 BYTE),
  INVOICE_NUMBER           VARCHAR2(60 BYTE),
  ORDER_TYPE               VARCHAR2(100 BYTE),
  BILL_TO_CUSTOMER_ID      NUMBER,
  BILL_TO_SITE_USE_ID      NUMBER,
  SHIP_TO_SITE_USE_ID      NUMBER,
  INVOICE_CURRENCY_CODE    VARCHAR2(60 BYTE),
  TRX_DATE                 DATE,
  TO_GBP_EXCHG_RT_CORP     NUMBER,
  TO_EUR_EXCHG_RT_CORP     NUMBER,
  TO_USD_EXCHG_RT_CORP     NUMBER,
  WAREHOUSE_NAME           VARCHAR2(60 BYTE),
  VAT_NUMBER               VARCHAR2(60 BYTE),
  INVOICED_QTY             NUMBER,
  GL_TAX_ACCOUNT           VARCHAR2(60 BYTE),
  TAX_RATE_CODE            VARCHAR2(60 BYTE),
  TAX_REGIME_CODE          VARCHAR2(60 BYTE),
  INVOICE_TOTAL            NUMBER,
  INVENTORY_ITEM_ID        NUMBER,
  STYLE                    VARCHAR2(60 BYTE),
  COLOR                    VARCHAR2(60 BYTE),
  COMMODITY_CODE           VARCHAR2(60 BYTE),
  DIVISION                 VARCHAR2(60 BYTE),
  DEPARTMENT               VARCHAR2(60 BYTE),
  PRE_CONV_INV_AMT         NUMBER,
  PRE_CONV_TAX_AMT         NUMBER,
  DESCRIPTION              VARCHAR2(360 BYTE),
  GL_ENTITY_CODE           VARCHAR2(60 BYTE),
  DOCUMENT_CLASS           VARCHAR2(80 BYTE),
  REASON_CODE              VARCHAR2(240 BYTE),
  WAREHOUSE_ID             NUMBER,
  LINE_NUMBER              NUMBER,
  GL_DATE                  DATE,
  GL_ACCOUNT               VARCHAR2(60 BYTE),
  GL_ACCOUNT_DESC          VARCHAR2(360 BYTE),
  GL_GEO_CODE              VARCHAR2(60 BYTE),
  REFERENCE_NUMBER         VARCHAR2(60 BYTE),
  ORIG_WH_NAME             VARCHAR2(60 BYTE),
  TAX_RATE                 NUMBER,
  ORG_ID                   NUMBER,
  ORG_NAME                 VARCHAR2(60 BYTE),
  CUSTOMER_NUMBER          VARCHAR2(120 BYTE),
  SELL_TO_CUSTOMER_NAME    VARCHAR2(120 BYTE),
  BILL_VAT_NUMBER          VARCHAR2(60 BYTE),
  SHIP_VAT_NUMBER          VARCHAR2(60 BYTE),
  INVOICE_DATE             DATE,
  SHIP_TO_CITY             VARCHAR2(60 BYTE),
  SHIP_TO_STATE            VARCHAR2(60 BYTE),
  SHIP_TO_COUNTRY          VARCHAR2(60 BYTE),
  SHIP_TO_PROVINCE         VARCHAR2(60 BYTE),
  SHIP_TO_POSTAL_CODE      VARCHAR2(60 BYTE),
  BILL_TO_COUNTRY          VARCHAR2(60 BYTE),
  SHIP_FROM_COUNTRY        VARCHAR2(60 BYTE),
  GL_PERIOD                VARCHAR2(60 BYTE),
  GL_COUNTRY_DESC          VARCHAR2(100 BYTE),
  CREATION_DATE            DATE,
  CREATED_BY               NUMBER,
  LAST_UPDATE_DATE         DATE,
  LAST_UPDATED_BY          NUMBER,
  REQUEST_ID               NUMBER,
  LINE_GBP_INV_AMT         NUMBER,
  LINE_EUR_INV_AMT         NUMBER,
  LINE_USD_INV_AMT         NUMBER,
  LINE_USD_TAX_AMT         NUMBER,
  LINE_EUR_TAX_AMT         NUMBER,
  LINE_GBP_TAX_AMT         NUMBER,
  TRX_ID                   NUMBER,
  TRX_LINE_ID              NUMBER,
  ADJ_TRX_DATE             DATE,
  GAPLESS_SEQUENCE_NUMBER  VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
