--
-- XXD_ONT_SHADOW_BULK_ORDERS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_SHADOW_BULK_ORDERS_T
(
  RECORD_SET         NUMBER,
  RECORD_ID          NUMBER,
  ORG_ID             NUMBER,
  OE_HEADER_ID       NUMBER,
  OE_ORDER_NUMBER    NUMBER,
  CUST_ACCOUNT_ID    NUMBER,
  OE_LINE_ID         NUMBER,
  SHIP_FROM_ORG_ID   NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  BATCH_ID           NUMBER,
  STATUS             VARCHAR2(10 BYTE),
  ERR_MSG            VARCHAR2(4000 BYTE),
  REQUEST_ID         NUMBER,
  CUST_PO_NUMBER     VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
