--
-- XXDO_MAIN_DATA  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXDO_MAIN_DATA
(
  VENDOR_NAME           VARCHAR2(240 BYTE),
  PO_DATE               DATE,
  PO_NUMBER             VARCHAR2(20 BYTE),
  SHIP_TO_LOCATION_ID   NUMBER,
  STYLE                 VARCHAR2(40 BYTE),
  STYLE_NAME            VARCHAR2(240 BYTE),
  COLOR                 VARCHAR2(40 BYTE),
  ITEM_SIZE             VARCHAR2(40 BYTE),
  EX_FACTORY_DATE       DATE,
  CONF_EX_FACTORY_DATE  DATE,
  PROMISED_DATE         DATE,
  DEST                  VARCHAR2(240 BYTE),
  BRAND                 VARCHAR2(40 BYTE),
  PO_QTY                NUMBER,
  RCV_QTY               NUMBER,
  BAL_QTY               NUMBER,
  UNIT_PRICE            NUMBER,
  BUY_MONTH             VARCHAR2(150 BYTE),
  BUY_SEASON            VARCHAR2(150 BYTE),
  FACILITY              VARCHAR2(50 BYTE),
  ETD_PORT              VARCHAR2(150 BYTE),
  TOTAL_PRICE           NUMBER,
  PRODUCT_CATEGORY      VARCHAR2(100 BYTE),
  PO_TYPE               VARCHAR2(100 BYTE),
  COUNTRY               VARCHAR2(100 BYTE),
  GLOBAL_SURCHARGE      VARCHAR2(100 BYTE),
  SHIP_TO_ID_SURCHARGE  VARCHAR2(100 BYTE),
  BLENDED_FOB           VARCHAR2(100 BYTE),
  GTN_TRANSFER_FLAG     VARCHAR2(100 BYTE),
  SO_NUMBER             VARCHAR2(100 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE
/


--
-- XXDO_MAIN_DATA_N1  (Index) 
--
--  Dependencies: 
--   XXDO_MAIN_DATA (Table)
--
CREATE INDEX XXDO.XXDO_MAIN_DATA_N1 ON XXDO.XXDO_MAIN_DATA
(PO_NUMBER, STYLE, COLOR, ITEM_SIZE, EX_FACTORY_DATE, 
CONF_EX_FACTORY_DATE, PROMISED_DATE, SHIP_TO_LOCATION_ID, UNIT_PRICE)
/

--
-- XXDO_MAIN_DATA_N2  (Index) 
--
--  Dependencies: 
--   XXDO_MAIN_DATA (Table)
--
CREATE INDEX APPS.XXDO_MAIN_DATA_N2 ON XXDO.XXDO_MAIN_DATA
(ITEM_SIZE)
/

--
-- XXDO_MAIN_DATA  (Synonym) 
--
--  Dependencies: 
--   XXDO_MAIN_DATA (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_MAIN_DATA FOR XXDO.XXDO_MAIN_DATA
/
