--
-- XXD_CST_DUTY_ELE_INB_STG_TR_T  (Table) 
--
CREATE TABLE XXDO.XXD_CST_DUTY_ELE_INB_STG_TR_T
(
  STYLE_NUMBER             VARCHAR2(1000 BYTE),
  STYLE_DESCRIPTION        VARCHAR2(4000 BYTE),
  COUNTRY_OF_ORIGIN        VARCHAR2(1000 BYTE),
  HTS_CODE                 VARCHAR2(1000 BYTE),
  DUTY_RATE                VARCHAR2(1000 BYTE),
  ADDITIONAL_DUTY          VARCHAR2(1000 BYTE),
  APPLICABLE_UOM           VARCHAR2(1000 BYTE),
  DESTINATION_COUNTRY      VARCHAR2(1000 BYTE),
  PREFERENTIAL_RATE        VARCHAR2(1000 BYTE),
  PR_START_DATE            VARCHAR2(1000 BYTE),
  PR_END_DATE              VARCHAR2(1000 BYTE),
  DEFAULT_DUTY_RATE        VARCHAR2(1000 BYTE),
  DEFAULT_ADDITIONAL_DUTY  VARCHAR2(1000 BYTE),
  DEFAULT_APPLICABLE_UOM   VARCHAR2(1000 BYTE),
  EFFECTIVE_START_DATE     VARCHAR2(1000 BYTE),
  EFFECTIVE_END_DATE       VARCHAR2(1000 BYTE),
  DEPARTMENT               VARCHAR2(1000 BYTE),
  DATA_SOURCE              VARCHAR2(1000 BYTE),
  OTHER_VENDOR_SITES       VARCHAR2(1000 BYTE),
  INTRO_SEASON             VARCHAR2(1000 BYTE),
  SIZE_RUN                 VARCHAR2(1000 BYTE),
  PD_ASSIGNED              VARCHAR2(1000 BYTE),
  COLLECTION               VARCHAR2(1000 BYTE),
  TARRIF_DESCRIPTION       VARCHAR2(4000 BYTE),
  ITEMCATEGORY             VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD1        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD2        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD3        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD4        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD5        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD6        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD7        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD8        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD9        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD10       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD11       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD12       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD13       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD14       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD15       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD16       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD17       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD18       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD19       VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD20       VARCHAR2(1000 BYTE),
  REGION                   VARCHAR2(1000 BYTE),
  COUNTRY                  VARCHAR2(1000 BYTE),
  COUNTRY_CODE             VARCHAR2(1000 BYTE),
  OPERATING_UNIT           VARCHAR2(1000 BYTE),
  ORGANIZATION_CODE        VARCHAR2(1000 BYTE),
  INVENTORY_ORG_ID         VARCHAR2(1000 BYTE),
  COO_PRECEDENCE           NUMBER,
  COO_PREFERENCE_FLAG      VARCHAR2(1 BYTE),
  ACTIVE_FLAG              VARCHAR2(1 BYTE)     DEFAULT 'Y',
  PREFERENTIAL_DUTY_FLAG   VARCHAR2(1 BYTE),
  REC_STATUS               VARCHAR2(1 BYTE)     DEFAULT 'N',
  ERROR_MSG                VARCHAR2(4000 BYTE),
  CREATED_BY               NUMBER,
  CREATION_DATE            DATE,
  LAST_UPDATE_DATE         DATE,
  LAST_UPDATED_BY          NUMBER,
  REQUEST_ID               NUMBER,
  FILENAME                 VARCHAR2(1000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_CST_DUTY_ELE_INB_STG_N1  (Index) 
--
--  Dependencies: 
--   XXD_CST_DUTY_ELE_INB_STG_TR_T (Table)
--
CREATE INDEX XXDO.XXD_CST_DUTY_ELE_INB_STG_N1 ON XXDO.XXD_CST_DUTY_ELE_INB_STG_TR_T
(ACTIVE_FLAG, REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_CST_DUTY_ELE_INB_STG_TR_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CST_DUTY_ELE_INB_STG_TR_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_CST_DUTY_ELE_INB_STG_TR_T FOR XXDO.XXD_CST_DUTY_ELE_INB_STG_TR_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_CST_DUTY_ELE_INB_STG_TR_T TO APPS
/
