--
-- XXD_OM_ODC_US_TRAN_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_OM_ODC_US_TRAN_GT
(
  REQUEST_ID            NUMBER,
  INVENTORY_ITEM_ID     NUMBER,
  COMMERCIAL_INVOICE    VARCHAR2(25 BYTE),
  PO_HEADER_ID          NUMBER,
  PO_NUMBER             VARCHAR2(140 BYTE),
  TOT_PO_QTY            NUMBER,
  PRICE                 NUMBER,
  PO_RECEIPT_DATE       DATE,
  PO_RECEIVED_LOCATION  VARCHAR2(100 BYTE),
  UNITS_RECEIVED        NUMBER,
  ITEM_STYLE            VARCHAR2(240 BYTE),
  ORDER_NUMBER          NUMBER,
  ITEM_COLOR            VARCHAR2(240 BYTE),
  ITEM_SIZE             VARCHAR2(240 BYTE),
  CUST_PO_NUMBER        VARCHAR2(240 BYTE),
  SHIPPING_UNIT         NUMBER,
  SHIPPING_ORG          VARCHAR2(100 BYTE),
  ITEM_NUMBER           VARCHAR2(240 BYTE),
  ASN_PO_EXISTS_FLAG    VARCHAR2(1 BYTE),
  ITEM_EXISTS_LKP       VARCHAR2(1 BYTE),
  EMAIL_ID              VARCHAR2(1000 BYTE),
  FILE_NAME             VARCHAR2(1000 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
