--
-- XXDOOD_EBSINTEGRATION_CRM_HIST  (Table) 
--
CREATE TABLE XXDO.XXDOOD_EBSINTEGRATION_CRM_HIST
(
  INTEGRATIONID    NUMBER,
  EBSID            NUMBER,
  RECORDTYPE       VARCHAR2(50 BYTE),
  LASTUPDATE       DATE,
  ACCOUNTNAME      VARCHAR2(200 BYTE),
  ACCOUNTNO        NUMBER,
  BRANDREP         VARCHAR2(500 BYTE),
  STATE            VARCHAR2(10 BYTE),
  MAINPHONE        VARCHAR2(50 BYTE),
  MAINFAX          VARCHAR2(50 BYTE),
  ZIPCODE          VARCHAR2(20 BYTE),
  EDI810           CHAR(1 BYTE),
  EDI850           CHAR(1 BYTE),
  EDI860           CHAR(1 BYTE),
  EDI856           CHAR(1 BYTE),
  COUNTRY          VARCHAR2(100 BYTE),
  ACCOUNTDBA       VARCHAR2(200 BYTE),
  ACTIVE           CHAR(1 BYTE),
  PROFILECLASS     VARCHAR2(50 BYTE),
  ZEROFRIEGHTFLAG  CHAR(1 BYTE),
  FIRSTNAME        VARCHAR2(50 BYTE),
  LASTNAME         VARCHAR2(50 BYTE),
  JOBTITLE         VARCHAR2(50 BYTE),
  CELLPHONE        VARCHAR2(50 BYTE),
  CITY             VARCHAR2(100 BYTE),
  ERRORFLAG        NUMBER,
  TRIGGERNAME      VARCHAR2(100 BYTE),
  SOURCEID         VARCHAR2(100 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOOD_EBSINTEGRATION_CRM_HIST  (Synonym) 
--
--  Dependencies: 
--   XXDOOD_EBSINTEGRATION_CRM_HIST (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOOD_EBSINTEGRATION_CRM_HIST FOR XXDO.XXDOOD_EBSINTEGRATION_CRM_HIST
/


--
-- XXDOOD_EBSINTEGRATION_CRM_HIST  (Synonym) 
--
--  Dependencies: 
--   XXDOOD_EBSINTEGRATION_CRM_HIST (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOOD_EBSINTEGRATION_CRM_HIST FOR XXDO.XXDOOD_EBSINTEGRATION_CRM_HIST
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOOD_EBSINTEGRATION_CRM_HIST TO APPS
/

GRANT SELECT ON XXDO.XXDOOD_EBSINTEGRATION_CRM_HIST TO APPSRO WITH GRANT OPTION
/
