--
-- XXD_AMS_APPROVAL_UPLOAD_TBL  (Table) 
--
CREATE TABLE XXDO.XXD_AMS_APPROVAL_UPLOAD_TBL
(
  OPERATING_UNIT         VARCHAR2(100 BYTE),
  OLD_APPR_RULE_NAME     VARCHAR2(200 BYTE),
  APPROVAL_RULE_NAME     VARCHAR2(200 BYTE),
  APPROVAL_TYPE          VARCHAR2(100 BYTE),
  CLAIM_TYPE             VARCHAR2(100 BYTE),
  REASON                 VARCHAR2(100 BYTE),
  START_DATE             DATE,
  END_DATE               DATE,
  CURRENCY               VARCHAR2(30 BYTE),
  MINIMUM_AMOUNT         NUMBER,
  MAXIMUM_AMOUNT         NUMBER,
  DESCRIPTION            VARCHAR2(240 BYTE),
  APPROVER_ORDER         NUMBER,
  APPROVER_TYPE          VARCHAR2(100 BYTE),
  APPROVER_USER_ROLE     VARCHAR2(100 BYTE),
  APPROVER_START_DATE    DATE,
  APPROVER_END_DATE      DATE,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  ATTRIBUTE_NUM1         NUMBER,
  ATTRIBUTE_NUM2         NUMBER,
  ATTRIBUTE_NUM3         NUMBER,
  ATTRIBUTE_NUM4         NUMBER,
  ATTRIBUTE_CHR1         VARCHAR2(100 BYTE),
  ATTRIBUTE_CHR2         VARCHAR2(100 BYTE),
  ATTRIBUTE_CHR3         VARCHAR2(100 BYTE),
  ATTRIBUTE_CHR4         VARCHAR2(240 BYTE),
  ATTRIBUTE_DATE1        DATE,
  ATTRIBUTE_DATE2        DATE,
  SEQUENCE_ID            NUMBER,
  SOURCE                 VARCHAR2(100 BYTE),
  ORG_ID                 NUMBER,
  CLAIM_TYPE_ID          NUMBER,
  REASON_CODE_ID         NUMBER,
  APPROVAL_DETAIL_ID     NUMBER,
  APPROVER_ID            NUMBER,
  APPROVER_USER_ROLE_ID  NUMBER,
  OPR_MODE               VARCHAR2(100 BYTE),
  BATCH_ID               NUMBER,
  REQUEST_ID             NUMBER,
  STATUS                 VARCHAR2(1 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_AMS_APPROVAL_UPLOAD_TBL  (Synonym) 
--
--  Dependencies: 
--   XXD_AMS_APPROVAL_UPLOAD_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_AMS_APPROVAL_UPLOAD_TBL FOR XXDO.XXD_AMS_APPROVAL_UPLOAD_TBL
/
