--
-- XXD_FA_RF_INVDET_REP_SUM_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_FA_RF_INVDET_REP_SUM_GT
(
  BOOK                    VARCHAR2(100 BYTE),
  PERIOD_FROM             VARCHAR2(100 BYTE),
  PERIOD_TO               VARCHAR2(100 BYTE),
  CURRENCY                VARCHAR2(100 BYTE),
  ASSET_CATEGORY          VARCHAR2(30 BYTE),
  ASSET_COST_ACCOUNT      VARCHAR2(103 BYTE),
  BRAND                   VARCHAR2(150 BYTE),
  ASSET_NUMBER            VARCHAR2(15 BYTE),
  DESCRIPTION             VARCHAR2(80 BYTE),
  DATE_PLACED_IN_SERVICE  VARCHAR2(30 BYTE),
  DEPRN_METHOD            VARCHAR2(30 BYTE),
  LIFE_YR_MO              VARCHAR2(30 BYTE),
  CUSTODIAN               VARCHAR2(150 BYTE),
  COST_CENTER             VARCHAR2(100 BYTE),
  PARENT_ASSET            NUMBER(15),
  BEGIN_YEAR              NUMBER,
  ADDITION                NUMBER,
  ADJUSTMENT              NUMBER,
  RETIREMENT              NUMBER,
  REVALUATION             NUMBER,
  RECLASS                 NUMBER,
  TRANSFER                NUMBER,
  END_YEAR                NUMBER,
  REPORT_TYPE             VARCHAR2(30 BYTE),
  ASSET_ID                NUMBER,
  NET_BOOK_VALUE          NUMBER,
  CAPITALIZATION          NUMBER,
  IMPAIRMENT              NUMBER,
  BEGIN_YEAR_FUN          NUMBER,
  BEGIN_YEAR_SPOTRATE     NUMBER,
  BEGIN_FX_TRANSLATION    NUMBER,
  END_YEAR_FUN            NUMBER,
  END_YEAR_SPOTRATE       NUMBER,
  END_FX_TRANSLATION      NUMBER,
  NET_FX_TRANSLATION      NUMBER,
  ADDITION_NONF           NUMBER,
  ADJUSTMENT_NONF         NUMBER,
  RETIREMENT_NONF         NUMBER,
  CAPITALIZATION_NONF     NUMBER,
  REVALUATION_NONF        NUMBER,
  RECLASS_NONF            NUMBER,
  TRANSFER_NONF           NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_FA_RF_INVDET_REP_SUM_GT TO APPS
/
