--
-- XXD_ONT_CONSUM_PARAMETERS_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_ONT_CONSUM_PARAMETERS_GT
(
  PARAMETER_NAME   VARCHAR2(200 BYTE),
  PARAMETER_VALUE  VARCHAR2(200 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE
/
