--
-- XXD_FA_RF_INVDET_SUM_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_FA_RF_INVDET_SUM_GT
(
  ASSET_ID                NUMBER(15),
  DISTRIBUTION_CCID       NUMBER(15),
  ADJUSTMENT_CCID         NUMBER(15),
  CATEGORY_BOOKS_ACCOUNT  VARCHAR2(25 BYTE),
  SOURCE_TYPE_CODE        VARCHAR2(15 BYTE),
  AMOUNT                  NUMBER,
  COST_ACCOUNT            VARCHAR2(25 BYTE),
  COST_BEGIN_BALANCE      NUMBER,
  GROUP_ASSET_ID          NUMBER(15),
  REPORT_TYPE             VARCHAR2(30 BYTE),
  AMOUNT_FUN              NUMBER,
  AMOUNT_NONF             NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_FA_RF_INVDET_SUM_GT TO APPS
/
