--
-- XXD_GL_ARCHIVE_HEADERS  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ARCHIVE_HEADERS
(
  JE_HEADER_ID                  NUMBER(15)      NOT NULL,
  LAST_UPDATE_DATE              DATE            NOT NULL,
  LAST_UPDATED_BY               NUMBER(15)      NOT NULL,
  LEDGER_ID                     NUMBER(15)      NOT NULL,
  NAME                          VARCHAR2(100 BYTE) NOT NULL,
  JE_CATEGORY                   VARCHAR2(25 BYTE) NOT NULL,
  JE_SOURCE                     VARCHAR2(25 BYTE) NOT NULL,
  PERIOD_NAME                   VARCHAR2(15 BYTE) NOT NULL,
  CURRENCY_CODE                 VARCHAR2(15 BYTE) NOT NULL,
  STATUS                        VARCHAR2(1 BYTE) NOT NULL,
  DATE_CREATED                  DATE            NOT NULL,
  ACCRUAL_REV_FLAG              VARCHAR2(1 BYTE) NOT NULL,
  ACCRUAL_REV_CHANGE_SIGN_FLAG  VARCHAR2(1 BYTE) NOT NULL,
  MULTI_BAL_SEG_FLAG            VARCHAR2(1 BYTE) NOT NULL,
  ACTUAL_FLAG                   VARCHAR2(1 BYTE) NOT NULL,
  CONVERSION_FLAG               VARCHAR2(1 BYTE),
  DEFAULT_EFFECTIVE_DATE        DATE            NOT NULL,
  CREATION_DATE                 DATE,
  CREATED_BY                    NUMBER(15),
  LAST_UPDATE_LOGIN             NUMBER(15),
  ENCUMBRANCE_TYPE_ID           NUMBER(15),
  BUDGET_VERSION_ID             NUMBER(15),
  BALANCED_JE_FLAG              VARCHAR2(1 BYTE),
  BALANCING_SEGMENT_VALUE       VARCHAR2(25 BYTE),
  JE_BATCH_ID                   NUMBER(15),
  FROM_RECURRING_HEADER_ID      NUMBER(15),
  UNIQUE_DATE                   VARCHAR2(30 BYTE),
  EARLIEST_POSTABLE_DATE        DATE,
  POSTED_DATE                   DATE,
  ACCRUAL_REV_EFFECTIVE_DATE    DATE,
  ACCRUAL_REV_PERIOD_NAME       VARCHAR2(15 BYTE),
  ACCRUAL_REV_STATUS            VARCHAR2(1 BYTE),
  ACCRUAL_REV_JE_HEADER_ID      NUMBER(15),
  DESCRIPTION                   VARCHAR2(240 BYTE),
  CONTROL_TOTAL                 NUMBER,
  RUNNING_TOTAL_DR              NUMBER,
  RUNNING_TOTAL_CR              NUMBER,
  RUNNING_TOTAL_ACCOUNTED_DR    NUMBER,
  RUNNING_TOTAL_ACCOUNTED_CR    NUMBER,
  CURRENCY_CONVERSION_RATE      NUMBER,
  CURRENCY_CONVERSION_TYPE      VARCHAR2(30 BYTE),
  CURRENCY_CONVERSION_DATE      DATE,
  EXTERNAL_REFERENCE            VARCHAR2(80 BYTE),
  ATTRIBUTE1                    VARCHAR2(150 BYTE),
  ATTRIBUTE2                    VARCHAR2(150 BYTE),
  ATTRIBUTE3                    VARCHAR2(150 BYTE),
  ATTRIBUTE4                    VARCHAR2(150 BYTE),
  ATTRIBUTE5                    VARCHAR2(150 BYTE),
  ATTRIBUTE6                    VARCHAR2(150 BYTE),
  ATTRIBUTE7                    VARCHAR2(150 BYTE),
  ATTRIBUTE8                    VARCHAR2(150 BYTE),
  ATTRIBUTE9                    VARCHAR2(150 BYTE),
  ATTRIBUTE10                   VARCHAR2(150 BYTE),
  CONTEXT                       VARCHAR2(150 BYTE),
  USSGL_TRANSACTION_CODE        VARCHAR2(30 BYTE),
  CONTEXT2                      VARCHAR2(150 BYTE),
  DOC_SEQUENCE_ID               NUMBER,
  DOC_SEQUENCE_VALUE            NUMBER,
  JGZZ_RECON_CONTEXT            VARCHAR2(30 BYTE),
  JGZZ_RECON_REF                VARCHAR2(240 BYTE),
  TAX_STATUS_CODE               VARCHAR2(1 BYTE) NOT NULL,
  PARENT_JE_HEADER_ID           NUMBER(15),
  REVERSED_JE_HEADER_ID         NUMBER(15),
  ORIGINATING_BAL_SEG_VALUE     VARCHAR2(25 BYTE),
  INTERCOMPANY_MODE             NUMBER(15),
  DR_BAL_SEG_VALUE              VARCHAR2(25 BYTE),
  CR_BAL_SEG_VALUE              VARCHAR2(25 BYTE),
  GLOBAL_ATTRIBUTE_CATEGORY     VARCHAR2(30 BYTE),
  GLOBAL_ATTRIBUTE1             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE2             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE3             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE4             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE5             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE6             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE7             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE8             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE9             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE10            VARCHAR2(150 BYTE),
  REFERENCE_DATE                DATE,
  LOCAL_DOC_SEQUENCE_ID         NUMBER,
  LOCAL_DOC_SEQUENCE_VALUE      NUMBER,
  DISPLAY_ALC_JOURNAL_FLAG      VARCHAR2(1 BYTE),
  JE_FROM_SLA_FLAG              VARCHAR2(1 BYTE),
  POSTING_ACCT_SEQ_VERSION_ID   NUMBER,
  POSTING_ACCT_SEQ_ASSIGN_ID    NUMBER,
  POSTING_ACCT_SEQ_VALUE        NUMBER,
  CLOSE_ACCT_SEQ_VERSION_ID     NUMBER,
  CLOSE_ACCT_SEQ_ASSIGN_ID      NUMBER,
  CLOSE_ACCT_SEQ_VALUE          NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    1
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1000K
            NEXT             1000K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
COMPRESS FOR QUERY HIGH
NOCACHE
/


--
-- XXD_GL_ARCHIVE_HEADERS_CIX1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_CIX1 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(PERIOD_NAME, LEDGER_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS_N1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_N1 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(JE_BATCH_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS_N2  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_N2 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(PERIOD_NAME, JE_CATEGORY)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS_N3  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_N3 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(DOC_SEQUENCE_VALUE, DOC_SEQUENCE_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS_N4  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_N4 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(PARENT_JE_HEADER_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS_U1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_U1 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(JE_HEADER_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS_U2  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_HEADERS_U2 ON XXDO.XXD_GL_ARCHIVE_HEADERS
(NAME, JE_BATCH_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_HEADERS  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_HEADERS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_ARCHIVE_HEADERS FOR XXDO.XXD_GL_ARCHIVE_HEADERS
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_GL_ARCHIVE_HEADERS TO APPS WITH GRANT OPTION
/
