--
-- XXD_UTL_FILE_UPLOAD_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_UTL_FILE_UPLOAD_GT
(
  FILENAME  VARCHAR2(240 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- XXD_UTL_FILE_UPLOAD_GT  (Synonym) 
--
--  Dependencies: 
--   XXD_UTL_FILE_UPLOAD_GT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_UTL_FILE_UPLOAD_GT FOR XXDO.XXD_UTL_FILE_UPLOAD_GT
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_UTL_FILE_UPLOAD_GT TO APPS
/
