--
-- XXD_ONT_VAS_ASSIGNMENT_DTLS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_VAS_ASSIGNMENT_DTLS_T
(
  ACCOUNT_NUMBER     VARCHAR2(360 BYTE),
  CUST_ACCOUNT_ID    NUMBER,
  ORG_ID             NUMBER,
  ENTITY             VARCHAR2(100 BYTE),
  ATTRIBUTE_LEVEL    VARCHAR2(30 BYTE),
  ATTRIBUTE_VALUE    VARCHAR2(100 BYTE),
  DESCRIPTION        VARCHAR2(100 BYTE),
  VAS_CODE           VARCHAR2(20 BYTE),
  VAS_COMMENTS       VARCHAR2(2000 BYTE),
  ATTRIBUTE1         VARCHAR2(240 BYTE),
  ATTRIBUTE2         VARCHAR2(240 BYTE),
  ATTRIBUTE3         VARCHAR2(240 BYTE),
  ATTRIBUTE4         VARCHAR2(240 BYTE),
  ATTRIBUTE5         VARCHAR2(240 BYTE),
  ATTRIBUTE6         VARCHAR2(240 BYTE),
  ATTRIBUTE7         VARCHAR2(240 BYTE),
  ATTRIBUTE8         VARCHAR2(240 BYTE),
  ATTRIBUTE9         VARCHAR2(240 BYTE),
  ATTRIBUTE10        VARCHAR2(240 BYTE),
  ATTRIBUTE11        VARCHAR2(240 BYTE),
  ATTRIBUTE12        VARCHAR2(240 BYTE),
  ATTRIBUTE13        VARCHAR2(240 BYTE),
  ATTRIBUTE14        VARCHAR2(240 BYTE),
  ATTRIBUTE15        VARCHAR2(240 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATED_DATE  DATE,
  LAST_UPDATE_LOGIN  NUMBER,
  SUPPLEMENTAL LOG GROUP GGS_16375326 (ACCOUNT_NUMBER,CUST_ACCOUNT_ID,ORG_ID,ENTITY,ATTRIBUTE_LEVEL,ATTRIBUTE_VALUE,DESCRIPTION,VAS_CODE,VAS_COMMENTS,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATED_DATE,LAST_UPDATE_LOGIN) ALWAYS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_VAS_ASSIGNMENT_DTLS_N1  (Index) 
--
--  Dependencies: 
--   XXD_ONT_VAS_ASSIGNMENT_DTLS_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_VAS_ASSIGNMENT_DTLS_N1 ON XXDO.XXD_ONT_VAS_ASSIGNMENT_DTLS_T
(CUST_ACCOUNT_ID, ORG_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_ONT_VAS_ASSIGNMENT_DTLS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_VAS_ASSIGNMENT_DTLS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_VAS_ASSIGNMENT_DTLS_T FOR XXDO.XXD_ONT_VAS_ASSIGNMENT_DTLS_T
/
