--
-- XXD_ONT_MULTI_ORDER_UPLOAD_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_MULTI_ORDER_UPLOAD_T
(
  ORG_ID                  NUMBER,
  ORDER_SOURCE_ID         NUMBER,
  ORDER_TYPE              VARCHAR2(40 BYTE),
  ORIG_SYS_DOCUMENT_REF   VARCHAR2(50 BYTE),
  ORIG_SYS_LINE_REF       VARCHAR2(50 BYTE),
  BRAND                   VARCHAR2(240 BYTE),
  HEADER_REQUEST_DATE     DATE,
  HEADER_CANCEL_DATE      DATE,
  BOOK_ORDER              VARCHAR2(1 BYTE),
  CUSTOMER_NUMBER         VARCHAR2(360 BYTE),
  CUST_PO_NUMBER          VARCHAR2(50 BYTE),
  PRICE_LIST              VARCHAR2(240 BYTE),
  SHIP_FROM_ORG           VARCHAR2(240 BYTE),
  SHIP_FROM_ORG_ID        NUMBER,
  SHIP_TO_ORG_ID          NUMBER,
  INVOICE_TO_ORG_ID       NUMBER,
  DELIVER_TO_ORG_ID       NUMBER,
  INVENTORY_ITEM          VARCHAR2(2000 BYTE),
  INVENTORY_ITEM_ID       NUMBER,
  CUSTOMER_ITEM           VARCHAR2(2000 BYTE),
  CUST_INVENTORY_ITEM_ID  NUMBER,
  ORDERED_QUANTITY        NUMBER,
  LINE_REQUEST_DATE       DATE,
  LINE_CANCEL_DATE        DATE,
  UNIT_SELLING_PRICE      NUMBER,
  SUBINVENTORY            VARCHAR2(10 BYTE),
  SHIPPING_INSTRUCTIONS   VARCHAR2(2000 BYTE),
  COMMENTS1               VARCHAR2(240 BYTE),
  COMMENTS2               VARCHAR2(240 BYTE),
  PRICING_AGREEMENT       VARCHAR2(240 BYTE),
  SALES_AGREEMENT         NUMBER,
  STATUS                  VARCHAR2(1 BYTE),
  ERROR_MESSAGE           VARCHAR2(4000 BYTE),
  CREATED_BY              VARCHAR2(200 BYTE),
  CREATION_DATE           DATE,
  LAST_UPDATED_BY         VARCHAR2(200 BYTE),
  LAST_UPDATE_DATE        DATE,
  RETURN_REASON_CODE      VARCHAR2(30 BYTE),
  PACKING_INSTRUCTIONS    VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN1      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN2      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN3      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN4      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN5      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN6      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN7      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN8      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN9      VARCHAR2(2000 BYTE),
  ADDITIONAL_COLUMN10     VARCHAR2(2000 BYTE),
  CUST_ACCOUNT_ID         NUMBER,
  LINE_VAS_CODE           VARCHAR2(1000 BYTE),
  STYLE                   VARCHAR2(100 BYTE),
  COLOR                   VARCHAR2(100 BYTE),
  HDR_VAS_CODE            VARCHAR2(1000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_MULTI_ORDER_UPLOAD_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_MULTI_ORDER_UPLOAD_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_MULTI_ORDER_UPLOAD_T FOR XXDO.XXD_ONT_MULTI_ORDER_UPLOAD_T
/
