--
-- XXD_GL_PERIOD_NAME_GT  (Table) 
--
CREATE TABLE XXDO.XXD_GL_PERIOD_NAME_GT
(
  LEDGER_ID        NUMBER,
  PERIOD_NAME      VARCHAR2(10 BYTE),
  PERIOD_END_DATE  VARCHAR2(30 BYTE),
  LEDGER_TYPE      VARCHAR2(20 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
