--
-- XXD_LDAP_SECURITY_MASTER_T  (Table) 
--
CREATE TABLE XXDO.XXD_LDAP_SECURITY_MASTER_T
(
  AD_SECURITY_OBJ_NAME   VARCHAR2(50 BYTE),
  AD_SECURITY_SEG_NAME   VARCHAR2(30 BYTE),
  AD_SECURITY_SEG_VALUE  VARCHAR2(40 BYTE),
  DESCRIPTION            VARCHAR2(300 BYTE),
  INSTANCE_NAME          VARCHAR2(10 BYTE),
  CREATED_BY             NUMBER,
  LAST_UPDATED_BY        NUMBER,
  CREATION_DATE          DATE,
  LAST_UPDATE_DATE       DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
