--
-- XXD_ONT_D2B_DMND_FCST_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_D2B_DMND_FCST_STG_T
(
  RECORD_ID            NUMBER,
  ASCP_INV_ITEM_ID     NUMBER,
  EBS_INV_ITEM_ID      NUMBER,
  SKU                  VARCHAR2(250 BYTE),
  BRAND                VARCHAR2(40 BYTE),
  REGION               VARCHAR2(30 BYTE),
  BATCH_NAME           VARCHAR2(50 BYTE),
  REQUEST_ID           NUMBER,
  DIVISION             VARCHAR2(40 BYTE),
  DEPARTMENT           VARCHAR2(40 BYTE),
  CHANNEL              VARCHAR2(30 BYTE),
  FCST_REGION          VARCHAR2(150 BYTE),
  FCST_MONTH           VARCHAR2(40 BYTE),
  FINAL_FCST           NUMBER,
  STATUS               VARCHAR2(100 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  FORECAST_START_DATE  DATE,
  FORECAST_END_DATE    DATE,
  UOM_CODE             VARCHAR2(10 BYTE),
  LIST_PRICE           NUMBER,
  ORGANIZATION_ID      NUMBER,
  INV_ORG_CODE         VARCHAR2(10 BYTE),
  BULK_QTY             NUMBER,
  SCHDL_QTY            NUMBER,
  UNSCH_QTY            NUMBER,
  OPERATION            VARCHAR2(1 BYTE),
  QTY_UPDATE           NUMBER,
  ORDER_NUMBER         NUMBER,
  LINE_NUMBER          VARCHAR2(30 BYTE),
  ATTRIBUTE1           VARCHAR2(240 BYTE),
  ATTRIBUTE2           VARCHAR2(240 BYTE),
  ATTRIBUTE3           VARCHAR2(240 BYTE),
  ATTRIBUTE4           VARCHAR2(240 BYTE),
  ATTRIBUTE5           VARCHAR2(240 BYTE),
  ATTRIBUTE6           VARCHAR2(240 BYTE),
  ATTRIBUTE7           VARCHAR2(240 BYTE),
  ATTRIBUTE8           VARCHAR2(240 BYTE),
  ATTRIBUTE9           VARCHAR2(240 BYTE),
  ATTRIBUTE10          VARCHAR2(240 BYTE),
  ATTRIBUTE11          VARCHAR2(240 BYTE),
  ATTRIBUTE12          VARCHAR2(240 BYTE),
  ATTRIBUTE13          VARCHAR2(240 BYTE),
  ATTRIBUTE14          VARCHAR2(240 BYTE),
  ATTRIBUTE15          VARCHAR2(240 BYTE),
  CREATION_DATE        DATE,
  CREATED_BY           NUMBER,
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATED_BY      NUMBER,
  LAST_UPDATE_LOGIN    NUMBER,
  BATCH_NUM            NUMBER,
  ORG_ID               NUMBER,
  HEADER_ID            NUMBER,
  PROCESS_MODE         VARCHAR2(30 BYTE),
  ORDER_TYPE           VARCHAR2(30 BYTE),
  FILE_NAME            VARCHAR2(240 BYTE),
  SOLD_TO_ID           NUMBER,
  HEADER_BATCH         NUMBER,
  LINE_ID              NUMBER,
  SHIP_TO_ID           NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_D2B_DMND_FCST_N1  (Index) 
--
--  Dependencies: 
--   XXD_ONT_D2B_DMND_FCST_STG_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_D2B_DMND_FCST_N1 ON XXDO.XXD_ONT_D2B_DMND_FCST_STG_T
(RECORD_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 3 INSTANCES 2 )
/

--
-- XXD_ONT_D2B_DMND_FCST_N2  (Index) 
--
--  Dependencies: 
--   XXD_ONT_D2B_DMND_FCST_STG_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_D2B_DMND_FCST_N2 ON XXDO.XXD_ONT_D2B_DMND_FCST_STG_T
(BATCH_NAME)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 3 INSTANCES 2 )
/

--
-- XXD_ONT_D2B_DMND_FCST_N4  (Index) 
--
--  Dependencies: 
--   XXD_ONT_D2B_DMND_FCST_STG_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_D2B_DMND_FCST_N4 ON XXDO.XXD_ONT_D2B_DMND_FCST_STG_T
(EBS_INV_ITEM_ID, REQUEST_ID, FCST_REGION, CHANNEL, FCST_MONTH)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 3 INSTANCES 2 )
/
