--
-- XXD_INV_GIVR_ACCT_DETLS_T  (Table) 
--
CREATE TABLE XXDO.XXD_INV_GIVR_ACCT_DETLS_T
(
  STYLE                     VARCHAR2(50 BYTE),
  COLOR_CODE                VARCHAR2(50 BYTE),
  ITEM_SIZE                 VARCHAR2(50 BYTE),
  DESCRIPTION               VARCHAR2(240 BYTE),
  BRAND                     VARCHAR2(50 BYTE),
  DEPARTMENT                VARCHAR2(50 BYTE),
  ITEM_CLASS                VARCHAR2(50 BYTE),
  SUB_CLASS                 VARCHAR2(50 BYTE),
  ITEM_TYPE                 VARCHAR2(50 BYTE),
  INTRO_SEASON              VARCHAR2(50 BYTE),
  CURRENT_SEASON            VARCHAR2(50 BYTE),
  DEFAULT_DUTY_RATE         NUMBER,
  ONHAND_QTY                NUMBER,
  MATERIAL_COST             NUMBER,
  DUTY_AMOUNT               NUMBER,
  FREIGHT_DUTIABLE          NUMBER,
  FREIGHT                   NUMBER,
  OH_DUTY                   NUMBER,
  OH_NONDUTY                NUMBER,
  TOTAL_COST                NUMBER,
  ONHAND_VALUE              NUMBER,
  INTRANSIT_QTY             NUMBER,
  INTRANSIT_VAL             NUMBER,
  INTRANSIT_MATERIAL_VAL    NUMBER,
  INTRANSIT_DUTY_VAL        NUMBER,
  INTRANSIT_FREIGHT_VAL     NUMBER,
  INTRANSIT_FREIGHT_DU_VAL  NUMBER,
  INTRANSIT_OH_DUTY_VAL     NUMBER,
  INTRANSIT_OH_NONDUTY_VAL  NUMBER,
  TOTAL_INVENTORY_QTY       NUMBER,
  TOTAL_INVENTORY_VAL       NUMBER,
  EXTENDED_MATERIAL_COST    NUMBER,
  MACAU_COST                NUMBER,
  EXTENDED_MACAU_COST       NUMBER,
  AVG_MARGIN_VALUE_USD      NUMBER,
  AVG_MARGIN_VALUE_LOCAL    NUMBER,
  INVENTORY_ORG             NUMBER,
  ENTITY_UNIQUE_IDENTIFIER  VARCHAR2(10 BYTE),
  ACCOUNT_NUMBER            VARCHAR2(10 BYTE),
  KEY3                      VARCHAR2(10 BYTE),
  KEY4                      VARCHAR2(10 BYTE),
  KEY5                      VARCHAR2(10 BYTE),
  KEY6                      VARCHAR2(10 BYTE),
  KEY7                      VARCHAR2(10 BYTE),
  KEY8                      VARCHAR2(10 BYTE),
  KEY9                      VARCHAR2(10 BYTE),
  KEY10                     VARCHAR2(10 BYTE),
  PERIOD_END_DATE           VARCHAR2(30 BYTE),
  SUBLEDGER_REP_BAL         NUMBER,
  SUBLEDGER_ALT_BAL         NUMBER,
  SUBLEDGER_ACC_BAL         NUMBER,
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATED_BY           NUMBER,
  LAST_UPDATE_DATE          DATE,
  REQUEST_ID                NUMBER,
  INTRANSIT_QTY_PO_REV      NUMBER,
  INTRANSIT_VAL_PO_REV      NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
