--
-- XXDO_PLM_ITEM_UPD_ERRORS  (Table) 
--
CREATE TABLE XXDO.XXDO_PLM_ITEM_UPD_ERRORS
(
  RECORD_ID        NUMBER,
  STYLE            VARCHAR2(100 BYTE),
  COLOR            VARCHAR2(100 BYTE),
  ORGANIZATION_ID  NUMBER,
  ERROR_MESSAGE    VARCHAR2(4000 BYTE),
  CRETION_DATE     DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
