--
-- XXDOAP_ACCRUAL  (Table) 
--
CREATE TABLE XXDO.XXDOAP_ACCRUAL
(
  INVOICE_NUM        VARCHAR2(50 BYTE)          NOT NULL,
  INVOICE_DATE       DATE,
  STYLE              VARCHAR2(50 BYTE),
  COLOR              VARCHAR2(50 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  QUANTITY_INVOICED  NUMBER,
  UNIT_PRICE         NUMBER,
  EXT_VALUE          NUMBER,
  INVOICE_AMOUNT     NUMBER,
  PAYMENT_DATE       DATE,
  ORG_ID             NUMBER(15),
  AP_TYPE            CHAR(30 BYTE),
  PO_NUM             VARCHAR2(20 BYTE),
  VENDOR_ID          NUMBER,
  VENDOR             VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAP_ACCRUAL  (Index) 
--
--  Dependencies: 
--   XXDOAP_ACCRUAL (Table)
--
CREATE INDEX XXDO.XXDOAP_ACCRUAL ON XXDO.XXDOAP_ACCRUAL
(ORG_ID, INVOICE_NUM, PO_NUM, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAP_ACCRUAL  (Synonym) 
--
--  Dependencies: 
--   XXDOAP_ACCRUAL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAP_ACCRUAL FOR XXDO.XXDOAP_ACCRUAL
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOAP_ACCRUAL TO APPS
/

GRANT SELECT ON XXDO.XXDOAP_ACCRUAL TO APPSRO WITH GRANT OPTION
/
