--
-- XXD_CM_CALC_PERCNT_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_CM_CALC_PERCNT_STG_T
(
  REGION                 VARCHAR2(1000 BYTE),
  BRAND                  VARCHAR2(1000 BYTE),
  FORECAST_AMOUNT        NUMBER,
  FORECAST_QTY           NUMBER,
  TOTAL_FORECAST_VALUE   NUMBER,
  TOTAL_FORECAST_PERCNT  NUMBER,
  FORECAST_GLOBAL_VALUE  NUMBER,
  OH_NONDUTY             NUMBER,
  DEPARTMENT             VARCHAR2(1000 BYTE),
  ORGANIZATION_ID        NUMBER,
  OPERATING_UNIT         NUMBER,
  ADDITIONAL_FIELD1      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD2      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD3      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD4      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD5      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD6      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD7      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD8      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD9      VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD10     VARCHAR2(1000 BYTE),
  REC_STATUS             VARCHAR2(1 BYTE),
  ERROR_MSG              VARCHAR2(4000 BYTE),
  CREATED_BY             VARCHAR2(1000 BYTE),
  CREATION_DATE          DATE,
  LAST_UPDATED_BY        VARCHAR2(1000 BYTE),
  LAST_UPDATE_DATE       DATE,
  REQUEST_ID             NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_CM_CALC_PERCNT_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CM_CALC_PERCNT_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_CM_CALC_PERCNT_STG_T FOR XXDO.XXD_CM_CALC_PERCNT_STG_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_CM_CALC_PERCNT_STG_T TO APPS
/
