--
-- XXDO_ONT_RMA_HDR_STG_LOG  (Table) 
--
CREATE TABLE XXDO.XXDO_ONT_RMA_HDR_STG_LOG
(
  WH_ID                  VARCHAR2(10 BYTE)      NOT NULL,
  RMA_NUMBER             VARCHAR2(30 BYTE),
  RMA_RECEIPT_DATE       DATE                   NOT NULL,
  RMA_REFERENCE          VARCHAR2(30 BYTE),
  CUSTOMER_ID            NUMBER,
  ORDER_NUMBER           VARCHAR2(30 BYTE),
  ORDER_NUMBER_TYPE      VARCHAR2(20 BYTE),
  CUSTOMER_NAME          VARCHAR2(250 BYTE),
  CUSTOMER_ADDR1         VARCHAR2(250 BYTE),
  CUSTOMER_ADDR2         VARCHAR2(250 BYTE),
  CUSTOMER_ADDR3         VARCHAR2(250 BYTE),
  CUSTOMER_CITY          VARCHAR2(250 BYTE),
  CUSTOMER_STATE         VARCHAR2(250 BYTE),
  CUSTOMER_ZIP           VARCHAR2(250 BYTE),
  CUSTOMER_PHONE         VARCHAR2(250 BYTE),
  CUSTOMER_EMAIL         VARCHAR2(250 BYTE),
  COMMENTS               VARCHAR2(250 BYTE),
  RMA_TYPE               VARCHAR2(30 BYTE),
  NOTIFIED_TO_WMS        VARCHAR2(1 BYTE),
  COMPANY                VARCHAR2(50 BYTE),
  CUSTOMER_COUNTRY_CODE  VARCHAR2(5 BYTE),
  CUSTOMER_COUNTRY_NAME  VARCHAR2(30 BYTE),
  REQUEST_ID             NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  ATTRIBUTE1             VARCHAR2(50 BYTE),
  ATTRIBUTE2             VARCHAR2(50 BYTE),
  ATTRIBUTE3             VARCHAR2(50 BYTE),
  ATTRIBUTE4             VARCHAR2(50 BYTE),
  ATTRIBUTE5             VARCHAR2(50 BYTE),
  ATTRIBUTE6             VARCHAR2(50 BYTE),
  ATTRIBUTE7             VARCHAR2(50 BYTE),
  ATTRIBUTE8             VARCHAR2(50 BYTE),
  ATTRIBUTE9             VARCHAR2(50 BYTE),
  ATTRIBUTE10            VARCHAR2(50 BYTE),
  ATTRIBUTE11            VARCHAR2(50 BYTE),
  ATTRIBUTE12            VARCHAR2(50 BYTE),
  ATTRIBUTE13            VARCHAR2(50 BYTE),
  ATTRIBUTE14            VARCHAR2(50 BYTE),
  ATTRIBUTE15            VARCHAR2(50 BYTE),
  ATTRIBUTE16            VARCHAR2(50 BYTE),
  ATTRIBUTE17            VARCHAR2(50 BYTE),
  ATTRIBUTE18            VARCHAR2(50 BYTE),
  ATTRIBUTE19            VARCHAR2(50 BYTE),
  ATTRIBUTE20            VARCHAR2(50 BYTE),
  SOURCE                 VARCHAR2(20 BYTE)      DEFAULT 'WMS',
  DESTINATION            VARCHAR2(20 BYTE)      DEFAULT 'EBS',
  HEADER_ID              NUMBER,
  PROCESS_STATUS         VARCHAR2(30 BYTE),
  ERROR_MESSAGE          VARCHAR2(1000 BYTE),
  RETCODE                NUMBER,
  RESULT_CODE            VARCHAR2(1 BYTE),
  RECORD_TYPE            VARCHAR2(10 BYTE),
  RECEIPT_HEADER_SEQ_ID  NUMBER,
  ARCHIVE_DATE           DATE,
  ARCHIVE_REQUEST_ID     NUMBER,
  MESSAGE_ID             VARCHAR2(50 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ONT_RMA_HDR_STG_LOG  (Synonym) 
--
--  Dependencies: 
--   XXDO_ONT_RMA_HDR_STG_LOG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_ONT_RMA_HDR_STG_LOG FOR XXDO.XXDO_ONT_RMA_HDR_STG_LOG
/
