--
-- XXDOAR_B2B_BILLING_HDR_STG  (Table) 
--
CREATE TABLE XXDO.XXDOAR_B2B_BILLING_HDR_STG
(
  CONCURRENT_REQUEST_ID      NUMBER,
  CUSTOMER_TRX_ID            NUMBER,
  REMIT_TO_ADDRESS1          VARCHAR2(360 BYTE),
  REMIT_TO_ADDRESS2          VARCHAR2(360 BYTE),
  REMIT_TO_ADDRESS3          VARCHAR2(360 BYTE),
  REMIT_TO_ADDRESS4          VARCHAR2(360 BYTE),
  REMIT_CITY                 VARCHAR2(120 BYTE),
  REMIT_STATE                VARCHAR2(120 BYTE),
  REMIT_POSTAL_CODE          VARCHAR2(120 BYTE),
  REMIT_COUNTRY              VARCHAR2(30 BYTE),
  REMIT_COUNTRY_NAME         VARCHAR2(120 BYTE),
  TRANSACTION_CLASS          VARCHAR2(80 BYTE),
  TRANSACTION_NUMBER         VARCHAR2(30 BYTE),
  BRAND                      VARCHAR2(150 BYTE),
  TRANSACTION_DATE           DATE,
  DISCOUNT_DATE              DATE,
  DISCOUNT_AMOUNT            NUMBER,
  DISCOUNTED_AMOUNT          NUMBER,
  CF_DUE_DATE                DATE,
  INVOICE_AMOUNT             NUMBER,
  BILL_TO_CUSTOMER           VARCHAR2(360 BYTE),
  BILL_TO_ADDRESS1           VARCHAR2(360 BYTE),
  BILL_TO_ADDRESS2           VARCHAR2(360 BYTE),
  BILL_TO_ADDRESS3           VARCHAR2(360 BYTE),
  BILL_TO_ADDRESS4           VARCHAR2(360 BYTE),
  BILL_TO_CITY               VARCHAR2(120 BYTE),
  BILL_TO_STATE              VARCHAR2(120 BYTE),
  BILL_TO_POSTAL_CODE        VARCHAR2(120 BYTE),
  BILL_TO_COUNTRY            VARCHAR2(30 BYTE),
  BILL_TO_COUNTRY_NAME       VARCHAR2(120 BYTE),
  BILL_TO_TAX_REFERENCE      VARCHAR2(360 BYTE),
  SHIP_TO_CUSTOMER           VARCHAR2(360 BYTE),
  SHIP_TO_ADDRESS1           VARCHAR2(360 BYTE),
  SHIP_TO_ADDRESS2           VARCHAR2(360 BYTE),
  SHIP_TO_ADDRESS3           VARCHAR2(360 BYTE),
  SHIP_TO_ADDRESS4           VARCHAR2(360 BYTE),
  SHIP_TO_CITY               VARCHAR2(120 BYTE),
  SHIP_TO_STATE              VARCHAR2(120 BYTE),
  SHIP_TO_POSTAL_CODE        VARCHAR2(120 BYTE),
  SHIP_TO_COUNTRY            VARCHAR2(30 BYTE),
  SHIP_TO_COUNTRY_NAME       VARCHAR2(120 BYTE),
  ORDER_NUMBER               VARCHAR2(150 BYTE),
  PO_NUMBER                  VARCHAR2(50 BYTE),
  PAYMENT_TERMS              VARCHAR2(150 BYTE),
  PAYMENT_TERMS_DESC         VARCHAR2(150 BYTE),
  ACCOUNT_NUMBER             VARCHAR2(50 BYTE),
  SALESPERSON                VARCHAR2(150 BYTE),
  STORE_NUMBER               VARCHAR2(150 BYTE),
  DC_NUMBER                  VARCHAR2(150 BYTE),
  DEPT_NUM                   VARCHAR2(150 BYTE),
  VENDOR_NUMBER              VARCHAR2(150 BYTE),
  SHIP_VIA                   VARCHAR2(60 BYTE),
  PRINTING_PENDING           VARCHAR2(1 BYTE),
  DELIVERY_NUMBER            VARCHAR2(150 BYTE),
  TRANSACTION_TYPE_NAME      VARCHAR2(80 BYTE),
  FACTOR_FLAG                VARCHAR2(30 BYTE),
  WAYBILL_NUMBER             VARCHAR2(50 BYTE),
  ORDER_TYPE                 VARCHAR2(150 BYTE),
  INVOICE_COMMENTS           VARCHAR2(2000 BYTE),
  INTERNAL_NOTES             VARCHAR2(240 BYTE),
  COMMENTS                   VARCHAR2(2000 BYTE),
  DOC_LANGUAGE               VARCHAR2(150 BYTE),
  FROM_EMAIL                 VARCHAR2(150 BYTE),
  TO_EMAIL                   VARCHAR2(360 BYTE),
  CC_EMAIL                   VARCHAR2(150 BYTE),
  BCC_EMAIL                  VARCHAR2(150 BYTE),
  EMAIL_SUBJECT              VARCHAR2(150 BYTE),
  BUYING_GROUP               VARCHAR2(360 BYTE),
  MEMBER_NUMBER              VARCHAR2(240 BYTE),
  VAT_NUMBER                 VARCHAR2(360 BYTE),
  CUSTOMER_REFERENCE         VARCHAR2(150 BYTE),
  GST_PERCENT                NUMBER,
  HST_PERCENT                NUMBER,
  QST_PERCENT                NUMBER,
  PST_PERCENT                NUMBER,
  ORIGINAL_TRANSACTION       VARCHAR2(30 BYTE),
  HEADER_COMMENTS1           VARCHAR2(2000 BYTE),
  HEADER_COMMENTS2           VARCHAR2(2000 BYTE),
  HEADER_COMMENTS3           VARCHAR2(2000 BYTE),
  HEADER_COMMENTS4           VARCHAR2(2000 BYTE),
  FOOTER_NOTES1              VARCHAR2(2000 BYTE),
  FOOTER_NOTES2              VARCHAR2(2000 BYTE),
  FOOTER_NOTES3              VARCHAR2(2000 BYTE),
  FOOTER_NOTES4              VARCHAR2(2000 BYTE),
  FOOTER_NOTES5              VARCHAR2(2000 BYTE),
  BRAND_PHONE_NUMBER         VARCHAR2(100 BYTE),
  BILLING_PHONE              VARCHAR2(100 BYTE),
  LINE_SUBTOTAL              NUMBER,
  FREIGHT_SUBTOTAL           NUMBER,
  TAX_SUBTOTAL               NUMBER,
  TAX_EXT_LINE_SUBTOTAL      VARCHAR2(30 BYTE),
  NON_TAX_EXT_LINE_SUBTOTAL  VARCHAR2(30 BYTE),
  TOTAL_AMOUNT               VARCHAR2(30 BYTE),
  CURRENCY_CODE              VARCHAR2(30 BYTE),
  NON_TAX_TEXT               VARCHAR2(360 BYTE),
  TAX_TEXT                   VARCHAR2(360 BYTE),
  NON_TAX_TOTAL_QTY          VARCHAR2(30 BYTE),
  TAX_TOTAL_QTY              VARCHAR2(30 BYTE),
  NON_TAX_AMOUNT_TOTAL       VARCHAR2(30 BYTE),
  TAX_AMOUNT_TOTAL           VARCHAR2(30 BYTE),
  FOOTER_COMMENTS1           VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS2           VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS3           VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS4           VARCHAR2(2000 BYTE),
  ERROR_MESSAGE              VARCHAR2(4000 BYTE),
  PROCESS_FLAG               VARCHAR2(1 BYTE),
  REMIT_CONTACT_NUMBER       VARCHAR2(150 BYTE),
  REMIT_ADDRESSEE            VARCHAR2(360 BYTE),
  BILL_TO_CUSTOMER_NUM       VARCHAR2(50 BYTE),
  SHIP_TO_CUSTOMER_NUM       VARCHAR2(50 BYTE),
  FILE_DATE_TIME             VARCHAR2(30 BYTE),
  PRINT_OR_EMAIL             VARCHAR2(60 BYTE),
  OPERATING_UNIT             VARCHAR2(120 BYTE),
  HEADER_COMMENTS5           VARCHAR2(360 BYTE),
  HEADER_COMMENTS6           VARCHAR2(360 BYTE),
  HEADER_COMMENTS7           VARCHAR2(360 BYTE),
  HEADER_COMMENTS8           VARCHAR2(360 BYTE),
  HEADER_COMMENTS9           VARCHAR2(360 BYTE),
  HEADER_COMMENTS10          VARCHAR2(360 BYTE),
  SHIP_TO_TAX_REF            VARCHAR2(60 BYTE),
  REPROCESS_FLAG             VARCHAR2(1 BYTE),
  SOLD_BY_LEGAL_ENTITY       VARCHAR2(120 BYTE),
  SHIP_FROM_COUNTRY          VARCHAR2(30 BYTE),
  INCO_TERM                  VARCHAR2(120 BYTE),
  REVERSE_CHARGE             VARCHAR2(30 BYTE),
  TOTAL_QUANTITY             NUMBER,
  SUBTOTAL_GOODS_EXEMPT      NUMBER,
  SUBTOTAL_GOODS_TAXABLE     NUMBER,
  SUBTOTAL_GOODS_TOTAL       NUMBER,
  SUBTOTAL_FREIGHT_EXEMPT    NUMBER,
  SUBTOTAL_FREIGHT_TAXABLE   NUMBER,
  SUBTOTAL_FREIGHT_TOTAL     NUMBER,
  GRAND_TOTAL1_EXEMPT        NUMBER,
  GRAND_TOTAL1_TAXABLE       NUMBER,
  GRAND_TOTAL1_TOTAL         NUMBER,
  VAT_RATE                   VARCHAR2(30 BYTE),
  VAT_RATE_NAME              VARCHAR2(120 BYTE),
  VAT_GOODS_EXEMPT           NUMBER,
  VAT_GOODS_TAXABLE          NUMBER,
  VAT_GOODS_TOTAL            NUMBER,
  VAT_FREIGHT_EXEMPT         NUMBER,
  VAT_FREIGHT_TOTAL          NUMBER,
  GRAND_TOTAL2_EXEMPT        NUMBER,
  GRAND_TOTAL2_TAXABLE       NUMBER,
  GRAND_TOTAL2_TOTAL         NUMBER,
  GRAND_TOTAL_QTY            NUMBER,
  VAT_FREIGHT_TAXABLE        NUMBER,
  TAX_RATE_NAME_T0           VARCHAR2(100 BYTE),
  TAX_RATE_NAME_T1           VARCHAR2(100 BYTE),
  TAX_RATE_NAME_T2           VARCHAR2(100 BYTE),
  TAX_RATE_DESC_T0           VARCHAR2(100 BYTE),
  TAX_RATE_DESC_T1           VARCHAR2(100 BYTE),
  TAX_RATE_DESC_T2           VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAR_B2B_BILLING_HDR_U1  (Index) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_HDR_STG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOAR_B2B_BILLING_HDR_U1 ON XXDO.XXDOAR_B2B_BILLING_HDR_STG
(CONCURRENT_REQUEST_ID, CUSTOMER_TRX_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_B2B_BILLING_HDR_N1  (Index) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_HDR_STG (Table)
--
CREATE INDEX XXDO.XXDOAR_B2B_BILLING_HDR_N1 ON XXDO.XXDOAR_B2B_BILLING_HDR_STG
(PROCESS_FLAG)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_B2B_BILLING_HDR_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_HDR_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAR_B2B_BILLING_HDR_STG FOR XXDO.XXDOAR_B2B_BILLING_HDR_STG
/


--
-- XXDOAR_B2B_BILLING_HDR_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_HDR_STG (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOAR_B2B_BILLING_HDR_STG FOR XXDO.XXDOAR_B2B_BILLING_HDR_STG
/
