--
-- XXDOINV010_INT  (Table) 
--
CREATE TABLE XXDO.XXDOINV010_INT
(
  SLNO               NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  ORGANIZATION_ID    NUMBER,
  STYLE              VARCHAR2(40 BYTE),
  COLOR              VARCHAR2(40 BYTE),
  SZE                VARCHAR2(40 BYTE),
  REGION_CODE        VARCHAR2(40 BYTE),
  REGION_COST        VARCHAR2(40 BYTE),
  STATUS_FLAG        VARCHAR2(10 BYTE)          DEFAULT 'N',
  PROCESSED_FLAG     VARCHAR2(10 BYTE)          DEFAULT 'N',
  TRANSMISSION_DATE  TIMESTAMP(6)               DEFAULT SYSDATE,
  ERRORCODE          VARCHAR2(240 BYTE),
  XDATA              CLOB,
  RETVAL             CLOB,
  STORE_WAREHOUSE    VARCHAR2(10 CHAR),
  PARENT_REQUEST_ID  NUMBER,
  CHILD_REQUEST_ID   NUMBER
)
LOB (RETVAL) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (XDATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOINV010_INT_U1  (Index) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOINV010_INT_U1 ON XXDO.XXDOINV010_INT
(SLNO)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOINV010_INT_N1  (Index) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE INDEX XXDO.XXDOINV010_INT_N1 ON XXDO.XXDOINV010_INT
(INVENTORY_ITEM_ID, ORGANIZATION_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOINV010_INT_N2  (Index) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE INDEX XXDO.XXDOINV010_INT_N2 ON XXDO.XXDOINV010_INT
(STYLE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOINV010_INT_N3  (Index) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE INDEX XXDO.XXDOINV010_INT_N3 ON XXDO.XXDOINV010_INT
(COLOR)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOINV010_INT_N4  (Index) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE INDEX XXDO.XXDOINV010_INT_N4 ON XXDO.XXDOINV010_INT
(SZE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOINV010_INT_N5  (Index) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE INDEX XXDO.XXDOINV010_INT_N5 ON XXDO.XXDOINV010_INT
(PARENT_REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOINV010_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOINV010_INT FOR XXDO.XXDOINV010_INT
/


--
-- XXDOINV010_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOINV010_INT (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOINV010_INT FOR XXDO.XXDOINV010_INT
/
