--
-- XXDO_INV_ITM_MVMT_TABLE  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_ITM_MVMT_TABLE
(
  INTEGRATION_CODE    VARCHAR2(100 BYTE),
  LAST_RUN_DATE_TIME  DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_ITM_MVMT_TABLE  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_ITM_MVMT_TABLE (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INV_ITM_MVMT_TABLE FOR XXDO.XXDO_INV_ITM_MVMT_TABLE
/


--
-- XXDO_INV_ITM_MVMT_TABLE  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_ITM_MVMT_TABLE (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDO_INV_ITM_MVMT_TABLE FOR XXDO.XXDO_INV_ITM_MVMT_TABLE
/
