--
-- XXDOEC_RETURN_LINES_STAGING  (Table) 
--
CREATE TABLE XXDO.XXDOEC_RETURN_LINES_STAGING
(
  ID                   NUMBER                   NOT NULL,
  SKU                  VARCHAR2(100 BYTE),
  UPC                  VARCHAR2(50 BYTE),
  QUANTITY             NUMBER,
  LINE_TYPE            VARCHAR2(25 BYTE),
  ORDER_ID             VARCHAR2(50 BYTE),
  LINE_ID              VARCHAR2(25 BYTE),
  EXCHANGE_PREFERENCE  NUMBER,
  STATUS               VARCHAR2(1 BYTE),
  RETURN_REASON        VARCHAR2(25 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- RETURN_HEADER_LINES_IDX1  (Index) 
--
--  Dependencies: 
--   XXDOEC_RETURN_LINES_STAGING (Table)
--
CREATE INDEX XXDO.RETURN_HEADER_LINES_IDX1 ON XXDO.XXDOEC_RETURN_LINES_STAGING
(ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- RETURN_HEADER_LINES_IDX2  (Index) 
--
--  Dependencies: 
--   XXDOEC_RETURN_LINES_STAGING (Table)
--
CREATE INDEX XXDO.RETURN_HEADER_LINES_IDX2 ON XXDO.XXDOEC_RETURN_LINES_STAGING
(ORDER_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDOEC_RETURN_LINES_STAGING ADD (
  CONSTRAINT FK_ID 
  FOREIGN KEY (ID) 
  REFERENCES XXDO.XXDOEC_RETURN_HEADER_STAGING (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
