--
-- XXD_GL_RECON_REP_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_GL_RECON_REP_GT
(
  DESCRIPTION                 VARCHAR2(1000 BYTE),
  SHORT_CODE                  VARCHAR2(100 BYTE),
  RECEIPT_NUM                 VARCHAR2(100 BYTE),
  GL_DATE                     DATE,
  REMIT_DATE                  DATE,
  CUSTOMER_NAME               VARCHAR2(360 BYTE),
  PAYMENT_METHOD              VARCHAR2(100 BYTE),
  STATUS                      VARCHAR2(100 BYTE),
  CURRENCY                    VARCHAR2(15 BYTE),
  AMOUNT                      VARCHAR2(100 BYTE),
  ACCOUNTED_AMT               VARCHAR2(100 BYTE),
  PAYMENT_NUM                 NUMBER,
  SUPPLIER_NAME               VARCHAR2(240 BYTE),
  PAYMENT_DATE                DATE,
  CASHFLOW_NUM                NUMBER,
  TRANSACTION_DATE            DATE,
  COUNTERPARTY_NAME           VARCHAR2(240 BYTE),
  TRANSACTION_SUBTYPE         VARCHAR2(30 BYTE),
  JE_LINE_NUM                 NUMBER,
  JE_EFFECTIVE_DATE           DATE,
  JE_POSTED_DATE              DATE,
  JE_ENTRY_NAME               VARCHAR2(200 BYTE),
  JE_LINE_TYPE                VARCHAR2(100 BYTE),
  ERR_STATEMENT               VARCHAR2(100 BYTE),
  ERR_STATEMENT_DATE          DATE,
  ERR_TRANSACTION_DATE        DATE,
  ERR_TRANSACTION_TYPE        VARCHAR2(100 BYTE),
  ERR_LINE_NUM                NUMBER,
  GL_ACCOUNT_COMB             VARCHAR2(200 BYTE),
  STATEMENT_NUM               VARCHAR2(100 BYTE),
  STATEMENT_LINE_DESC         VARCHAR2(300 BYTE),
  STATEMENT_TRANSACTION_CODE  VARCHAR2(100 BYTE),
  STATEMENT_DATE              DATE,
  STATEMENT_TRX_TYPE          VARCHAR2(100 BYTE),
  STATEMENT_LINE_NUM          NUMBER,
  STATEMENT_EFF_DATE          DATE,
  BANK_TRX_NUMBER             VARCHAR2(240 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_RECON_REP_GT TO APPS
/
