--
-- XXDO_INV_MINMAX_UPLOAD_LOG  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_MINMAX_UPLOAD_LOG
(
  CHANGE_SEQ_ID                 NUMBER,
  ORGANIZATION_ID               NUMBER,
  SUBINVENTORY_NAME             VARCHAR2(10 BYTE),
  SOURCE_ORG_ID                 NUMBER,
  INVENTORY_ITEM_ID             NUMBER,
  MIN_QUANTITY                  NUMBER,
  MAX_QUANTITY                  NUMBER,
  LEAD_TIME                     NUMBER,
  PREPROCESSING_LEAD_TIME       NUMBER,
  PROCESSING_LEAD_TIME          NUMBER,
  POSTPROCESSING_LEAD_TIME      NUMBER,
  OLD_MIN_QUANTITY              NUMBER,
  OLD_MAX_QUANTITY              NUMBER,
  OLD_PREPROCESSING_LEAD_TIME   NUMBER,
  OLD_PROCESSING_LEAD_TIME      NUMBER,
  OLD_POSTPROCESSING_LEAD_TIME  NUMBER,
  CREATED_BY                    NUMBER,
  CREATION_DATE                 DATE,
  LAST_UPDATED_BY               NUMBER,
  LAST_UPDATE_DATE              DATE,
  LAST_UPDATE_LOGIN             NUMBER,
  ATTRIBUTE1                    VARCHAR2(240 BYTE),
  ATTRIBUTE2                    VARCHAR2(240 BYTE),
  ATTRIBUTE3                    VARCHAR2(240 BYTE),
  ATTRIBUTE4                    VARCHAR2(240 BYTE),
  ATTRIBUTE5                    VARCHAR2(240 BYTE),
  ATTRIBUTE6                    VARCHAR2(240 BYTE),
  ATTRIBUTE7                    VARCHAR2(240 BYTE),
  ATTRIBUTE8                    VARCHAR2(240 BYTE),
  ATTRIBUTE9                    VARCHAR2(240 BYTE),
  ATTRIBUTE10                   VARCHAR2(240 BYTE),
  ATTRIBUTE11                   VARCHAR2(240 BYTE),
  ATTRIBUTE12                   VARCHAR2(240 BYTE),
  ATTRIBUTE13                   VARCHAR2(240 BYTE),
  ATTRIBUTE14                   VARCHAR2(240 BYTE),
  ATTRIBUTE15                   VARCHAR2(240 BYTE),
  ATTRIBUTE16                   VARCHAR2(240 BYTE),
  ATTRIBUTE17                   VARCHAR2(240 BYTE),
  ATTRIBUTE18                   VARCHAR2(240 BYTE),
  ATTRIBUTE19                   VARCHAR2(240 BYTE),
  ATTRIBUTE20                   VARCHAR2(240 BYTE),
  FIXED_LOT_MULTIPLIER          NUMBER,
  OLD_FIXED_LOT_MULTIPLIER      NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_MINMAX_UPLOAD_LOG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_MINMAX_UPLOAD_LOG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INV_MINMAX_UPLOAD_LOG FOR XXDO.XXDO_INV_MINMAX_UPLOAD_LOG
/
