--
-- XXD_AP_INV_UPLOAD_HDRS  (Table) 
--
CREATE TABLE XXDO.XXD_AP_INV_UPLOAD_HDRS
(
  PO_NUMBER                 VARCHAR2(100 BYTE),
  INVOICE_NUMBER            VARCHAR2(100 BYTE),
  OPERATING_UNIT            VARCHAR2(100 BYTE),
  VENDOR_NAME               VARCHAR2(100 BYTE),
  VENDOR_SITE_CODE          VARCHAR2(100 BYTE),
  GL_DATE                   DATE,
  INVOICE_AMOUNT            NUMBER,
  INVOICE_DATE              DATE,
  INVOICE_CURRENCY_CODE     VARCHAR2(100 BYTE),
  PAYMENT_METHOD            VARCHAR2(100 BYTE),
  PAYMENT_TERMS             VARCHAR2(100 BYTE),
  USER_ENTERED_TAX          VARCHAR2(100 BYTE),
  TAX_CONTROL_AMT           NUMBER,
  FAPIO_RECEIVED            VARCHAR2(10 BYTE),
  APPROVER                  VARCHAR2(100 BYTE),
  DATE_SENT_APPROVER        VARCHAR2(100 BYTE),
  MISC_NOTES                VARCHAR2(100 BYTE),
  CHARGEBACK                VARCHAR2(100 BYTE),
  INVOICE_NUMBER_D          VARCHAR2(100 BYTE),
  PAYMENT_REF               VARCHAR2(100 BYTE),
  SAMPLE_INVOICE            VARCHAR2(100 BYTE),
  TAX_CLASSIFICATION_CODE   VARCHAR2(100 BYTE),
  ORG_ID                    NUMBER,
  VENDOR_ID                 NUMBER,
  VENDOR_SITE_ID            NUMBER,
  PAYMENT_TERMS_ID          NUMBER,
  TEMP_INVOICE_HDR_ID       NUMBER,
  UNIQUE_SEQ                VARCHAR2(100 BYTE),
  PROCESS_FLAG              VARCHAR2(1 BYTE),
  ERROR_MESSAGE             VARCHAR2(4000 BYTE),
  PAYMENT_CODE              VARCHAR2(100 BYTE),
  CREATED_BY                NUMBER,
  LAST_UPDATED_BY           NUMBER,
  LAST_UPDATE_LOGIN         NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATE_DATE          DATE,
  SOURCE                    VARCHAR2(100 BYTE),
  INVOICE_ID                NUMBER,
  PO_HEADER_ID              NUMBER,
  FAPIO_FLAG                VARCHAR2(10 BYTE),
  SAMPLE_INV_FLAG           VARCHAR2(10 BYTE),
  INVOICE_TYPE_LOOKUP_CODE  VARCHAR2(100 BYTE),
  VENDOR_NUMBER             VARCHAR2(30 BYTE),
  HDR_DESCRIPTION           VARCHAR2(240 BYTE),
  INV_ADDL_INFO             VARCHAR2(240 BYTE),
  PAY_ALONE                 VARCHAR2(10 BYTE),
  PAY_ALONE_FLAG            VARCHAR2(10 BYTE),
  PAY_GROUP                 VARCHAR2(500 BYTE),
  PAYMENT_HOLD              VARCHAR2(5 BYTE),
  REQUEST_ID                NUMBER,
  MTD_OU_FLAG               VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_AP_INV_UPLOAD_HDRS TO APPS
/
