--
-- XXD_ONT_CALLOFF_ORDER_RELINK_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_CALLOFF_ORDER_RELINK_T
(
  ORG_ID                  NUMBER,
  HEADER_ID               NUMBER,
  ORDER_NUMBER            NUMBER,
  SOLD_TO_ORG_ID          NUMBER,
  CUST_PO_NUMBER          VARCHAR2(50 BYTE),
  REQUEST_DATE            DATE,
  ORDER_BRAND             VARCHAR2(50 BYTE),
  LINE_ID                 NUMBER,
  LINE_NUMBER             NUMBER,
  SHIPMENT_NUMBER         NUMBER,
  ORDERED_ITEM            VARCHAR2(2000 BYTE),
  INVENTORY_ITEM_ID       NUMBER,
  ORDERED_QUANTITY        NUMBER,
  LINE_REQUEST_DATE       DATE,
  SCHEDULE_SHIP_DATE      DATE,
  LATEST_ACCEPTABLE_DATE  DATE,
  LINE_DEMAND_CLASS_CODE  VARCHAR2(30 BYTE),
  BULK_AVAILABLE          VARCHAR2(1 BYTE),
  PARENT_REQUEST_ID       NUMBER,
  REQUEST_ID              NUMBER,
  BATCH_ID                NUMBER,
  REPROCESS_HOLD_ID       NUMBER,
  STATUS                  VARCHAR2(1 BYTE),
  ERROR_MESSAGE           VARCHAR2(4000 BYTE),
  CREATION_DATE           DATE,
  CREATED_BY              NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATED_BY         NUMBER,
  LAST_UPDATE_LOGIN       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_CALLOFF_ORDER_RELINK_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_CALLOFF_ORDER_RELINK_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_CALLOFF_ORDER_RELINK_T FOR XXDO.XXD_ONT_CALLOFF_ORDER_RELINK_T
/
