--
-- XXD_OE_US_LOYALTY_POINTS_T  (Table) 
--
CREATE TABLE XXDO.XXD_OE_US_LOYALTY_POINTS_T
(
  CREATED_AT                   VARCHAR2(100 BYTE),
  ACQ_BEGINING_BALANCE         VARCHAR2(100 BYTE),
  ACQ_EARNED                   VARCHAR2(100 BYTE),
  ACQ_REWARD                   VARCHAR2(100 BYTE),
  ACQ_EXPIRED                  VARCHAR2(100 BYTE),
  ACQ_RETURNED                 VARCHAR2(100 BYTE),
  ACQ_ENDING_BALANCE           VARCHAR2(100 BYTE),
  ACQ_CONVERSION               VARCHAR2(100 BYTE),
  PARTNER_ACQ_BEGIN_BALANCE    VARCHAR2(100 BYTE),
  PARTNER_ACQ_EARNED           VARCHAR2(100 BYTE),
  PARTNER_ACQ_REWARD           VARCHAR2(100 BYTE),
  PARTNER_ACQ_EXPIRED          VARCHAR2(100 BYTE),
  PARTNER_ACQ_ENDING_BALANCE   VARCHAR2(100 BYTE),
  ENGAGEMENT_BEGINING_BALANCE  VARCHAR2(100 BYTE),
  ENGAGEMENT_EARNED            VARCHAR2(100 BYTE),
  ENGAGEMENT_REWARD            VARCHAR2(100 BYTE),
  ENGAGEMENT_EXPIRED           VARCHAR2(100 BYTE),
  ENGAGEMENT_RETURNED          VARCHAR2(100 BYTE),
  ENGAGEMENT_ADJUSTED          VARCHAR2(100 BYTE),
  ENGAGEMENT_ENDING_BALANCE    VARCHAR2(100 BYTE),
  ENGAGEMENT_CONVERSION        VARCHAR2(100 BYTE),
  OVERAGE_BEGINING_BALANCE     VARCHAR2(100 BYTE),
  OVERAGE_REWARD               VARCHAR2(100 BYTE),
  OVERAGE_EXPIRED              VARCHAR2(100 BYTE),
  OVERAGE_ADJUSTED             VARCHAR2(100 BYTE),
  OVERAGE_ENDING_BALANCE       VARCHAR2(100 BYTE),
  TOTAL_DAY                    VARCHAR2(100 BYTE),
  TOTAL_ENDING_BALANCE         VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE1            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE2            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE3            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE4            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE5            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE6            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE7            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE8            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE9            VARCHAR2(100 BYTE),
  FUTURE_ATTRIBUTE10           VARCHAR2(100 BYTE),
  ENTITY_UNIQUE_IDENTIFIER     VARCHAR2(10 BYTE),
  ACCOUNT_NUMBER               VARCHAR2(10 BYTE),
  KEY3                         VARCHAR2(10 BYTE),
  KEY                          VARCHAR2(10 BYTE),
  KEY5                         VARCHAR2(10 BYTE),
  KEY6                         VARCHAR2(10 BYTE),
  KEY7                         VARCHAR2(10 BYTE),
  KEY8                         VARCHAR2(10 BYTE),
  KEY9                         VARCHAR2(10 BYTE),
  KEY10                        VARCHAR2(10 BYTE),
  PERIOD_END_DATE              VARCHAR2(20 BYTE),
  SUBLEDGER_REP_BAL            NUMBER,
  SUBLEDGER_ALT_BAL            NUMBER,
  SUBLEDGER_ACC_BAL            NUMBER,
  CREATED_BY                   NUMBER,
  CREATION_DATE                DATE,
  LAST_UPDATED_BY              NUMBER,
  LAST_UPDATE_DATE             DATE,
  REQUEST_ID                   NUMBER,
  FILE_NAME                    VARCHAR2(100 BYTE),
  ORG_ID                       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_OE_US_LOYALTY_POINTS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_OE_US_LOYALTY_POINTS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_OE_US_LOYALTY_POINTS_T FOR XXDO.XXD_OE_US_LOYALTY_POINTS_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_OE_US_LOYALTY_POINTS_T TO APPS
/
