--
-- XXDO_EDI_856_REPORTING_NEW  (Table) 
--
CREATE TABLE XXDO.XXDO_EDI_856_REPORTING_NEW
(
  SHIPMENT_ID         VARCHAR2(1000 BYTE),
  PARTNER             VARCHAR2(1000 BYTE),
  ACCOUNT_NUMBER      VARCHAR2(100 BYTE),
  BATCH_NUMBER        NUMBER(30),
  CURRENT_STATUS      VARCHAR2(100 BYTE),
  CURRENT_DATE        DATE,
  CREATION_DATE       DATE,
  B2BID               VARCHAR2(2000 BYTE),
  B2B_CONTROL         VARCHAR2(2000 BYTE),
  B2B_ERRORMESSAGE    VARCHAR2(2000 BYTE),
  B2B_STATUS          VARCHAR2(2000 BYTE),
  SHIPCONFIRM_DATE    VARCHAR2(100 BYTE),
  BAM_STATUS          VARCHAR2(100 BYTE),
  EXISTS_IN_VIEW      VARCHAR2(1 BYTE),
  EXISTS_IN_SOA       VARCHAR2(1 BYTE),
  EXISTS_IN_B2B       VARCHAR2(1 BYTE),
  SHIPNOTICE_NUMBER   VARCHAR2(100 BYTE),
  REQUIRED_REPROCESS  VARCHAR2(1 BYTE),
  ATTRIBUTE1          VARCHAR2(200 BYTE),
  ATTRIBUTE2          VARCHAR2(200 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_EDI_856_REPORTING_NEW  (Synonym) 
--
--  Dependencies: 
--   XXDO_EDI_856_REPORTING_NEW (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXDO_EDI_856_REPORTING_NEW FOR XXDO.XXDO_EDI_856_REPORTING_NEW
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_EDI_856_REPORTING_NEW TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_EDI_856_REPORTING_NEW TO SOA_INT
/
