--
-- XXDO_DC_SUPPORT_FIX_AUDIT  (Table) 
--
CREATE TABLE XXDO.XXDO_DC_SUPPORT_FIX_AUDIT
(
  REQUEST_ID             NUMBER                 NOT NULL,
  INCIDENT_NUM           VARCHAR2(30 BYTE)      NOT NULL,
  TABLE_NAME             VARCHAR2(50 BYTE)      NOT NULL,
  ID_COLUMN              VARCHAR2(50 BYTE)      NOT NULL,
  ID_COLUMN_VALUE        NUMBER                 NOT NULL,
  STATUS                 VARCHAR2(30 BYTE)      NOT NULL,
  OLD_SUBINV_CODE        VARCHAR2(30 BYTE),
  NEW_SUBINV_CODE        VARCHAR2(30 BYTE),
  OLD_LOCATOR_ID         NUMBER,
  NEW_LOCATOR_ID         NUMBER,
  OLD_LPN_CONTEXT        NUMBER,
  NEW_LPN_CONTEXT        NUMBER,
  OLD_PARENT_LPN_ID      NUMBER,
  NEW_PARENT_LPN_ID      NUMBER,
  OLD_OUTER_LPN_ID       NUMBER,
  NEW_OUTER_LPN_ID       NUMBER,
  OLD_MMTT_LPN_ID        NUMBER,
  NEW_MMTT_LPN_ID        NUMBER,
  OLD_MMTT_TRANS_LPN_ID  NUMBER,
  NEW_MMTT_TRANS_LPN_ID  NUMBER,
  DELETE_WSTT_COUNT      NUMBER,
  COMMENTS               VARCHAR2(300 BYTE),
  ATTRIBUTE1             VARCHAR2(100 BYTE),
  ATTRIBUTE2             VARCHAR2(100 BYTE),
  ATTRIBUTE3             VARCHAR2(100 BYTE),
  ATTRIBUTE4             VARCHAR2(100 BYTE),
  ATTRIBUTE5             VARCHAR2(100 BYTE),
  CREATION_DATE          DATE                   NOT NULL,
  CREATED_BY             NUMBER                 NOT NULL,
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  LAST_UPDATED_BY        NUMBER                 NOT NULL,
  LAST_UPDATE_LOGIN      NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_DC_SUPPORT_FIX_AUDIT_PK  (Index) 
--
--  Dependencies: 
--   XXDO_DC_SUPPORT_FIX_AUDIT (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_DC_SUPPORT_FIX_AUDIT_PK ON XXDO.XXDO_DC_SUPPORT_FIX_AUDIT
(REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDO_DC_SUPPORT_FIX_AUDIT ADD (
  CONSTRAINT XXDO_DC_SUPPORT_FIX_AUDIT_PK
  PRIMARY KEY
  (REQUEST_ID)
  USING INDEX XXDO.XXDO_DC_SUPPORT_FIX_AUDIT_PK
  ENABLE VALIDATE)
/


--
-- XXDO_DC_SUPPORT_FIX_AUDIT  (Synonym) 
--
--  Dependencies: 
--   XXDO_DC_SUPPORT_FIX_AUDIT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_DC_SUPPORT_FIX_AUDIT FOR XXDO.XXDO_DC_SUPPORT_FIX_AUDIT
/
