--
-- XXDO_FSCOPE_MON_JOBS  (Table) 
--
CREATE TABLE XXDO.XXDO_FSCOPE_MON_JOBS
(
  LOOKUP_CODE          VARCHAR2(30 BYTE),
  LOOKUP_TYPE          VARCHAR2(30 BYTE),
  MEANING              VARCHAR2(80 BYTE),
  DESCRIPTION          VARCHAR2(240 BYTE),
  ATTRIBUTE1           VARCHAR2(150 BYTE),
  ATTRIBUTE2           VARCHAR2(150 BYTE),
  ATTRIBUTE3           VARCHAR2(150 BYTE),
  ATTRIBUTE4           VARCHAR2(150 BYTE),
  ATTRIBUTE5           VARCHAR2(150 BYTE),
  ATTRIBUTE6           VARCHAR2(150 BYTE),
  LANGUAGE             VARCHAR2(30 BYTE),
  RESPONSIBILITY_NAME  VARCHAR2(60 BYTE),
  SCHEDULE_TIME        NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_FSCOPE_MON_JOBS  (Synonym) 
--
--  Dependencies: 
--   XXDO_FSCOPE_MON_JOBS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_FSCOPE_MON_JOBS FOR XXDO.XXDO_FSCOPE_MON_JOBS
/
