--
-- XXDO_PERF_MEASURES_LOG  (Table) 
--
CREATE TABLE XXDO.XXDO_PERF_MEASURES_LOG
(
  LOG_ID             NUMBER                     NOT NULL,
  PERF_MEASURE_NAME  VARCHAR2(100 BYTE)         NOT NULL,
  START_DATE         DATE                       NOT NULL,
  END_DATE           DATE                       NOT NULL,
  USER_NAME          VARCHAR2(100 BYTE),
  MEASURE_NUMERIC    NUMBER,
  MEASURE_QUALIFIER  VARCHAR2(50 BYTE),
  PARAMETER_1        VARCHAR2(100 BYTE),
  PARAMETER_2        VARCHAR2(100 BYTE),
  PARAMETER_3        VARCHAR2(100 BYTE),
  PARAMETER_4        VARCHAR2(100 BYTE),
  PARAMETER_5        VARCHAR2(100 BYTE),
  PARAMETER_6        VARCHAR2(100 BYTE),
  PARAMETER_7        VARCHAR2(100 BYTE),
  PARAMETER_8        VARCHAR2(100 BYTE),
  PARAMETER_9        VARCHAR2(100 BYTE),
  PARAMETER_10       VARCHAR2(100 BYTE),
  PARAMETER_11       VARCHAR2(100 BYTE),
  PARAMETER_12       VARCHAR2(100 BYTE),
  PARAMETER_13       VARCHAR2(100 BYTE),
  PARAMETER_14       VARCHAR2(100 BYTE),
  PARAMETER_15       VARCHAR2(100 BYTE),
  PARAMETER_16       VARCHAR2(100 BYTE),
  PARAMETER_17       VARCHAR2(100 BYTE),
  PARAMETER_18       VARCHAR2(100 BYTE),
  PARAMETER_19       VARCHAR2(100 BYTE),
  PARAMETER_20       VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_PERF_MEASURES_PK  (Index) 
--
--  Dependencies: 
--   XXDO_PERF_MEASURES_LOG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_PERF_MEASURES_PK ON XXDO.XXDO_PERF_MEASURES_LOG
(LOG_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDO_PERF_MEASURES_LOG ADD (
  CONSTRAINT XXDO_PERF_MEASURES_PK
  PRIMARY KEY
  (LOG_ID)
  USING INDEX XXDO.XXDO_PERF_MEASURES_PK
  ENABLE VALIDATE)
/


--
-- XXDO_PERF_MEASURES_LOG  (Synonym) 
--
--  Dependencies: 
--   XXDO_PERF_MEASURES_LOG (Table)
--
CREATE OR REPLACE SYNONYM XXDO_CLIP.XXDO_PERF_MEASURES_LOG FOR XXDO.XXDO_PERF_MEASURES_LOG
/


GRANT INSERT, SELECT, UPDATE ON XXDO.XXDO_PERF_MEASURES_LOG TO XXDO_CLIP
/
