--
-- XXD_ONT_PK_INTF_P_HDR_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_PK_INTF_P_HDR_STG_T
(
  WAREHOUSE_CODE     VARCHAR2(10 BYTE),
  ORDER_NUMBER       VARCHAR2(30 BYTE),
  VAS_CODE           VARCHAR2(20 BYTE),
  PARAMETER          VARCHAR2(100 BYTE),
  PARAMETER_VALUE    VARCHAR2(1000 BYTE),
  PROCESS_STATUS     VARCHAR2(20 BYTE),
  ERROR_MESSAGE      VARCHAR2(1000 BYTE),
  REQUEST_ID         NUMBER,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER,
  SOURCE             VARCHAR2(20 BYTE),
  DESTINATION        VARCHAR2(20 BYTE),
  BATCH_NUMBER       NUMBER,
  ATTRIBUTE1         VARCHAR2(240 BYTE),
  ATTRIBUTE2         VARCHAR2(240 BYTE),
  ATTRIBUTE3         VARCHAR2(240 BYTE),
  ATTRIBUTE4         VARCHAR2(240 BYTE),
  ATTRIBUTE5         VARCHAR2(240 BYTE),
  ATTRIBUTE6         VARCHAR2(240 BYTE),
  ATTRIBUTE7         VARCHAR2(240 BYTE),
  ATTRIBUTE8         VARCHAR2(240 BYTE),
  ATTRIBUTE9         VARCHAR2(240 BYTE),
  ATTRIBUTE10        VARCHAR2(240 BYTE),
  ATTRIBUTE11        VARCHAR2(240 BYTE),
  ATTRIBUTE12        VARCHAR2(240 BYTE),
  ATTRIBUTE13        VARCHAR2(240 BYTE),
  ATTRIBUTE14        VARCHAR2(240 BYTE),
  ATTRIBUTE15        VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_PK_INTF_HDR_STG_N1  (Index) 
--
--  Dependencies: 
--   XXD_ONT_PK_INTF_P_HDR_STG_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_PK_INTF_HDR_STG_N1 ON XXDO.XXD_ONT_PK_INTF_P_HDR_STG_T
(PROCESS_STATUS, REQUEST_ID, ORDER_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_ONT_PK_INTF_P_HDR_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_PK_INTF_P_HDR_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_PK_INTF_P_HDR_STG_T FOR XXDO.XXD_ONT_PK_INTF_P_HDR_STG_T
/


GRANT DELETE, INSERT, SELECT, UPDATE ON XXDO.XXD_ONT_PK_INTF_P_HDR_STG_T TO SOA_INT
/
