--
-- XXDOPO_EARLIER_RECEIPTS  (Table) 
--
CREATE TABLE XXDO.XXDOPO_EARLIER_RECEIPTS
(
  INVENTORY_ITEM_ID  NUMBER,
  RECEIPT_DATE       DATE,
  RECEIPT_NUM        VARCHAR2(50 BYTE),
  PO_NUM             VARCHAR2(30 BYTE),
  VENDOR_ID          NUMBER,
  VENDOR             VARCHAR2(240 BYTE),
  STYLE              VARCHAR2(20 BYTE),
  COLOR              VARCHAR2(20 BYTE),
  RECEIVED_QTY       NUMBER,
  UNIT_PRICE         NUMBER,
  RECEIVED_VALUE     NUMBER,
  FTY_INVC_NUM       VARCHAR2(50 BYTE),
  SALES_REGION       VARCHAR2(50 BYTE),
  COST_CENTER        VARCHAR2(50 BYTE),
  COUNTRY            VARCHAR2(50 BYTE),
  BRAND              VARCHAR2(50 BYTE),
  ORG_ID             NUMBER,
  PO_TYPE            VARCHAR2(50 BYTE),
  CURRENT_MONTH      VARCHAR2(10 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOPO_EARLIER_RECEIPTS  (Index) 
--
--  Dependencies: 
--   XXDOPO_EARLIER_RECEIPTS (Table)
--
CREATE INDEX XXDO.XXDOPO_EARLIER_RECEIPTS ON XXDO.XXDOPO_EARLIER_RECEIPTS
(ORG_ID, FTY_INVC_NUM, PO_NUM, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOPO_EARLIER_RECEIPTS  (Synonym) 
--
--  Dependencies: 
--   XXDOPO_EARLIER_RECEIPTS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOPO_EARLIER_RECEIPTS FOR XXDO.XXDOPO_EARLIER_RECEIPTS
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOPO_EARLIER_RECEIPTS TO APPS
/

GRANT SELECT ON XXDO.XXDOPO_EARLIER_RECEIPTS TO APPSRO WITH GRANT OPTION
/
