--
-- XXD_ICX_POREQ_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_ICX_POREQ_STG_T
(
  RECORD_ID             NUMBER                  NOT NULL,
  CART_NUM              NUMBER,
  CART_LINE_NUM         NUMBER,
  OPERATING_UNIT        VARCHAR2(240 BYTE),
  PO_ITEM_CAT           VARCHAR2(240 BYTE),
  ITEM_TYPE             VARCHAR2(240 BYTE),
  ITEM_DESC             VARCHAR2(240 BYTE),
  REQUESTER             VARCHAR2(240 BYTE),
  QUANTITY              NUMBER,
  UOM                   VARCHAR2(100 BYTE),
  UNIT_PRICE            NUMBER,
  AMOUNT                NUMBER,
  CURRENCY              VARCHAR2(50 BYTE),
  VENDOR_NAME           VARCHAR2(240 BYTE),
  VENDOR_SITE           VARCHAR2(240 BYTE),
  NEED_BY_DATE          DATE,
  CHARGE_ACCOUNT        VARCHAR2(240 BYTE),
  DELIVER_TO_LOC        VARCHAR2(240 BYTE),
  JUSTIFICATION         VARCHAR2(500 BYTE),
  GL_COMPANY            VARCHAR2(100 BYTE),
  GL_BRAND              VARCHAR2(100 BYTE),
  GL_GEO                VARCHAR2(100 BYTE),
  GL_CHANNEL            VARCHAR2(100 BYTE),
  GL_COST_CENTER        VARCHAR2(100 BYTE),
  GL_ACCOUNT            VARCHAR2(100 BYTE),
  GL_INTERCO            VARCHAR2(100 BYTE),
  GL_FUTURE             VARCHAR2(100 BYTE),
  CHARGE_ACCOUNT_CCID   NUMBER,
  ORG_ID                NUMBER,
  PO_ITEM_CAT_ID        NUMBER,
  PO_ITEM_CAT_CLASS     VARCHAR2(100 BYTE),
  REQUESTER_ID          NUMBER,
  VENDOR_ID             NUMBER,
  VENDOR_SITE_ID        NUMBER,
  DELIVER_TO_LOC_ID     NUMBER,
  GL_VALID_COMPANY      VARCHAR2(100 BYTE),
  GL_VALID_COST_CENTER  VARCHAR2(100 BYTE),
  GL_VALID_ACCOUNT      VARCHAR2(100 BYTE),
  ASSET_EXP_TYPE        VARCHAR2(100 BYTE),
  DEST_ORGANIZATION_ID  NUMBER,
  INTERFACE_BATCH_ID    NUMBER,
  REQUISITION_NUMBER    NUMBER,
  RECORD_STATUS         VARCHAR2(1 BYTE),
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_LOGIN     NUMBER,
  REQUEST_ID            NUMBER,
  ERROR_MESSAGE         VARCHAR2(4000 BYTE),
  PROCESS_MESSAGE       VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
