--
-- XXD_PRICELIST_BKP_INC0337098  (Table) 
--
CREATE TABLE XXDO.XXD_PRICELIST_BKP_INC0337098
(
  NAME                   VARCHAR2(240 BYTE)     NOT NULL,
  LIST_HEADER_ID         NUMBER                 NOT NULL,
  CURRENCY_CODE          VARCHAR2(30 BYTE),
  LIST_LINE_ID           NUMBER                 NOT NULL,
  PRODUCT_ATTRIBUTE      VARCHAR2(30 BYTE),
  PRODUCT_ATTR_VAL_DISP  VARCHAR2(4000 BYTE),
  PRODUCT_UOM_CODE       VARCHAR2(3 BYTE),
  OPERAND                NUMBER,
  START_DATE_ACTIVE      DATE,
  END_DATE_ACTIVE        DATE,
  ATTRIBUTE1             VARCHAR2(240 BYTE),
  ATTRIBUTE2             VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
