--
-- XXD_ONT_AUTO_ATP_SUMRY_BKP_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_AUTO_ATP_SUMRY_BKP_T
(
  BATCH_ID           NUMBER,
  SEQ_NUMBER         NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  ORGANIZATION_ID    NUMBER,
  ITEM_NUMBER        VARCHAR2(100 BYTE),
  NEG_DATE           DATE,
  NEG_QTY            NUMBER,
  NEG_EDATE          DATE,
  SF_EL_QTY          NUMBER,
  SF_EX_QTY          NUMBER,
  AR_EL_QTY          NUMBER,
  AR_EX_QTY          NUMBER,
  UN_EL_QTY          NUMBER,
  UN_EX_QTY          NUMBER,
  PROCESS_STATUS     VARCHAR2(100 BYTE),
  REQUEST_ID         NUMBER,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
