--
-- XXD_FA_ARO_PTD_VALUES_T  (Table) 
--
CREATE TABLE XXDO.XXD_FA_ARO_PTD_VALUES_T
(
  ASSET_NUMBER              VARCHAR2(100 BYTE),
  ASSET_DESCRIPTION         VARCHAR2(100 BYTE),
  ACCERTION_BALANCE_TYPE    VARCHAR2(100 BYTE),
  COST_CENTER               VARCHAR2(10 BYTE),
  PV_ARO_AT_ESTABLISHMENT   NUMBER,
  TOTAL_LIABILITY_LY        NUMBER,
  PV_ARO_ADDITION           NUMBER,
  ACCERTION_ADDITION        NUMBER,
  DELETIONS                 NUMBER,
  GAIN_OR_LOSS              NUMBER,
  TOTAL_LIABILITY_CY        NUMBER,
  TOTAL_TARGET_ARO          NUMBER,
  ASSET_DATE_RETIRED        VARCHAR2(100 BYTE),
  TEAR_DOWN_EXPENSE         NUMBER,
  PERIOD_NUM                NUMBER,
  PERIOD_YEAR               NUMBER,
  PV_FINANCIAL_YEAR         VARCHAR2(20 BYTE),
  ASSET_BOOK                VARCHAR2(30 BYTE),
  PERIOD_NAME               VARCHAR2(30 BYTE),
  PERIOD_COUNTER            NUMBER,
  REGION                    VARCHAR2(30 BYTE),
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATED_BY           NUMBER,
  LAST_UPDATE_DATE          DATE,
  REQUEST_ID                NUMBER,
  PROGRAM_MODE              VARCHAR2(10 BYTE),
  ENTITY_UNIQUE_IDENTIFIER  VARCHAR2(10 BYTE),
  ACCOUNT_NUMBER            VARCHAR2(10 BYTE),
  KEY3                      VARCHAR2(10 BYTE),
  KEY                       VARCHAR2(10 BYTE),
  KEY5                      VARCHAR2(10 BYTE),
  KEY6                      VARCHAR2(10 BYTE),
  KEY7                      VARCHAR2(10 BYTE),
  KEY8                      VARCHAR2(10 BYTE),
  KEY9                      VARCHAR2(10 BYTE),
  KEY10                     VARCHAR2(10 BYTE),
  PERIOD_END_DATE           VARCHAR2(20 BYTE),
  SUBLEDGER_REP_BAL         NUMBER,
  SUBLEDGER_ALT_BAL         NUMBER,
  SUBLEDGER_ACC_BAL         NUMBER,
  SENT_TO_BLACKLINE         VARCHAR2(10 BYTE),
  SENT_TO_GL                VARCHAR2(10 BYTE),
  TOTAL_NET_LIABILITY       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
