--
-- XXD_PLM_ITEM_ATTRIBUTES_SIZE_T  (Table) 
--
CREATE TABLE XXDO.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T
(
  PARENT_RECORD_ID      NUMBER                  NOT NULL,
  SEQUENCE_NUM          NUMBER,
  SIZE_VAL              VARCHAR2(200 BYTE),
  SIZE_DESCRIPTION      VARCHAR2(200 BYTE),
  ITEM_TYPE             VARCHAR2(100 BYTE),
  ERROR_MESSAGE         VARCHAR2(3000 BYTE),
  CREATION_DATE         DATE                    DEFAULT SYSDATE,
  CREATED_BY            NUMBER                  DEFAULT -1,
  LAST_UPDATE_DATE      DATE                    DEFAULT SYSDATE,
  LAST_UPDATED_BY       NUMBER                  DEFAULT -1,
  REQUEST_ID            NUMBER,
  LAST_UPDATE_LOGIN     NUMBER,
  NRF_SIZE_CODE         VARCHAR2(2000 BYTE),
  NRF_SIZE_DESCRIPTION  VARCHAR2(2000 BYTE),
  ATTRIBUTE1            VARCHAR2(2000 BYTE),
  ATTRIBUTE2            VARCHAR2(2000 BYTE),
  ATTRIBUTE3            VARCHAR2(2000 BYTE),
  ATTRIBUTE4            VARCHAR2(2000 BYTE),
  ATTRIBUTE5            VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PLM_ITEM_ATTRIBUTES_SIZE_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PLM_ITEM_ATTRIBUTES_SIZE_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T FOR XXDO.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T
/


--
-- XXD_PLM_ITEM_ATTRIBUTES_SIZE_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PLM_ITEM_ATTRIBUTES_SIZE_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T FOR XXDO.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T
/


ALTER TABLE XXDO.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T ADD (
  FOREIGN KEY (PARENT_RECORD_ID) 
  REFERENCES XXDO.XXD_PLM_ITEM_ATTRIBUTES_T (RECORD_ID)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_PLM_ITEM_ATTRIBUTES_SIZE_T TO SOA_INT
/
