--
-- XXD_AP_INV_EXCEL_UPLOAD_TBL  (Table) 
--
CREATE TABLE XXDO.XXD_AP_INV_EXCEL_UPLOAD_TBL
(
  PO_NUMBER                 VARCHAR2(100 BYTE),
  OPERATING_UNIT            VARCHAR2(100 BYTE),
  SUPPLIER                  VARCHAR2(100 BYTE),
  INVOICE_DATE              DATE,
  INVOICE_AMOUNT            NUMBER,
  USER_ENTERED_TAX          VARCHAR2(100 BYTE),
  TAX_CONTROL_AMT           NUMBER,
  FAPIO_RECEIVED            VARCHAR2(10 BYTE),
  PAYMENT_METHOD            VARCHAR2(100 BYTE),
  PAYMENT_TERMS             VARCHAR2(100 BYTE),
  APPROVER                  VARCHAR2(100 BYTE),
  DATE_SENT_APPROVER        VARCHAR2(100 BYTE),
  MISC_NOTES                VARCHAR2(100 BYTE),
  CHARGEBACK                VARCHAR2(100 BYTE),
  INVOICE_NUMBER_D          VARCHAR2(100 BYTE),
  PAYMENT_REF               VARCHAR2(100 BYTE),
  SAMPLE_INVOICE            VARCHAR2(100 BYTE),
  LINE_TYPE                 VARCHAR2(100 BYTE),
  DESCRIPTION               VARCHAR2(240 BYTE),
  LINE_AMOUNT               NUMBER,
  DIST_ACCOUNT              VARCHAR2(100 BYTE),
  SHIP_TO_LOCATION          VARCHAR2(100 BYTE),
  PO_NUMBER_L               VARCHAR2(100 BYTE),
  PO_LINE_NUM               NUMBER,
  QTY_INVOICED              NUMBER,
  UNIT_PRICE                NUMBER,
  TAX_CLASSIFICATION_CODE   VARCHAR2(100 BYTE),
  INTERCO_EXP_ACCOUNT       VARCHAR2(100 BYTE),
  DEFERRED                  VARCHAR2(100 BYTE),
  DEFERRED_START_DATE       DATE,
  DEFERRED_END_DATE         DATE,
  PRORATE                   VARCHAR2(100 BYTE),
  TRACK_AS_ASSET            VARCHAR2(100 BYTE),
  ASSET_CATEGORY            VARCHAR2(100 BYTE),
  ASSET_BOOK                VARCHAR2(100 BYTE),
  DISTRIBUTION_SET          VARCHAR2(100 BYTE),
  ORG_ID                    NUMBER,
  VENDOR_ID                 NUMBER,
  PAYMENT_CODE              VARCHAR2(100 BYTE),
  TERM_ID                   NUMBER,
  DIST_CCID                 NUMBER,
  SHIP_LOCATION_ID          NUMBER,
  PO_LINE_ID                NUMBER,
  ASSET_ID                  NUMBER,
  ASSET_CAT_ID              NUMBER,
  PROCESS_FLAG              VARCHAR2(1 BYTE),
  ERROR_MESSAGE             VARCHAR2(4000 BYTE),
  CREATED_BY                NUMBER,
  LAST_UPDATED_BY           NUMBER,
  LAST_UPDATE_LOGIN         NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATE_DATE          DATE,
  SUPPLIER_SITE             VARCHAR2(100 BYTE),
  SOURCE                    VARCHAR2(100 BYTE),
  GL_DATE                   DATE,
  VENDOR_SITE_ID            NUMBER,
  LINE_NUMBER               NUMBER,
  CURRENCY_CODE             VARCHAR2(100 BYTE),
  UNIQUE_SEQ                VARCHAR2(100 BYTE),
  DATA_IDENTIFIER           VARCHAR2(100 BYTE),
  TEMP_INVOICE_HDR_ID       NUMBER,
  TEMP_INVOICE_LINE_ID      NUMBER,
  ERROR_MESSAGE_L           VARCHAR2(4000 BYTE),
  PROCESS_FLAG_L            VARCHAR2(1 BYTE),
  SEQ_NO                    NUMBER              NOT NULL,
  LINE_TOTAL                NUMBER,
  INVOICE_NUMBER            VARCHAR2(100 BYTE),
  DIST_SET_ID               NUMBER,
  INTERCO_EXP_ACCOUNT_ID    NUMBER,
  SHIP_TO_LOCATION_ID       NUMBER,
  DIST_ACCOUNT_ID           NUMBER,
  PO_HEADER_ID              NUMBER,
  ASSET_BOOK_CODE           VARCHAR2(100 BYTE),
  DEFERRED_FLAG             VARCHAR2(10 BYTE),
  FAPIO_FLAG                VARCHAR2(10 BYTE),
  ASSET_FLAG                VARCHAR2(10 BYTE),
  PRORATE_FLAG              VARCHAR2(10 BYTE),
  SAMPLE_INV_FLAG           VARCHAR2(10 BYTE),
  INVOICE_TYPE_LOOKUP_CODE  VARCHAR2(100 BYTE),
  PO_HEADER_L_ID            NUMBER,
  VENDOR_NUMBER             VARCHAR2(30 BYTE),
  HDR_DESCRIPTION           VARCHAR2(240 BYTE),
  INV_ADDL_INFO             VARCHAR2(240 BYTE),
  PAY_ALONE                 VARCHAR2(10 BYTE),
  PAY_ALONE_FLAG            VARCHAR2(10 BYTE),
  PAY_GROUP                 VARCHAR2(500 BYTE),
  PAYMENT_HOLD              VARCHAR2(5 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_AP_INV_EXCEL_UPLOAD_TBL TO APPS
/
