--
-- XXD_GTN_DSA_AUDIT_REPORT  (Table) 
--
CREATE TABLE XXDO.XXD_GTN_DSA_AUDIT_REPORT
(
  INVOICE_NUMBER          VARCHAR2(100 BYTE),
  CONFIRMED_PAYMENT_DATE  VARCHAR2(100 BYTE),
  BANK_NAME               VARCHAR2(100 BYTE),
  VENDOR_NAME             VARCHAR2(100 BYTE),
  PAYMENT_ID              VARCHAR2(100 BYTE),
  SETTLEMENT_AMOUNT       VARCHAR2(100 BYTE),
  IN_ORACLE               VARCHAR2(100 BYTE),
  INVOICE_ID              VARCHAR2(100 BYTE),
  INVOICE_QUANTITY        VARCHAR2(100 BYTE),
  ATTRIBUTE1              VARCHAR2(100 BYTE),
  ATTRIBUTE2              VARCHAR2(100 BYTE),
  ATTRIBUTE3              VARCHAR2(100 BYTE),
  ATTRIBUTE4              VARCHAR2(100 BYTE),
  ATTRIBUTE5              VARCHAR2(100 BYTE),
  ORACLE_INVOICE          VARCHAR2(200 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
