--
-- XXDOAR_B2B_CASHAPP_FILES  (Table) 
--
CREATE TABLE XXDO.XXDOAR_B2B_CASHAPP_FILES
(
  FILE_NAME          VARCHAR2(240 BYTE),
  FILE_PATH          VARCHAR2(240 BYTE),
  FILE_PROCESS_FLAG  VARCHAR2(30 BYTE),
  CONC_REQUEST_ID    NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAR_B2B_CASHAPP_FILES  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_B2B_CASHAPP_FILES (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAR_B2B_CASHAPP_FILES FOR XXDO.XXDOAR_B2B_CASHAPP_FILES
/
