--
-- XXDO_PLM_ITEMAST_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_PLM_ITEMAST_STG
(
  SEQ_NUM                NUMBER,
  PARENT_RECORD_ID       NUMBER,
  BATCH_ID               NUMBER,
  STYLE                  VARCHAR2(100 BYTE),
  MASTER_STYLE           VARCHAR2(100 BYTE),
  SCALE_CODE_ID          NUMBER,
  COLOR_CODE             VARCHAR2(100 BYTE),
  COLORWAY               VARCHAR2(2000 BYTE),
  SUB_GROUP              VARCHAR2(2000 BYTE),
  SIZE_VAL               VARCHAR2(100 BYTE),
  SIZE_SCALE_ID          VARCHAR2(100 BYTE),
  INVENTORY_TYPE         VARCHAR2(2000 BYTE),
  BRAND                  VARCHAR2(100 BYTE),
  CLASS                  VARCHAR2(2000 BYTE),
  SUB_CLASS              VARCHAR2(2000 BYTE),
  REGION                 VARCHAR2(100 BYTE),
  GENDER                 VARCHAR2(100 BYTE),
  PROJECTEDCOST          NUMBER,
  LANDEDCOST             NUMBER,
  PURCHASE_COST          NUMBER,
  TEMPLATEID             VARCHAR2(100 BYTE),
  STYLEDESCRIPTION       VARCHAR2(1000 BYTE),
  CURRENTSEASON          VARCHAR2(1000 BYTE),
  BEGIN_DATE             VARCHAR2(100 BYTE),
  END_DATE               VARCHAR2(100 BYTE),
  UOM                    VARCHAR2(100 BYTE),
  COST_TYPE              VARCHAR2(1000 BYTE),
  COUNTRY_CODE           VARCHAR2(100 BYTE),
  FACTORY                VARCHAR2(100 BYTE),
  RANK                   VARCHAR2(100 BYTE),
  LEAD_TIME              VARCHAR2(100 BYTE),
  USER_ID                NUMBER,
  RETAIL_PRICE           NUMBER,
  WHOLESALE_PRICE        NUMBER,
  COLORWAYSTATUS         VARCHAR2(1000 BYTE),
  ORG_ID                 NUMBER,
  ORG_CODE               VARCHAR2(100 BYTE),
  ITEM_ID                NUMBER,
  ITEM_NUMBER            VARCHAR2(100 BYTE),
  ITEM_STATUS            VARCHAR2(100 BYTE),
  STG_REQUEST_ID         NUMBER,
  STATUS_FLAG            VARCHAR2(100 BYTE),
  UPC                    VARCHAR2(100 BYTE),
  BUYER_ID               NUMBER,
  DESCRIPTION            VARCHAR2(240 BYTE),
  ITEMSTATUS             VARCHAR2(30 BYTE),
  UOM_CODE               VARCHAR2(30 BYTE),
  STG_TRANSACTION_TYPE   VARCHAR2(100 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  TARIFF                 VARCHAR2(100 BYTE),
  PROJECT_TYPE           VARCHAR2(240 BYTE),
  COLLECTION             VARCHAR2(240 BYTE),
  ITEM_TYPE              VARCHAR2(240 BYTE),
  SUPPLIER               VARCHAR2(240 BYTE),
  PRODUCTION_LINE        VARCHAR2(240 BYTE),
  PRODUCT_GROUP          VARCHAR2(50 BYTE),
  DETAIL_SILHOUETTE      VARCHAR2(2000 BYTE),
  SUB_DIVISION           VARCHAR2(2000 BYTE),
  LIFE_CYCLE             VARCHAR2(2000 BYTE),
  VENDOR_ID              NUMBER,
  VENDOR_SITE_ID         NUMBER,
  PO_ITEM_CAT_ID         NUMBER,
  SOURCING_FLAG          VARCHAR2(240 BYTE),
  USER_ITEM_TYPE         VARCHAR2(240 BYTE),
  CREATION_DATE          DATE,
  LAST_UPDATED_DATE      DATE,
  CREATED_BY             NUMBER,
  UPDATED_BY             NUMBER,
  PURCHASING_START_DATE  VARCHAR2(1000 BYTE),
  PURCHASING_END_DATE    VARCHAR2(1000 BYTE),
  TARIFF_COUNTRY_CODE    VARCHAR2(100 BYTE),
  STYLE_NAME             VARCHAR2(1000 BYTE),
  NRF_COLOR_CODE         VARCHAR2(2000 BYTE),
  NRF_DESCRIPTION        VARCHAR2(2000 BYTE),
  NRF_SIZE_CODE          VARCHAR2(2000 BYTE),
  NRF_SIZE_DESCRIPTION   VARCHAR2(2000 BYTE),
  INTRO_DATE             VARCHAR2(200 BYTE),
  TQ_SOURCING_NAME       VARCHAR2(200 BYTE),
  DISABLE_AUTO_UPC       VARCHAR2(10 BYTE),
  ATS_DATE               VARCHAR2(20 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- IDX_XXDO_PLM_ITEMAST_STG  (Index) 
--
--  Dependencies: 
--   XXDO_PLM_ITEMAST_STG (Table)
--
CREATE INDEX XXDO.IDX_XXDO_PLM_ITEMAST_STG ON XXDO.XXDO_PLM_ITEMAST_STG
(SEQ_NUM, PARENT_RECORD_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

GRANT SELECT ON XXDO.XXDO_PLM_ITEMAST_STG TO APPSRO
/
