--
-- XXD_OU_ALIGNMENT_LINES_T  (Table) 
--
CREATE TABLE XXDO.XXD_OU_ALIGNMENT_LINES_T
(
  BATCH_ID                                  NUMBER,
  SOURCE_OU                                 VARCHAR2(150 BYTE),
  SOURCE_ORG_ID                             NUMBER,
  SOURCE_CUSTOMER                           VARCHAR2(150 BYTE),
  SOURCE_ORDER_NUMBER                       VARCHAR2(60 BYTE),
  SOURCE_ORDER_CUST_PO_NUMBER               VARCHAR2(150 BYTE),
  SOURCE_ORDER_REQUEST_DATE                 DATE,
  SOURCE_ORDER_SHIP_TO_LOCATION             NUMBER,
  SOURCE_ORDER_BILL_TO_LOCATION             NUMBER,
  SOURCE_ORDER_ORDERED_DATE                 DATE,
  SOURCE_ORDER_CREATION_DATE                DATE,
  SOURCE_ORDER_CANCEL_DATE                  VARCHAR2(240 BYTE),
  SOURCE_ORDER_TYPE                         VARCHAR2(150 BYTE),
  SOURCE_ORDER_SHIP_FROM_WAREHOUSE          NUMBER,
  SOURCE_ORDER_SALES_REP                    NUMBER,
  SOURCE_ORDER_PRICE_LIST                   NUMBER,
  SOURCE_ORDER_LINE_TAX_RATE                NUMBER,
  SOURCE_ORDER_LINE_TAX_AMOUNT              NUMBER,
  SOURCE_LINE_ID                            NUMBER,
  SOURCE_LINE_NUM                           NUMBER,
  SOURCE_ORDER_LINE_ORDERED_ITEM            VARCHAR2(2000 BYTE),
  SOURCE_ORDER_LINE_ORDERED_QUANTITY        NUMBER,
  SOURCE_ORDER_LINE_LATEST_ACCEPTABLE_DATE  DATE,
  SOURCE_ORDER_LINE_CREATION_DATE           DATE,
  SOURCE_ORDER_LINE_SCHEDULE_SHIPPED_DATE   DATE,
  SOURCE_ORDER_LINE_FLOW_STATUS_CODE        VARCHAR2(30 BYTE),
  TARGET_OU                                 VARCHAR2(150 BYTE),
  TARGET_ORG_ID                             NUMBER,
  TARGET_CUSTOMER                           VARCHAR2(150 BYTE),
  TARGET_ORDER_NUMBER                       VARCHAR2(60 BYTE),
  TARGET_ORDER_CUST_PO_NUMBER               VARCHAR2(150 BYTE),
  TARGET_ORDER_REQUEST_DATE                 DATE,
  TARGET_ORDER_SHIP_TO_LOCATION             NUMBER,
  TARGET_ORDER_BILL_TO_LOCATION             NUMBER,
  TARGET_ORDER_ORDERED_DATE                 DATE,
  TARGET_ORDER_CREATION_DATE                DATE,
  TARGET_ORDER_CANCEL_DATE                  VARCHAR2(240 BYTE),
  TARGET_ORDER_TYPE                         VARCHAR2(150 BYTE),
  TARGET_ORDER_SHIP_FROM_WAREHOUSE          VARCHAR2(150 BYTE),
  TARGET_ORDER_SALES_REP                    NUMBER,
  TARGET_ORDER_PRICE_LIST                   VARCHAR2(60 BYTE),
  TARGET_ORDER_LINE_TAX_RATE                NUMBER,
  TARGET_ORDER_LINE_TAX_AMOUNT              NUMBER,
  TARGET_LINE_ID                            NUMBER,
  TARGET_LINE_NUM                           NUMBER,
  TARGET_ORDER_LINE_ORDERED_ITEM            VARCHAR2(2000 BYTE),
  TARGET_ORDER_LINE_ORDERED_QUANTITY        NUMBER,
  TARGET_ORDER_LINE_LATEST_ACCEPTABLE_DATE  DATE,
  TARGET_ORDER_LINE_CREATION_DATE           DATE,
  TARGET_ORDER_LINE_SCHEDULE_SHIPPED_DATE   DATE,
  TARGET_ORDER_LINE_FLOW_STATUS_CODE        VARCHAR2(30 BYTE),
  CREATION_DATE                             DATE,
  CREATED_BY                                NUMBER,
  LAST_UPDATE_DATE                          DATE,
  LAST_UPDATED_BY                           NUMBER,
  REQUEST_ID                                NUMBER,
  ERROR_MESSAGE                             VARCHAR2(2000 BYTE),
  STATUS                                    VARCHAR2(150 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_OU_ALIGNMENT_LINES_T  (Synonym) 
--
--  Dependencies: 
--   XXD_OU_ALIGNMENT_LINES_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_OU_ALIGNMENT_LINES_T FOR XXDO.XXD_OU_ALIGNMENT_LINES_T
/
