--
-- XXD_PO_CONFIRM_DATE_ALERT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_PO_CONFIRM_DATE_ALERT
(
  SALES_REGION      VARCHAR2(240 BYTE)          NOT NULL,
  VENDOR_NAME       VARCHAR2(240 BYTE),
  CREATION_DATE     DATE,
  PO_NUMBER         VARCHAR2(20 BYTE)           NOT NULL,
  SHIP_TO_ID        NUMBER,
  CUSTOMER_NAME     VARCHAR2(360 BYTE),
  BRAND             VARCHAR2(40 BYTE),
  STYLE             VARCHAR2(160 BYTE),
  DESCRIPTION       VARCHAR2(240 BYTE),
  COLOR             VARCHAR2(160 BYTE),
  OPEN_QUANTITY     NUMBER,
  PO_QUANTITY       NUMBER,
  PROMISED_DATE     DATE,
  REQ_EX_FAC_DATE   DATE,
  CONF_EX_FAC_DATE  DATE
)
ON COMMIT DELETE ROWS
NOCACHE
/


--
-- XXD_PO_CONFIRM_DATE_ALERT  (Synonym) 
--
--  Dependencies: 
--   XXD_PO_CONFIRM_DATE_ALERT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PO_CONFIRM_DATE_ALERT FOR XXDO.XXD_PO_CONFIRM_DATE_ALERT
/
