--
-- XXD_ONT_B2B_RA_REPROCESS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_B2B_RA_REPROCESS_T
(
  B2B_RETURN_ORDER     VARCHAR2(1000 BYTE),
  EBS_ORDER_NUMBER     VARCHAR2(1000 BYTE),
  STATUS_NAME          VARCHAR2(1000 BYTE),
  B2B_ORDER_STATUS     VARCHAR2(1000 BYTE),
  PO_NUMBER            VARCHAR2(1000 BYTE),
  BRAND                VARCHAR2(1000 BYTE),
  PROCESS_STATUS       VARCHAR2(100 BYTE),
  PORTAL               VARCHAR2(1000 BYTE),
  ORDER_REQUEST_DATE   VARCHAR2(1000 BYTE),
  ORDER_CREATION_DATE  VARCHAR2(1000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_B2B_RA_REPROCESS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_B2B_RA_REPROCESS_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_ONT_B2B_RA_REPROCESS_T FOR XXDO.XXD_ONT_B2B_RA_REPROCESS_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_ONT_B2B_RA_REPROCESS_T TO SOA_INT
/
