--
-- XXD_PO_PRICE_RULE_ARCHIVE_T  (Table) 
--
CREATE TABLE XXDO.XXD_PO_PRICE_RULE_ARCHIVE_T
(
  PO_PRICE_RULE_ARC_ID  NUMBER,
  PO_PRICE_RULE         VARCHAR2(30 BYTE),
  DESCRIPTION           VARCHAR2(180 BYTE),
  PRICE_SOURCE          VARCHAR2(80 BYTE),
  PRICE_SOURCE_ID       VARCHAR2(80 BYTE),
  RATE_MULTIPLIER       NUMBER,
  RATE_AMOUNT           NUMBER,
  OLD_RATE_MULTIPLIER   NUMBER,
  OLD_RATE_AMOUNT       NUMBER,
  ENABLED_FLAG          VARCHAR2(1 BYTE),
  CREATED_BY            NUMBER,
  CREATION_DATE         DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATE_LOGIN     NUMBER,
  VENDOR_ID             NUMBER,
  VENDOR_NAME           VARCHAR2(100 BYTE),
  ATTRIBUTE1            VARCHAR2(240 BYTE),
  ATTRIBUTE2            VARCHAR2(240 BYTE),
  ATTRIBUTE3            VARCHAR2(240 BYTE),
  ATTRIBUTE4            VARCHAR2(240 BYTE),
  ATTRIBUTE5            VARCHAR2(240 BYTE),
  ATTRIBUTE6            VARCHAR2(240 BYTE),
  ATTRIBUTE7            VARCHAR2(240 BYTE),
  ATTRIBUTE8            VARCHAR2(240 BYTE),
  ATTRIBUTE9            VARCHAR2(240 BYTE),
  ATTRIBUTE10           VARCHAR2(240 BYTE),
  ATTRIBUTE11           VARCHAR2(240 BYTE),
  ATTRIBUTE12           VARCHAR2(240 BYTE),
  ATTRIBUTE13           VARCHAR2(240 BYTE),
  ATTRIBUTE14           VARCHAR2(240 BYTE),
  ATTRIBUTE15           VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PO_PRICE_RULE_ARCHIVE_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PO_PRICE_RULE_ARCHIVE_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PO_PRICE_RULE_ARCHIVE_T FOR XXDO.XXD_PO_PRICE_RULE_ARCHIVE_T
/
