--
-- XXDO_INV_ONHAND_CONV_LOG  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_ONHAND_CONV_LOG
(
  SOURCE_ORG_ID          NUMBER,
  SOURCE_SUBINVENTORY    VARCHAR2(30 BYTE),
  SOURCE_LOCATOR_ID      NUMBER,
  TARGET_ORG_ID          NUMBER,
  TARGET_SUBINVENTORY    VARCHAR2(30 BYTE),
  TARGET_LOCATOR_ID      NUMBER,
  INVENTORY_ITEM_ID      NUMBER,
  QUANTITY               NUMBER,
  AGING_DATE             DATE,
  RCV_TRANSACTION_ID     NUMBER,
  CONV_QUANTITY          NUMBER,
  UOM                    VARCHAR2(30 BYTE),
  BRAND                  VARCHAR2(30 BYTE),
  GENDER                 VARCHAR2(30 BYTE),
  PRODUCT_GROUP          VARCHAR2(40 BYTE),
  PRODUCT_SUBGROUP       VARCHAR2(40 BYTE),
  PROCESS_STATUS         VARCHAR2(30 BYTE),
  ERROR_MESSAGE          VARCHAR2(2000 BYTE),
  CONV_SEQ_ID            NUMBER,
  TRANSACTION_HEADER_ID  NUMBER,
  SOURCE_ORG             VARCHAR2(30 BYTE),
  TARGET_ORG             VARCHAR2(30 BYTE),
  SOURCE_LOCATOR         VARCHAR2(150 BYTE),
  TARGET_LOCATOR         VARCHAR2(150 BYTE),
  ITEM_NUMBER            VARCHAR2(60 BYTE),
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  REQUEST_ID             NUMBER,
  ATTRIBUTE1             VARCHAR2(150 BYTE),
  ATTRIBUTE2             VARCHAR2(150 BYTE),
  ATTRIBUTE3             VARCHAR2(150 BYTE),
  ATTRIBUTE4             VARCHAR2(150 BYTE),
  ATTRIBUTE5             VARCHAR2(150 BYTE),
  ATTRIBUTE6             VARCHAR2(150 BYTE),
  ATTRIBUTE7             VARCHAR2(150 BYTE),
  ATTRIBUTE8             VARCHAR2(150 BYTE),
  ATTRIBUTE9             VARCHAR2(150 BYTE),
  ATTRIBUTE10            VARCHAR2(150 BYTE),
  ATTRIBUTE11            VARCHAR2(150 BYTE),
  ATTRIBUTE12            VARCHAR2(150 BYTE),
  ATTRIBUTE13            VARCHAR2(150 BYTE),
  ATTRIBUTE14            VARCHAR2(150 BYTE),
  ATTRIBUTE15            VARCHAR2(150 BYTE),
  RESERVED_QUANTITY      NUMBER,
  REMARKS                VARCHAR2(1000 BYTE),
  STYLE_NAME             VARCHAR2(240 BYTE),
  COLOR_NAME             VARCHAR2(240 BYTE),
  UPC                    VARCHAR2(240 BYTE),
  DESCRIPTION            VARCHAR2(240 BYTE),
  ITEM_UNIT_COST         NUMBER,
  ARCHIVE_REQUEST_ID     NUMBER,
  ARCHIVE_DATE           DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_ONHAND_CONV_LOG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_ONHAND_CONV_LOG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INV_ONHAND_CONV_LOG FOR XXDO.XXDO_INV_ONHAND_CONV_LOG
/
