--
-- XXD_GL_JE_UPLOAD_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_JE_UPLOAD_STG_T
(
  ACCOUNTING_DATE        NUMBER,
  GL_DR_COMPANY          VARCHAR2(50 BYTE),
  GL_DR_BRAND            VARCHAR2(50 BYTE),
  GL_DR_GEO              VARCHAR2(50 BYTE),
  GL_DR_CHANNEL          VARCHAR2(50 BYTE),
  GL_DR_COST_CENTER      VARCHAR2(50 BYTE),
  GL_DR_ACCOUNT_CODE     VARCHAR2(50 BYTE),
  GL_DR_INTERCO          VARCHAR2(50 BYTE),
  GL_DR_FUTURE           VARCHAR2(50 BYTE),
  ENTERED_DR             NUMBER,
  GL_CR_COMPANY          VARCHAR2(50 BYTE),
  GL_CR_BRAND            VARCHAR2(50 BYTE),
  GL_CR_GEO              VARCHAR2(50 BYTE),
  GL_CR_CHANNEL          VARCHAR2(50 BYTE),
  GL_CR_COST_CENTER      VARCHAR2(50 BYTE),
  GL_CR_ACCOUNT_CODE     VARCHAR2(50 BYTE),
  GL_CR_INTERCO          VARCHAR2(50 BYTE),
  GL_CR_FUTURE           VARCHAR2(50 BYTE),
  ENTERED_CR             NUMBER,
  LINE_DESCRIPTION       VARCHAR2(240 BYTE),
  CREDIT_CCID            VARCHAR2(50 BYTE),
  DEBIT_CCID             VARCHAR2(50 BYTE),
  LEDGER_ID              NUMBER,
  LEDGER_NAME            VARCHAR2(30 BYTE),
  LEDGER_CURRENCY_CODE   VARCHAR2(15 BYTE),
  USER_JE_SOURCE_NAME    VARCHAR2(25 BYTE),
  USER_JE_CATEGORY_NAME  VARCHAR2(25 BYTE),
  JOURNAL_BATCH_NAME     VARCHAR2(50 BYTE),
  JOURNAL_NAME           VARCHAR2(50 BYTE),
  RECORD_STATUS          VARCHAR2(1 BYTE),
  REQUEST_ID             NUMBER,
  FILE_NAME              VARCHAR2(500 BYTE),
  ERROR_MSG              VARCHAR2(4000 BYTE),
  CREATED_BY             NUMBER,
  CREATION_DATE          DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATE_LOGIN      NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_JE_UPLOAD_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_JE_UPLOAD_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_JE_UPLOAD_STG_T FOR XXDO.XXD_GL_JE_UPLOAD_STG_T
/
