--
-- XXDOEC_CP_SHIPMENT_DTLS_STG  (Table) 
--
CREATE TABLE XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
(
  SHIPMENT_ID           NUMBER,
  SENDER_ID             VARCHAR2(120 BYTE),
  ORDER_ID              VARCHAR2(40 BYTE),
  CURRENCY_CODE         VARCHAR2(3 BYTE),
  CARRIER               VARCHAR2(120 BYTE),
  SERVICE_LEVEL         VARCHAR2(120 BYTE),
  WAYBILL               VARCHAR2(120 BYTE),
  TRACKING_NUMBER       VARCHAR2(120 BYTE),
  STATUS                VARCHAR2(40 BYTE),
  SHIPPED_DATE          DATE,
  FLUID_RECIPE_ID       VARCHAR2(50 BYTE),
  ORDER_LINE_NUMBER     NUMBER,
  ITEM_CODE             VARCHAR2(40 BYTE),
  SHIPPED_QUANTITY      NUMBER,
  UNIT_PRICE            NUMBER,
  ITEM_DESCRIPTION      VARCHAR2(240 BYTE),
  PO_RECEIVED_FLAG      VARCHAR2(1 BYTE),
  SO_PICK_RELEASE_FLAG  VARCHAR2(1 BYTE),
  SO_SHIP_CONFIRM_FLAG  VARCHAR2(1 BYTE),
  PO_INVOICED_FLAG      VARCHAR2(1 BYTE),
  ERROR_MESSAGE         VARCHAR2(2000 BYTE),
  PO_LINE_LOCATION_ID   NUMBER,
  SO_DELIVERY_ID        NUMBER,
  SO_LINE_ID            NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_CP_SHIPMENT_DTLS_STG_U1  (Index) 
--
--  Dependencies: 
--   XXDOEC_CP_SHIPMENT_DTLS_STG (Table)
--
CREATE UNIQUE INDEX APPS.XXDOEC_CP_SHIPMENT_DTLS_STG_U1 ON XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
(SHIPMENT_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_CP_SHIPMENT_DTLS_STG_N1  (Index) 
--
--  Dependencies: 
--   XXDOEC_CP_SHIPMENT_DTLS_STG (Table)
--
CREATE INDEX APPS.XXDOEC_CP_SHIPMENT_DTLS_STG_N1 ON XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
(ORDER_ID, TRACKING_NUMBER)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_CP_SHIPMENT_DTLS_STG_N2  (Index) 
--
--  Dependencies: 
--   XXDOEC_CP_SHIPMENT_DTLS_STG (Table)
--
CREATE INDEX APPS.XXDOEC_CP_SHIPMENT_DTLS_STG_N2 ON XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
(PO_RECEIVED_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_CP_SHIPMENT_DTLS_STG_N3  (Index) 
--
--  Dependencies: 
--   XXDOEC_CP_SHIPMENT_DTLS_STG (Table)
--
CREATE INDEX APPS.XXDOEC_CP_SHIPMENT_DTLS_STG_N3 ON XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
(SO_PICK_RELEASE_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_CP_SHIPMENT_DTLS_STG_N4  (Index) 
--
--  Dependencies: 
--   XXDOEC_CP_SHIPMENT_DTLS_STG (Table)
--
CREATE INDEX APPS.XXDOEC_CP_SHIPMENT_DTLS_STG_N4 ON XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
(SO_SHIP_CONFIRM_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_CP_SHIPMENT_DTLS_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_CP_SHIPMENT_DTLS_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_CP_SHIPMENT_DTLS_STG FOR XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG
/


GRANT SELECT ON XXDO.XXDOEC_CP_SHIPMENT_DTLS_STG TO APPSRO
/
