--
-- XXDO_WMS_3PL_GRN_L_GTT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXDO_WMS_3PL_GRN_L_GTT
(
  GRN_LINE_ID        NUMBER,
  GRN_RECEIVED_QTY   NUMBER,
  SHIPMENT_LINE_ID   NUMBER,
  SHIPMENT_OPEN_QTY  NUMBER,
  GRN_SPLIT_QTY      NUMBER,
  TRANSACTION_ID     NUMBER
)
ON COMMIT DELETE ROWS
NOCACHE
/
