--
-- XXD_ONT_ADV_LOC_MASTER_INT_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_ADV_LOC_MASTER_INT_T
(
  COUNTRY                   VARCHAR2(10 BYTE),
  REGION                    VARCHAR2(30 BYTE),
  SUB_REGION                VARCHAR2(150 BYTE),
  BRAND                     VARCHAR2(30 BYTE),
  SALES_CHANNEL_CODE        VARCHAR2(30 BYTE),
  FORECAST_REGION           VARCHAR2(150 BYTE),
  INCLUDE_STATE_PROVINCE    VARCHAR2(1 BYTE),
  INCLUDE_BRAND_IN_COUNTRY  VARCHAR2(1 BYTE),
  INV_ORG_CODE              VARCHAR2(3 BYTE),
  INV_ORG_ID                NUMBER,
  START_DATE                DATE,
  END_DATE                  DATE,
  ENABLED_FLAG              VARCHAR2(1 BYTE),
  CREATION_DATE             DATE,
  CREATED_BY                NUMBER,
  LAST_UPDATE_DATE          DATE,
  LAST_UPDATED_BY           NUMBER,
  LAST_UPDATE_LOGIN         NUMBER,
  REQUEST_ID                NUMBER,
  ATTRIBUTE1                VARCHAR2(240 BYTE),
  ATTRIBUTE2                VARCHAR2(240 BYTE),
  ATTRIBUTE3                VARCHAR2(240 BYTE),
  ATTRIBUTE4                VARCHAR2(240 BYTE),
  ATTRIBUTE5                VARCHAR2(240 BYTE),
  ATTRIBUTE6                VARCHAR2(240 BYTE),
  ATTRIBUTE7                VARCHAR2(240 BYTE),
  ATTRIBUTE8                VARCHAR2(240 BYTE),
  ATTRIBUTE9                VARCHAR2(240 BYTE),
  ATTRIBUTE10               VARCHAR2(240 BYTE),
  ATTRIBUTE11               VARCHAR2(240 BYTE),
  ATTRIBUTE12               VARCHAR2(240 BYTE),
  ATTRIBUTE13               VARCHAR2(240 BYTE),
  ATTRIBUTE14               VARCHAR2(240 BYTE),
  ATTRIBUTE15               VARCHAR2(240 BYTE),
  FORECAST_COUNTRY          VARCHAR2(10 BYTE),
  DIVISION                  VARCHAR2(40 BYTE),
  DEPARTMENT                VARCHAR2(40 BYTE),
  MASTER_CLASS              VARCHAR2(40 BYTE),
  SUB_CLASS                 VARCHAR2(40 BYTE),
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_ADV_LOC_MASTER_INT_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_ADV_LOC_MASTER_INT_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_ADV_LOC_MASTER_INT_T FOR XXDO.XXD_ONT_ADV_LOC_MASTER_INT_T
/
