--
-- XXD_GL_PJE_DOC_SEQ_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_GL_PJE_DOC_SEQ_GT
(
  SL_NO               NUMBER,
  DOC_SEQUENCE_VALUE  VARCHAR2(2000 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- XXD_GL_PJE_DOC_SEQ_GT  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_PJE_DOC_SEQ_GT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_PJE_DOC_SEQ_GT FOR XXDO.XXD_GL_PJE_DOC_SEQ_GT
/


GRANT SELECT ON XXDO.XXD_GL_PJE_DOC_SEQ_GT TO APPSRO WITH GRANT OPTION
/
