--
-- XXD_PPM_TIMESHEET_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_PPM_TIMESHEET_STG_T
(
  RECORD_ID                   NUMBER,
  TRANSACTION_SOURCE          VARCHAR2(30 BYTE),
  BATCH_NAME                  VARCHAR2(240 BYTE),
  PERSON_ID                   NUMBER,
  EMPLOYEE_NUMBER             VARCHAR2(30 BYTE),
  EMPLOYEE_EMAIL              VARCHAR2(240 BYTE),
  ORGANIZATION_NAME           VARCHAR2(240 BYTE),
  EXPENDITURE_ITEM_DATE       DATE,
  EXPENDITURE_ENDING_DATE     DATE,
  PROJECT_NUMBER              VARCHAR2(25 BYTE),
  TASK_NUMBER                 VARCHAR2(25 BYTE),
  EXPENDITURE_TYPE            VARCHAR2(30 BYTE),
  QUANTITY                    NUMBER,
  TRANSACTION_STATUS_CODE     VARCHAR2(2 BYTE),
  ORIG_TRANSACTION_REFERENCE  VARCHAR2(50 BYTE),
  ATTRIBUTE_CATEGORY          VARCHAR2(30 BYTE),
  ATTRIBUTE1                  VARCHAR2(150 BYTE),
  ATTRIBUTE2                  VARCHAR2(150 BYTE),
  ATTRIBUTE3                  VARCHAR2(150 BYTE),
  ATTRIBUTE4                  VARCHAR2(150 BYTE),
  ATTRIBUTE5                  VARCHAR2(150 BYTE),
  ATTRIBUTE6                  VARCHAR2(150 BYTE),
  ATTRIBUTE7                  VARCHAR2(150 BYTE),
  ATTRIBUTE8                  VARCHAR2(150 BYTE),
  ATTRIBUTE9                  VARCHAR2(150 BYTE),
  ATTRIBUTE10                 VARCHAR2(150 BYTE),
  SYSTEM_LINKAGE              VARCHAR2(30 BYTE),
  ORG_ID                      NUMBER,
  REQUEST_ID                  NUMBER,
  STATUS                      VARCHAR2(1 BYTE),
  ERROR_MESSAGE               VARCHAR2(4000 BYTE),
  CREATED_BY                  NUMBER,
  CREATION_DATE               DATE,
  LAST_UPDATED_BY             NUMBER,
  LAST_UPDATE_DATE            DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
