--
-- XXD_PGR_RESPONSE_MSGS_T  (Table) 
--
CREATE TABLE XXDO.XXD_PGR_RESPONSE_MSGS_T
(
  INVOICE_TYPE           VARCHAR2(50 BYTE),
  RECEIVER_NAME          VARCHAR2(240 BYTE),
  INVOICE_ID             NUMBER,
  INVOICE_NUMBER         VARCHAR2(240 BYTE),
  INVOICE_DATE           DATE,
  CUST_ACCT_NUM          VARCHAR2(100 BYTE),
  H_INVOICE_TOTAL        NUMBER,
  INVOICE_CURRENCY_CODE  VARCHAR2(10 BYTE),
  DOCUMENT_IDENTIFIER    VARCHAR2(50 BYTE),
  DOCUMENT_SUBTYPE       VARCHAR2(100 BYTE),
  SENDER_NAME            VARCHAR2(240 BYTE),
  BILL_TO_ROUTING_CODE   VARCHAR2(100 BYTE),
  SENDER_VATNUMBER       VARCHAR2(100 BYTE),
  DOCUMENT_TYPE          VARCHAR2(100 BYTE),
  RESPONSE_MESSAGE       VARCHAR2(4000 BYTE),
  MESSAGE_CREATETIME     VARCHAR2(100 BYTE),
  CREATED_BY             NUMBER,
  CREATION_DATE          DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_DATE       DATE,
  REQUEST_ID             NUMBER,
  FILE_NAME              VARCHAR2(100 BYTE),
  ORG_ID                 NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PGR_RESPONSE_MSGS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PGR_RESPONSE_MSGS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PGR_RESPONSE_MSGS_T FOR XXDO.XXD_PGR_RESPONSE_MSGS_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_PGR_RESPONSE_MSGS_T TO APPS
/
