--
-- XXDO_PLM_ORA_ERRORS  (Table) 
--
CREATE TABLE XXDO.XXDO_PLM_ORA_ERRORS
(
  BATCH_ID        NUMBER(10),
  PLM_ROWID       NUMBER(10),
  STYLE           VARCHAR2(100 BYTE),
  ITEM_NUMBER     VARCHAR2(100 BYTE),
  COLOR           VARCHAR2(100 BYTE),
  SIZE1           VARCHAR2(100 BYTE),
  WH_PRICE        NUMBER(9,2),
  RT_PRICE        NUMBER(9,2),
  BRAND           VARCHAR2(100 BYTE),
  PRODUCT_GROUP   VARCHAR2(100 BYTE),
  GENDER          VARCHAR2(100 BYTE),
  CLASS           VARCHAR2(100 BYTE),
  SUB_CLASS       VARCHAR2(100 BYTE),
  SUB_GROUP       VARCHAR2(100 BYTE),
  MASTER_STYLE    VARCHAR2(100 BYTE),
  CURRENT_SEASON  VARCHAR2(100 BYTE),
  TARIFF          VARCHAR2(100 BYTE),
  REGION          VARCHAR2(100 BYTE),
  COLLECTION      VARCHAR2(100 BYTE),
  UPC_CODE        VARCHAR2(100 BYTE),
  ITEM_ID         VARCHAR2(100 BYTE),
  ORG_ID          VARCHAR2(100 BYTE),
  VERRCODE        VARCHAR2(3000 BYTE),
  VERRMSG         VARCHAR2(4000 BYTE),
  CREATION_DATE   DATE                          DEFAULT sysdate,
  REQUEST_ID      NUMBER,
  ERROR_TYPE      VARCHAR2(200 BYTE),
  REP_STATUS      VARCHAR2(200 BYTE),
  ATTRIBUTE1      VARCHAR2(3000 BYTE),
  ATTRIBUTE2      VARCHAR2(3000 BYTE),
  ATTRIBUTE3      VARCHAR2(3000 BYTE),
  ATTRIBUTE4      VARCHAR2(3000 BYTE),
  ATTRIBUTE5      VARCHAR2(3000 BYTE),
  ATTRIBUTE6      VARCHAR2(3000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- IDX_XXDO_PLM_ORA_ERRORS  (Index) 
--
--  Dependencies: 
--   XXDO_PLM_ORA_ERRORS (Table)
--
CREATE INDEX XXDO.IDX_XXDO_PLM_ORA_ERRORS ON XXDO.XXDO_PLM_ORA_ERRORS
(STYLE, REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
