--
-- XXDOGL005_INT  (Table) 
--
CREATE TABLE XXDO.XXDOGL005_INT
(
  SLNO                  NUMBER,
  FROM_CURRENCY         VARCHAR2(10 BYTE),
  TO_CURRENCY           VARCHAR2(10 BYTE),
  CONVERSION_DATE       VARCHAR2(20 BYTE),
  CONVERSION_RATE       NUMBER,
  USER_CONVERSION_TYPE  VARCHAR2(40 BYTE),
  STATUS_FLAG           VARCHAR2(10 BYTE)       DEFAULT 'N',
  PROCESSED_FLAG        VARCHAR2(10 BYTE)       DEFAULT 'N',
  TRANSMISSION_DATE     TIMESTAMP(6)            DEFAULT SYSDATE,
  ERRORCODE             VARCHAR2(4000 BYTE),
  XDATA                 CLOB,
  RETVAL                CLOB
)
LOB (RETVAL) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (XDATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOGL005_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOGL005_INT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOGL005_INT FOR XXDO.XXDOGL005_INT
/


--
-- XXDOGL005_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOGL005_INT (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOGL005_INT FOR XXDO.XXDOGL005_INT
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOGL005_INT TO APPS WITH GRANT OPTION
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOGL005_INT TO APPSRO WITH GRANT OPTION
/
