--
-- XXDOASCP_ITEM_ATTR_UPD_STG2  (Table) 
--
CREATE TABLE XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2
(
  INV_ORG_CODE                  VARCHAR2(100 BYTE),
  ITEM_NUMBER                   VARCHAR2(100 BYTE),
  STYLE_COLOUR                  VARCHAR2(100 BYTE),
  CATEGORY_STRUCTURE            VARCHAR2(100 BYTE),
  CATEGORY_CODE                 VARCHAR2(100 BYTE),
  ITEM_TEMPLATE                 VARCHAR2(100 BYTE),
  DEFAULT_BUYER                 VARCHAR2(100 BYTE),
  LIST_PRICE                    NUMBER(10,2),
  MAKE_BUY                      VARCHAR2(100 BYTE),
  XXDO_MAKE_BUY                 NUMBER,
  PLANNER_CODE                  VARCHAR2(100 BYTE),
  XXDO_PLANNER_CODE             VARCHAR2(10 BYTE),
  MIN_ORDER_QTY                 NUMBER,
  FIXED_ORDER_QTY               NUMBER,
  MRP_PLANNING_METHOD           VARCHAR2(100 BYTE),
  XXDO_MRP_PLANNING_METHOD      NUMBER,
  FORECAST_CONTROL_METHOD       VARCHAR2(100 BYTE),
  XXDO_FORECAST_CONTROL_METHOD  NUMBER,
  END_ASSEMBLY_PEGGING          VARCHAR2(100 BYTE),
  XXDO_END_ASSEMBLY_PEGGING     VARCHAR2(1 BYTE),
  PLANNING_TIME_FENCE           VARCHAR2(100 BYTE),
  XXDO_PLANNING_TIME_FENCE      NUMBER,
  PLAN_TIME_FENCE_DAYS          NUMBER,
  DEMAND_TIME_FENCE             VARCHAR2(100 BYTE),
  XXDO_DEMAND_TIME_FENCE        NUMBER,
  DEMAND_TIME_FENCE_DAYS        NUMBER,
  PRE_PROCESSING_LEAD_TIME      NUMBER,
  PROCESSING_LEAD_TIME          NUMBER,
  POST_PROCESSING_LEAD_TIME     NUMBER,
  CHECK_ATP                     VARCHAR2(100 BYTE),
  XXDO_CHECK_ATP                VARCHAR2(10 BYTE),
  ATP_COMPONENTS                VARCHAR2(100 BYTE),
  XXDO_ATP_COMPONENTS           VARCHAR2(10 BYTE),
  ATP_RULE                      VARCHAR2(100 BYTE),
  SNO                           NUMBER,
  STATUS                        NUMBER,
  ERROR_MESSAGE                 VARCHAR2(4000 BYTE),
  REQUEST_ID                    NUMBER,
  ITEM_IMPORT_REQUEST_ID        NUMBER,
  CREATED_BY                    VARCHAR2(100 BYTE),
  CREATION_DATE                 DATE,
  LAST_UPDATED_BY               VARCHAR2(100 BYTE),
  LAST_UPDATE_DATE              DATE,
  ORGANIZATION_ID               NUMBER,
  INVENTORY_ITEM_ID             NUMBER,
  STRUCTURE_ID                  NUMBER,
  CATEGORY_ID                   NUMBER,
  TEMPLATE_ID                   NUMBER,
  BUYER_ID                      NUMBER,
  PLANNING_MAKE_BUY_CODE        NUMBER,
  MRP_PLANNING_CODE             NUMBER,
  ATO_FORECAST_CONTROL_FLAG     NUMBER,
  END_ASSEMBLY_PEGGING_FLAG     VARCHAR2(100 BYTE),
  PLANNING_TIME_FENCE_CODE      NUMBER,
  DEMAND_TIME_FENCE_FLAG        NUMBER,
  CHECK_ATP_FLAG                VARCHAR2(100 BYTE),
  ATP_COMPONENTS_FLAG           VARCHAR2(100 BYTE),
  ATP_RULE_ID                   VARCHAR2(100 BYTE),
  SET_PROCESS_ID                NUMBER,
  FILE_NAME                     VARCHAR2(240 BYTE),
  PNO                           NUMBER,
  EX_MESSAGE                    VARCHAR2(4000 BYTE),
  FIXED_DAYS_SUPPLY             NUMBER(10),
  FIXED_LOT_MULTIPLIER          VARCHAR2(100 BYTE),
  ROUND_ORDER_QUANTITIES        VARCHAR2(100 BYTE),
  XXDO_ROUND_ORDER_QTY          NUMBER,
  CREATE_SUPPLY                 VARCHAR2(5 BYTE),
  XXDO_CREATE_SUPPLY            VARCHAR2(1 BYTE),
  INVENTORY_PLANNING_METHOD     VARCHAR2(100 BYTE),
  XXDO_INV_PLANNING_METHOD      NUMBER,
  MAX_ORDER_QTY                 NUMBER,
  SAFETY_STOCK_METHOD           VARCHAR2(100 BYTE),
  XXDO_SAFETY_STOCK_METHOD      NUMBER,
  SAFETY_STOCK_BUCKET_DAYS      NUMBER,
  SAFETY_STOCK_PERCENT          NUMBER,
  ROUNDING_ORD_TYPE             NUMBER,
  CREATE_SUPPLY_FLAG            VARCHAR2(1 BYTE),
  INVENTORY_PLANNING_CODE       NUMBER,
  SAFETY_STOCK_CODE             NUMBER,
  DIMENSION_UOM_CODE            VARCHAR2(3 BYTE),
  WEIGHT_UOM_CODE               VARCHAR2(3 BYTE),
  CUMULATIVE_TOTAL_LEAD_TIME    NUMBER,
  SUPPLIER                      VARCHAR2(250 BYTE),
  SUPPLIER_SITE                 VARCHAR2(250 BYTE),
  PRODUCT_LINE                  VARCHAR2(250 BYTE),
  STATUS_CATEGORY               NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOASCP_ITEM_ATTR_UPD_STG2_N1  (Index) 
--
--  Dependencies: 
--   XXDOASCP_ITEM_ATTR_UPD_STG2 (Table)
--
CREATE INDEX XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2_N1 ON XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2
(STATUS)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOASCP_ITEM_ATTR_UPD_STG2_N2  (Index) 
--
--  Dependencies: 
--   XXDOASCP_ITEM_ATTR_UPD_STG2 (Table)
--
CREATE INDEX XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2_N2 ON XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2
(INVENTORY_ITEM_ID, ORGANIZATION_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOASCP_ITEM_ATTR_UPD_STG2_N3  (Index) 
--
--  Dependencies: 
--   XXDOASCP_ITEM_ATTR_UPD_STG2 (Table)
--
CREATE INDEX XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2_N3 ON XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2
(SNO)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOASCP_ITEM_ATTR_UPD_STG2  (Synonym) 
--
--  Dependencies: 
--   XXDOASCP_ITEM_ATTR_UPD_STG2 (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOASCP_ITEM_ATTR_UPD_STG2 FOR XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2 TO APPS
/

GRANT SELECT ON XXDO.XXDOASCP_ITEM_ATTR_UPD_STG2 TO APPSRO
/
