--
-- XXDO_COST_EXT_TABLE_CSV  (Table) 
--
CREATE TABLE XXDO.XXDO_COST_EXT_TABLE_CSV
(
  STYLE             VARCHAR2(150 BYTE),
  STYLE_COLOR       VARCHAR2(150 BYTE),
  INVENTORY_ORG     VARCHAR2(150 BYTE),
  ITEM              VARCHAR2(150 BYTE),
  COUNTY_OF_ORIGIN  VARCHAR2(150 BYTE),
  DUTY              VARCHAR2(150 BYTE),
  PRIME_DUTY        VARCHAR2(150 BYTE),
  DUTY_START_DATE   VARCHAR2(150 BYTE),
  DUTY_END_DATE     VARCHAR2(150 BYTE),
  FREIGHT           VARCHAR2(150 BYTE),
  FREIGHT_DU        VARCHAR2(150 BYTE),
  OH_DUTY           VARCHAR2(150 BYTE),
  OH_NONDUTY        VARCHAR2(150 BYTE),
  FACTORY_COST      VARCHAR2(150 BYTE),
  ADDITIONAL_DUTY   VARCHAR2(150 BYTE),
  TARRIF_CODE       VARCHAR2(150 BYTE),
  COUNTRY           VARCHAR2(150 BYTE),
  DEFAULT_CATEGORY  VARCHAR2(150 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY XXDO_COST_UPLOAD_DIR
     ACCESS PARAMETERS 
       ( 
         RECORDS DELIMITED BY NEWLINE
    SKIP 1
    FIELDS TERMINATED BY ','
    MISSING FIELD VALUES ARE NULL
       )
     LOCATION (XXDO_COST_UPLOAD_DIR:'Costing_Material_Overhead_Elements_Upload.csv')
  )
REJECT LIMIT UNLIMITED
/
