--
-- XXDO_ATP_CONTROL  (Table) 
--
CREATE TABLE XXDO.XXDO_ATP_CONTROL
(
  REFRESH_NUMBER       NUMBER                   NOT NULL,
  ASCP_REFRESH_NUMBER  NUMBER,
  SUBMIT_TIME          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  START_TIME           TIMESTAMP(6) WITH TIME ZONE,
  SNAP_TIME            TIMESTAMP(6) WITH TIME ZONE,
  END_TIME             TIMESTAMP(6) WITH TIME ZONE,
  DURATION             NUMBER,
  REFRESH_TYPE         VARCHAR2(4 BYTE),
  STATUS               VARCHAR2(1 BYTE)         DEFAULT 'N',
  MILESTONE_01         NUMBER,
  MILESTONE_02         NUMBER,
  MILESTONE_03         NUMBER,
  MILESTONE_04         NUMBER,
  MILESTONE_05         NUMBER,
  MILESTONE_06         NUMBER,
  MILESTONE_07         NUMBER,
  MILESTONE_08         NUMBER,
  MILESTONE_09         NUMBER,
  MILESTONE_10         NUMBER,
  MILESTONE_11         NUMBER,
  MILESTONE_12         NUMBER,
  MILESTONE_13         NUMBER,
  MILESTONE_14         NUMBER,
  MILESTONE_15         NUMBER,
  MILESTONE_16         NUMBER,
  MILESTONE_17         NUMBER,
  MILESTONE_18         NUMBER,
  MILESTONE_19         NUMBER,
  LAST_MILESTONE       TIMESTAMP(6) WITH TIME ZONE,
  NOTES                VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ATP_CONTROL_N1  (Index) 
--
--  Dependencies: 
--   XXDO_ATP_CONTROL (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_ATP_CONTROL_N1 ON XXDO.XXDO_ATP_CONTROL
(ASCP_REFRESH_NUMBER, REFRESH_NUMBER)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
--
-- XXDO_ATP_CONTROL_U1  (Index) 
--
--  Dependencies: 
--   XXDO_ATP_CONTROL (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_ATP_CONTROL_U1 ON XXDO.XXDO_ATP_CONTROL
(REFRESH_NUMBER)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
