--
-- XXDOAR_BRNDEXP_CUST_TEMP  (Table) 
--
CREATE TABLE XXDO.XXDOAR_BRNDEXP_CUST_TEMP
(
  CUSTOMER_NUMBER  VARCHAR2(30 BYTE),
  CUSTOMER_NAME    VARCHAR2(50 BYTE),
  CREDIT_LIMIT     NUMBER,
  REQUEST_ID       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAR_BRNDEXP_CUST_TEMP  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_BRNDEXP_CUST_TEMP (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAR_BRNDEXP_CUST_TEMP FOR XXDO.XXDOAR_BRNDEXP_CUST_TEMP
/


--
-- XXDOAR_BRNDEXP_CUST_TEMP  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_BRNDEXP_CUST_TEMP (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOAR_BRNDEXP_CUST_TEMP FOR XXDO.XXDOAR_BRNDEXP_CUST_TEMP
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOAR_BRNDEXP_CUST_TEMP TO APPS WITH GRANT OPTION
/

GRANT SELECT ON XXDO.XXDOAR_BRNDEXP_CUST_TEMP TO APPSRO
/
