--
-- XXD_OE_US_LOYALTY_BROK_DTLS_T  (Table) 
--
CREATE TABLE XXDO.XXD_OE_US_LOYALTY_BROK_DTLS_T
(
  REQUEST_ID          NUMBER,
  MONTH1_AMOUNT       NUMBER,
  MONTH2_AMOUNT       NUMBER,
  MONTH3_AMOUNT       NUMBER,
  MONTH1_VS_BROKAGE   NUMBER,
  MONTH2_VS_BROKAGE   NUMBER,
  MONTH3_VS_BROKAGE   NUMBER,
  MONTH1_BROKAGE_AMT  NUMBER,
  MONTH2_BROKAGE_AMT  NUMBER,
  MONTH3_BROKAGE_AMT  NUMBER,
  PERIOD_END_DATE     DATE,
  ORG_ID              NUMBER,
  PERIOD_TYPE         VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
