--
-- XXDOOD_EBSCRM_COUNTRY_CODE  (Table) 
--
CREATE TABLE XXDO.XXDOOD_EBSCRM_COUNTRY_CODE
(
  EBS_SHORT_NAME      VARCHAR2(10 BYTE),
  CRM_COUNTRY_NAME    VARCHAR2(100 BYTE),
  PHONE_COUNTRY_CODE  VARCHAR2(20 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOOD_EBSCRM_COUNTRY_CODE  (Synonym) 
--
--  Dependencies: 
--   XXDOOD_EBSCRM_COUNTRY_CODE (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOOD_EBSCRM_COUNTRY_CODE FOR XXDO.XXDOOD_EBSCRM_COUNTRY_CODE
/


--
-- XXDOOD_EBSCRM_COUNTRY_CODE  (Synonym) 
--
--  Dependencies: 
--   XXDOOD_EBSCRM_COUNTRY_CODE (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOOD_EBSCRM_COUNTRY_CODE FOR XXDO.XXDOOD_EBSCRM_COUNTRY_CODE
/
