--
-- XXDO_INV_INT_009_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_INT_009_STG
(
  DC_DEST_ID         VARCHAR2(100 BYTE),
  DISTRO_NUMBER      VARCHAR2(210 BYTE),
  DISTRO_DOC_TYPE    VARCHAR2(100 BYTE),
  CUST_ORDER_NBR     VARCHAR2(210 BYTE),
  ITEM_ID            VARCHAR2(225 BYTE),
  ORDER_LINE_NBR     NUMBER,
  UNIT_QTY           NUMBER(12,4),
  STATUS             VARCHAR2(22 BYTE),
  REC_STATUS         VARCHAR2(22 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATE_BY     NUMBER,
  SKU                VARCHAR2(100 BYTE),
  ITEM_DESCRIPTION   VARCHAR2(100 BYTE),
  SEQ_NO             NUMBER,
  PROCESSED_FLAG     VARCHAR2(240 BYTE),
  TRANSMISSION_DATE  DATE,
  ERRORCODE          VARCHAR2(240 BYTE),
  XMLDATA            CLOB,
  RETVAL             CLOB,
  DEST_ID            NUMBER,
  USER_ID            VARCHAR2(100 BYTE)
)
LOB (RETVAL) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (XMLDATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_INT_009_PK  (Index) 
--
--  Dependencies: 
--   XXDO_INV_INT_009_STG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_INV_INT_009_PK ON XXDO.XXDO_INV_INT_009_STG
(SEQ_NO)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDO_INV_INT_009_STG ADD (
  CONSTRAINT XXDO_INV_INT_009_PK
  PRIMARY KEY
  (SEQ_NO)
  USING INDEX XXDO.XXDO_INV_INT_009_PK
  ENABLE VALIDATE)
/


--
-- XXDO_INV_INT_009_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_INT_009_STG (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM XXDO_INV_INT_009_STG FOR XXDO.XXDO_INV_INT_009_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_INV_INT_009_STG TO SOA_INT
/
