--
-- XXD_ONT_GENESIS_DTLS_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_GENESIS_DTLS_STG_T
(
  BATCH_ID                 NUMBER,
  ORG_ID                   NUMBER,
  HEADER_ID                NUMBER,
  LINE_ID                  NUMBER,
  INVENTORY_ITEM_ID        NUMBER,
  SALESREP_ID              NUMBER,
  SALES_ORDER_NUM          NUMBER,
  DB2B_ORDER_NUM           VARCHAR2(50 BYTE),
  CUST_PO_NUM              VARCHAR2(50 BYTE),
  ITEM_NUMBER              VARCHAR2(250 BYTE),
  ACCOUNT_NUMBER           VARCHAR2(30 BYTE),
  BRAND                    VARCHAR2(40 BYTE),
  WAREHOUSE                VARCHAR2(40 BYTE),
  HDR_ACTION               VARCHAR2(30 BYTE),
  ORIG_HOLD_STATUS         VARCHAR2(10 BYTE),
  NEW_HOLD_STATUS          VARCHAR2(10 BYTE),
  ORIG_HDR_REQ_DATE        DATE,
  NEW_HDR_REQ_DATE         DATE,
  ORIG_HDR_CANCEL_DATE     DATE,
  NEW_HDR_CANCEL_DATE      DATE,
  ORIG_LINE_REQ_DATE       DATE,
  NEW_LINE_REQ_DATE        DATE,
  ORIG_LINE_CANCEL_DATE    DATE,
  NEW_LINE_CANCEL_DATE     DATE,
  LNE_ACTION               VARCHAR2(30 BYTE),
  ORIG_QTY                 NUMBER,
  NEW_QTY                  NUMBER,
  STATUS                   VARCHAR2(30 BYTE),
  ERROR_MESSAGE            VARCHAR2(2000 BYTE),
  CREATED_BY               NUMBER,
  LAST_UPDATED_BY          NUMBER,
  CREATION_DATE            DATE,
  LAST_UPDATE_DATE         DATE,
  HDR_UPDATES              VARCHAR2(4000 BYTE),
  LINE_UPDATES             VARCHAR2(4000 BYTE),
  ORIG_SYS_LINE_REF        VARCHAR2(100 BYTE),
  ORIG_LATEST_ACCEPT_DATE  DATE,
  NEW_LATEST_ACCEPT_DATE   DATE,
  HDR_CANCEL_REASON        VARCHAR2(100 BYTE),
  HDR_CANCEL_COMMENT       VARCHAR2(4000 BYTE),
  APPRVL_REQD              VARCHAR2(10 BYTE),
  LINE_REASON              VARCHAR2(100 BYTE),
  LINE_COMMENT             VARCHAR2(4000 BYTE),
  LINE_PRICE               NUMBER,
  UNIT_SELLING_PRICE       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_ONT_GENESIS_DTLS_STG_T TO APPS
/
