--
-- XXD_ONT_B2B_SUBMIT_ORDERS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_B2B_SUBMIT_ORDERS_T
(
  BATCH_ID            NUMBER,
  B2B_ORDER           VARCHAR2(100 BYTE),
  EBS_SALES_ORDER     VARCHAR2(100 BYTE),
  CUST_PO_NUMBER      VARCHAR2(100 BYTE),
  B2B_ORDER_STATUS    VARCHAR2(100 BYTE),
  BRAND               VARCHAR2(100 BYTE),
  REGION              VARCHAR2(100 BYTE),
  PROCESS_STATUS      VARCHAR2(10 BYTE),
  ERROR_STATUS        VARCHAR2(10 BYTE),
  ERROR_MESSAGE       VARCHAR2(3000 BYTE),
  RECORD_TYPE         VARCHAR2(1000 BYTE),
  ACTION_ITEMS        VARCHAR2(3000 BYTE),
  DATA_FIELD          VARCHAR2(3000 BYTE),
  PORTAL              VARCHAR2(50 BYTE),
  ORDER_REQUEST_DATE  VARCHAR2(50 BYTE),
  ORDER_CREATE_DATE   VARCHAR2(50 BYTE),
  CREATION_DATE       DATE,
  LAST_UPDATE_DATE    DATE,
  PORTAL_NAME         VARCHAR2(100 BYTE),
  ORDERTYPE           VARCHAR2(25 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_B2B_SUBMIT_BATCH_IND  (Index) 
--
--  Dependencies: 
--   XXD_ONT_B2B_SUBMIT_ORDERS_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_B2B_SUBMIT_BATCH_IND ON XXDO.XXD_ONT_B2B_SUBMIT_ORDERS_T
(BATCH_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_ONT_B2B_SUBMIT_ORDERS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_B2B_SUBMIT_ORDERS_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_ONT_B2B_SUBMIT_ORDERS_T FOR XXDO.XXD_ONT_B2B_SUBMIT_ORDERS_T
/


GRANT DELETE, INSERT, SELECT, UPDATE ON XXDO.XXD_ONT_B2B_SUBMIT_ORDERS_T TO SOA_INT
/
