--
-- XXD_AP_GAPLESS_SEQ_PRG_DET_T  (Table) 
--
CREATE TABLE XXDO.XXD_AP_GAPLESS_SEQ_PRG_DET_T
(
  OPERATING_UNIT    NUMBER,
  PERIOD_NAME       VARCHAR2(20 BYTE),
  MAX_GAPLESS_SEQ   NUMBER,
  MODULE_NAME       VARCHAR2(10 BYTE),
  CREATED_BY        NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATED_BY   NUMBER,
  LAST_UPDATE_DATE  DATE,
  PROGRAM_MODE      VARCHAR2(50 BYTE),
  PROGRAM_STATUS    VARCHAR2(10 BYTE),
  ERROR_MESSAGE     VARCHAR2(4000 BYTE),
  REQUEST_ID        NUMBER,
  EMAIL_ADDRESS     VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
