--
-- XXD_PARTNER_TRAFFIC_ERROR_REC  (Table) 
--
CREATE TABLE XXDO.XXD_PARTNER_TRAFFIC_ERROR_REC
(
  ERROR_RECORDS      VARCHAR2(861 BYTE),
  ERROR_DESCRIPTION  VARCHAR2(33 BYTE),
  BATCH_ID           NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PARTNER_TRAFFIC_ERROR_REC  (Synonym) 
--
--  Dependencies: 
--   XXD_PARTNER_TRAFFIC_ERROR_REC (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_PARTNER_TRAFFIC_ERROR_REC FOR XXDO.XXD_PARTNER_TRAFFIC_ERROR_REC
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_PARTNER_TRAFFIC_ERROR_REC TO SOA_INT
/
