--
-- XXD_ONT_PROMOTIONS_HISTORY_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_PROMOTIONS_HISTORY_T
(
  PROMOTION_HISTORY_ID       NUMBER,
  PROMOTION_ID               NUMBER,
  PROMOTION_CODE             VARCHAR2(50 BYTE),
  PROMOTION_NAME             VARCHAR2(100 BYTE),
  OPERATING_UNIT             VARCHAR2(240 BYTE),
  ORG_ID                     NUMBER,
  BRAND                      VARCHAR2(15 BYTE),
  CURRENCY                   VARCHAR2(15 BYTE),
  PROMOTION_CODE_STATUS      VARCHAR2(1 BYTE),
  ACTION                     VARCHAR2(50 BYTE),
  CREATION_DATE              DATE,
  CREATED_BY                 NUMBER,
  LAST_UPDATE_DATE           DATE,
  LAST_UPDATED_BY            NUMBER,
  LAST_UPDATE_LOGIN          NUMBER,
  REQUEST_ID                 NUMBER,
  ORDER_NUMBER               NUMBER,
  HEADER_ID                  NUMBER,
  CUSTOMER_NUMBER            VARCHAR2(30 BYTE),
  CUSTOMER_NAME              VARCHAR2(360 BYTE),
  ORDER_TYPE                 VARCHAR2(30 BYTE),
  ORDER_SOURCE               VARCHAR2(240 BYTE),
  ORDERED_DATE               DATE,
  REQUEST_DATE               DATE,
  FROM_SHIP_METHOD           VARCHAR2(30 BYTE),
  FROM_SHIPPING_METHOD_CODE  VARCHAR2(30 BYTE),
  FROM_FREIGHT_TERM          VARCHAR2(100 BYTE),
  FROM_FREIGHT_TERMS_CODE    VARCHAR2(100 BYTE),
  FROM_PAYMENT_TERM          VARCHAR2(100 BYTE),
  FROM_PAYMENT_TERM_ID       VARCHAR2(100 BYTE),
  FROM_HEADER_DISCOUNT       NUMBER,
  TO_SHIP_METHOD             VARCHAR2(30 BYTE),
  TO_SHIPPING_METHOD_CODE    VARCHAR2(30 BYTE),
  TO_FREIGHT_TERM            VARCHAR2(100 BYTE),
  TO_FREIGHT_TERMS_CODE      VARCHAR2(100 BYTE),
  TO_PAYMENT_TERM            VARCHAR2(100 BYTE),
  TO_PAYMENT_TERM_ID         VARCHAR2(100 BYTE),
  TO_HEADER_DISCOUNT         NUMBER,
  LINE_ID                    NUMBER,
  LINE_NUMBER                NUMBER,
  ORDERED_ITEM               VARCHAR2(40 BYTE),
  DEPARTMENT                 VARCHAR2(40 BYTE),
  DIVISION                   VARCHAR2(40 BYTE),
  CLASS                      VARCHAR2(40 BYTE),
  SUB_CLASS                  VARCHAR2(40 BYTE),
  STYLE_NUMBER               VARCHAR2(40 BYTE),
  COLOR_CODE                 VARCHAR2(40 BYTE),
  NUMBER_OF_STYLES           NUMBER,
  NUMBER_OF_COLORS           NUMBER,
  FROM_LINE_DISCOUNT         NUMBER,
  TO_LINE_DISCOUNT           NUMBER,
  PROMOTION_LEVEL            VARCHAR2(10 BYTE),
  ERROR_MESSAGE              VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


ALTER TABLE XXDO.XXD_ONT_PROMOTIONS_HISTORY_T ADD (
  PRIMARY KEY
  (PROMOTION_HISTORY_ID)
  USING INDEX
    TABLESPACE CUSTOM_TX_TS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE)
/


--  There is no statement for index XXDO.SYS_C002212901.
--  The object is created when the parent object is created.

--
-- XXD_ONT_PROMOTIONS_HISTORY_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_PROMOTIONS_HISTORY_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_PROMOTIONS_HISTORY_T FOR XXDO.XXD_ONT_PROMOTIONS_HISTORY_T
/
