--
-- XXDOINT_COUNTRY_REGION  (Table) 
--
CREATE TABLE XXDO.XXDOINT_COUNTRY_REGION
(
  COUNTRY_CODE  VARCHAR2(3 BYTE),
  COUNTRY_NAME  VARCHAR2(50 BYTE),
  REGION        VARCHAR2(10 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
