--
-- XXD_COMMON_MAPPING_LINES_TBL  (Table) 
--
CREATE TABLE XXDO.XXD_COMMON_MAPPING_LINES_TBL
(
  LINE_ID                   NUMBER,
  HEADER_ID                 NUMBER,
  PRIORITY                  NUMBER,
  OPERATING_UNIT            VARCHAR2(100 BYTE),
  ORG_ID                    NUMBER,
  HIGH_SCORE                NUMBER,
  LOW_SCORE                 NUMBER,
  CREDIT_PERCENT            NUMBER(10,2),
  GRACE_DAYS                NUMBER,
  ACCOUNT_TYPE_ID           NUMBER,
  ACCOUNT_TYPE              VARCHAR2(100 BYTE),
  ACCOUNT                   VARCHAR2(100 BYTE),
  DAYS_OF_REVENUE_DEFERRAL  NUMBER,
  GROSS_PROFIT_MARGIN       NUMBER(10,2),
  CALENDAR_CODE             VARCHAR2(50 BYTE),
  EFFECTIVE_DATE_FROM       DATE,
  EFFECTIVE_DATE_TO         DATE,
  CHANNEL                   VARCHAR2(100 BYTE),
  RETURN_PERCENTAGE         NUMBER(10,2),
  YEAR_ENTERED              VARCHAR2(100 BYTE),
  TIME_BUCKET               NUMBER(10,2),
  SHRINK_PERCENT            NUMBER(10,2),
  PERIOD_NAME               VARCHAR2(50 BYTE),
  TIME_STAMP                DATE,
  ENABLED                   VARCHAR2(1 BYTE),
  ATTRIBUTE1                VARCHAR2(200 BYTE),
  ATTRIBUTE2                VARCHAR2(200 BYTE),
  ATTRIBUTE3                VARCHAR2(200 BYTE),
  ATTRIBUTE4                VARCHAR2(200 BYTE),
  ATTRIBUTE5                VARCHAR2(200 BYTE),
  ATTRIBUTE6                VARCHAR2(200 BYTE),
  ATTRIBUTE7                VARCHAR2(200 BYTE),
  ATTRIBUTE8                VARCHAR2(200 BYTE),
  ATTRIBUTE9                VARCHAR2(200 BYTE),
  ATTRIBUTE10               VARCHAR2(200 BYTE),
  ATTRIBUTE11               VARCHAR2(200 BYTE),
  ATTRIBUTE12               VARCHAR2(200 BYTE),
  ATTRIBUTE13               VARCHAR2(200 BYTE),
  ATTRIBUTE14               VARCHAR2(200 BYTE),
  ATTRIBUTE15               VARCHAR2(200 BYTE),
  ATTRIBUTE16               NUMBER,
  ATTRIBUTE17               NUMBER,
  ATTRIBUTE18               NUMBER,
  ATTRIBUTE19               NUMBER,
  ATTRIBUTE20               NUMBER,
  ATTRIBUTE21               DATE,
  ATTRIBUTE22               DATE,
  ATTRIBUTE23               DATE,
  ATTRIBUTE24               DATE,
  ATTRIBUTE25               DATE,
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE,
  LAST_UPDATE_BY            NUMBER,
  LAST_UPDATE_DATE          DATE,
  START_DATE                DATE,
  END_DATE                  DATE,
  GRADE_CODE                VARCHAR2(100 BYTE),
  GRADE_DESCRIPTION         VARCHAR2(300 BYTE),
  COA_CHANNEL               VARCHAR2(100 BYTE),
  COA_COST_CENTER           VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_COMMON_MAPPING_LINES_TBL  (Synonym) 
--
--  Dependencies: 
--   XXD_COMMON_MAPPING_LINES_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_COMMON_MAPPING_LINES_TBL FOR XXDO.XXD_COMMON_MAPPING_LINES_TBL
/


--
-- XXD_COMMON_MAPPING_LINES_TBL  (Synonym) 
--
--  Dependencies: 
--   XXD_COMMON_MAPPING_LINES_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXD_COMMON_MAPPING_LINES_TBL FOR XXDO.XXD_COMMON_MAPPING_LINES_TBL
/


ALTER TABLE XXDO.XXD_COMMON_MAPPING_LINES_TBL ADD (
  CONSTRAINT XXD_COMMON_MAP_HDR_ID_FK 
  FOREIGN KEY (HEADER_ID) 
  REFERENCES XXDO.XXD_COMMON_MAPPING_HEADERS_TBL (HEADER_ID)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_COMMON_MAPPING_LINES_TBL TO APPS WITH GRANT OPTION
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_COMMON_MAPPING_LINES_TBL TO APPSRO WITH GRANT OPTION
/
