--
-- XXD_FILE_UPLOAD_T  (Table) 
--
CREATE TABLE XXDO.XXD_FILE_UPLOAD_T
(
  FILE_ID            NUMBER                     NOT NULL,
  FILE_NAME          VARCHAR2(200 BYTE),
  FILE_DATA          BLOB,
  FILE_SOURCE        VARCHAR2(50 BYTE),
  PROCESS_STATUS     VARCHAR2(20 BYTE),
  ERROR_MESSAGE      VARCHAR2(4000 BYTE),
  BATCH_ID           NUMBER,
  ATTRIBUTE1         VARCHAR2(240 BYTE),
  ATTRIBUTE2         VARCHAR2(240 BYTE),
  ATTRIBUTE3         VARCHAR2(240 BYTE),
  ATTRIBUTE4         VARCHAR2(240 BYTE),
  ATTRIBUTE5         VARCHAR2(240 BYTE),
  ATTRIBUTE6         VARCHAR2(240 BYTE),
  ATTRIBUTE7         VARCHAR2(240 BYTE),
  ATTRIBUTE8         VARCHAR2(240 BYTE),
  ATTRIBUTE9         VARCHAR2(240 BYTE),
  ATTRIBUTE10        VARCHAR2(240 BYTE),
  ATTRIBUTE11        VARCHAR2(240 BYTE),
  ATTRIBUTE12        VARCHAR2(240 BYTE),
  ATTRIBUTE13        VARCHAR2(240 BYTE),
  ATTRIBUTE14        VARCHAR2(240 BYTE),
  ATTRIBUTE15        VARCHAR2(240 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATE_LOGIN  NUMBER
)
LOB (FILE_DATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
