--
-- XXD_PLM_ITEM_ATTRIBUTES_T  (Table) 
--
CREATE TABLE XXDO.XXD_PLM_ITEM_ATTRIBUTES_T
(
  RECORD_ID                 NUMBER              NOT NULL,
  STYLE                     VARCHAR2(2000 BYTE) NOT NULL,
  STYLE_NAME                VARCHAR2(2000 BYTE),
  COLOR_CODE                VARCHAR2(2000 BYTE),
  COLORWAY_NAME             VARCHAR2(2000 BYTE),
  COLORWAY_STATE            VARCHAR2(2000 BYTE),
  COLORWAY_LIFECYCLE        VARCHAR2(2000 BYTE),
  BRAND                     VARCHAR2(2000 BYTE),
  DEPARTMENT                VARCHAR2(2000 BYTE),
  DIVISION                  VARCHAR2(2000 BYTE),
  SUB_DIVISION              VARCHAR2(2000 BYTE),
  PLM_CLASS                 VARCHAR2(2000 BYTE),
  SUB_CLASS                 VARCHAR2(2000 BYTE),
  MASTER_STYLE              VARCHAR2(2000 BYTE),
  DETAIL_SILHOUETTE         VARCHAR2(2000 BYTE),
  COLLECTION                VARCHAR2(2000 BYTE),
  COLORWAY_STATUS           VARCHAR2(2000 BYTE),
  INTRO_DATE                VARCHAR2(2000 BYTE),
  PROJECT_TYPE              VARCHAR2(2000 BYTE),
  UOM                       VARCHAR2(2000 BYTE),
  CUSTOMER_POSITIONING      VARCHAR2(2000 BYTE),
  GROSS_WHOLESALE_PRICE     VARCHAR2(2000 BYTE),
  RETAIL_PRICE              VARCHAR2(2000 BYTE),
  ITEM_TYPE                 VARCHAR2(2000 BYTE),
  ATS_DATE                  VARCHAR2(2000 BYTE),
  UPPER_MATERIALS           VARCHAR2(2000 BYTE),
  LINING_MATERIALS          VARCHAR2(2000 BYTE),
  OUTSOLE_MATERIALS         VARCHAR2(2000 BYTE),
  PRODUCT_DESCRIPTION_LONG  VARCHAR2(2000 BYTE),
  SIZE_DESCRIPTION          VARCHAR2(2000 BYTE),
  FOREFOOT_HEIGHT           VARCHAR2(2000 BYTE),
  HEEL_HEIGHT_DETAILS       VARCHAR2(2000 BYTE),
  WEIGHT                    VARCHAR2(2000 BYTE),
  SEASON_NAME               VARCHAR2(2000 BYTE),
  CREATION_DATE             DATE                DEFAULT SYSDATE,
  CREATED_BY                NUMBER              DEFAULT -1,
  LAST_UPDATE_DATE          DATE                DEFAULT SYSDATE,
  LAST_UPDATED_BY           NUMBER              DEFAULT -1,
  REQUEST_ID                NUMBER,
  LAST_UPDATE_LOGIN         NUMBER,
  ATTRIBUTE1                VARCHAR2(2000 BYTE),
  ATTRIBUTE2                VARCHAR2(2000 BYTE),
  ATTRIBUTE3                VARCHAR2(2000 BYTE),
  ATTRIBUTE4                VARCHAR2(2000 BYTE),
  ATTRIBUTE5                VARCHAR2(2000 BYTE),
  ATTRIBUTE6                VARCHAR2(2000 BYTE),
  ATTRIBUTE7                VARCHAR2(2000 BYTE),
  ATTRIBUTE8                VARCHAR2(2000 BYTE),
  ATTRIBUTE9                VARCHAR2(2000 BYTE),
  ATTRIBUTE10               VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


ALTER TABLE XXDO.XXD_PLM_ITEM_ATTRIBUTES_T ADD (
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX
    TABLESPACE CUSTOM_TX_TS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE)
/


--  There is no statement for index XXDO.SYS_C007603294.
--  The object is created when the parent object is created.

--
-- XXD_PLM_ITEM_ATTR_INDX  (Index) 
--
--  Dependencies: 
--   XXD_PLM_ITEM_ATTRIBUTES_T (Table)
--
CREATE INDEX APPS.XXD_PLM_ITEM_ATTR_INDX ON XXDO.XXD_PLM_ITEM_ATTRIBUTES_T
(STYLE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PLM_ITEM_ATTRIBUTES_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PLM_ITEM_ATTRIBUTES_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PLM_ITEM_ATTRIBUTES_T FOR XXDO.XXD_PLM_ITEM_ATTRIBUTES_T
/


--
-- XXD_PLM_ITEM_ATTRIBUTES_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PLM_ITEM_ATTRIBUTES_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_PLM_ITEM_ATTRIBUTES_T FOR XXDO.XXD_PLM_ITEM_ATTRIBUTES_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_PLM_ITEM_ATTRIBUTES_T TO SOA_INT
/
