--
-- XXD_PPM_STRUCTURE_CURRENT_T  (Table) 
--
CREATE TABLE XXDO.XXD_PPM_STRUCTURE_CURRENT_T
(
  STRUCTURE_NAME   VARCHAR2(10 BYTE)            NOT NULL,
  STRUCTURE_CODE   VARCHAR2(10 BYTE)            NOT NULL,
  PLACE            NUMBER                       NOT NULL,
  FATHER_CODE      VARCHAR2(10 BYTE),
  DESCRIPTION      VARCHAR2(50 BYTE),
  USER_FLAG        VARCHAR2(10 BYTE),
  DEPTH            NUMBER,
  DETAILED         VARCHAR2(2 BYTE),
  IMPORT_CODE      VARCHAR2(50 BYTE),
  LAST_UPDATED_ON  DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
