--
-- XXDOINV_CIR_MASTER_ITEM_CST  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXDOINV_CIR_MASTER_ITEM_CST
(
  INVENTORY_ITEM_ID     NUMBER                  NOT NULL,
  ORGANIZATION_ID       NUMBER                  NOT NULL,
  MATERIAL_COST         NUMBER,
  FREIGHT_COST          NUMBER,
  DUTY_COST             NUMBER,
  ITEM_COST             NUMBER,
  DUTY_RATE             NUMBER,
  MACAU_COST            NUMBER,
  IS_DIRECT_IMPORT_SKU  VARCHAR2(1 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- XXDOINV_CIR_MASTER_ITEM_CST_PK  (Index) 
--
--  Dependencies: 
--   XXDOINV_CIR_MASTER_ITEM_CST (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOINV_CIR_MASTER_ITEM_CST_PK ON XXDO.XXDOINV_CIR_MASTER_ITEM_CST
(INVENTORY_ITEM_ID)
/
