--
-- XXD_RCV_TRANSACTIONS_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_RCV_TRANSACTIONS_GT
(
  TRANSACTION_ID         NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  TRANSACTION_DATE       DATE,
  TRANSACTION_TYPE       VARCHAR2(25 BYTE),
  SOURCE_DOC_QUANTITY    NUMBER,
  SOURCE_DOCUMENT_CODE   VARCHAR2(25 BYTE),
  ORGANIZATION_ID        NUMBER,
  VENDOR_ID              NUMBER,
  PO_HEADER_ID           NUMBER,
  SHIPMENT_HEADER_ID     NUMBER,
  PO_LINE_ID             NUMBER,
  PO_LINE_LOCATION_ID    NUMBER,
  PARENT_TRANSACTION_ID  NUMBER,
  REQUISITION_LINE_ID    NUMBER,
  ATTRIBUTE1             VARCHAR2(150 BYTE),
  SHIPMENT_NUM           VARCHAR2(30 BYTE),
  SHIP_VNT               VARCHAR2(150 BYTE),
  SHIP_DC1               VARCHAR2(150 BYTE),
  RPT_GROUP_ID           NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
