--
-- XXD_PO_PRC_UPDATE_DETAILS_T  (Table) 
--
CREATE TABLE XXDO.XXD_PO_PRC_UPDATE_DETAILS_T
(
  ACTION_TYPE          VARCHAR2(20 BYTE),
  FILE_NAME            VARCHAR2(100 BYTE),
  BATCH_ID             NUMBER,
  ORG_ID               NUMBER,
  PO_HEADER_ID         NUMBER,
  PO_NUMBER            VARCHAR2(20 BYTE),
  REVISION_NUM         NUMBER,
  PO_LINE_ID           NUMBER,
  LINE_NUM             NUMBER,
  SHIPMENT_NUM         NUMBER,
  STYLE                VARCHAR2(50 BYTE),
  COLOR                VARCHAR2(50 BYTE),
  CONF_XF_DATE         VARCHAR2(15 BYTE),
  QUANTITY             NUMBER,
  UNIT_PRICE           NUMBER,
  FOB_COST             NUMBER,
  MOQ_SURCHARGE        NUMBER,
  SHIP_SURCHARGE       NUMBER,
  NEW_UNIT_PRICE       NUMBER,
  NEW_FOB_COST         NUMBER,
  NEW_MOQ_SURCHARGE    NUMBER,
  NEW_SHIP_SURCHARGE   NUMBER,
  REQUEST_ID           NUMBER,
  STATUS               VARCHAR2(100 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  CREATION_DATE        DATE,
  CREATED_BY           NUMBER,
  LAST_UPDATED_DATE    DATE,
  LAST_UPDATED_BY      NUMBER,
  VENDOR_SITE_CODE     VARCHAR2(15 BYTE),
  BRAND                VARCHAR2(100 BYTE),
  PRICE_APPROVED_BY    NUMBER,
  PRICE_APPROVED_DATE  DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PO_PRC_UPDATE_DETAILS_T_N1  (Index) 
--
--  Dependencies: 
--   XXD_PO_PRC_UPDATE_DETAILS_T (Table)
--
CREATE INDEX XXDO.XXD_PO_PRC_UPDATE_DETAILS_T_N1 ON XXDO.XXD_PO_PRC_UPDATE_DETAILS_T
(PO_HEADER_ID, STYLE, COLOR, VENDOR_SITE_CODE, STATUS)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PO_PRC_UPDATE_DETAILS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PO_PRC_UPDATE_DETAILS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PO_PRC_UPDATE_DETAILS_T FOR XXDO.XXD_PO_PRC_UPDATE_DETAILS_T
/
