--
-- XXD_CST_DUTY_ELE_UPLD_STG_T_1102  (Table) 
--
CREATE TABLE XXDO.XXD_CST_DUTY_ELE_UPLD_STG_T_1102
(
  REGION                   VARCHAR2(1000 BYTE),
  STYLE_NUMBER             VARCHAR2(1000 BYTE),
  STYLE_COLOR              VARCHAR2(1000 BYTE),
  ITEM_SIZE                VARCHAR2(1000 BYTE),
  ORGANIZATION_CODE        VARCHAR2(1000 BYTE),
  ITEM_NUMBER              VARCHAR2(1000 BYTE),
  COUNTRY_OF_ORIGIN        VARCHAR2(1000 BYTE),
  DESTINATION_COUNTRY      VARCHAR2(1000 BYTE),
  DEPARTMENT               VARCHAR2(1000 BYTE),
  DUTY_RATE                VARCHAR2(1000 BYTE),
  ADDITIONAL_DUTY          VARCHAR2(1000 BYTE),
  APPLICABLE_UOM           VARCHAR2(1000 BYTE),
  PREFERENTIAL_RATE        VARCHAR2(1000 BYTE),
  PREFERENTIAL_DUTY_FLAG   VARCHAR2(1 BYTE),
  PR_START_DATE            VARCHAR2(1000 BYTE),
  PR_END_DATE              VARCHAR2(1000 BYTE),
  DEFAULT_DUTY_RATE        VARCHAR2(1000 BYTE),
  DEFAULT_ADDITIONAL_DUTY  VARCHAR2(1000 BYTE),
  DEFAULT_APPLICABLE_UOM   VARCHAR2(1000 BYTE),
  EFFECTIVE_START_DATE     VARCHAR2(1000 BYTE),
  EFFECTIVE_END_DATE       VARCHAR2(1000 BYTE),
  DUTY                     VARCHAR2(1000 BYTE),
  PRIMARY_DUTY_FLAG        VARCHAR2(1000 BYTE),
  DUTY_START_DATE          VARCHAR2(1000 BYTE),
  DUTY_END_DATE            VARCHAR2(1000 BYTE),
  FREIGHT                  VARCHAR2(1000 BYTE),
  FREIGHT_DUTY             VARCHAR2(1000 BYTE),
  OH_DUTY                  VARCHAR2(1000 BYTE),
  OH_NONDUTY               VARCHAR2(1000 BYTE),
  FACTORY_COST             VARCHAR2(1000 BYTE),
  ADDL_DUTY                VARCHAR2(1000 BYTE),
  TARRIF_CODE              VARCHAR2(1000 BYTE),
  COUNTRY                  VARCHAR2(1000 BYTE),
  DEFAULT_CATEGORY         VARCHAR2(1000 BYTE),
  OPERATING_UNIT           VARCHAR2(1000 BYTE),
  INVENTORY_ORG_ID         VARCHAR2(1000 BYTE),
  INVENTORY_ITEM_ID        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD1        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD2        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD3        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD4        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD5        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD6        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD7        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD8        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD9        VARCHAR2(1000 BYTE),
  ADDITIONAL_FIELD10       VARCHAR2(1000 BYTE),
  COO_PRECEDENCE           NUMBER,
  COO_PREFERENCE_FLAG      VARCHAR2(1 BYTE),
  ACTIVE_FLAG              VARCHAR2(1 BYTE),
  REC_STATUS               VARCHAR2(1 BYTE),
  ERROR_MSG                VARCHAR2(4000 BYTE),
  GROUP_ID                 NUMBER,
  DUTY_OVERRIDE            VARCHAR2(1 BYTE),
  STATUS_CATEGORY          VARCHAR2(1000 BYTE),
  CREATED_BY               NUMBER,
  CREATION_DATE            DATE,
  LAST_UPDATE_DATE         DATE,
  LAST_UPDATED_BY          NUMBER,
  REQUEST_ID               NUMBER,
  FILENAME                 VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
