--
-- XXD_GL_AAR_VS_BKP_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_AAR_VS_BKP_T
(
  REQUEST_ID                     NUMBER,
  DESCRIPTIVE_FLEX_CONTEXT_CODE  VARCHAR2(240 BYTE),
  APPLICATION_COLUMN_NAME        VARCHAR2(240 BYTE),
  COLUMN_SEQ_NUM                 NUMBER,
  END_USER_COLUMN_NAME           VARCHAR2(240 BYTE),
  ENABLED_FLAG                   VARCHAR2(240 BYTE),
  ACTUAL_VALUE                   VARCHAR2(240 BYTE),
  VS_LINE_IDENTIFIER             VARCHAR2(240 BYTE),
  CREATED_BY                     NUMBER,
  CREATION_DATE                  DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_AAR_VS_BKP_T TO APPS
/
