--
-- XXDO_PLM_REGION_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_PLM_REGION_STG
(
  PARENT_RECORD_ID  NUMBER,
  BATCH_ID          NUMBER,
  REGION_NAME       VARCHAR2(100 BYTE),
  INTRO_DATE        VARCHAR2(100 BYTE),
  COLORWAY_STATUS   VARCHAR2(100 BYTE),
  VERRCODE          VARCHAR2(3000 BYTE),
  VERRMSG           VARCHAR2(1000 BYTE),
  CREATION_DATE     DATE                        DEFAULT SYSDATE,
  REQUEST_ID        NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


ALTER TABLE XXDO.XXDO_PLM_REGION_STG ADD (
  FOREIGN KEY (PARENT_RECORD_ID) 
  REFERENCES XXDO.XXDO_PLM_STAGING (RECORD_ID)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_REGION_STG TO APPS
/

GRANT SELECT ON XXDO.XXDO_PLM_REGION_STG TO APPSRO
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_REGION_STG TO SOA_INT
/
