--
-- XXDO_SOURCING_RULE_STGBKP  (Table) 
--
CREATE TABLE XXDO.XXDO_SOURCING_RULE_STGBKP
(
  STYLE               VARCHAR2(40 BYTE),
  COLOR               VARCHAR2(40 BYTE),
  ORACLE_REGION       VARCHAR2(20 BYTE),
  ORG_ID              NUMBER,
  ASSIGNMENT_SET_ID   NUMBER,
  START_DATE          DATE,
  END_DATE            DATE,
  SUPPLIER_NAME       VARCHAR2(240 BYTE),
  VENDOR_ID           NUMBER,
  SUPPLIER_SITE_CODE  VARCHAR2(15 BYTE),
  VENDOR_SITE_ID      NUMBER,
  SOURCING_RULE_ID    NUMBER,
  RECORD_STATUS       VARCHAR2(40 BYTE),
  ERROR_MESSAGE       VARCHAR2(4000 BYTE),
  SEQ_ID              NUMBER,
  RUN_ID              NUMBER,
  PLM_REGION          VARCHAR2(20 BYTE),
  SOURCE              VARCHAR2(20 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
