--
-- XXD_AP_PREPAID_JOURNAL_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_AP_PREPAID_JOURNAL_STG_T
(
  PROJECT_ID             NUMBER,
  OU_NAME                VARCHAR2(240 BYTE),
  INVOICE_NUM            VARCHAR2(50 BYTE),
  LINE_NUMBER            NUMBER,
  INVOICE_DATE           DATE,
  INVOICE_AMOUNT         NUMBER,
  DIST_AMOUNT            NUMBER,
  USD_DIST_AMOUNT        NUMBER,
  ACCOUNTING_DATE        DATE,
  VENDOR_NAME            VARCHAR2(240 BYTE),
  VENDOR_SITE_CODE       VARCHAR2(15 BYTE),
  INVOICE_CURRENCY_CODE  VARCHAR2(15 BYTE),
  GL_CODE                VARCHAR2(207 BYTE),
  COST_CENTER            VARCHAR2(240 BYTE),
  ACCOUNT                VARCHAR2(240 BYTE),
  LINE_DESCRIPTION       VARCHAR2(240 BYTE),
  BRAND                  VARCHAR2(40 BYTE),
  IC_EXPENSE             VARCHAR2(207 BYTE),
  PO_NUMBER              VARCHAR2(20 BYTE),
  LATEST_RCV_DATE        DATE,
  RELATED_PERIOD_RCV     DATE,
  MULTIPLE_RECEIPTS      NUMBER,
  DEFERRED_ACCTG_FLAG    VARCHAR2(1 BYTE),
  DEF_ACCTG_START_DATE   DATE,
  DEF_ACCTG_END_DATE     DATE,
  PAYMENT_DATE           DATE,
  TERMS_START_DATE       DATE,
  DUE_DATE               DATE,
  LINE_CREATION          DATE,
  SEGMENT1               VARCHAR2(25 BYTE),
  SEGMENT2               VARCHAR2(25 BYTE),
  SEGMENT3               VARCHAR2(25 BYTE),
  SEGMENT4               VARCHAR2(25 BYTE),
  SEGMENT5               VARCHAR2(25 BYTE),
  SEGMENT6               VARCHAR2(25 BYTE),
  SEGMENT7               VARCHAR2(25 BYTE),
  SEGMENT8               VARCHAR2(25 BYTE),
  REQUEST_ID             NUMBER,
  STATUS                 VARCHAR2(100 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  JE_HEADER_ID           NUMBER,
  JR_REQUEST_ID          NUMBER,
  JOURNAL_NAME           VARCHAR2(240 BYTE),
  ATTRIBUTE1             VARCHAR2(240 BYTE),
  ATTRIBUTE2             VARCHAR2(240 BYTE),
  ATTRIBUTE3             VARCHAR2(240 BYTE),
  ATTRIBUTE4             VARCHAR2(240 BYTE),
  ATTRIBUTE5             VARCHAR2(240 BYTE),
  ATTRIBUTE6             VARCHAR2(240 BYTE),
  ATTRIBUTE7             VARCHAR2(240 BYTE),
  ATTRIBUTE8             VARCHAR2(240 BYTE),
  ATTRIBUTE9             VARCHAR2(240 BYTE),
  ATTRIBUTE10            VARCHAR2(240 BYTE),
  ATTRIBUTE11            VARCHAR2(240 BYTE),
  ATTRIBUTE12            VARCHAR2(240 BYTE),
  ATTRIBUTE13            VARCHAR2(240 BYTE),
  ATTRIBUTE14            VARCHAR2(240 BYTE),
  ATTRIBUTE15            VARCHAR2(240 BYTE),
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATE_LOGIN      NUMBER,
  INVOICE_ID             NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
