--
-- XXD_CST_DUTY_ELE_CAT_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_CST_DUTY_ELE_CAT_STG_T
(
  BATCH_NUMBER       NUMBER,
  RECORD_ID          NUMBER,
  CONC_REQUEST_ID    NUMBER,
  RECORD_STATUS      VARCHAR2(30 BYTE),
  ITEM_NUMBER        VARCHAR2(250 BYTE),
  ORGANIZATION_ID    NUMBER,
  CATEGORY_SET_NAME  VARCHAR2(250 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  SEGMENT1           VARCHAR2(250 BYTE),
  SEGMENT1_DESC      VARCHAR2(250 BYTE),
  SEGMENT2           VARCHAR2(250 BYTE),
  SEGMENT2_DESC      VARCHAR2(250 BYTE),
  SEGMENT3           VARCHAR2(250 BYTE),
  SEGMENT3_DESC      VARCHAR2(250 BYTE),
  SEGMENT4           VARCHAR2(250 BYTE),
  SEGMENT4_DESC      VARCHAR2(250 BYTE),
  SEGMENT5           VARCHAR2(250 BYTE),
  SEGMENT5_DESC      VARCHAR2(250 BYTE),
  SEGMENT6           VARCHAR2(250 BYTE),
  SEGMENT6_DESC      VARCHAR2(250 BYTE),
  SEGMENT7           VARCHAR2(250 BYTE),
  SEGMENT7_DESC      VARCHAR2(250 BYTE),
  SEGMENT8           VARCHAR2(250 BYTE),
  SEGMENT8_DESC      VARCHAR2(250 BYTE),
  SEGMENT9           VARCHAR2(250 BYTE),
  SEGMENT9_DESC      VARCHAR2(250 BYTE),
  SEGMENT10          VARCHAR2(250 BYTE),
  SEGMENT10_DESC     VARCHAR2(250 BYTE),
  SEGMENT11          VARCHAR2(250 BYTE),
  SEGMENT11_DESC     VARCHAR2(250 BYTE),
  SEGMENT12          VARCHAR2(250 BYTE),
  SEGMENT12_DESC     VARCHAR2(250 BYTE),
  SEGMENT13          VARCHAR2(250 BYTE),
  SEGMENT13_DESC     VARCHAR2(250 BYTE),
  SEGMENT14          VARCHAR2(250 BYTE),
  SEGMENT14_DESC     VARCHAR2(250 BYTE),
  SEGMENT15          VARCHAR2(250 BYTE),
  SEGMENT15_DESC     VARCHAR2(250 BYTE),
  SEGMENT16          VARCHAR2(250 BYTE),
  SEGMENT16_DESC     VARCHAR2(250 BYTE),
  SEGMENT17          VARCHAR2(250 BYTE),
  SEGMENT17_DESC     VARCHAR2(250 BYTE),
  SEGMENT18          VARCHAR2(250 BYTE),
  SEGMENT18_DESC     VARCHAR2(250 BYTE),
  SEGMENT19          VARCHAR2(250 BYTE),
  SEGMENT19_DESC     VARCHAR2(250 BYTE),
  SEGMENT20          VARCHAR2(250 BYTE),
  SEGMENT20_DESC     VARCHAR2(250 BYTE),
  GROUP_ID           NUMBER,
  ERROR_MSG          VARCHAR2(2000 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER,
  LAST_UPDATE_DATE   DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_CST_DUTY_ELE_CAT_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CST_DUTY_ELE_CAT_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_CST_DUTY_ELE_CAT_STG_T FOR XXDO.XXD_CST_DUTY_ELE_CAT_STG_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_CST_DUTY_ELE_CAT_STG_T TO APPS
/
