--
-- XXDOINV006_INT  (Table) 
--
CREATE TABLE XXDO.XXDOINV006_INT
(
  SLNO                    NUMBER,
  SERVICETYPE             VARCHAR2(30 BYTE),
  ITEM_TYPE               VARCHAR2(30 BYTE),
  OPERATION               VARCHAR2(30 BYTE),
  INVENTORY_ITEM_ID       NUMBER,
  ORGANIZATION_ID         NUMBER,
  STYLE                   VARCHAR2(40 BYTE),
  COLOR                   VARCHAR2(40 BYTE),
  SZE                     VARCHAR2(40 BYTE),
  ITEM_STATUS             VARCHAR2(40 BYTE),
  ITEM_DESCRIPTION        VARCHAR2(240 BYTE),
  SCALE_CODE_ID           NUMBER,
  DEPARTMENT              NUMBER,
  CLASS                   NUMBER,
  SUBCLASS                VARCHAR2(40 BYTE),
  SUBCLASS_CREATION_DATE  VARCHAR2(40 BYTE),
  SUBCLASS_UPDATE_DATE    VARCHAR2(40 BYTE),
  SUBCLASS_UPDATEDBY      VARCHAR2(40 BYTE),
  VERTEX_TAX              VARCHAR2(40 BYTE),
  VERTEX_CREATION_DATE    VARCHAR2(40 BYTE),
  VERTEX_UPDATE_DATE      VARCHAR2(40 BYTE),
  VERTEX_UPDATEDBY        VARCHAR2(40 BYTE),
  US_REGION_COST          NUMBER,
  US_REGION_PRICE         NUMBER,
  UK_REGION_COST          NUMBER,
  UK_REGION_PRICE         NUMBER,
  CA_REGION_COST          NUMBER,
  CA_REGION_PRICE         NUMBER,
  CN_REGION_COST          NUMBER,
  CN_REGION_PRICE         NUMBER,
  JP_REGION_COST          NUMBER,
  JP_REGION_PRICE         NUMBER,
  STYLE_STATUS_FLAG       VARCHAR2(10 BYTE),
  SKU_STATUS_FLAG         VARCHAR2(10 BYTE),
  PROCESSED_FLAG          VARCHAR2(10 BYTE),
  TRANSMISSION_DATE       TIMESTAMP(6),
  ERRORCODE               VARCHAR2(240 BYTE),
  XDATA                   CLOB,
  RETVAL                  CLOB,
  UPC_VALUE               VARCHAR2(100 BYTE),
  UPC_STATUS_FLAG         VARCHAR2(10 BYTE),
  FR_REGION_COST          NUMBER(10,2),
  FR_REGION_PRICE         NUMBER(10,2),
  HK_REGION_COST          NUMBER,
  HK_REGION_PRICE         NUMBER,
  PARENT_REQUEST_ID       NUMBER,
  CHILD_REQUEST_ID        NUMBER,
  SUB_DIVISION            VARCHAR2(150 BYTE)
)
LOB (RETVAL) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (XDATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOINV006_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOINV006_INT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOINV006_INT FOR XXDO.XXDOINV006_INT
/
