--
-- XXDO_CIT_INBND_AR_ACT_CTL_INT  (Table) 
--
CREATE TABLE XXDO.XXDO_CIT_INBND_AR_ACT_CTL_INT
(
  TOTAL_TRANS_CUST_COUNT  NUMBER,
  TOTAL_TRANS_AR_COUNT    NUMBER,
  TOTAL_GROSS_AMOUNT      NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_CIT_INBND_AR_ACT_CTL_INT  (Synonym) 
--
--  Dependencies: 
--   XXDO_CIT_INBND_AR_ACT_CTL_INT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_CIT_INBND_AR_ACT_CTL_INT FOR XXDO.XXDO_CIT_INBND_AR_ACT_CTL_INT
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_CIT_INBND_AR_ACT_CTL_INT TO APPS
/
