--
-- XXD_PARTNER_RET_SALE_STG  (Table) 
--
CREATE TABLE XXDO.XXD_PARTNER_RET_SALE_STG
(
  BATCH_ID               NUMBER,
  ORG_ID                 NUMBER,
  FILE_FREQUENCY         VARCHAR2(100 BYTE),
  ACCOUNT_NUMBER         VARCHAR2(30 BYTE),
  PARTY_NAME             VARCHAR2(360 BYTE),
  STORE_CODE             VARCHAR2(150 BYTE),
  STORE_NAME             VARCHAR2(100 BYTE),
  STORE_TYPE             VARCHAR2(100 BYTE),
  TRANSACTION_DATE       NUMBER,
  TRANSACTION_NUM        VARCHAR2(60 BYTE),
  STYLE_NUMBER           VARCHAR2(100 BYTE),
  COLOR                  VARCHAR2(100 BYTE),
  ITEM_SIZE              VARCHAR2(100 BYTE),
  SKU                    VARCHAR2(100 BYTE),
  SALES_QTY              NUMBER,
  UNIT_PRICE             NUMBER,
  CUSTOMER_LIST_PRICE    NUMBER,
  SALES_AMOUNT           NUMBER,
  DISCOUNT               NUMBER,
  FILE_NAME              VARCHAR2(100 BYTE),
  NUMBER_ATTRIBUTE1      NUMBER,
  NUMBER_ATTRIBUTE2      NUMBER,
  NUMBER_ATTRIBUTE3      NUMBER,
  NUMBER_ATTRIBUTE4      NUMBER,
  NUMBER_ATTRIBUTE5      NUMBER,
  CHAR_ATTRIBUTE1        VARCHAR2(100 BYTE),
  CHAR_ATTRIBUTE2        VARCHAR2(100 BYTE),
  CHAR_ATTRIBUTE3        VARCHAR2(100 BYTE),
  CHAR_ATTRIBUTE4        VARCHAR2(100 BYTE),
  CHAR_ATTRIBUTE5        VARCHAR2(100 BYTE),
  DATE_ATTRIBUTE1        DATE,
  DATE_ATTRIBUTE2        DATE,
  DATE_ATTRIBUTE3        DATE,
  DATE_ATTRIBUTE4        DATE,
  DATE_ATTRIBUTE5        DATE,
  STORE_STATUS           VARCHAR2(1 BYTE),
  SKU_STATUS             VARCHAR2(1 BYTE),
  DATE_STATUS            VARCHAR2(1 BYTE),
  OVERALL_STATUS         VARCHAR2(1 BYTE),
  TECH_ERROR             VARCHAR2(1 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  FILE_FORMAT_STATUS     VARCHAR2(10 BYTE),
  FILE_FREQUENCY_STATUS  VARCHAR2(100 BYTE),
  BLANK_STATUS           VARCHAR2(5 BYTE),
  PRICE_STATUS           VARCHAR2(5 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PART_SALE_BATCH_ID_INDX  (Index) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_SALE_STG (Table)
--
CREATE INDEX APPS.XXD_PART_SALE_BATCH_ID_INDX ON XXDO.XXD_PARTNER_RET_SALE_STG
(BATCH_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PART_SALE_BATCH_ID_SKU_IDX  (Index) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_SALE_STG (Table)
--
CREATE INDEX APPS.XXD_PART_SALE_BATCH_ID_SKU_IDX ON XXDO.XXD_PARTNER_RET_SALE_STG
(BATCH_ID, SKU)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PARTNER_RET_SALE_STG  (Synonym) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_SALE_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PARTNER_RET_SALE_STG FOR XXDO.XXD_PARTNER_RET_SALE_STG
/


--
-- XXD_PARTNER_RET_SALE_STG  (Synonym) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_SALE_STG (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_PARTNER_RET_SALE_STG FOR XXDO.XXD_PARTNER_RET_SALE_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_PARTNER_RET_SALE_STG TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_PARTNER_RET_SALE_STG TO SOA_INT
/
