--
-- XXDOINT_PRICELIST_MSRP_CFG  (Table) 
--
CREATE TABLE XXDO.XXDOINT_PRICELIST_MSRP_CFG
(
  PRICELIST_ID       NUMBER                     NOT NULL,
  MSRP_PRICELIST_ID  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOINT_PRICELIST_MSRP_CF_PK  (Index) 
--
--  Dependencies: 
--   XXDOINT_PRICELIST_MSRP_CFG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOINT_PRICELIST_MSRP_CF_PK ON XXDO.XXDOINT_PRICELIST_MSRP_CFG
(PRICELIST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDOINT_PRICELIST_MSRP_CFG ADD (
  CONSTRAINT XXDOINT_PRICELIST_MSRP_CF_PK
  PRIMARY KEY
  (PRICELIST_ID)
  USING INDEX XXDO.XXDOINT_PRICELIST_MSRP_CF_PK
  ENABLE VALIDATE)
/
