--
-- XXDOEC_FACTORY_INVOICES_STG  (Table) 
--
CREATE TABLE XXDO.XXDOEC_FACTORY_INVOICES_STG
(
  INVOICE_ID            NUMBER,
  SENDER_ID             VARCHAR2(120 BYTE),
  INVOICE_NUMBER        VARCHAR2(120 BYTE),
  INVOICE_DATE          DATE,
  INVOICE_CURRENCY      VARCHAR2(30 BYTE),
  PERIOD_START_DATE     DATE,
  PERIOD_END_DATE       DATE,
  TOTAL_UNITS_SHIPPED   NUMBER,
  TOTAL_INVOICE_AMOUNT  NUMBER,
  PROCESS_FLAG          VARCHAR2(1 BYTE),
  ERROR_MESSAGE         VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_FACTORY_INVOICES_STG_U1  (Index) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INVOICES_STG (Table)
--
CREATE UNIQUE INDEX APPS.XXDOEC_FACTORY_INVOICES_STG_U1 ON XXDO.XXDOEC_FACTORY_INVOICES_STG
(INVOICE_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_FACTORY_INVOICES_STG_N1  (Index) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INVOICES_STG (Table)
--
CREATE INDEX APPS.XXDOEC_FACTORY_INVOICES_STG_N1 ON XXDO.XXDOEC_FACTORY_INVOICES_STG
(PROCESS_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_FACTORY_INVOICES_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INVOICES_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_FACTORY_INVOICES_STG FOR XXDO.XXDOEC_FACTORY_INVOICES_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOEC_FACTORY_INVOICES_STG TO APPS
/
