--
-- XXDO_BANK_STMT_FILES  (Table) 
--
CREATE TABLE XXDO.XXDO_BANK_STMT_FILES
(
  BANK_NAME          VARCHAR2(100 BYTE),
  CREATED_DT         VARCHAR2(250 BYTE),
  FILE_NAME          VARCHAR2(2000 BYTE),
  FILE_PATH          VARCHAR2(2000 BYTE),
  LOAD_STATUS        VARCHAR2(50 BYTE),
  PROCESS_STATUS     VARCHAR2(50 BYTE),
  PARENT_REQUEST_ID  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_BANK_STMT_FILES TO APPS
/
