--
-- XXDO_COMMON_DAILY_STATUS_TBL  (Table) 
--
CREATE TABLE XXDO.XXDO_COMMON_DAILY_STATUS_TBL
(
  QUERY_ID                    NUMBER,
  QUERY_DESC                  VARCHAR2(400 BYTE),
  ACTUAL_QUERY                VARCHAR2(4000 BYTE),
  QUERY_COLUMN                VARCHAR2(1000 BYTE),
  ENABLED_FLAG                VARCHAR2(10 BYTE),
  EMAIL_ADDRESS               VARCHAR2(1000 BYTE),
  CREATED_BY                  NUMBER,
  CREATION_DATE               DATE,
  LAST_UPDATE_DATE            DATE,
  LAST_UPDATE_BY              NUMBER,
  ATTRIBUTE1                  VARCHAR2(50 BYTE),
  ATTRIBUTE2                  VARCHAR2(50 BYTE),
  ATTRIBUTE3                  VARCHAR2(50 BYTE),
  ATTRIBUTE4                  VARCHAR2(50 BYTE),
  ATTRIBUTE5                  VARCHAR2(50 BYTE),
  ATTRIBUTE6                  VARCHAR2(50 BYTE),
  ATTRIBUTE7                  VARCHAR2(50 BYTE),
  ATTRIBUTE8                  VARCHAR2(50 BYTE),
  ATTRIBUTE9                  VARCHAR2(50 BYTE),
  ATTRIBUTE10                 VARCHAR2(50 BYTE),
  ATTRIBUTE11                 VARCHAR2(50 BYTE),
  ATTRIBUTE12                 VARCHAR2(50 BYTE),
  ATTRIBUTE13                 VARCHAR2(50 BYTE),
  ATTRIBUTE14                 VARCHAR2(50 BYTE),
  ATTRIBUTE15                 VARCHAR2(50 BYTE),
  ATTRIBUTE16                 VARCHAR2(50 BYTE),
  ATTRIBUTE17                 VARCHAR2(50 BYTE),
  ATTRIBUTE18                 VARCHAR2(50 BYTE),
  ATTRIBUTE20                 VARCHAR2(50 BYTE),
  ATTRIBUTE19                 VARCHAR2(50 BYTE),
  EMAIL_ATTACHMENT_FILE_NAME  VARCHAR2(200 BYTE),
  EMAIL_MESSAGE_TEXT          VARCHAR2(4000 BYTE),
  EFFECTIVE_START_DATE        DATE,
  EFFECTIVE_END_DATE          DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_QUERY_ID_PRI  (Index) 
--
--  Dependencies: 
--   XXDO_COMMON_DAILY_STATUS_TBL (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_QUERY_ID_PRI ON XXDO.XXDO_COMMON_DAILY_STATUS_TBL
(QUERY_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDO_COMMON_DAILY_STATUS_TBL ADD (
  CONSTRAINT XXDO_QUERY_ID_PRI
  PRIMARY KEY
  (QUERY_ID)
  USING INDEX XXDO.XXDO_QUERY_ID_PRI
  ENABLE VALIDATE)
/


--
-- XXDO_COMMON_DAILY_STATUS_TBL  (Synonym) 
--
--  Dependencies: 
--   XXDO_COMMON_DAILY_STATUS_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_COMMON_DAILY_STATUS_TBL FOR XXDO.XXDO_COMMON_DAILY_STATUS_TBL
/
