--
-- XXD_EDI_855_SPS_ORDER_PROCESS  (Table) 
--
CREATE TABLE XXDO.XXD_EDI_855_SPS_ORDER_PROCESS
(
  ORDER_NUMBER      NUMBER,
  CUST_PO_NUMBER    VARCHAR2(100 BYTE),
  ACCOUNT_NUMBER    VARCHAR2(100 BYTE),
  CUSTOMER_NAME     VARCHAR2(100 BYTE),
  PROCESS_STATUS    VARCHAR2(100 BYTE),
  RESPONSE_MESSAGE  VARCHAR2(2000 BYTE),
  BULK_ORDER_FLAG   VARCHAR2(100 BYTE),
  CREATION_DATE     DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER,
  ATTRIBUTE1        VARCHAR2(200 BYTE),
  ATTRIBUTE2        VARCHAR2(200 BYTE),
  ATTRIBUTE3        VARCHAR2(200 BYTE),
  ATTRIBUTE4        VARCHAR2(200 BYTE),
  ATTRIBUTE5        VARCHAR2(1000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT INSERT, SELECT, UPDATE ON XXDO.XXD_EDI_855_SPS_ORDER_PROCESS TO SOA_INT
/
