--
-- XXD_AR_CREATE_ADJUSTMENTS_STG  (Table) 
--
CREATE TABLE XXDO.XXD_AR_CREATE_ADJUSTMENTS_STG
(
  INV_TYPE              VARCHAR2(3 BYTE),
  PAYMENT_TYPE          VARCHAR2(30 BYTE),
  PAYMENT_DATE          DATE,
  ORDER_NUMBER          NUMBER,
  CUST_PO_NUMBER        VARCHAR2(50 BYTE),
  CUSTOMER_NUMBER       VARCHAR2(30 BYTE),
  INVOICE_TO_ORG_ID     NUMBER,
  SHIP_TO_ORG_ID        NUMBER,
  EXCHANGE_ORDER_TYPE   VARCHAR2(240 BYTE),
  HEADER_ID             NUMBER,
  LINE_GRP_ID           VARCHAR2(240 BYTE),
  STATUS_CODE           VARCHAR2(240 BYTE),
  PGC_TRANS_NUM         VARCHAR2(240 BYTE),
  CUSTOMER_TRX_ID       NUMBER(15),
  TRX_NUMBER            VARCHAR2(20 BYTE),
  ADJ_ACTIVITY_NAME     VARCHAR2(50 BYTE),
  TRX_TYPE_NAME         VARCHAR2(20 BYTE),
  TYPE                  VARCHAR2(20 BYTE),
  OM_LINE_TOTAL         NUMBER,
  INV_LINE_TOTAL        NUMBER,
  PAYMENT_AMOUNT        NUMBER,
  AMOUNT_DUE_ORIGINAL   NUMBER,
  AMOUNT_DUE_REMAINING  NUMBER,
  BAL_AMOUNT            NUMBER,
  DIFF                  NUMBER,
  AMOUNT_ADJUSTED       NUMBER,
  ADJUSTMENT_NUMBER     NUMBER,
  ADJUSTED_DATE         DATE,
  STATUS                VARCHAR2(2 BYTE),
  ERROR_MESSAGE         VARCHAR2(2000 BYTE),
  REQUEST_ID            NUMBER,
  CREATED_BY            NUMBER,
  CREATION_DATE         DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_AR_CREATE_ADJUSTMENTS_STG  (Synonym) 
--
--  Dependencies: 
--   XXD_AR_CREATE_ADJUSTMENTS_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_AR_CREATE_ADJUSTMENTS_STG FOR XXDO.XXD_AR_CREATE_ADJUSTMENTS_STG
/
