--
-- XXD_GL_ACCT_CONTROL_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ACCT_CONTROL_STG_T
(
  NATURAL_ACCT       VARCHAR2(100 BYTE),
  REQUESTED_BY       VARCHAR2(200 BYTE),
  DESCRIPTION        VARCHAR2(200 BYTE),
  CONTROLLED         VARCHAR2(10 BYTE),
  REQUEST_ID         NUMBER,
  FILE_NAME          VARCHAR2(500 BYTE),
  STATUS             VARCHAR2(10 BYTE),
  ERROR_MSG          VARCHAR2(4000 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  RECORD_TYPE        VARCHAR2(100 BYTE),
  UNCONT_REQUEST_ID  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_ACCT_CONTROL_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_ACCT_CONTROL_STG_T (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM XXD_GL_ACCT_CONTROL_STG_T FOR XXDO.XXD_GL_ACCT_CONTROL_STG_T
/
