--
-- XXDO_PO_ASN_PO_LINES_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_PO_ASN_PO_LINES_STG
(
  WAREHOUSE_CODE             VARCHAR2(10 BYTE)  NOT NULL,
  SHIPMENT_NUMBER            VARCHAR2(30 BYTE)  NOT NULL,
  PO_NUMBER                  VARCHAR2(30 BYTE)  NOT NULL,
  CARTON_ID                  VARCHAR2(250 BYTE),
  LINE_NUMBER                VARCHAR2(5 BYTE)   NOT NULL,
  ITEM_NUMBER                VARCHAR2(60 BYTE)  NOT NULL,
  STATUS                     VARCHAR2(60 BYTE)  NOT NULL,
  QTY                        NUMBER,
  ORDERED_UOM                VARCHAR2(10 BYTE),
  CARTON_WEIGHT              NUMBER,
  CARTON_LENGTH              NUMBER,
  CARTON_WIDTH               NUMBER,
  CARTON_HEIGHT              NUMBER,
  INSPECTION_TYPE            VARCHAR2(60 BYTE),
  CARTON_DIM_UOM             VARCHAR2(10 BYTE),
  CARTON_WEIGHT_UOM          VARCHAR2(10 BYTE),
  CARTON_CROSSDOCK_REF       VARCHAR2(30 BYTE),
  OVERAGE_ALLOWANCE_TYPE     VARCHAR2(10 BYTE)  NOT NULL,
  OVERAGE_ALLOWANCE_QTY      NUMBER,
  OVERAGE_ALLOWANCE_PERCENT  NUMBER,
  PROCESS_STATUS             VARCHAR2(20 BYTE),
  ERROR_MESSAGE              VARCHAR2(1000 BYTE),
  REQUEST_ID                 NUMBER,
  CREATION_DATE              DATE,
  CREATED_BY                 NUMBER,
  LAST_UPDATE_DATE           DATE,
  LAST_UPDATED_BY            NUMBER,
  SOURCE_TYPE                VARCHAR2(20 BYTE),
  ATTRIBUTE1                 VARCHAR2(50 BYTE),
  ATTRIBUTE2                 VARCHAR2(50 BYTE),
  ATTRIBUTE3                 VARCHAR2(50 BYTE),
  ATTRIBUTE4                 VARCHAR2(50 BYTE),
  ATTRIBUTE5                 VARCHAR2(50 BYTE),
  ATTRIBUTE6                 VARCHAR2(50 BYTE),
  ATTRIBUTE7                 VARCHAR2(50 BYTE),
  ATTRIBUTE8                 VARCHAR2(50 BYTE),
  ATTRIBUTE9                 VARCHAR2(50 BYTE),
  ATTRIBUTE10                VARCHAR2(50 BYTE),
  ATTRIBUTE11                VARCHAR2(50 BYTE),
  ATTRIBUTE12                VARCHAR2(50 BYTE),
  ATTRIBUTE13                VARCHAR2(50 BYTE),
  ATTRIBUTE14                VARCHAR2(50 BYTE),
  ATTRIBUTE15                VARCHAR2(50 BYTE),
  ATTRIBUTE16                VARCHAR2(50 BYTE),
  ATTRIBUTE17                VARCHAR2(50 BYTE),
  ATTRIBUTE18                VARCHAR2(50 BYTE),
  ATTRIBUTE19                VARCHAR2(50 BYTE),
  ATTRIBUTE20                VARCHAR2(50 BYTE),
  SOURCE                     VARCHAR2(20 BYTE),
  DESTINATION                VARCHAR2(20 BYTE),
  RECORD_TYPE                VARCHAR2(20 BYTE),
  PO_LINE_ID                 NUMBER,
  SHIPMENT_LINE_ID           NUMBER,
  PO_LINE_SEQ_ID             NUMBER,
  PO_SEQ_ID                  NUMBER,
  ASN_HEADER_SEQ_ID          NUMBER,
  INVENTORY_ITEM_ID          NUMBER,
  ORGANIZATION_ID            NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_PO_ASN_PO_LINES_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_PO_ASN_PO_LINES_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_PO_ASN_PO_LINES_STG FOR XXDO.XXDO_PO_ASN_PO_LINES_STG
/
