--
-- XXDO_DEBUG  (Table) 
--
CREATE TABLE XXDO.XXDO_DEBUG
(
  DEBUG_TEXT      VARCHAR2(2000 BYTE),
  CREATION_DATE   TIMESTAMP(6) WITH TIME ZONE   DEFAULT SYSTIMESTAMP,
  CREATED_BY      NUMBER,
  SESSION_ID      NUMBER,
  DEBUG_ID        NUMBER,
  REQUEST_ID      NUMBER,
  APPLICATION_ID  VARCHAR2(240 BYTE),
  CALL_STACK      VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_DEBUG_I1  (Trigger) 
--
--  Dependencies: 
--   XXDO_DEBUG (Table)
--
CREATE OR REPLACE TRIGGER XXDO.XXDO_DEBUG_I1
   BEFORE INSERT
   ON xxdo.xxdo_debug
   REFERENCING OLD AS old NEW AS new
   FOR EACH ROW
BEGIN
   SELECT xxdo.xxdo_debug_s.NEXTVAL INTO :new.debug_id FROM DUAL;
END;
/
