--
-- XXDOAR_RECV_CR_LINE_TEMP  (Table) 
--
CREATE TABLE XXDO.XXDOAR_RECV_CR_LINE_TEMP
(
  CUSTOMER_NUMBER    VARCHAR2(30 BYTE),
  SIMPLE_AMOUNT      NUMBER,
  TEVA_AMOUNT        NUMBER,
  UGG_AMOUNT         NUMBER,
  AHNU_AMOUNT        NUMBER,
  TSUBO_AMOUNT       NUMBER,
  DECKERS_AMOUNT     NUMBER,
  OTHERS_AMOUNT      NUMBER,
  REQUEST_ID         NUMBER,
  HOKA_AMOUNT        NUMBER,
  SANUK_AMOUNT       NUMBER,
  KOOLABURRA_AMOUNT  NUMBER,
  OPEN_REL_BAL       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOAR_RECV_CR_LINE_TEMP TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOAR_RECV_CR_LINE_TEMP TO APPSRO
/
