--
-- XXD_GL_COST_DUTY_JOURNAL_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_COST_DUTY_JOURNAL_T
(
  INV_ORG_ID                     NUMBER,
  INV_ORG_CODE                   VARCHAR2(3 BYTE),
  OPERATING_UNIT_ID              NUMBER,
  OPERATING_UNIT_NAME            VARCHAR2(240 BYTE),
  LEDGER_ID                      NUMBER,
  LEDGER_NAME                    VARCHAR2(30 BYTE),
  LEDGER_CURRENCY_CODE           VARCHAR2(15 BYTE),
  USER_JE_SOURCE_NAME            VARCHAR2(25 BYTE),
  JE_SOURCE_NAME                 VARCHAR2(25 BYTE),
  USER_JE_CATEGORY_NAME          VARCHAR2(25 BYTE),
  JE_CATEGORY_NAME               VARCHAR2(25 BYTE),
  TRX_CURRENCY_CODE              VARCHAR2(15 BYTE),
  ACCOUNTING_DATE                DATE,
  CURRENCY_CONVERSION_DATE       DATE,
  USER_CURRENCY_CONVERSION_TYPE  VARCHAR2(30 BYTE),
  ENTERED_CR                     NUMBER,
  ENTERED_DR                     NUMBER,
  CREDIT_CONCATENATED_SEGMENTS   VARCHAR2(207 BYTE),
  CREDIT_CCID                    NUMBER,
  DEBIT_CONCATENATED_SEGMENTS    VARCHAR2(207 BYTE),
  DEBIT_CCID                     NUMBER,
  REFERENCE10_LINE_DESCRIPTION   VARCHAR2(240 BYTE),
  REFERENCE21                    VARCHAR2(240 BYTE),
  MMT_TRANSACTION_ID             NUMBER,
  MMT_TRANSACTION_DATE           DATE,
  MMT_CREATION_DATE              DATE,
  MMT_TRANSACTION_TYPE_NAME      VARCHAR2(30 BYTE),
  MMT_TRANSACTION_TYPE_ID        NUMBER,
  DUTY                           NUMBER,
  MMT_TRANSACTION_QUANTITY       NUMBER,
  ORDER_NUMBER                   NUMBER,
  ORDER_LINE_NUM                 VARCHAR2(30 BYTE),
  ORDERED_ITEM                   VARCHAR2(30 BYTE),
  PROGRAM_MODE                   VARCHAR2(10 BYTE),
  RECORD_STATUS                  VARCHAR2(1 BYTE),
  ERROR_MESSAGE                  VARCHAR2(4000 BYTE),
  REQUEST_ID                     NUMBER,
  CREATED_BY                     NUMBER,
  CREATION_DATE                  DATE,
  LAST_UPDATED_BY                NUMBER,
  LAST_UPDATE_DATE               DATE,
  LAST_UPDATE_LOGIN              NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
