--
-- XXD_GL_ACC_RECON_EXTRACT_H  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ACC_RECON_EXTRACT_H
(
  REQUEST_ID            NUMBER,
  CCID                  NUMBER,
  VS_UNIQUE_IDENTIFIER  VARCHAR2(240 BYTE),
  CREATED_BY            NUMBER,
  CREATION_DATE         DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_ACC_RECON_EXTRACT_H TO APPS
/
