--
-- XXD_GL_ACC_RECON_EXTRACT_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ACC_RECON_EXTRACT_T
(
  REQUEST_ID            NUMBER,
  CCID                  NUMBER,
  COAID                 NUMBER,
  VS_UNIQUE_IDENTIFIER  VARCHAR2(240 BYTE),
  COMPANY               VARCHAR2(240 BYTE),
  BRAND                 VARCHAR2(240 BYTE),
  GEO                   VARCHAR2(240 BYTE),
  CHANNEL               VARCHAR2(240 BYTE),
  COSTCENTER            VARCHAR2(240 BYTE),
  ACCOUNT               VARCHAR2(240 BYTE),
  INTERCOMPANY          VARCHAR2(240 BYTE),
  WEIGHTAGE             VARCHAR2(240 BYTE),
  COMPANY_HIERCHY       VARCHAR2(1 BYTE),
  BRAND_HIERCHY         VARCHAR2(1 BYTE),
  GEO_HIERCHY           VARCHAR2(1 BYTE),
  CHANNEL_HIERCHY       VARCHAR2(1 BYTE),
  COSTCENTER_HIERCHY    VARCHAR2(1 BYTE),
  ACCOUNT_HIERCHY       VARCHAR2(1 BYTE),
  INTERCOMPANY_HIERCHY  VARCHAR2(1 BYTE),
  TOTAL_RANK            NUMBER,
  EXTRACT_LEVEL         NUMBER,
  RECORD_SOURCE         VARCHAR2(10 BYTE),
  CREATED_BY            NUMBER,
  CREATION_DATE         DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_ACCT_TBL_N1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ACC_RECON_EXTRACT_T (Table)
--
CREATE INDEX XXDO.XXD_GL_ACCT_TBL_N1 ON XXDO.XXD_GL_ACC_RECON_EXTRACT_T
(CCID, EXTRACT_LEVEL)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_ACC_RECON_EXTRACT_T TO APPS
/
