--
-- XXD_AR_CONS_INV_GE_T  (Table) 
--
CREATE TABLE XXDO.XXD_AR_CONS_INV_GE_T
(
  OPERATING_UNIT           VARCHAR2(240 BYTE),
  TRX_NUMBER               VARCHAR2(20 BYTE),
  TRX_TYPE                 VARCHAR2(20 BYTE),
  TRX_TYPE_NAME            VARCHAR2(20 BYTE),
  ACCOUNT_NUMBER           VARCHAR2(30 BYTE),
  PARTY_NAME               VARCHAR2(360 BYTE),
  CUSTOMER_TRX_ID          NUMBER,
  CUSTOMER_TRX_LINE_ID     NUMBER,
  LINE_TYPE                VARCHAR2(100 BYTE),
  TRX_LINE_NUMBER          NUMBER,
  SALES_ORDER              VARCHAR2(50 BYTE),
  WAREHOUSE                VARCHAR2(100 BYTE),
  INVENTORY_ITEM_ID        NUMBER,
  SKU                      VARCHAR2(100 BYTE),
  TRX_LINE_DESC            VARCHAR2(240 BYTE),
  QUANTITY                 NUMBER,
  UNIT_SELLING_PRICE       NUMBER,
  TAX_RATE                 NUMBER,
  TAX_AMOUNT               NUMBER,
  VAT_TAX_ID               NUMBER,
  TAX_RATE_CODE            VARCHAR2(100 BYTE),
  TAX_CODE                 VARCHAR2(100 BYTE),
  FREIGHT_AMOUNT           NUMBER,
  ITEM_TOTAL               NUMBER,
  TOTAL_AMOUNT             NUMBER,
  ORG_ID                   NUMBER,
  TRX_DATE                 DATE,
  TRX_CREATION_DATE        DATE,
  BRAND                    VARCHAR2(20 BYTE),
  ORDER_LINE_ID            NUMBER,
  DISCOUNT_ADJ_ID          NUMBER,
  STATUS                   VARCHAR2(10 BYTE),
  PRINTED                  VARCHAR2(1 BYTE),
  BILL_TO_NAME             VARCHAR2(100 BYTE),
  BILL_TO_ADDR_LINE1       VARCHAR2(100 BYTE),
  BILL_TO_ADDR_LINE2       VARCHAR2(100 BYTE),
  BILL_TO_ADDR_LINE3       VARCHAR2(100 BYTE),
  BILL_TO_ADDR_LINE4       VARCHAR2(100 BYTE),
  BILL_TO_COMP_NUMBER      NUMBER,
  BILL_TO_VAT_NUMBER       VARCHAR2(100 BYTE),
  BILL_TO_EMAIL            VARCHAR2(100 BYTE),
  BILL_FROM_NAME           VARCHAR2(100 BYTE),
  BILL_FROM_ADDR_LINE1     VARCHAR2(100 BYTE),
  BILL_FROM_ADDR_LINE2     VARCHAR2(100 BYTE),
  BILL_FROM_ADDR_LINE3     VARCHAR2(100 BYTE),
  BILL_FROM_ADDR_LINE4     VARCHAR2(100 BYTE),
  BILL_FROM_COMP_NUMBER    NUMBER,
  BILL_FROM_VAT_NUMBER     VARCHAR2(100 BYTE),
  BILL_FROM_EMAIL          VARCHAR2(100 BYTE),
  SHIP_FROM_NAME           VARCHAR2(100 BYTE),
  SHIP_FROM_ADDR_LINE1     VARCHAR2(100 BYTE),
  SHIP_FROM_ADDR_LINE2     VARCHAR2(100 BYTE),
  SHIP_FROM_ADDR_LINE3     VARCHAR2(100 BYTE),
  SHIP_FROM_ADDR_LINE4     VARCHAR2(100 BYTE),
  SHIP_FROM_ADDR_LINE5     VARCHAR2(100 BYTE),
  SHIP_TO_NAME             VARCHAR2(100 BYTE),
  SHIP_TO_ADDR_LINE1       VARCHAR2(100 BYTE),
  SHIP_TO_ADDR_LINE2       VARCHAR2(100 BYTE),
  SHIP_TO_ADDR_LINE3       VARCHAR2(100 BYTE),
  SHIP_TO_ADDR_LINE4       VARCHAR2(100 BYTE),
  SHIP_TO_ADDR_LINE5       VARCHAR2(100 BYTE),
  TAXSTMT_SHIP_TO_COUNTRY  VARCHAR2(50 BYTE),
  TAXSTMT_STMT             VARCHAR2(240 BYTE),
  TAXRATE_WAREHOUSE        VARCHAR2(50 BYTE),
  TAXRATE_SHIP_TO_COUNTRY  VARCHAR2(50 BYTE),
  TAXRATE_RATE             VARCHAR2(100 BYTE),
  SEQUENCE_NUM             NUMBER,
  CONS_INVOICE_NUM         VARCHAR2(100 BYTE),
  DATE_OF_ISSUE            VARCHAR2(100 BYTE),
  REQUEST_ID               NUMBER,
  EMAIL_ADDRESS            VARCHAR2(100 BYTE),
  CREATION_DATE            DATE,
  CREATED_BY               NUMBER,
  UPDATED_BY               NUMBER,
  UPDATED_DATE             DATE,
  LINE_DETAILS             VARCHAR2(10 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_AR_CONS_INV_GE_T TO APPS
/
