--
-- XXD_CIT_DATA_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_CIT_DATA_STG_T
(
  BATCH_ID                        NUMBER,
  CUSTOMER_TRX_ID                 NUMBER,
  TRX_NUMBER                      VARCHAR2(20 BYTE),
  BRAND                           VARCHAR2(20 BYTE),
  BILL_TO_CUSTOMER_ID             NUMBER,
  SHIP_TO_CUSTOMER_ID             NUMBER,
  AMOUNT_DUE_REMAINING            NUMBER,
  PAYMENT_SCHEDULE_ID             NUMBER,
  STATUS                          VARCHAR2(30 BYTE),
  ERROR_MSG                       VARCHAR2(200 BYTE),
  TRX_DATE                        DATE,
  NEGATIVE_LINE_ADJUSTMENT_ID     NUMBER,
  NEGATIVE_TAX_ADJUSTMENT_ID      NUMBER,
  NEGATIVE_FREIGHT_ADJUSTMENT_ID  NUMBER,
  POSITIVE_ADJUSTMENT_ID          NUMBER,
  NEGATIVE_CHARGES_ADJUSTMENT_ID  NUMBER,
  RECEIVABLES_CHARGES_REMAINING   NUMBER,
  AMOUNT_LINE_ITEMS_REMAINING     NUMBER,
  TAX_REMAINING                   NUMBER,
  FREIGHT_REMAINING               NUMBER,
  CREATED_BY                      VARCHAR2(50 BYTE),
  CREATION_DATE                   DATE,
  LAST_UPDATED_BY                 VARCHAR2(50 BYTE),
  LAST_UPDATED_DATE               DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_CIT_DATA_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CIT_DATA_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_CIT_DATA_STG_T FOR XXDO.XXD_CIT_DATA_STG_T
/


--
-- XXD_CIT_DATA_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CIT_DATA_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXD_CIT_DATA_STG_T FOR XXDO.XXD_CIT_DATA_STG_T
/
