--
-- XXD_ONT_EDI_ORDER_INSTRS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_EDI_ORDER_INSTRS_T
(
  INSTRUCTION_ID         NUMBER,
  ORG_ID                 NUMBER,
  ORIG_SYS_DOCUMENT_REF  VARCHAR2(50 BYTE),
  OPERATION_MODE         VARCHAR2(20 BYTE),
  INSTRUCTION_CATEGORY   VARCHAR2(50 BYTE),
  FILE_NAME              VARCHAR2(100 BYTE),
  FILE_DATA              BLOB,
  STATUS                 VARCHAR2(1 BYTE),
  ERROR_MESSAGE          VARCHAR2(4000 BYTE),
  REQUEST_ID             NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  CUST_PO_NUMBER         VARCHAR2(50 BYTE),
  ACCOUNT_NUMBER         VARCHAR2(30 BYTE),
  GLOBAL_ATTRIBUTE1      VARCHAR2(10 BYTE)
)
LOB (FILE_DATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_EDI_ORDER_INSTRS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_EDI_ORDER_INSTRS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_EDI_ORDER_INSTRS_T FOR XXDO.XXD_ONT_EDI_ORDER_INSTRS_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_ONT_EDI_ORDER_INSTRS_T TO SOA_INT
/
