--
-- XXD_AR_EXT_SALES_EXTRACT_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_AR_EXT_SALES_EXTRACT_GT
(
  AE_HEADER_ID           NUMBER,
  AE_LINE_NUM            NUMBER,
  LEDGER_ID              NUMBER,
  EVENT_ID               NUMBER,
  ACCOUNTING_CLASS_CODE  VARCHAR2(30 BYTE),
  SOURCE_ID_INT_1        NUMBER,
  CODE_COMBINATION_ID    NUMBER,
  ENTITY_ID              NUMBER,
  ACCOUNTING_DATE        DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- XXD_AR_EXT_SALES_EXTRACT_GT  (Synonym) 
--
--  Dependencies: 
--   XXD_AR_EXT_SALES_EXTRACT_GT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_AR_EXT_SALES_EXTRACT_GT FOR XXDO.XXD_AR_EXT_SALES_EXTRACT_GT
/
