--
-- XXDOEC_FACTORY_INV_DTLS_STG  (Table) 
--
CREATE TABLE XXDO.XXDOEC_FACTORY_INV_DTLS_STG
(
  INVOICE_DETAIL_ID     NUMBER,
  INVOICE_ID            NUMBER,
  ORDER_ID              VARCHAR2(50 BYTE),
  FLUID_RECIPE_ID       VARCHAR2(50 BYTE),
  ORDER_LINE_NUMBER     NUMBER,
  ACTUAL_SHIPMENT_DATE  DATE,
  AWB_NUMBER            VARCHAR2(120 BYTE),
  TRACKING_NUMBER       VARCHAR2(120 BYTE),
  ITEM_UPC              VARCHAR2(40 BYTE),
  ITEM_CODE             VARCHAR2(120 BYTE),
  ITEM_DESCRIPTION      VARCHAR2(240 BYTE),
  QUANTITY              NUMBER,
  UNIT_COST             NUMBER,
  PO_LINE_LOCATION_ID   NUMBER,
  PROCESS_FLAG          VARCHAR2(1 BYTE),
  ERROR_MESSAGE         VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_FACTORY_INV_DTLS_STG_U1  (Index) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INV_DTLS_STG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOEC_FACTORY_INV_DTLS_STG_U1 ON XXDO.XXDOEC_FACTORY_INV_DTLS_STG
(INVOICE_DETAIL_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_FACTORY_INV_DTLS_STG_N1  (Index) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INV_DTLS_STG (Table)
--
CREATE INDEX XXDO.XXDOEC_FACTORY_INV_DTLS_STG_N1 ON XXDO.XXDOEC_FACTORY_INV_DTLS_STG
(INVOICE_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_FACTORY_INV_DTLS_STG_N2  (Index) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INV_DTLS_STG (Table)
--
CREATE INDEX XXDO.XXDOEC_FACTORY_INV_DTLS_STG_N2 ON XXDO.XXDOEC_FACTORY_INV_DTLS_STG
(PROCESS_FLAG)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_FACTORY_INV_DTLS_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_FACTORY_INV_DTLS_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_FACTORY_INV_DTLS_STG FOR XXDO.XXDOEC_FACTORY_INV_DTLS_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOEC_FACTORY_INV_DTLS_STG TO APPS
/
