--
-- XXD_AR_DRCT_DEBIT_T  (Table) 
--
CREATE TABLE XXDO.XXD_AR_DRCT_DEBIT_T
(
  TRX_NUMBER             VARCHAR2(100 BYTE),
  TRX_ID                 NUMBER,
  ACCOUNT_NUM            VARCHAR2(100 BYTE),
  PARTY_NAME             VARCHAR2(500 BYTE),
  PARTY_ID               NUMBER,
  ADDRESS1               VARCHAR2(240 BYTE),
  ADDRESS2               VARCHAR2(240 BYTE),
  CITY                   VARCHAR2(100 BYTE),
  STATE                  VARCHAR2(100 BYTE),
  ZIPCODE                VARCHAR2(100 BYTE),
  COUNTRY                VARCHAR2(100 BYTE),
  AMOUNT                 NUMBER,
  FINAL_AMOUNT           NUMBER,
  GL_DATE                DATE,
  TRX_DATE               DATE,
  ORG_ID                 NUMBER,
  DIRECT_DEBIT_CUSTOMER  VARCHAR2(10 BYTE),
  DISCOUNT_DAYS          NUMBER,
  DISCOUNT_PERCENT       VARCHAR2(10 BYTE),
  DATA_SENT              VARCHAR2(10 BYTE),
  TRX_CLASS              VARCHAR2(50 BYTE),
  RECEIPT_BALANCE        NUMBER,
  TRX_BALANCE            NUMBER,
  REQUEST_ID             NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_DATE       DATE,
  CUST_ACCOUNT_ID        NUMBER,
  PROCESS_RECORD         VARCHAR2(10 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_AR_DRCT_DEBIT_T TO APPS
/
