--
-- XXD_FDA_PREV_SCN_T  (Table) 
--
CREATE TABLE XXDO.XXD_FDA_PREV_SCN_T
(
  INTEGRATION        VARCHAR2(100 BYTE),
  FDA_TABLE          VARCHAR2(100 BYTE),
  PREV_SCN           NUMBER,
  MAX_SCN            NUMBER,
  LAST_UPDATED_DATE  DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_FDA_PREV_SCN_T  (Synonym) 
--
--  Dependencies: 
--   XXD_FDA_PREV_SCN_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_FDA_PREV_SCN_T FOR XXDO.XXD_FDA_PREV_SCN_T
/


--
-- XXD_FDA_PREV_SCN_T  (Synonym) 
--
--  Dependencies: 
--   XXD_FDA_PREV_SCN_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_FDA_PREV_SCN_T FOR XXDO.XXD_FDA_PREV_SCN_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_FDA_PREV_SCN_T TO SOA_INT
/
