--
-- XXD_OM_HK_APB_TRAN_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_OM_HK_APB_TRAN_GT
(
  REQUEST_ID          NUMBER,
  ORDER_NUMBER        NUMBER,
  CUSTOMER_NUMBER     VARCHAR2(30 BYTE),
  CUSTOMER_NAME       VARCHAR2(360 BYTE),
  SHIP_TO_ADDRESS     VARCHAR2(1200 BYTE),
  PICK_TICKET_NUMBER  NUMBER,
  CUST_PO_NUMBER      VARCHAR2(240 BYTE),
  INVENTORY_ITEM_ID   NUMBER,
  PRICE               NUMBER,
  ITEM_STYLE          VARCHAR2(240 BYTE),
  ITEM_COLOR          VARCHAR2(240 BYTE),
  ITEM_SIZE           VARCHAR2(240 BYTE),
  SHIPPING_UNIT       NUMBER,
  SHIPPING_ORG        VARCHAR2(100 BYTE),
  ITEM_NUMBER         VARCHAR2(240 BYTE),
  ASN_PO_EXISTS_FLAG  VARCHAR2(1 BYTE),
  ITEM_EXISTS_LKP     VARCHAR2(1 BYTE),
  ATTR_NUM            NUMBER,
  ATTR_VAR            VARCHAR2(240 BYTE),
  ATTR_DATE           DATE,
  EMAIL_ID            VARCHAR2(1000 BYTE),
  FILE_NAME           VARCHAR2(1000 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
