--
-- XXD_ONT_ATP_STYLE_COLOR_GTT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_ONT_ATP_STYLE_COLOR_GTT
(
  DEMAND_CLASS       VARCHAR2(120 BYTE),
  PRIORITY_DATE      VARCHAR2(120 BYTE),
  ORGANIZATION_ID    NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  SKU                VARCHAR2(100 BYTE),
  DTE                VARCHAR2(100 BYTE),
  SIZES              VARCHAR2(100 BYTE),
  REQUEST_DATE       VARCHAR2(100 BYTE),
  POH                NUMBER,
  ATP                NUMBER,
  ATP_WB             NUMBER
)
ON COMMIT DELETE ROWS
NOCACHE
/
