--
-- XXD_MASTER_ATP_FULL_T  (Table) 
--
CREATE TABLE XXDO.XXD_MASTER_ATP_FULL_T
(
  SLNO                 NUMBER,
  SKU                  VARCHAR2(40 BYTE),
  INVENTORY_ITEM_ID    NUMBER,
  INV_ORGANIZATION_ID  NUMBER,
  DEMAND_CLASS_CODE    VARCHAR2(30 BYTE),
  APPLICATION          VARCHAR2(30 BYTE),
  BRAND                VARCHAR2(30 BYTE),
  UOM_CODE             VARCHAR2(3 BYTE),
  REQUESTED_SHIP_DATE  DATE,
  AVAILABLE_QUANTITY   NUMBER,
  AVAILABLE_DATE       DATE,
  CREATION_DATE        DATE,
  CREATED_BY           NUMBER,
  LAST_UPDATE_LOGIN    NUMBER,
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATED_BY      NUMBER,
  STORE_TYPE           VARCHAR2(20 BYTE)
)
NOCOMPRESS 
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
PARTITION BY HASH (APPLICATION)
(  
  PARTITION P1
    TABLESPACE CUSTOM_TX_TS
)
NOCACHE
/


--
-- XXD_MASTER_ATP_FULL_T_N1  (Index) 
--
--  Dependencies: 
--   XXD_MASTER_ATP_FULL_T (Table)
--
CREATE INDEX XXDO.XXD_MASTER_ATP_FULL_T_N1 ON XXDO.XXD_MASTER_ATP_FULL_T
(INVENTORY_ITEM_ID, DEMAND_CLASS_CODE, INV_ORGANIZATION_ID, AVAILABLE_DATE)
  TABLESPACE APPS_TS_TX_IDX
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
NOLOGGING
LOCAL (  
  PARTITION P1
    TABLESPACE APPS_TS_TX_IDX
)
/

--
-- XXD_MASTER_ATP_FULL_T_N2  (Index) 
--
--  Dependencies: 
--   XXD_MASTER_ATP_FULL_T (Table)
--
CREATE INDEX XXDO.XXD_MASTER_ATP_FULL_T_N2 ON XXDO.XXD_MASTER_ATP_FULL_T
(INVENTORY_ITEM_ID, INV_ORGANIZATION_ID, DEMAND_CLASS_CODE)
  TABLESPACE APPS_TS_TX_IDX
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
NOLOGGING
LOCAL (  
  PARTITION P1
    TABLESPACE APPS_TS_TX_IDX
)
/

--
-- XXD_MASTER_ATP_FULL_T_N5  (Index) 
--
--  Dependencies: 
--   XXD_MASTER_ATP_FULL_T (Table)
--
CREATE INDEX XXDO.XXD_MASTER_ATP_FULL_T_N5 ON XXDO.XXD_MASTER_ATP_FULL_T
(AVAILABLE_QUANTITY)
  TABLESPACE APPS_TS_TX_IDX
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
NOLOGGING
LOCAL (  
  PARTITION P1
    TABLESPACE APPS_TS_TX_IDX
)
/

--
-- XXD_MASTER_ATP_FULL_T_N6  (Index) 
--
--  Dependencies: 
--   XXD_MASTER_ATP_FULL_T (Table)
--
CREATE INDEX XXDO.XXD_MASTER_ATP_FULL_T_N6 ON XXDO.XXD_MASTER_ATP_FULL_T
(APPLICATION)
  TABLESPACE APPS_TS_TX_IDX
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
NOLOGGING
LOCAL (  
  PARTITION P1
    TABLESPACE APPS_TS_TX_IDX
)
/

--
-- XXD_MASTER_ATP_FULL_T  (Synonym) 
--
--  Dependencies: 
--   XXD_MASTER_ATP_FULL_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_MASTER_ATP_FULL_T FOR XXDO.XXD_MASTER_ATP_FULL_T
/


--
-- XXD_MASTER_ATP_FULL_T  (Synonym) 
--
--  Dependencies: 
--   XXD_MASTER_ATP_FULL_T (Table)
--
CREATE OR REPLACE SYNONYM XXBIUSER.XXD_MASTER_ATP_FULL_T FOR XXDO.XXD_MASTER_ATP_FULL_T
/
