--
-- XXD_AP_INV_UPLOAD_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_AP_INV_UPLOAD_STG_T
(
  PO_NUMBER_HDR            VARCHAR2(20 BYTE),
  INVOICE_NUMBER           VARCHAR2(50 BYTE),
  ORG_ID                   NUMBER,
  VENDOR_NAME              VARCHAR2(240 BYTE),
  VENDOR_NUM               VARCHAR2(30 BYTE),
  VENDOR_SITE_CODE         VARCHAR2(15 BYTE),
  INVOICE_DATE             VARCHAR2(100 BYTE),
  INVOICE_AMOUNT           NUMBER,
  INVOICE_CURRENCY_CODE    VARCHAR2(15 BYTE),
  INVOICE_DESCRIPTION      VARCHAR2(1000 BYTE),
  VENDOR_CHARGED_TAX       NUMBER,
  TAX_CONTROL_AMOUNT       NUMBER,
  FAPIO_RECEIVED           VARCHAR2(240 BYTE),
  LINE_TYPE                VARCHAR2(25 BYTE),
  LINE_DESCRIPTION         VARCHAR2(1000 BYTE),
  LINE_AMOUNT              NUMBER,
  DIST_ACCOUNT             VARCHAR2(250 BYTE),
  SHIP_TO                  VARCHAR2(25 BYTE),
  PO_NUMBER_LINE           VARCHAR2(20 BYTE),
  PO_LINE_NUMBER           NUMBER,
  QUANTITY_INVOICED        NUMBER,
  UNIT_PRICE               NUMBER,
  TAX_CLASSIFICATION_CODE  VARCHAR2(150 BYTE),
  INTERCO_EXPENSE_ACCOUNT  VARCHAR2(150 BYTE),
  DEFERRED                 VARCHAR2(1 BYTE),
  DEFERRED_START_DATE      DATE,
  DEFERRED_END_DATE        DATE,
  PRORATE_ALL_ITEM_LINES   VARCHAR2(1 BYTE),
  TRACK_AS_ASSET           VARCHAR2(1 BYTE),
  ASSET_CATEGORY           VARCHAR2(15 BYTE),
  APPROVER                 VARCHAR2(150 BYTE),
  DATE_SENT_TO_APPROVER    DATE,
  MISC_NOTES               VARCHAR2(150 BYTE),
  CHARGEBACK               VARCHAR2(150 BYTE),
  INVOICE_NUM              VARCHAR2(150 BYTE),
  PAYMENT_REF_NUMBER       VARCHAR2(150 BYTE),
  SAMPLE_INVOICE           VARCHAR2(150 BYTE),
  ASSET_BOOK               VARCHAR2(240 BYTE),
  DISTRIBUTION_SET         VARCHAR2(50 BYTE),
  PAYMENT_TERMS            VARCHAR2(50 BYTE),
  INVOICE_ADDL_INFO        VARCHAR2(150 BYTE),
  PAY_ALONE                VARCHAR2(1 BYTE),
  TRANSACTION_TYPE         VARCHAR2(50 BYTE),
  VENDOR_VAT_REG_NUM       VARCHAR2(50 BYTE),
  NATURE_CODES             VARCHAR2(150 BYTE),
  TAX_EXEMPTION_REASON     VARCHAR2(150 BYTE),
  REQUEST_ID               NUMBER,
  FILE_NAME                VARCHAR2(500 BYTE),
  STATUS                   VARCHAR2(20 BYTE),
  ERROR_MSG                VARCHAR2(4000 BYTE),
  CREATION_DATE            DATE,
  CREATED_BY               NUMBER,
  LAST_UPDATE_DATE         DATE,
  LAST_UPDATED_BY          NUMBER,
  VENDOR_ID                NUMBER,
  VENDOR_SITE_ID           NUMBER,
  INV_HDR_GRP_ID           NUMBER,
  GL_DATE                  DATE,
  TERMS_ID                 NUMBER,
  PO_HEADER_ID_LINE        NUMBER,
  PO_LINE_ID               NUMBER,
  LOCATION_ID              NUMBER,
  DIST_ACCT_ID             NUMBER,
  INV_SOURCE               VARCHAR2(100 BYTE),
  PAYMENT_METHOD_CODE      VARCHAR2(30 BYTE),
  INV_HEADER_ID            NUMBER,
  INV_LINE_ID              NUMBER,
  INV_LINE_NUMBER          NUMBER,
  INVOICE_ID               NUMBER,
  HOLD_FLAG                VARCHAR2(10 BYTE),
  VENDOR_CHARGE_TAX        NUMBER,
  PO_HDR_INCLUDE           VARCHAR2(10 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_AP_INV_UPLOAD_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_AP_INV_UPLOAD_STG_T (Table)
--
CREATE OR REPLACE PUBLIC SYNONYM XXD_AP_INV_UPLOAD_STG_T FOR XXDO.XXD_AP_INV_UPLOAD_STG_T
/
