--
-- XXDOEC_ORDER_ATTRIBUTE  (Table) 
--
CREATE TABLE XXDO.XXDOEC_ORDER_ATTRIBUTE
(
  ATTRIBUTE_ID     NUMBER,
  ATTRIBUTE_TYPE   VARCHAR2(30 BYTE)            NOT NULL,
  ATTRIBUTE_VALUE  VARCHAR2(2000 BYTE)          NOT NULL,
  USER_NAME        VARCHAR2(50 BYTE),
  ORDER_HEADER_ID  NUMBER                       NOT NULL,
  LINE_ID          NUMBER,
  CREATION_DATE    DATE                         NOT NULL,
  SUPPLEMENTAL LOG GROUP GGS_3154655 (ATTRIBUTE_ID) ALWAYS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- ATTRIBUTE_PK  (Index) 
--
--  Dependencies: 
--   XXDOEC_ORDER_ATTRIBUTE (Table)
--
CREATE UNIQUE INDEX XXDO.ATTRIBUTE_PK ON XXDO.XXDOEC_ORDER_ATTRIBUTE
(ATTRIBUTE_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDOEC_ORDER_ATTRIBUTE ADD (
  CONSTRAINT ATTRIBUTE_PK
  PRIMARY KEY
  (ATTRIBUTE_ID)
  USING INDEX XXDO.ATTRIBUTE_PK
  ENABLE VALIDATE)
/


--
-- XXDOEC_ORDER_ATTRIBUTE_N1  (Index) 
--
--  Dependencies: 
--   XXDOEC_ORDER_ATTRIBUTE (Table)
--
CREATE INDEX XXDO.XXDOEC_ORDER_ATTRIBUTE_N1 ON XXDO.XXDOEC_ORDER_ATTRIBUTE
(ORDER_HEADER_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ORDER_ATTRIBUTE_N5  (Index) 
--
--  Dependencies: 
--   XXDOEC_ORDER_ATTRIBUTE (Table)
--
CREATE INDEX APPS.XXDO_ORDER_ATTRIBUTE_N5 ON XXDO.XXDOEC_ORDER_ATTRIBUTE
(LINE_ID, ATTRIBUTE_TYPE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_ORDER_ATTRIBUTE  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_ORDER_ATTRIBUTE (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_ORDER_ATTRIBUTE FOR XXDO.XXDOEC_ORDER_ATTRIBUTE
/


GRANT SELECT ON XXDO.XXDOEC_ORDER_ATTRIBUTE TO APPSRO
/
