--
-- XXDOINV_CIR_DATA  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXDOINV_CIR_DATA
(
  TPE                    VARCHAR2(20 BYTE)      NOT NULL,
  ORGANIZATION_ID        NUMBER                 NOT NULL,
  INVENTORY_ITEM_ID      NUMBER                 NOT NULL,
  QUANTITY               NUMBER,
  RCV_TRANSACTION_ID     NUMBER,
  TRX_MATERIAL_COST      NUMBER,
  TRX_FREIGHT_COST       NUMBER,
  TRX_DUTY_COST          NUMBER,
  TRX_ITEM_COST          NUMBER,
  ITM_MATERIAL_COST      NUMBER,
  ITM_FREIGHT_COST       NUMBER,
  ITM_DUTY_COST          NUMBER,
  ITM_ITEM_COST          NUMBER,
  SYS_ITEM_COST          NUMBER,
  SYS_ITEM_NON_MAT_COST  NUMBER,
  ACCRUAL_MISSING        NUMBER                 DEFAULT 0                     NOT NULL
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- XXDOINV_CIR_DATA_N1  (Index) 
--
--  Dependencies: 
--   XXDOINV_CIR_DATA (Table)
--
CREATE INDEX XXDO.XXDOINV_CIR_DATA_N1 ON XXDO.XXDOINV_CIR_DATA
(ORGANIZATION_ID, INVENTORY_ITEM_ID)
/
