--
-- XXD_ATP_LEVEL_API_ERROR_T  (Table) 
--
CREATE TABLE XXDO.XXD_ATP_LEVEL_API_ERROR_T
(
  SESSION_ID       NUMBER,
  ORDER_HEADER_ID  NUMBER,
  ACTION_TYPE      VARCHAR2(100 BYTE),
  ERROR_MESSAGE    VARCHAR2(4000 BYTE),
  CREATION_DATE    DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ATP_LEVEL_API_ERROR_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ATP_LEVEL_API_ERROR_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ATP_LEVEL_API_ERROR_T FOR XXDO.XXD_ATP_LEVEL_API_ERROR_T
/
