--
-- XXDOEC_COUNTRY_BRAND_PARAMS  (Table) 
--
CREATE TABLE XXDO.XXDOEC_COUNTRY_BRAND_PARAMS
(
  COUNTRY_CODE            VARCHAR2(10 BYTE),
  BRAND_NAME              VARCHAR2(10 BYTE),
  CUSTOMER_ID             NUMBER,
  CUSTOMER_NUMBER         VARCHAR2(10 BYTE),
  TRANSACTION_USER_ID     NUMBER,
  ERP_LOGIN_RESP_ID       NUMBER,
  ERP_LOGIN_APP_ID        NUMBER,
  ERP_ORG_ID              NUMBER,
  INV_ORG_ID              NUMBER,
  COMPANY_NAME            VARCHAR2(80 BYTE),
  AR_BATCH_SOURCE_ID      NUMBER,
  AR_BANK_BRANCH_ID       NUMBER,
  AR_BANK_ACCOUNT_ID      NUMBER,
  AR_BATCH_TYPE           VARCHAR2(40 BYTE),
  AR_RECEIPT_CLASS_ID     NUMBER,
  AR_RECEIPT_METHOD_ID    NUMBER,
  AR_CM_REASON_CODE       VARCHAR2(40 BYTE),
  AR_CM_CUST_TRX_TYPE_ID  NUMBER,
  AR_REVENUE_ACCOUNT_ID   NUMBER,
  OM_ORDER_TYPE_ID        NUMBER,
  OM_PRICE_LIST_ID        NUMBER,
  WEBSITE_ID              VARCHAR2(120 BYTE),
  ERP_LANGUAGE            VARCHAR2(150 BYTE),
  VIRTUAL_INV_ORG_ID      NUMBER,
  SS_WAIT_HOURS           NUMBER                DEFAULT 0,
  CREATION_DATE           DATE,
  CREATED_BY              NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATED_BY         NUMBER,
  LAST_UPDATE_LOGIN       NUMBER,
  RECORD_ID               NUMBER                NOT NULL,
  SUPPLEMENTAL LOG GROUP GGS_3154408 (RECORD_ID) ALWAYS,
  SUPPLEMENTAL LOG GROUP GGS_700544 (COUNTRY_CODE,BRAND_NAME,CUSTOMER_ID,CUSTOMER_NUMBER,TRANSACTION_USER_ID,ERP_LOGIN_RESP_ID,ERP_LOGIN_APP_ID,ERP_ORG_ID,INV_ORG_ID,COMPANY_NAME,AR_BATCH_SOURCE_ID,AR_BANK_BRANCH_ID,AR_BANK_ACCOUNT_ID,AR_BATCH_TYPE,AR_RECEIPT_CLASS_ID,AR_RECEIPT_METHOD_ID,AR_CM_REASON_CODE,AR_CM_CUST_TRX_TYPE_ID,AR_REVENUE_ACCOUNT_ID,OM_ORDER_TYPE_ID,OM_PRICE_LIST_ID,WEBSITE_ID,ERP_LANGUAGE,VIRTUAL_INV_ORG_ID,SS_WAIT_HOURS) ALWAYS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_COUNTRY_BRAND_PARAMS_PK  (Index) 
--
--  Dependencies: 
--   XXDOEC_COUNTRY_BRAND_PARAMS (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOEC_COUNTRY_BRAND_PARAMS_PK ON XXDO.XXDOEC_COUNTRY_BRAND_PARAMS
(RECORD_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_COUNTRY_BRAND_PARAMS  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_COUNTRY_BRAND_PARAMS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_COUNTRY_BRAND_PARAMS FOR XXDO.XXDOEC_COUNTRY_BRAND_PARAMS
/


GRANT SELECT ON XXDO.XXDOEC_COUNTRY_BRAND_PARAMS TO APPS WITH GRANT OPTION
/
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOEC_COUNTRY_BRAND_PARAMS TO APPS
/

GRANT SELECT ON XXDO.XXDOEC_COUNTRY_BRAND_PARAMS TO APPSRO
/

GRANT ALTER, SELECT, FLASHBACK ON XXDO.XXDOEC_COUNTRY_BRAND_PARAMS TO OGGADM
/
