--
-- XXD_PO_BUYER_UPD_PO_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_PO_BUYER_UPD_PO_STG_T
(
  OPERATING_UNIT     VARCHAR2(240 BYTE),
  BRAND              VARCHAR2(20 BYTE),
  DEPARTMENT         VARCHAR2(50 BYTE),
  PO_NUMBER          VARCHAR2(30 BYTE),
  PO_DATE            DATE,
  BUY_SEASON         VARCHAR2(30 BYTE),
  BUY_MONTH          VARCHAR2(30 BYTE),
  BUYER_NAME         VARCHAR2(120 BYTE),
  NEW_BUYER_NAME     VARCHAR2(120 BYTE),
  PO_HEADER_ID       NUMBER,
  ORG_ID             NUMBER,
  OLD_BUYER_ID       NUMBER,
  NEW_BUYER_ID       NUMBER,
  STATUS             VARCHAR2(30 BYTE),
  ERROR_MESSAGE      VARCHAR2(4000 BYTE),
  REQUEST_ID         NUMBER,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
