--
-- XXDO_GLOBAL_ERROR_LOG_T  (Table) 
--
CREATE TABLE XXDO.XXDO_GLOBAL_ERROR_LOG_T
(
  SEQ              NUMBER,
  MODULE           VARCHAR2(300 BYTE),
  CUST_ACCOUNT_ID  NUMBER,
  OBJECT_NAME      VARCHAR2(300 BYTE),
  ERROR_MESSAGE    VARCHAR2(3000 BYTE),
  ERROR_LINE       VARCHAR2(300 BYTE),
  CREATION_DATE    DATE,
  CREATED_BY       VARCHAR2(300 BYTE),
  REQUEST_ID       NUMBER,
  USEFUL_INFO1     VARCHAR2(3000 BYTE),
  USEFUL_INFO2     VARCHAR2(3000 BYTE),
  USEFUL_INFO3     VARCHAR2(3000 BYTE),
  USEFUL_INFO4     VARCHAR2(3000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ERROR_LOG_N1  (Index) 
--
--  Dependencies: 
--   XXDO_GLOBAL_ERROR_LOG_T (Table)
--
CREATE INDEX XXDO.XXDO_ERROR_LOG_N1 ON XXDO.XXDO_GLOBAL_ERROR_LOG_T
(REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ERROR_LOG_N2  (Index) 
--
--  Dependencies: 
--   XXDO_GLOBAL_ERROR_LOG_T (Table)
--
CREATE INDEX XXDO.XXDO_ERROR_LOG_N2 ON XXDO.XXDO_GLOBAL_ERROR_LOG_T
(USEFUL_INFO1)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_GLOBAL_ERROR_LOG_T  (Synonym) 
--
--  Dependencies: 
--   XXDO_GLOBAL_ERROR_LOG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_GLOBAL_ERROR_LOG_T FOR XXDO.XXDO_GLOBAL_ERROR_LOG_T
/


GRANT SELECT ON XXDO.XXDO_GLOBAL_ERROR_LOG_T TO APPS
/

GRANT SELECT ON XXDO.XXDO_GLOBAL_ERROR_LOG_T TO APPSRO WITH GRANT OPTION
/
