--
-- XXD_GL_CONCUR_ACC_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_CONCUR_ACC_T
(
  SEQ_DB_NUM           NUMBER,
  CREATION_DATE        VARCHAR2(10 BYTE),
  CREATED_BY           NUMBER,
  LAST_UPDATE_DATE     VARCHAR2(10 BYTE),
  LAST_UPDATED_BY      NUMBER,
  LAST_UPDATE_LOGIN    NUMBER,
  FILE_NAME            VARCHAR2(500 BYTE),
  FILE_PROCESSED_DATE  VARCHAR2(10 BYTE),
  STATUS               VARCHAR2(1 BYTE),
  JOURNAL_BATCH_ID     NUMBER,
  JOUNAL_HEADER_ID     NUMBER,
  JOURNAL_LINE_NUM     NUMBER,
  REQUEST_ID           NUMBER,
  EMP_FIRST_NAME       VARCHAR2(240 BYTE),
  EMP_LAST_NAME        VARCHAR2(240 BYTE),
  BAL_SEG              VARCHAR2(100 BYTE),
  INTERCO_BAL_SEG      VARCHAR2(100 BYTE),
  REPORT_ID            VARCHAR2(240 BYTE),
  COMPANY_SEG          VARCHAR2(100 BYTE),
  BRAND_SEG            VARCHAR2(100 BYTE),
  GEO_SEG              VARCHAR2(100 BYTE),
  CHANNEL_SEG          VARCHAR2(100 BYTE),
  COST_CENTER_SEG      VARCHAR2(100 BYTE),
  ACCOUNT_CODE_SEG     VARCHAR2(100 BYTE),
  INTERCOMPANY_SEG     VARCHAR2(100 BYTE),
  FUTURE_USE_SEG       VARCHAR2(100 BYTE),
  VENDOR_NAME          VARCHAR2(500 BYTE),
  VENDOR_DESC          VARCHAR2(500 BYTE),
  DESCRIPTION          VARCHAR2(500 BYTE),
  AMOUNT               NUMBER,
  CURRENCY             VARCHAR2(100 BYTE),
  PAID_FLAG            VARCHAR2(10 BYTE),
  FUTURE_VALUE1        VARCHAR2(255 BYTE),
  FUTURE_VALUE2        VARCHAR2(255 BYTE),
  FUTURE_VALUE3        VARCHAR2(255 BYTE),
  FUTURE_VALUE4        VARCHAR2(255 BYTE),
  FUTURE_VALUE5        VARCHAR2(255 BYTE),
  FUTURE_VALUE6        VARCHAR2(255 BYTE),
  FUTURE_VALUE7        VARCHAR2(255 BYTE),
  FUTURE_VALUE8        VARCHAR2(255 BYTE),
  FUTURE_VALUE9        VARCHAR2(255 BYTE),
  FUTURE_VALUE10       VARCHAR2(255 BYTE),
  FUTURE_VALUE11       VARCHAR2(255 BYTE),
  FUTURE_VALUE12       VARCHAR2(255 BYTE),
  FUTURE_VALUE13       VARCHAR2(255 BYTE),
  FUTURE_VALUE14       VARCHAR2(255 BYTE),
  FUTURE_VALUE15       VARCHAR2(255 BYTE),
  FUTURE_VALUE16       VARCHAR2(255 BYTE),
  FUTURE_VALUE17       VARCHAR2(255 BYTE),
  FUTURE_VALUE18       VARCHAR2(255 BYTE),
  FUTURE_VALUE19       VARCHAR2(255 BYTE),
  FUTURE_VALUE20       VARCHAR2(255 BYTE),
  FUTURE_VALUE21       VARCHAR2(255 BYTE),
  FUTURE_VALUE22       VARCHAR2(255 BYTE),
  FUTURE_VALUE23       VARCHAR2(255 BYTE),
  FUTURE_VALUE24       VARCHAR2(255 BYTE),
  FUTURE_VALUE25       VARCHAR2(255 BYTE),
  FUTURE_VALUE26       VARCHAR2(255 BYTE),
  FUTURE_VALUE27       VARCHAR2(255 BYTE),
  FUTURE_VALUE28       VARCHAR2(255 BYTE),
  FUTURE_VALUE29       VARCHAR2(255 BYTE),
  FUTURE_VALUE30       VARCHAR2(255 BYTE),
  ERROR_MSG            VARCHAR2(4000 BYTE),
  GL_JE_SOURCE         VARCHAR2(100 BYTE),
  GL_JE_CATEGORY       VARCHAR2(100 BYTE),
  PROCESS_FLAG         VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_CONS_PK1  (Index) 
--
--  Dependencies: 
--   XXD_GL_CONCUR_ACC_T (Table)
--
CREATE UNIQUE INDEX XXDO.XXD_GL_CONS_PK1 ON XXDO.XXD_GL_CONCUR_ACC_T
(SEQ_DB_NUM)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXD_GL_CONCUR_ACC_T ADD (
  CONSTRAINT XXD_GL_CONS_PK1
  PRIMARY KEY
  (SEQ_DB_NUM)
  USING INDEX XXDO.XXD_GL_CONS_PK1
  ENABLE VALIDATE)
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_CONCUR_ACC_T TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_CONCUR_ACC_T TO SOA_INT
/
