--
-- XXDOAP_INV_ONHOLD_NOTIF_TEMP  (Table) 
--
CREATE TABLE XXDO.XXDOAP_INV_ONHOLD_NOTIF_TEMP
(
  BATCH_ID                 NUMBER               NOT NULL,
  INVOICE_NUM              VARCHAR2(50 BYTE),
  INVOICE_DATE             DATE,
  INVOICE_AMOUNT           NUMBER,
  INVOICE_LINE_NUMBER      NUMBER,
  LINE_TYPE                VARCHAR2(25 BYTE),
  INV_LINE_DESC            VARCHAR2(240 BYTE),
  INVOICE_LINE_AMOUNT      NUMBER,
  QUANTITY_INVOICED        NUMBER,
  INVOICE_LINE_UNIT_PRICE  NUMBER,
  UOM                      VARCHAR2(25 BYTE),
  VENDOR_NAME              VARCHAR2(240 BYTE),
  VENDOR_SITE              VARCHAR2(15 BYTE),
  HOLD_CODE                VARCHAR2(25 BYTE),
  HOLD_REASON              VARCHAR2(240 BYTE),
  PO_NUMBER                VARCHAR2(20 BYTE),
  PO_LINE_NUMBER           NUMBER,
  PO_LINE_QUANTITY         NUMBER,
  PO_LINE_UNIT_PRICE       NUMBER,
  PO_LINE_AMOUNT           NUMBER,
  SHIPMENT_ORDERED         NUMBER,
  SHIPMENT_BILLED          NUMBER,
  SHIPMENT_RECEIVED        NUMBER,
  RECEIPT_TOTAL            NUMBER,
  ORG_ID                   NUMBER,
  AGENT_ID                 NUMBER,
  PREPARER_ID              NUMBER,
  CREATION_DATE            DATE,
  CREATED_BY               NUMBER,
  LAST_UPDATE_DATE         DATE,
  LAST_UPDATED_BY          NUMBER,
  LAST_UPDATE_LOGIN        NUMBER,
  REQUEST_ID               NUMBER,
  INVOICE_CREATE_DATE      DATE,
  INVOICE_DUE_DATE         DATE,
  PREPARER_NAME            VARCHAR2(240 BYTE),
  REQUESTER_NAME           VARCHAR2(240 BYTE),
  APPROVER_NAME            VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAP_INV_ONHOLD_NOTIF_TEMP  (Synonym) 
--
--  Dependencies: 
--   XXDOAP_INV_ONHOLD_NOTIF_TEMP (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAP_INV_ONHOLD_NOTIF_TEMP FOR XXDO.XXDOAP_INV_ONHOLD_NOTIF_TEMP
/
