--
-- XXD_FA_ROLL_RSV_LEDGER_T  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_FA_ROLL_RSV_LEDGER_T
(
  ASSET_ID                NUMBER(15),
  DH_CCID                 NUMBER(15),
  DATE_PLACED_IN_SERVICE  DATE,
  METHOD_CODE             VARCHAR2(12 BYTE),
  LIFE                    NUMBER(6),
  RATE                    NUMBER,
  CAPACITY                NUMBER,
  COST                    NUMBER,
  DEPRN_AMOUNT            NUMBER,
  YTD_DEPRN               NUMBER,
  PERCENT                 NUMBER,
  TRANSACTION_TYPE        VARCHAR2(1 BYTE),
  DEPRN_RESERVE           NUMBER,
  PERIOD_COUNTER          NUMBER(15),
  DATE_EFFECTIVE          DATE,
  DEPRN_RESERVE_ACCT      VARCHAR2(25 BYTE),
  RESERVE_ACCT            VARCHAR2(25 BYTE),
  DISTRIBUTION_ID         NUMBER(15)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_FA_ROLL_RSV_LEDGER_T TO APPS
/
