--
-- XXD_OU_ALIGNMENT_INBOUND_T  (Table) 
--
CREATE TABLE XXDO.XXD_OU_ALIGNMENT_INBOUND_T
(
  ORIGINAL_OU                        VARCHAR2(150 BYTE),
  SOURCE_CUSTOMER                    VARCHAR2(150 BYTE),
  SOURCE_ORDER_NUMBER                VARCHAR2(30 BYTE),
  SOURCE_ORDER_REQUEST_DATE_FROM     VARCHAR2(150 BYTE),
  SOURCE_ORDER_REQUEST_DATE_TO       VARCHAR2(150 BYTE),
  TARGET_OU                          VARCHAR2(150 BYTE),
  TARGET_CUSTOMER                    VARCHAR2(150 BYTE),
  TARGET_SHIP_TO_LOCATION            VARCHAR2(240 BYTE),
  TARGET_BILL_TO_LOCATION            VARCHAR2(240 BYTE),
  TARGET_ORDER_TYPE                  VARCHAR2(150 BYTE),
  TARGET_SALE_REP                    VARCHAR2(150 BYTE),
  TARGET_PRICE_LIST                  NUMBER,
  TARGET_ORDERED_DATE                VARCHAR2(150 BYTE),
  TARGET_CANCEL_DATE                 VARCHAR2(150 BYTE),
  TARGET_REQUEST_DATE                VARCHAR2(150 BYTE),
  TARGET_LATEST_ACCEPTABLE_DATE      VARCHAR2(150 BYTE),
  ALLOW_TO_CREATE_UNSCHEDULED_LINES  VARCHAR2(30 BYTE),
  SOURCE_ORG_ID                      NUMBER,
  TARGET_ORG_ID                      NUMBER,
  CREATION_DATE                      DATE,
  CREATED_BY                         NUMBER,
  LAST_UPDATE_DATE                   DATE,
  LAST_UPDATED_BY                    NUMBER,
  REQUEST_ID                         NUMBER,
  FILE_NAME                          VARCHAR2(250 BYTE),
  ERROR_MESSAGE                      VARCHAR2(2000 BYTE),
  STATUS                             VARCHAR2(150 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_OU_ALIGNMENT_INBOUND_T  (Synonym) 
--
--  Dependencies: 
--   XXD_OU_ALIGNMENT_INBOUND_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_OU_ALIGNMENT_INBOUND_T FOR XXDO.XXD_OU_ALIGNMENT_INBOUND_T
/
