--
-- XXDO_SERIAL_TEMP  (Table) 
--
CREATE TABLE XXDO.XXDO_SERIAL_TEMP
(
  SERIAL_NUMBER          VARCHAR2(30 BYTE)      NOT NULL,
  LPN_ID                 NUMBER,
  LICENSE_PLATE_NUMBER   VARCHAR2(30 BYTE),
  INVENTORY_ITEM_ID      NUMBER,
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  LAST_UPDATED_BY        NUMBER                 NOT NULL,
  CREATION_DATE          DATE                   NOT NULL,
  CREATED_BY             NUMBER                 NOT NULL,
  ORGANIZATION_ID        NUMBER                 NOT NULL,
  SUBINVENTORY_CODE      VARCHAR2(10 BYTE),
  LOCATOR_ID             NUMBER,
  STATUS_ID              NUMBER                 NOT NULL,
  SOURCE_CODE            VARCHAR2(30 BYTE),
  SOURCE_CODE_REFERENCE  VARCHAR2(50 BYTE),
  SOA_EVENT              VARCHAR2(30 BYTE),
  SOA_STATUS             VARCHAR2(30 BYTE),
  SOA_MESSAGE_TEXT       VARCHAR2(1000 BYTE),
  SOA_UPDATE_DATE        DATE,
  PRODUCT_QR_CODE        VARCHAR2(30 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- SERIAL_NUMBER_PK  (Index) 
--
--  Dependencies: 
--   XXDO_SERIAL_TEMP (Table)
--
CREATE UNIQUE INDEX XXDO.SERIAL_NUMBER_PK ON XXDO.XXDO_SERIAL_TEMP
(SERIAL_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDO_SERIAL_TEMP ADD (
  CONSTRAINT SERIAL_NUMBER_PK
  PRIMARY KEY
  (SERIAL_NUMBER)
  USING INDEX XXDO.SERIAL_NUMBER_PK
  ENABLE VALIDATE)
/
