--
-- XXDO_ONT_RMA_LINE_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_ONT_RMA_LINE_STG
(
  WH_ID                  VARCHAR2(10 BYTE)      NOT NULL,
  RMA_NUMBER             VARCHAR2(30 BYTE),
  RMA_REFERENCE          VARCHAR2(30 BYTE),
  LINE_NUMBER            NUMBER,
  ITEM_NUMBER            VARCHAR2(30 BYTE)      NOT NULL,
  TYPE1                  VARCHAR2(20 BYTE),
  DISPOSITION            VARCHAR2(10 BYTE),
  COMMENTS               VARCHAR2(250 BYTE),
  QTY                    NUMBER,
  EMPLOYEE_ID            VARCHAR2(10 BYTE)      NOT NULL,
  EMPLOYEE_NAME          VARCHAR2(50 BYTE)      NOT NULL,
  CUST_RETURN_REASON     VARCHAR2(30 BYTE),
  FACTORY_CODE           VARCHAR2(20 BYTE),
  DAMAGE_CODE            VARCHAR2(30 BYTE),
  PROD_CODE              VARCHAR2(30 BYTE),
  UOM                    VARCHAR2(10 BYTE),
  HOST_SUBINVENTORY      VARCHAR2(20 BYTE)      NOT NULL,
  ATTRIBUTE1             VARCHAR2(50 BYTE),
  ATTRIBUTE2             VARCHAR2(50 BYTE),
  ATTRIBUTE3             VARCHAR2(50 BYTE),
  ATTRIBUTE4             VARCHAR2(50 BYTE),
  ATTRIBUTE5             VARCHAR2(50 BYTE),
  ATTRIBUTE6             VARCHAR2(50 BYTE),
  ATTRIBUTE7             VARCHAR2(50 BYTE),
  ATTRIBUTE8             VARCHAR2(50 BYTE),
  ATTRIBUTE9             VARCHAR2(50 BYTE),
  ATTRIBUTE10            VARCHAR2(50 BYTE),
  ATTRIBUTE11            VARCHAR2(50 BYTE),
  ATTRIBUTE12            VARCHAR2(50 BYTE),
  ATTRIBUTE13            VARCHAR2(50 BYTE),
  ATTRIBUTE14            VARCHAR2(50 BYTE),
  ATTRIBUTE15            VARCHAR2(50 BYTE),
  ATTRIBUTE16            VARCHAR2(50 BYTE),
  ATTRIBUTE17            VARCHAR2(50 BYTE),
  ATTRIBUTE18            VARCHAR2(50 BYTE),
  ATTRIBUTE19            VARCHAR2(50 BYTE),
  ATTRIBUTE20            VARCHAR2(50 BYTE),
  REQUEST_ID             NUMBER,
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  SOURCE                 VARCHAR2(20 BYTE)      DEFAULT 'WMS',
  DESTINATION            VARCHAR2(20 BYTE)      DEFAULT 'EBS',
  RECORD_TYPE            VARCHAR2(20 BYTE),
  HEADER_ID              NUMBER,
  LINE_ID                NUMBER,
  PROCESS_STATUS         VARCHAR2(30 BYTE),
  ERROR_MESSAGE          VARCHAR2(1000 BYTE),
  INVENTORY_ITEM_ID      NUMBER,
  SHIP_FROM_ORG_ID       NUMBER,
  RESULT_CODE            VARCHAR2(1 BYTE),
  GROUP_ID               NUMBER,
  RETCODE                NUMBER,
  RECEIPT_HEADER_SEQ_ID  NUMBER,
  RECEIPT_LINE_SEQ_ID    NUMBER,
  RMA_RECEIPT_DATE       DATE,
  ORG_ID                 NUMBER,
  RMA_XML_SEQ_ID         NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ONT_RMA_LINE_STG_IDX1  (Index) 
--
--  Dependencies: 
--   XXDO_ONT_RMA_LINE_STG (Table)
--
CREATE INDEX XXDO.XXDO_ONT_RMA_LINE_STG_IDX1 ON XXDO.XXDO_ONT_RMA_LINE_STG
(REQUEST_ID, RMA_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ONT_RMA_LINE_STG_IDX2  (Index) 
--
--  Dependencies: 
--   XXDO_ONT_RMA_LINE_STG (Table)
--
CREATE INDEX XXDO.XXDO_ONT_RMA_LINE_STG_IDX2 ON XXDO.XXDO_ONT_RMA_LINE_STG
(ITEM_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ONT_RMA_LINE_STG_IDX3  (Index) 
--
--  Dependencies: 
--   XXDO_ONT_RMA_LINE_STG (Table)
--
CREATE INDEX XXDO.XXDO_ONT_RMA_LINE_STG_IDX3 ON XXDO.XXDO_ONT_RMA_LINE_STG
(PROCESS_STATUS)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ONT_RMA_LINE_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_ONT_RMA_LINE_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_ONT_RMA_LINE_STG FOR XXDO.XXDO_ONT_RMA_LINE_STG
/


--
-- XXDO_ONT_RMA_LINE_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_ONT_RMA_LINE_STG (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXDO_ONT_RMA_LINE_STG FOR XXDO.XXDO_ONT_RMA_LINE_STG
/


GRANT DELETE, INSERT, SELECT, UPDATE ON XXDO.XXDO_ONT_RMA_LINE_STG TO SOA_INT
/
