--
-- XXDO_ORDERS_SPLIT  (Table) 
--
CREATE TABLE XXDO.XXDO_ORDERS_SPLIT
(
  RECORD_ID           NUMBER                    NOT NULL,
  CUSTOMER_NUMBER     VARCHAR2(200 BYTE),
  CUSTOMER_TYPE       VARCHAR2(200 BYTE),
  ORDER_SOURCE_ID     NUMBER,
  ORDER_TYPE_ID       NUMBER,
  DEMAND_CLASS        VARCHAR2(200 BYTE),
  CUSTOMER_PO_NUMBER  VARCHAR2(200 BYTE),
  RETAIL_STORE        VARCHAR2(200 BYTE),
  ORG_ID              NUMBER,
  BEGIN_DATE          DATE,
  END_DATE            DATE,
  CREATED_BY          NUMBER,
  CREATION_DATE       DATE,
  LAST_UPDATED_BY     NUMBER,
  LAST_UPDATE_DATE    DATE,
  LAST_UPDATE_LOGIN   NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ORDERS_SPLIT_PK  (Index) 
--
--  Dependencies: 
--   XXDO_ORDERS_SPLIT (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_ORDERS_SPLIT_PK ON XXDO.XXDO_ORDERS_SPLIT
(RECORD_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ORDERS_SPLIT  (Synonym) 
--
--  Dependencies: 
--   XXDO_ORDERS_SPLIT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_ORDERS_SPLIT FOR XXDO.XXDO_ORDERS_SPLIT
/


GRANT SELECT ON XXDO.XXDO_ORDERS_SPLIT TO APPS WITH GRANT OPTION
/

GRANT SELECT ON XXDO.XXDO_ORDERS_SPLIT TO APPSRO
/
