--
-- XXDO_ATP_VALIDATE_CONTROL  (Table) 
--
CREATE TABLE XXDO.XXDO_ATP_VALIDATE_CONTROL
(
  FLAG  VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
