--
-- XXDO_FA_RESERVE_LOCATION_REP_X  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXDO_FA_RESERVE_LOCATION_REP_X
(
  BOOK                         VARCHAR2(50 BYTE),
  PERIOD                       VARCHAR2(30 BYTE),
  ASSET_CATEGORY_TYPE          VARCHAR2(50 BYTE),
  ASSET_TYPE                   VARCHAR2(30 BYTE),
  ASSET_ACCOUNT                VARCHAR2(50 BYTE),
  ASSET_NUMBER                 VARCHAR2(50 BYTE),
  ASSET_DESCRIPTION            VARCHAR2(150 BYTE),
  SUPPLIER                     VARCHAR2(150 BYTE),
  CUSTODIAN                    VARCHAR2(150 BYTE),
  DATE_PLACED_IN_SERVICE       VARCHAR2(30 BYTE),
  DEPRN_METHOD                 VARCHAR2(30 BYTE),
  LIFE_YR_MO                   VARCHAR2(30 BYTE),
  COST                         NUMBER,
  BEGIN_YEAR_DEPR_RESERVE      NUMBER,
  CURRENT_PERIOD_DEPRECIATION  NUMBER,
  YTD_DEPRECIATION             NUMBER,
  ENDING_DEPR_RESERVE          NUMBER,
  NET_BOOK_VALUE               NUMBER,
  DEPRECIATION_ACCOUNT         VARCHAR2(50 BYTE),
  LOCATION_FLEXFIELD           VARCHAR2(200 BYTE),
  ASSET_TAG_NUMBER             VARCHAR2(50 BYTE),
  ASSET_SERIAL_NUMBER          VARCHAR2(50 BYTE),
  PROJECT_NUMBER               VARCHAR2(25 BYTE),
  ASSET_RESERVE_ACCOUNT        VARCHAR2(50 BYTE),
  ASSET_CC                     VARCHAR2(50 BYTE),
  ASSET_ACCT                   VARCHAR2(50 BYTE),
  ASSET_BRAND                  VARCHAR2(50 BYTE),
  IMPAIRMENT_AMOUNT            NUMBER
)
ON COMMIT DELETE ROWS
NOCACHE
/


--
-- XXDO_FA_RESERVE_LOCATION_REP_X  (Synonym) 
--
--  Dependencies: 
--   XXDO_FA_RESERVE_LOCATION_REP_X (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_FA_RESERVE_LOCATION_REP_X FOR XXDO.XXDO_FA_RESERVE_LOCATION_REP_X
/


--
-- XXDO_FA_RESERVE_LOCATION_REP_X  (Synonym) 
--
--  Dependencies: 
--   XXDO_FA_RESERVE_LOCATION_REP_X (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDO_FA_RESERVE_LOCATION_REP_X FOR XXDO.XXDO_FA_RESERVE_LOCATION_REP_X
/
