--
-- XXD_GL_ARCHIVE_REFERENCES  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ARCHIVE_REFERENCES
(
  JE_BATCH_ID                   NUMBER(15)      NOT NULL,
  JE_HEADER_ID                  NUMBER(15)      NOT NULL,
  JE_LINE_NUM                   NUMBER(15)      NOT NULL,
  LAST_UPDATE_DATE              DATE            NOT NULL,
  LAST_UPDATED_BY               NUMBER(15)      NOT NULL,
  CREATION_DATE                 DATE,
  CREATED_BY                    NUMBER(15),
  LAST_UPDATE_LOGIN             NUMBER(15),
  REFERENCE_1                   VARCHAR2(240 BYTE),
  REFERENCE_2                   VARCHAR2(240 BYTE),
  REFERENCE_3                   VARCHAR2(240 BYTE),
  REFERENCE_4                   VARCHAR2(240 BYTE),
  REFERENCE_5                   VARCHAR2(240 BYTE),
  REFERENCE_6                   VARCHAR2(240 BYTE),
  REFERENCE_7                   VARCHAR2(240 BYTE),
  REFERENCE_8                   VARCHAR2(240 BYTE),
  REFERENCE_9                   VARCHAR2(240 BYTE),
  REFERENCE_10                  VARCHAR2(240 BYTE),
  SUBLEDGER_DOC_SEQUENCE_ID     NUMBER,
  SUBLEDGER_DOC_SEQUENCE_VALUE  NUMBER,
  GL_SL_LINK_ID                 NUMBER,
  GL_SL_LINK_TABLE              VARCHAR2(30 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    1
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          80K
            NEXT             40K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
COMPRESS FOR QUERY HIGH
NOCACHE
/


--
-- XXD_GL_ARCHIVE_REFERENCES_N1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_REFERENCES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_REFERENCES_N1 ON XXDO.XXD_GL_ARCHIVE_REFERENCES
(JE_HEADER_ID, JE_LINE_NUM)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_REFERENCES_N2  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_REFERENCES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_REFERENCES_N2 ON XXDO.XXD_GL_ARCHIVE_REFERENCES
(SUBLEDGER_DOC_SEQUENCE_VALUE, SUBLEDGER_DOC_SEQUENCE_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_REFERENCES_N3  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_REFERENCES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_REFERENCES_N3 ON XXDO.XXD_GL_ARCHIVE_REFERENCES
(REFERENCE_6, REFERENCE_2, REFERENCE_3)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_REFERENCES_N4  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_REFERENCES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_REFERENCES_N4 ON XXDO.XXD_GL_ARCHIVE_REFERENCES
(GL_SL_LINK_ID, GL_SL_LINK_TABLE)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_REFERENCES  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_REFERENCES (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_ARCHIVE_REFERENCES FOR XXDO.XXD_GL_ARCHIVE_REFERENCES
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_GL_ARCHIVE_REFERENCES TO APPS WITH GRANT OPTION
/
