--
-- XXD_PO_BUY_SEASON_MTH_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_PO_BUY_SEASON_MTH_STG_T
(
  SEQ_NO             NUMBER,
  PO_NUMBER          VARCHAR2(50 BYTE),
  PO_HEADER_ID       NUMBER,
  BUY_SEASON         VARCHAR2(42 BYTE),
  BUY_MONTH          VARCHAR2(20 BYTE),
  STATUS             VARCHAR2(1 BYTE),
  ERROR_MESSAGE      VARCHAR2(200 BYTE),
  REQUEST_ID         NUMBER,
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
