--
-- XXD_CRM_CUST_DATA_CURRENT_T  (Table) 
--
CREATE TABLE XXDO.XXD_CRM_CUST_DATA_CURRENT_T
(
  ACCOUNT_NUMBER      VARCHAR2(30 BYTE),
  DOC_LANG            VARCHAR2(150 BYTE),
  BRAND               VARCHAR2(150 BYTE),
  BUYING_GROUP        VARCHAR2(150 BYTE),
  COLLECTOR_NAME      VARCHAR2(30 BYTE),
  CREDIT_LIMIT        NUMBER,
  CURRENCY_TYPE       VARCHAR2(15 BYTE),
  CUST_MEMBER_NUM     VARCHAR2(150 BYTE),
  CUST_NAME           VARCHAR2(360 BYTE),
  ORDER_LIMIT         NUMBER,
  PARENT_NUMBER       VARCHAR2(150 BYTE),
  PAYMENT_TERMS       VARCHAR2(15 BYTE),
  PROFILE_CLASS       VARCHAR2(30 BYTE),
  SALES_CHANNEL       VARCHAR2(30 BYTE),
  SALES_REP_NAME      VARCHAR2(360 BYTE),
  SHIP_METHOD         VARCHAR2(80 BYTE),
  ACCOUNT_STATUS      VARCHAR2(1 BYTE),
  SITE_NUMBER         VARCHAR2(30 BYTE),
  SITE_USE_CODE       VARCHAR2(30 BYTE),
  SITE_CITY           VARCHAR2(60 BYTE),
  SITE_COUNTY         VARCHAR2(60 BYTE),
  SITE_COUNTRY        VARCHAR2(360 BYTE),
  SITE_ADDRESS_LINE1  VARCHAR2(240 BYTE),
  SITE_ADDRESS_LINE2  VARCHAR2(240 BYTE),
  SITE_ADDRESS_LINE3  VARCHAR2(240 BYTE),
  SITE_ADDRESS_LINE4  VARCHAR2(240 BYTE),
  OPERATING_UNIT      VARCHAR2(240 BYTE),
  SITE_POSTAL_CODE    VARCHAR2(60 BYTE),
  SITE_PROVINCE       VARCHAR2(60 BYTE),
  SITE_STATE          VARCHAR2(60 BYTE),
  SITE_STATUS         VARCHAR2(1 BYTE),
  SITE_TAX_REF        VARCHAR2(50 BYTE),
  TAX_CLASS_CODE      VARCHAR2(50 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
