--
-- XXD_AP_CB_INV_HOLDS_T  (Table) 
--
CREATE TABLE XXDO.XXD_AP_CB_INV_HOLDS_T
(
  INVOICE_NUM       VARCHAR2(240 BYTE),
  INVOICE_ID        NUMBER,
  COUNTRY           VARCHAR2(50 BYTE),
  VEBDOR_ID         NUMBER,
  VENDOR_SITE_ID    NUMBER,
  VENDOR_NAME       VARCHAR2(240 BYTE),
  INVOICE_DATE      DATE,
  ORG_ID            NUMBER,
  HOLD_APPLIED      VARCHAR2(3 BYTE),
  HOLD_RELEASED     VARCHAR2(3 BYTE),
  CREATED_BY        NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATED_BY   NUMBER,
  LAST_UPDATE_DATE  DATE,
  REQUEST_ID        NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
