--
-- XXDOEC_DCDLOGTRACELEVEL  (Table) 
--
CREATE TABLE XXDO.XXDOEC_DCDLOGTRACELEVEL
(
  ID           NUMBER                           NOT NULL,
  APPLICATION  VARCHAR2(300 BYTE)               NOT NULL,
  MESSAGE      VARCHAR2(500 BYTE),
  TRACELEVEL   NUMBER                           DEFAULT 2,
  ACTIVE       NUMBER                           DEFAULT 1,
  UPDATEDATE   TIMESTAMP(6)                     DEFAULT CURRENT_TIMESTAMP
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- PK_XXDOEC_DCDLOGTRACELEVEL  (Index) 
--
--  Dependencies: 
--   XXDOEC_DCDLOGTRACELEVEL (Table)
--
CREATE UNIQUE INDEX XXDO.PK_XXDOEC_DCDLOGTRACELEVEL ON XXDO.XXDOEC_DCDLOGTRACELEVEL
(ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDOEC_DCDLOGTRACELEVEL ADD (
  CHECK (traceLevel IN (0,1,2,3,4))
  ENABLE VALIDATE
,  CHECK (Active IN (0,1))
  ENABLE VALIDATE
,  CONSTRAINT PK_XXDOEC_DCDLOGTRACELEVEL
  PRIMARY KEY
  (ID)
  USING INDEX XXDO.PK_XXDOEC_DCDLOGTRACELEVEL
  ENABLE VALIDATE)
/


--
-- XXDOEC_DCDLOGTRACELEVEL_IDX1  (Index) 
--
--  Dependencies: 
--   XXDOEC_DCDLOGTRACELEVEL (Table)
--
CREATE INDEX XXDO.XXDOEC_DCDLOGTRACELEVEL_IDX1 ON XXDO.XXDOEC_DCDLOGTRACELEVEL
(APPLICATION, ACTIVE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_DCDLOGTRACELEVEL  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_DCDLOGTRACELEVEL (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOEC_DCDLOGTRACELEVEL FOR XXDO.XXDOEC_DCDLOGTRACELEVEL
/
