--
-- XXD_GL_TAX_DOC_SEQ_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_TAX_DOC_SEQ_T
(
  LEDGER_NAME       VARCHAR2(50 BYTE),
  JOURNAL_NAME      VARCHAR2(200 BYTE),
  JOURNAL_DATE      DATE,
  JOURNAL_CATEGORY  VARCHAR2(100 BYTE),
  JOURNAL_SOURCE    VARCHAR2(100 BYTE),
  JOURNAL_DESC      VARCHAR2(500 BYTE),
  GL_DATE           DATE,
  DOCUMENT_NUMBER   VARCHAR2(20 BYTE),
  GAPLESS_SEQ_NUM   NUMBER,
  ACCOUNT_PERIOD    VARCHAR2(20 BYTE),
  SORT_BY           VARCHAR2(30 BYTE),
  CREATED_BY        NUMBER,
  CREATION_DATE     DATE,
  REQUEST_ID        NUMBER,
  LEDGER_ID         NUMBER,
  SOURCE            VARCHAR2(50 BYTE),
  CATEGORY          VARCHAR2(50 BYTE),
  JE_HEADER_ID      NUMBER,
  JE_LINE_NUM       NUMBER,
  EMAIL_ADDRESS     VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
