--
-- XXD_MSC_ATP_LEVEL_CRITERIA_TBL  (Table) 
--
CREATE TABLE XXDO.XXD_MSC_ATP_LEVEL_CRITERIA_TBL
(
  CRITERIA        VARCHAR2(50 BYTE),
  CONDITION       VARCHAR2(30 BYTE),
  CONDITION_FROM  VARCHAR2(1000 BYTE),
  CONDITION_TO    VARCHAR2(1000 BYTE),
  SESSION_ID      NUMBER
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_MSC_ATP_LEVEL_CRITERIA_TBL  (Synonym) 
--
--  Dependencies: 
--   XXD_MSC_ATP_LEVEL_CRITERIA_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_MSC_ATP_LEVEL_CRITERIA_TBL FOR XXDO.XXD_MSC_ATP_LEVEL_CRITERIA_TBL
/
