--
-- XXD_ONT_EDI_855_CUST_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_EDI_855_CUST_T
(
  ORDER_SOURCE_ID            NUMBER,
  ORIG_SYS_DOCUMENT_REF      VARCHAR2(50 BYTE),
  SOLD_TO_ORG_ID             NUMBER,
  CUSTOMER_PO_NUMBER         VARCHAR2(50 BYTE),
  ORDERED_DATE               DATE,
  ORIG_SYS_LINE_REF          VARCHAR2(50 BYTE),
  SHIP_TO_ORG_ID             NUMBER,
  INVENTORY_ITEM_ID          NUMBER,
  LINE_NUMBER                NUMBER,
  CUSTOMER_ITEM              VARCHAR2(240 BYTE),
  UNIT_SELLING_PRICE         NUMBER,
  REQUEST_DATE               DATE,
  ORDERED_QUANTITY           NUMBER,
  UOM_CODE                   VARCHAR2(25 BYTE),
  UPC_CODE                   VARCHAR2(240 BYTE),
  DELETED_FROM_HEADER_IFACE  VARCHAR2(10 BYTE),
  DELETED_FROM_LINES_IFACE   VARCHAR2(10 BYTE),
  SEND_HARD_REJECT           VARCHAR2(10 BYTE),
  EDI_855_PROCESSED          VARCHAR2(10 BYTE),
  ORG_ID                     NUMBER,
  REQUEST_ID                 NUMBER,
  CREATION_DATE              DATE,
  CREATED_BY                 NUMBER,
  LAST_UPDATE_DATE           DATE,
  LAST_UPDATED_BY            NUMBER,
  LAST_UPDATE_LOGIN          NUMBER,
  ATTRIBUTE1                 VARCHAR2(240 BYTE),
  ATTRIBUTE2                 VARCHAR2(240 BYTE),
  ATTRIBUTE3                 VARCHAR2(240 BYTE),
  ATTRIBUTE4                 VARCHAR2(240 BYTE),
  ATTRIBUTE5                 VARCHAR2(240 BYTE),
  ATTRIBUTE6                 VARCHAR2(240 BYTE),
  ATTRIBUTE7                 VARCHAR2(240 BYTE),
  ATTRIBUTE8                 VARCHAR2(240 BYTE),
  ATTRIBUTE9                 VARCHAR2(240 BYTE),
  ATTRIBUTE10                VARCHAR2(240 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_EDI_855_CUST_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_EDI_855_CUST_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_ONT_EDI_855_CUST_T FOR XXDO.XXD_ONT_EDI_855_CUST_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_ONT_EDI_855_CUST_T TO SOA_INT
/
