--
-- XXD_AR_LCX_INVOICES_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_AR_LCX_INVOICES_STG_T
(
  RECORD_ID              NUMBER                 NOT NULL,
  FILE_NAME              VARCHAR2(500 BYTE),
  FILE_PROCESSED_DATE    VARCHAR2(10 BYTE),
  STATUS                 VARCHAR2(2 BYTE),
  ERROR_MSG              VARCHAR2(4000 BYTE),
  REQUEST_ID             NUMBER,
  OPERATING_UNIT         VARCHAR2(240 BYTE),
  TRANSACTION_TYPE       VARCHAR2(20 BYTE),
  REASON_CODE            VARCHAR2(240 BYTE),
  ACCOUNT_NUMBER         VARCHAR2(30 BYTE),
  CUSTOMER               VARCHAR2(360 BYTE),
  BRAND                  VARCHAR2(100 BYTE),
  TRANSACTION_DATE       DATE,
  AMOUNT                 NUMBER,
  TAX_EXEMPT             VARCHAR2(10 BYTE),
  PRINT_OPTION           VARCHAR2(100 BYTE),
  SALES_REPRESENTATIVE   VARCHAR2(240 BYTE),
  CUST_PO_NUMBER         VARCHAR2(100 BYTE),
  GL_CODE                VARCHAR2(240 BYTE),
  COMMENTS               VARCHAR2(4000 BYTE),
  GROUPING               VARCHAR2(240 BYTE),
  ORG_ID                 NUMBER,
  BATCH_SOURCE_NAME      VARCHAR2(50 BYTE),
  BATCH_SOURCE_ID        NUMBER,
  CUST_TRX_TYPE_NAME     VARCHAR2(20 BYTE),
  CUST_TRX_TYPE_ID       NUMBER,
  CUST_ACCOUNT_ID        NUMBER,
  PARTY_ID               NUMBER,
  BILL_TO_LOCATION_ID    NUMBER,
  TERM_NAME              VARCHAR2(15 BYTE),
  TERM_ID                NUMBER,
  LINE_DESCRIPTION       VARCHAR2(240 BYTE),
  TAX_FLAG               VARCHAR2(10 BYTE),
  SALESREP_ID            NUMBER,
  DIST_CCID              NUMBER,
  REASON_SHORT_CODE      VARCHAR2(100 BYTE),
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  CURRENCY_CODE          VARCHAR2(10 CHAR),
  LINE_INTERFACED        VARCHAR2(10 BYTE),
  DIST_INTERFACED        VARCHAR2(10 BYTE),
  TRX_CREATED            VARCHAR2(10 BYTE),
  TRX_LINE_CREATED       VARCHAR2(10 BYTE),
  TRX_NUMBER             VARCHAR2(20 BYTE),
  CUSTOMER_TRX_ID        NUMBER,
  CUSTOMER_TRX_LINE_ID   NUMBER,
  TRX_LINE_DIST_CREATED  VARCHAR2(10 BYTE),
  CUSTOMER_TRX_DIST_ID   NUMBER,
  TRX_NEW_DATE           DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


ALTER TABLE XXDO.XXD_AR_LCX_INVOICES_STG_T ADD (
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX
    TABLESPACE CUSTOM_TX_TS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE)
/


--  There is no statement for index XXDO.SYS_C006125486.
--  The object is created when the parent object is created.

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_AR_LCX_INVOICES_STG_T TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_AR_LCX_INVOICES_STG_T TO SOA_INT
/
