--
-- XXD_ONT_PROMOTIONS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_PROMOTIONS_T
(
  PROMOTION_ID           NUMBER,
  PROMOTION_CODE         VARCHAR2(50 BYTE),
  PROMOTION_NAME         VARCHAR2(100 BYTE),
  OPERATING_UNIT         VARCHAR2(240 BYTE),
  ORG_ID                 NUMBER,
  BRAND                  VARCHAR2(15 BYTE),
  CURRENCY               VARCHAR2(15 BYTE),
  PROMOTION_CODE_STATUS  VARCHAR2(1 BYTE),
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATE_LOGIN      NUMBER,
  CUSTOMER_NUMBER        VARCHAR2(30 BYTE),
  CUSTOMER_NAME          VARCHAR2(360 BYTE),
  CUST_ACCOUNT_ID        NUMBER,
  DISTRIBUTION_CHANNEL   VARCHAR2(150 BYTE),
  SHIP_METHOD            VARCHAR2(30 BYTE),
  SHIPPING_METHOD_CODE   VARCHAR2(30 BYTE),
  FREIGHT_TERM           VARCHAR2(100 BYTE),
  FREIGHT_TERMS_CODE     VARCHAR2(30 BYTE),
  PAYMENT_TERM           VARCHAR2(100 BYTE),
  PAYMENT_TERM_ID        NUMBER,
  HEADER_DISCOUNT        NUMBER,
  LINE_DISCOUNT          NUMBER,
  ORDERED_DATE_FROM      DATE,
  ORDERED_DATE_TO        DATE,
  REQUEST_DATE_FROM      DATE,
  REQUEST_DATE_TO        DATE,
  DEPARTMENT             VARCHAR2(40 BYTE),
  DIVISION               VARCHAR2(40 BYTE),
  CLASS                  VARCHAR2(40 BYTE),
  SUB_CLASS              VARCHAR2(40 BYTE),
  STYLE_NUMBER           VARCHAR2(40 BYTE),
  COLOR_CODE             VARCHAR2(40 BYTE),
  NUMBER_OF_STYLES       NUMBER,
  NUMBER_OF_COLORS       NUMBER,
  COUNTRY_CODE           VARCHAR2(10 BYTE),
  STATE                  VARCHAR2(10 BYTE),
  PROMOTION_LEVEL        VARCHAR2(10 BYTE),
  INACTIVATION_DATE      DATE,
  INACTIVATED_BY         NUMBER,
  INACTIVATION_REASON    VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


ALTER TABLE XXDO.XXD_ONT_PROMOTIONS_T ADD (
  PRIMARY KEY
  (PROMOTION_ID)
  USING INDEX
    TABLESPACE CUSTOM_TX_TS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE)
/


--  There is no statement for index XXDO.SYS_C002212900.
--  The object is created when the parent object is created.

--
-- XXD_ONT_PROMOTIONS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_PROMOTIONS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_PROMOTIONS_T FOR XXDO.XXD_ONT_PROMOTIONS_T
/
