--
-- XXDO_ONT_HOLD_CANCEL_ORDER  (Table) 
--
CREATE TABLE XXDO.XXDO_ONT_HOLD_CANCEL_ORDER
(
  WH_ID              VARCHAR2(10 BYTE)          NOT NULL,
  ORDER_NUMBER       VARCHAR2(30 BYTE)          NOT NULL,
  ACTION             VARCHAR2(10 BYTE)          NOT NULL,
  PRIORITY           NUMBER,
  CREATED_BY         NUMBER                     DEFAULT -1                    NOT NULL,
  CREATION_DATE      DATE                       DEFAULT SYSDATE               NOT NULL,
  LAST_UPDATED_BY    NUMBER                     DEFAULT -1                    NOT NULL,
  LAST_UPDATE_DATE   DATE                       DEFAULT SYSDATE               NOT NULL,
  LAST_UPDATE_LOGIN  NUMBER                     DEFAULT -1                    NOT NULL,
  PROCESS_STATUS     VARCHAR2(20 BYTE)          NOT NULL,
  RECORD_TYPE        VARCHAR2(20 BYTE)          DEFAULT 'NEW'                 NOT NULL,
  SOURCE             VARCHAR2(20 BYTE)          DEFAULT 'EBS',
  DESTINATION        VARCHAR2(20 BYTE)          DEFAULT 'WMS',
  SEQ_ID             NUMBER,
  ERROR_MESSAGE      VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ONT_HOLD_CANCEL_ORDER  (Synonym) 
--
--  Dependencies: 
--   XXDO_ONT_HOLD_CANCEL_ORDER (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_ONT_HOLD_CANCEL_ORDER FOR XXDO.XXDO_ONT_HOLD_CANCEL_ORDER
/


--
-- XXDO_ONT_HOLD_CANCEL_ORDER  (Synonym) 
--
--  Dependencies: 
--   XXDO_ONT_HOLD_CANCEL_ORDER (Table)
--
CREATE OR REPLACE SYNONYM SOA_RO.XXDO_ONT_HOLD_CANCEL_ORDER FOR XXDO.XXDO_ONT_HOLD_CANCEL_ORDER
/


GRANT INSERT, SELECT, UPDATE ON XXDO.XXDO_ONT_HOLD_CANCEL_ORDER TO SOA_INT
/

GRANT SELECT ON XXDO.XXDO_ONT_HOLD_CANCEL_ORDER TO SOA_RO
/
