--
-- XXD_NEGATIVE_LEVEL_TBL  (Table) 
--
CREATE TABLE XXDO.XXD_NEGATIVE_LEVEL_TBL
(
  SESSION_ID         NUMBER,
  ORGANIZATION_ID    NUMBER                     NOT NULL,
  BRAND              VARCHAR2(40 BYTE),
  STYLE              VARCHAR2(150 BYTE),
  COLOR              VARCHAR2(150 BYTE),
  ITEM_SIZE          VARCHAR2(240 BYTE),
  ITEM_NUMBER        VARCHAR2(40 BYTE),
  INVENTORY_ITEM_ID  NUMBER,
  DEMAND_CLASS       VARCHAR2(30 BYTE),
  NEGATIVITY         NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_NEGATIVE_LEVEL_TBL  (Synonym) 
--
--  Dependencies: 
--   XXD_NEGATIVE_LEVEL_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_NEGATIVE_LEVEL_TBL FOR XXDO.XXD_NEGATIVE_LEVEL_TBL
/
