--
-- XXDO_ATP_VALIDATE  (Table) 
--
CREATE TABLE XXDO.XXDO_ATP_VALIDATE
(
  REFRESH_NUMBER       NUMBER,
  REFRESH_TIME         TIMESTAMP(6) WITH TIME ZONE,
  ASCP_REFRESH_NUMBER  NUMBER,
  ASCP_REFRESH_TIME    TIMESTAMP(6) WITH TIME ZONE,
  DEMAND_CLASS         VARCHAR2(30 BYTE),
  PRIORITY             NUMBER,
  ORGANIZATION_ID      NUMBER,
  INVENTORY_ITEM_ID    NUMBER,
  DTE                  DATE,
  ATP                  NUMBER,
  ATP_W_S              NUMBER,
  STD_ATP              NUMBER,
  PROCESSING_SESSION   NUMBER,
  PROCESSED_DATE       TIMESTAMP(6) WITH TIME ZONE,
  ATP_WB_RO            NUMBER,
  ATP_WB_RC            NUMBER,
  ATP_WB_RE            NUMBER,
  ATP_WB_RP            NUMBER,
  ATP_WB_RM            NUMBER,
  ATP_WB_EC            NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
PARALLEL ( DEGREE 3 INSTANCES 2 )
/


--
-- XXDO_ATP_VALIDATE_N1  (Index) 
--
--  Dependencies: 
--   XXDO_ATP_VALIDATE (Table)
--
CREATE INDEX XXDO.XXDO_ATP_VALIDATE_N1 ON XXDO.XXDO_ATP_VALIDATE
(PROCESSING_SESSION)
NOLOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 3 INSTANCES 2 )
/

--
-- XXDO_ATP_VALIDATE_N2  (Index) 
--
--  Dependencies: 
--   XXDO_ATP_VALIDATE (Table)
--
CREATE INDEX XXDO.XXDO_ATP_VALIDATE_N2 ON XXDO.XXDO_ATP_VALIDATE
(PROCESSING_SESSION, SYS_EXTRACT_UTC("PROCESSED_DATE"))
NOLOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
PARALLEL ( DEGREE 3 INSTANCES 2 )
/
