--
-- XXDO_INV_HJ_ONHAND_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_HJ_ONHAND_STG
(
  SOURCE_ORG_ID         NUMBER,
  SOURCE_SUBINVENTORY   VARCHAR2(30 BYTE),
  SOURCE_LOCATOR_ID     NUMBER,
  TARGET_ORG_ID         NUMBER,
  TARGET_SUBINVENTORY   VARCHAR2(30 BYTE),
  TARGET_LOCATOR_ID     NUMBER,
  INVENTORY_ITEM_ID     NUMBER,
  QTY                   NUMBER,
  AGING_DATE            DATE,
  UOM                   VARCHAR2(30 BYTE),
  PROCESS_STATUS        VARCHAR2(30 BYTE),
  ERROR_MESSAGE         VARCHAR2(2000 BYTE),
  SOURCE_ORG            VARCHAR2(30 BYTE),
  TARGET_ORG            VARCHAR2(30 BYTE),
  SOURCE_LOCATOR        VARCHAR2(150 BYTE),
  TARGET_LOCATOR        VARCHAR2(150 BYTE),
  ITEM_NUMBER           VARCHAR2(60 BYTE),
  LPN_CONTROLLED_FLAG   NUMBER,
  LPN_ID                NUMBER,
  LICENSE_PLATE_NUMBER  VARCHAR2(60 BYTE),
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  REQUEST_ID            NUMBER,
  ATTRIBUTE1            VARCHAR2(150 BYTE),
  ATTRIBUTE2            VARCHAR2(150 BYTE),
  ATTRIBUTE3            VARCHAR2(150 BYTE),
  ATTRIBUTE4            VARCHAR2(150 BYTE),
  ATTRIBUTE5            VARCHAR2(150 BYTE),
  ATTRIBUTE6            VARCHAR2(150 BYTE),
  ATTRIBUTE7            VARCHAR2(150 BYTE),
  ATTRIBUTE8            VARCHAR2(150 BYTE),
  ATTRIBUTE9            VARCHAR2(150 BYTE),
  ATTRIBUTE10           VARCHAR2(150 BYTE),
  ATTRIBUTE11           VARCHAR2(150 BYTE),
  ATTRIBUTE12           VARCHAR2(150 BYTE),
  ATTRIBUTE13           VARCHAR2(150 BYTE),
  ATTRIBUTE14           VARCHAR2(150 BYTE),
  ATTRIBUTE15           VARCHAR2(150 BYTE),
  ERRORED_QTY           NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_HJ_ONHAND_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_HJ_ONHAND_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INV_HJ_ONHAND_STG FOR XXDO.XXDO_INV_HJ_ONHAND_STG
/
