--
-- XXD_CIT_CTL_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_CIT_CTL_STG_T
(
  BATCH_ID           NUMBER,
  FILE_NAME          VARCHAR2(50 BYTE),
  FTP_STATUS         VARCHAR2(30 BYTE),
  CUST_COUNT         NUMBER,
  INVOICE_COUNT      NUMBER,
  TOT_INV_AMT        NUMBER,
  BATCH_DATE         DATE,
  NAME               VARCHAR2(10 BYTE),
  CREATED_BY         VARCHAR2(50 BYTE),
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    VARCHAR2(50 BYTE),
  LAST_UPDATED_DATE  DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_CIT_CTL_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CIT_CTL_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_CIT_CTL_STG_T FOR XXDO.XXD_CIT_CTL_STG_T
/


--
-- XXD_CIT_CTL_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CIT_CTL_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXD_CIT_CTL_STG_T FOR XXDO.XXD_CIT_CTL_STG_T
/
