--
-- XXDOPO_ACCRUAL_LINES  (Table) 
--
CREATE TABLE XXDO.XXDOPO_ACCRUAL_LINES
(
  RCV_TRANSACTION_ID  NUMBER                    NOT NULL,
  ORGANIZATION_ID     NUMBER                    NOT NULL,
  INVENTORY_ITEM_ID   NUMBER                    NOT NULL,
  PO_UNIT_PRICE       NUMBER,
  ACCRUAL_TYPE        VARCHAR2(10 BYTE)         NOT NULL,
  QUANTITY_TOTAL      NUMBER                    NOT NULL,
  QUANTITY_REMAINING  NUMBER                    NOT NULL,
  AMOUNT_TOTAL        NUMBER                    NOT NULL,
  AMOUNT_REMAINING    NUMBER                    NOT NULL,
  CURRENCY_CODE       VARCHAR2(15 BYTE)         NOT NULL,
  LEDGER_ID           NUMBER                    NOT NULL,
  OH_CCID             NUMBER                    NOT NULL,
  IT_CCID             NUMBER                    NOT NULL,
  CREATION_DATE       DATE                      DEFAULT sysdate               NOT NULL,
  CREATED_BY          NUMBER                    NOT NULL,
  LAST_UPDATE_DATE    DATE                      DEFAULT sysdate               NOT NULL,
  LAST_UPDATED_BY     NUMBER                    NOT NULL,
  ARCHIVE_FLAG        VARCHAR2(1 BYTE)          DEFAULT 'N'                   NOT NULL
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOPO_ACCRUAL_LINES_PK  (Index) 
--
--  Dependencies: 
--   XXDOPO_ACCRUAL_LINES (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOPO_ACCRUAL_LINES_PK ON XXDO.XXDOPO_ACCRUAL_LINES
(RCV_TRANSACTION_ID, ACCRUAL_TYPE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDOPO_ACCRUAL_LINES ADD (
  CONSTRAINT XXDOPO_ACCRUAL_LINES_PK
  PRIMARY KEY
  (RCV_TRANSACTION_ID, ACCRUAL_TYPE)
  USING INDEX XXDO.XXDOPO_ACCRUAL_LINES_PK
  ENABLE VALIDATE)
/


--
-- XXDOPO_ACCRUAL_LINES_N1  (Index) 
--
--  Dependencies: 
--   XXDOPO_ACCRUAL_LINES (Table)
--
CREATE INDEX XXDO.XXDOPO_ACCRUAL_LINES_N1 ON XXDO.XXDOPO_ACCRUAL_LINES
(ORGANIZATION_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOPO_ACCRUAL_LINES_N2  (Index) 
--
--  Dependencies: 
--   XXDOPO_ACCRUAL_LINES (Table)
--
CREATE INDEX XXDO.XXDOPO_ACCRUAL_LINES_N2 ON XXDO.XXDOPO_ACCRUAL_LINES
(OH_CCID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOPO_ACCRUAL_LINES_N3  (Index) 
--
--  Dependencies: 
--   XXDOPO_ACCRUAL_LINES (Table)
--
CREATE INDEX XXDO.XXDOPO_ACCRUAL_LINES_N3 ON XXDO.XXDOPO_ACCRUAL_LINES
(IT_CCID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOPO_ACCRUAL_LINES  (Synonym) 
--
--  Dependencies: 
--   XXDOPO_ACCRUAL_LINES (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOPO_ACCRUAL_LINES FOR XXDO.XXDOPO_ACCRUAL_LINES
/
