--
-- XXDOOE_LINES_STG  (Table) 
--
CREATE TABLE XXDO.XXDOOE_LINES_STG
(
  SOURCE_CODE             VARCHAR2(10 BYTE),
  HEADER_ID               NUMBER,
  LINE_ID                 NUMBER,
  INVENTORY_ITEM_ID       NUMBER,
  SHIP_FROM_ORG_ID        NUMBER,
  ORDERED_ITEM            VARCHAR2(2000 BYTE),
  LINE_NUMBER             NUMBER,
  ORDERED_QUANTITY        NUMBER,
  ORG_ID                  NUMBER,
  REQUEST_DATE            DATE,
  PROMISE_DATE            DATE,
  SCHEDULE_SHIP_DATE      DATE,
  ORDER_QUANTITY_UOM      VARCHAR2(3 BYTE),
  SHIPMENT_PRIORITY_CODE  VARCHAR2(30 BYTE),
  FLOW_STATUS_CODE        VARCHAR2(30 BYTE),
  CREATION_DATE           DATE,
  CREATED_BY              NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATED_BY         NUMBER,
  REQUEST_ID              NUMBER,
  ATTRIBUTE1              VARCHAR2(240 BYTE),
  ATTRIBUTE2              VARCHAR2(240 BYTE),
  ATTRIBUTE3              VARCHAR2(240 BYTE),
  ATTRIBUTE4              VARCHAR2(240 BYTE),
  ATTRIBUTE5              VARCHAR2(240 BYTE),
  STATUS_CODE             VARCHAR2(10 BYTE),
  STATUS_MSG              VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOOE_LINES_STG_N1  (Index) 
--
--  Dependencies: 
--   XXDOOE_LINES_STG (Table)
--
CREATE INDEX XXDO.XXDOOE_LINES_STG_N1 ON XXDO.XXDOOE_LINES_STG
(TRUNC("REQUEST_DATE"), FLOW_STATUS_CODE, SHIP_FROM_ORG_ID, INVENTORY_ITEM_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
