--
-- XXDO_PLM_SIZE_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_PLM_SIZE_STG
(
  PARENT_RECORD_ID      NUMBER                  NOT NULL,
  BATCH_ID              NUMBER(10),
  SEQUENCE_NUM          NUMBER,
  SIZE_VAL              VARCHAR2(100 BYTE),
  SIZE_DESCRIPTION      VARCHAR2(100 BYTE),
  ITEM_TYPE             VARCHAR2(100 BYTE),
  VERRCODE              VARCHAR2(3000 BYTE),
  VERRMSG               VARCHAR2(1000 BYTE),
  CREATION_DATE         DATE                    DEFAULT SYSDATE,
  REQUEST_ID            NUMBER,
  NRF_SIZE_CODE         VARCHAR2(2000 BYTE),
  NRF_SIZE_DESCRIPTION  VARCHAR2(2000 BYTE),
  ATTRIBUTE1            VARCHAR2(2000 BYTE),
  ATTRIBUTE2            VARCHAR2(2000 BYTE),
  ATTRIBUTE3            VARCHAR2(2000 BYTE),
  ATTRIBUTE4            VARCHAR2(2000 BYTE),
  ATTRIBUTE5            VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- U1_PLM_SIZE_STG_IDX  (Index) 
--
--  Dependencies: 
--   XXDO_PLM_SIZE_STG (Table)
--
CREATE UNIQUE INDEX APPS.U1_PLM_SIZE_STG_IDX ON XXDO.XXDO_PLM_SIZE_STG
(PARENT_RECORD_ID, SIZE_VAL, ITEM_TYPE)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDO_PLM_SIZE_STG ADD (
  FOREIGN KEY (PARENT_RECORD_ID) 
  REFERENCES XXDO.XXDO_PLM_STAGING (RECORD_ID)
  ENABLE VALIDATE)
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_SIZE_STG TO APPS
/

GRANT SELECT ON XXDO.XXDO_PLM_SIZE_STG TO APPSRO
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_SIZE_STG TO SOA_INT
/
