--
-- XXD_AR_TRX_LINE_STG  (Table) 
--
CREATE TABLE XXDO.XXD_AR_TRX_LINE_STG
(
  CONCURRENT_REQUEST_ID   NUMBER,
  CUSTOMER_TRX_ID         NUMBER,
  CUSTOMER_TRX_LINE_ID    NUMBER,
  L_COMPANY_SEGMENT       VARCHAR2(10 BYTE),
  L_DESCRIPTION_GOODS     VARCHAR2(240 BYTE),
  L_UNIT_OF_MEASURE       VARCHAR2(25 BYTE),
  L_QTY                   NUMBER,
  L_UNIT_PRICE            NUMBER,
  L_VAT_AMOUNT            NUMBER,
  L_VAT_RATE              NUMBER,
  VAT_NET_AMOUNT          NUMBER,
  VAT_RATE                NUMBER,
  VAT_AMOUNT              NUMBER,
  L_TAX_EXEMPTION_CODE    VARCHAR2(30 BYTE),
  L_NET_AMOUNT            NUMBER,
  L_DISCOUNT_AMOUNT       NUMBER,
  L_DISCOUNT_DESCRIPTION  VARCHAR2(150 BYTE),
  L_CHARGE_AMOUNT         NUMBER,
  L_CHARGE_DESCRIPTION    VARCHAR2(150 BYTE),
  TAX_CODE                VARCHAR2(150 BYTE),
  TAX_EXEMPTION_TEXT      VARCHAR2(150 BYTE),
  TAX_CHG_CODE            VARCHAR2(150 BYTE),
  L_DELIVERY_DATE         DATE,
  L_ITEM_STYLE            VARCHAR2(150 BYTE),
  L_SIZE_QTY              VARCHAR2(150 BYTE),
  LINE_PLACEHOLDER1       VARCHAR2(250 BYTE),
  LINE_PLACEHOLDER2       VARCHAR2(250 BYTE),
  LINE_PLACEHOLDER3       VARCHAR2(250 BYTE),
  ITEM_CODE               VARCHAR2(60 BYTE),
  COUNTRY_OF_ORIGIN       VARCHAR2(60 BYTE),
  CREATED_BY              NUMBER,
  CREATION_DATE           DATE,
  LAST_UPDATED_BY         NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATE_LOGIN       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_AR_TRX_LINE_STG  (Synonym) 
--
--  Dependencies: 
--   XXD_AR_TRX_LINE_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_AR_TRX_LINE_STG FOR XXDO.XXD_AR_TRX_LINE_STG
/
