--
-- XXDOGL006_INT  (Table) 
--
CREATE TABLE XXDO.XXDOGL006_INT
(
  CODE_COMBINATION_ID  NUMBER(15),
  PRIMARY_ACCOUNT      VARCHAR2(103 BYTE),
  ATTRIBUTE1           VARCHAR2(150 BYTE),
  ATTRIBUTE2           VARCHAR2(150 BYTE),
  ATTRIBUTE3           VARCHAR2(150 BYTE),
  ATTRIBUTE4           VARCHAR2(150 BYTE),
  ATTRIBUTE5           VARCHAR2(150 BYTE),
  ATTRIBUTE6           VARCHAR2(150 BYTE),
  ATTRIBUTE7           VARCHAR2(150 BYTE),
  DESCRIPTION1         VARCHAR2(240 BYTE),
  DESCRIPTION2         VARCHAR2(240 BYTE),
  DESCRIPTION3         VARCHAR2(240 BYTE),
  DESCRIPTION4         VARCHAR2(240 BYTE),
  SET_OF_BOOKS_ID      VARCHAR2(240 BYTE),
  STATUS_FLAG          VARCHAR2(10 BYTE)        DEFAULT 'N',
  PROCESSED_FLAG       VARCHAR2(10 BYTE)        DEFAULT 'N',
  TRANSMISSION_DATE    TIMESTAMP(6)             DEFAULT SYSDATE,
  ERRORCODE            VARCHAR2(4000 BYTE),
  XDATA                CLOB,
  RETVAL               CLOB,
  SEQ_NUMBER           NUMBER,
  CREATION_DATE        DATE,
  LAST_UPDATE_DATE     DATE,
  ATTRIBUTE8           VARCHAR2(150 BYTE),
  ATTRIBUTE9           VARCHAR2(150 BYTE),
  ATTRIBUTE10          VARCHAR2(150 BYTE),
  ATTRIBUTE11          VARCHAR2(150 BYTE),
  ATTRIBUTE12          VARCHAR2(150 BYTE),
  ATTRIBUTE13          VARCHAR2(150 BYTE),
  ATTRIBUTE14          VARCHAR2(150 BYTE),
  ATTRIBUTE15          VARCHAR2(150 BYTE),
  DESCRIPTION5         VARCHAR2(240 BYTE),
  DESCRIPTION6         VARCHAR2(240 BYTE),
  DESCRIPTION7         VARCHAR2(240 BYTE),
  DESCRIPTION8         VARCHAR2(240 BYTE),
  DESCRIPTION9         VARCHAR2(240 BYTE),
  DESCRIPTION10        VARCHAR2(240 BYTE),
  DESCRIPTION11        VARCHAR2(240 BYTE),
  DESCRIPTION12        VARCHAR2(240 BYTE),
  DESCRIPTION13        VARCHAR2(240 BYTE),
  DESCRIPTION14        VARCHAR2(240 BYTE),
  DESCRIPTION15        VARCHAR2(240 BYTE)
)
LOB (RETVAL) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
LOB (XDATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOGL006_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOGL006_INT (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOGL006_INT FOR XXDO.XXDOGL006_INT
/


--
-- XXDOGL006_INT  (Synonym) 
--
--  Dependencies: 
--   XXDOGL006_INT (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOGL006_INT FOR XXDO.XXDOGL006_INT
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOGL006_INT TO APPS WITH GRANT OPTION
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOGL006_INT TO APPSRO WITH GRANT OPTION
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDOGL006_INT TO SOA_INT
/
