--
-- XXDO_QR_INQUIRY_GTMP  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXDO_QR_INQUIRY_GTMP
(
  QR_IN_TYPE          VARCHAR2(500 BYTE),
  QR_IN_VALUE         VARCHAR2(500 BYTE),
  RESULT_CODE         VARCHAR2(500 BYTE),
  CODE_TYPE           VARCHAR2(500 BYTE),
  STATUS_CODE         VARCHAR2(500 BYTE),
  PACKAGE_CODE_VALUE  VARCHAR2(500 BYTE),
  PRODUCT_CODE_VALUE  VARCHAR2(500 BYTE),
  UPC                 VARCHAR2(500 BYTE),
  QUALITY_CODE        VARCHAR2(500 BYTE),
  CONTAINER_QR_CODE   VARCHAR2(500 BYTE),
  CONTAINER_UCC       VARCHAR2(500 BYTE),
  CUSTOMER_CODE       VARCHAR2(500 BYTE),
  LOCATION_NAME       VARCHAR2(500 BYTE),
  ADDRESS1            VARCHAR2(2000 BYTE),
  ADDRESS2            VARCHAR2(2000 BYTE),
  CITY                VARCHAR2(500 BYTE),
  STATE_CODE          VARCHAR2(500 BYTE),
  PROVINCE            VARCHAR2(500 BYTE),
  POSTAL_CODE         VARCHAR2(500 BYTE),
  COUNTRY_CODE        VARCHAR2(500 BYTE)
)
ON COMMIT DELETE ROWS
NOCACHE
/
