--
-- XXD_PO_TRANSIT_TIMES_UPL_T  (Table) 
--
CREATE TABLE XXDO.XXD_PO_TRANSIT_TIMES_UPL_T
(
  LOOKUP_CODE                NUMBER,
  VENDOR_NAME                VARCHAR2(240 BYTE),
  VENDOR_SITE_CODE           VARCHAR2(150 BYTE),
  VENDOR_ID                  NUMBER,
  ULTIMATE_DEST_CODE         VARCHAR2(150 BYTE),
  ULTIMATE_DEST_NAME         VARCHAR2(150 BYTE),
  TRANSIT_DAYS_OCEAN         NUMBER,
  OLD_TRANSIT_DAYS_OCEAN     NUMBER,
  TRANSIT_DAYS_AIR           NUMBER,
  OLD_TRANSIT_DAYS_AIR       NUMBER,
  TRANSIT_DAYS_TRUCK         NUMBER,
  OLD_TRANSIT_DAYS_TRUCK     NUMBER,
  PREFERRED_SHIP_METHOD      VARCHAR2(150 BYTE),
  OLD_PREFERRED_SHIP_METHOD  VARCHAR2(150 BYTE),
  ENABLED_FLAG               VARCHAR2(1 BYTE),
  OLD_ENABLED_FLAG           VARCHAR2(1 BYTE),
  ATTRIBUTE1                 VARCHAR2(150 BYTE),
  ATTRIBUTE2                 VARCHAR2(150 BYTE),
  ATTRIBUTE3                 VARCHAR2(150 BYTE),
  ATTRIBUTE4                 VARCHAR2(150 BYTE),
  ATTRIBUTE5                 VARCHAR2(150 BYTE),
  CREATION_DATE              DATE,
  CREATED_BY                 NUMBER(15),
  LAST_UPDATE_DATE           DATE,
  LAST_UPDATED_BY            NUMBER(15),
  LAST_UPDATE_LOGIN          NUMBER(15),
  BATCH_ID                   NUMBER,
  STATUS                     VARCHAR2(1 BYTE),
  MESSAGE                    VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_PO_TRANSIT_TIMES_UPL_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PO_TRANSIT_TIMES_UPL_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PO_TRANSIT_TIMES_UPL_T FOR XXDO.XXD_PO_TRANSIT_TIMES_UPL_T
/
