--
-- XXD_GL_COA_MAPPING_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_COA_MAPPING_T
(
  RECORD_ID            NUMBER                   NOT NULL,
  OLD_COMPANY          VARCHAR2(15 BYTE)        NOT NULL,
  OLD_COST_CENTER      VARCHAR2(15 BYTE)        NOT NULL,
  OLD_NATURAL_ACCOUNT  VARCHAR2(15 BYTE)        NOT NULL,
  OLD_PRODUCT          VARCHAR2(15 BYTE)        NOT NULL,
  NEW_COMPANY          VARCHAR2(15 BYTE)        NOT NULL,
  NEW_BRAND            VARCHAR2(15 BYTE)        NOT NULL,
  NEW_GEO              VARCHAR2(15 BYTE)        NOT NULL,
  NEW_CHANNEL          VARCHAR2(15 BYTE)        NOT NULL,
  NEW_COST_CENTER      VARCHAR2(15 BYTE)        NOT NULL,
  NEW_NATURAL_ACCOUNT  VARCHAR2(15 BYTE)        NOT NULL,
  NEW_INTERCOMPANY     VARCHAR2(15 BYTE)        NOT NULL,
  NEW_FUTURE_USE       VARCHAR2(15 BYTE)        NOT NULL,
  ENABLED_FLAG         VARCHAR2(1 BYTE)         NOT NULL,
  LAST_UPDATE_DATE     DATE                     NOT NULL,
  LAST_UPDATED_BY      NUMBER                   NOT NULL,
  CREATION_DATE        DATE                     NOT NULL,
  CREATED_BY           NUMBER                   NOT NULL,
  LAST_UPDATE_LOGIN    NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_COA_MAPPING_N1  (Index) 
--
--  Dependencies: 
--   XXD_GL_COA_MAPPING_T (Table)
--
CREATE INDEX XXDO.XXD_GL_COA_MAPPING_N1 ON XXDO.XXD_GL_COA_MAPPING_T
(RECORD_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_COA_MAPPING_T  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_COA_MAPPING_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_COA_MAPPING_T FOR XXDO.XXD_GL_COA_MAPPING_T
/


GRANT SELECT ON XXDO.XXD_GL_COA_MAPPING_T TO APPSRO WITH GRANT OPTION
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_COA_MAPPING_T TO XXD_CONV
/
