--
-- XXD_GL_JE_RET_IC_MARKUP_STG_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_T
(
  STORE_NUMBER             NUMBER,
  STORE_NAME               VARCHAR2(240 BYTE),
  STORE_TYPE               VARCHAR2(1 BYTE),
  STORE_CURRENCY           VARCHAR2(15 BYTE),
  ITEM_ID                  NUMBER,
  ITEM_NUMBER              VARCHAR2(40 BYTE),
  BRAND                    VARCHAR2(40 BYTE),
  TRANSACTION_DATE         DATE,
  TRANSACTION_DATE_TS      DATE,
  SALES_TOTAL_UNITS        NUMBER,
  SALES_TOTAL_COST         NUMBER,
  SALES_TOTAL_RETAIL       NUMBER,
  RETURN_TOTAL_UNITS       NUMBER,
  RETURN_TOTAL_COST        NUMBER,
  RETURN_TOTAL_RETAIL      NUMBER,
  SALES_AVG_COST           NUMBER,
  SALES_MRGN_CST_LOCAL     NUMBER,
  SALES_MRGN_CST_USD       NUMBER,
  SALES_MRGN_VALUE_LOCAL   NUMBER,
  SALES_MRGN_VALUE_USD     NUMBER,
  RETURN_MRGN_VALUE_LOCAL  NUMBER,
  RETURN_MRGN_VALUE_USD    NUMBER,
  SALES_DEBIT_CODE_COMB    VARCHAR2(50 BYTE),
  SALES_CREDIT_CODE_COMB   VARCHAR2(50 BYTE),
  RETURN_DEBIT_CODE_COMB   VARCHAR2(50 BYTE),
  RETURN_CREDIT_CODE_COMB  VARCHAR2(50 BYTE),
  SALES_LEDGER_CURRENCY    VARCHAR2(15 BYTE),
  SALES_JOURNAL_CURRENCY   VARCHAR2(3 BYTE),
  MARKUP_TYPE              VARCHAR2(20 BYTE),
  SALES_COMPANY            VARCHAR2(50 BYTE),
  SALES_DR_BRAND           VARCHAR2(50 BYTE),
  SALES_DR_GEO             VARCHAR2(50 BYTE),
  SALES_DR_CHANNEL         VARCHAR2(50 BYTE),
  SALES_DR_ACCOUNT         VARCHAR2(50 BYTE),
  SALES_DR_ACCT_RETURN     VARCHAR2(50 BYTE),
  SALES_DR_DEPT            VARCHAR2(50 BYTE),
  SALES_DR_INTERCOM        VARCHAR2(50 BYTE),
  SALES_CR_BRAND           VARCHAR2(50 BYTE),
  SALES_CR_GEO             VARCHAR2(50 BYTE),
  SALES_CR_CHANNEL         VARCHAR2(50 BYTE),
  SALES_CR_ACCOUNT         VARCHAR2(50 BYTE),
  SALES_CR_ACCT_RETURN     VARCHAR2(50 BYTE),
  SALES_CR_DEPT            VARCHAR2(50 BYTE),
  SALES_CR_INTERCOM        VARCHAR2(50 BYTE),
  LEDGER_ID                NUMBER,
  LEDGER_NAME              VARCHAR2(30 BYTE),
  OU_ID                    NUMBER,
  OPERATING_UNIT           NUMBER,
  INV_ORG_ID               NUMBER,
  INV_ORG_NAME             VARCHAR2(50 BYTE),
  USER_JE_SOURCE_NAME      VARCHAR2(25 BYTE),
  USER_JE_CATEGORY_NAME    VARCHAR2(25 BYTE),
  JOURNAL_BATCH_NAME       VARCHAR2(240 BYTE),
  JOURNAL_NAME             VARCHAR2(240 BYTE),
  RECORD_STATUS            VARCHAR2(1 BYTE),
  ERROR_MSG                VARCHAR2(4000 BYTE),
  REQUEST_ID               NUMBER,
  AS_OF_DATE               DATE,
  ATTRIBUTE1               VARCHAR2(240 BYTE),
  ATTRIBUTE2               VARCHAR2(240 BYTE),
  ATTRIBUTE3               VARCHAR2(240 BYTE),
  ATTRIBUTE4               VARCHAR2(240 BYTE),
  ATTRIBUTE5               VARCHAR2(240 BYTE),
  CREATED_BY               NUMBER,
  CREATION_DATE            DATE,
  LAST_UPDATED_BY          NUMBER,
  LAST_UPDATE_DATE         DATE,
  LAST_UPDATE_LOGIN        NUMBER,
  TRAN_DATA_TS             DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_JE_RET_IC_MARKUP_STG_N1  (Index) 
--
--  Dependencies: 
--   XXD_GL_JE_RET_IC_MARKUP_STG_T (Table)
--
CREATE INDEX XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_N1 ON XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_T
(STORE_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_JE_RET_IC_MARKUP_STG_N2  (Index) 
--
--  Dependencies: 
--   XXD_GL_JE_RET_IC_MARKUP_STG_T (Table)
--
CREATE INDEX XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_N2 ON XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_T
(ITEM_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_JE_RET_IC_MARKUP_STG_N3  (Index) 
--
--  Dependencies: 
--   XXD_GL_JE_RET_IC_MARKUP_STG_T (Table)
--
CREATE INDEX XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_N3 ON XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_T
(ITEM_ID, STORE_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_JE_RET_IC_MARKUP_STG_T  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_JE_RET_IC_MARKUP_STG_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_JE_RET_IC_MARKUP_STG_T FOR XXDO.XXD_GL_JE_RET_IC_MARKUP_STG_T
/
