--
-- XXDO_ONT_SCHEDULE_HIS_T  (Table) 
--
CREATE TABLE XXDO.XXDO_ONT_SCHEDULE_HIS_T
(
  ONT_SCHEDULE_HIS_ID  NUMBER                   NOT NULL,
  OU_ID                NUMBER,
  OU_NAME              VARCHAR2(240 BYTE),
  INV_ORG_ID           NUMBER,
  INV_ORG_NAME         VARCHAR2(3 BYTE),
  ORDER_NUMBER         NUMBER,
  ORDER_HEADER_ID      NUMBER,
  LINE_NUMBER          NUMBER,
  ORDER_LINE_ID        NUMBER,
  INVENTORY_ITEM_ID    NUMBER,
  ORDERED_ITEM         VARCHAR2(2000 BYTE),
  ORDERED_QUANTITY     NUMBER,
  ORDERED_DATE         DATE,
  REQUEST_DATE         DATE,
  SCHEDULE_SHIP_DATE   DATE,
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATED_BY      NUMBER(15),
  CREATION_DATE        DATE,
  CREATED_BY           NUMBER(15),
  LAST_UPDATE_LOGIN    NUMBER(15)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ONT_SCHEDULE_HIS_T_I1  (Index) 
--
--  Dependencies: 
--   XXDO_ONT_SCHEDULE_HIS_T (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_ONT_SCHEDULE_HIS_T_I1 ON XXDO.XXDO_ONT_SCHEDULE_HIS_T
(ORDER_HEADER_ID, ORDER_LINE_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
--
-- XXDO_ONT_SCHEDULE_HIS_T_U1  (Index) 
--
--  Dependencies: 
--   XXDO_ONT_SCHEDULE_HIS_T (Table)
--
CREATE UNIQUE INDEX XXDO.XXDO_ONT_SCHEDULE_HIS_T_U1 ON XXDO.XXDO_ONT_SCHEDULE_HIS_T
(ONT_SCHEDULE_HIS_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_ONT_SCHEDULE_HIS_T  (Synonym) 
--
--  Dependencies: 
--   XXDO_ONT_SCHEDULE_HIS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_ONT_SCHEDULE_HIS_T FOR XXDO.XXDO_ONT_SCHEDULE_HIS_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_ONT_SCHEDULE_HIS_T TO APPS
/
