--
-- XXD_FA_VT_INT_STG  (Table) 
--
CREATE TABLE XXDO.XXD_FA_VT_INT_STG
(
  ASSET_ID            VARCHAR2(50 BYTE),
  BOOK_TYPE_CODE      VARCHAR2(100 BYTE),
  PROCESS_HISTORY_ID  NUMBER,
  DESCRIPTION         VARCHAR2(500 BYTE),
  CATEGORY_ID         NUMBER,
  LOCATION_ID         NUMBER,
  UNITS               NUMBER,
  ACCOUNTED_CR        NUMBER,
  EXPENSE_ACCOUNT_ID  NUMBER,
  TRANSACTION_DATE    DATE,
  STATUS              VARCHAR2(1 BYTE),
  REQUEST_ID          NUMBER,
  CREATED_BY          NUMBER,
  CREATION_DATE       DATE,
  LAST_UPDATED_BY     NUMBER,
  LAST_UPDATED_DATE   DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_FA_VT_INT_STG  (Synonym) 
--
--  Dependencies: 
--   XXD_FA_VT_INT_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_FA_VT_INT_STG FOR XXDO.XXD_FA_VT_INT_STG
/
