--
-- XXD_OM_REP_ASSGN_BATCH_HIST_T  (Table) 
--
CREATE TABLE XXDO.XXD_OM_REP_ASSGN_BATCH_HIST_T
(
  BATCH_ID     NUMBER                           NOT NULL,
  ORG_ID       NUMBER                           NOT NULL,
  BRAND        VARCHAR2(15 BYTE)                NOT NULL,
  SITE_USE_ID  NUMBER                           NOT NULL,
  SALESREP_ID  NUMBER                           NOT NULL,
  CUSTOMER_ID  NUMBER                           NOT NULL,
  BATCH_DATE   DATE                             NOT NULL
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_OM_REP_ASS_UPD_BTCH_H_IDX1  (Index) 
--
--  Dependencies: 
--   XXD_OM_REP_ASSGN_BATCH_HIST_T (Table)
--
CREATE INDEX XXDO.XXD_OM_REP_ASS_UPD_BTCH_H_IDX1 ON XXDO.XXD_OM_REP_ASSGN_BATCH_HIST_T
(ORG_ID, BRAND, SITE_USE_ID, SALESREP_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_OM_REP_ASSGN_BATCH_HIST_T  (Synonym) 
--
--  Dependencies: 
--   XXD_OM_REP_ASSGN_BATCH_HIST_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_OM_REP_ASSGN_BATCH_HIST_T FOR XXDO.XXD_OM_REP_ASSGN_BATCH_HIST_T
/


--
-- XXD_OM_REP_ASSGN_BATCH_HIST_T  (Synonym) 
--
--  Dependencies: 
--   XXD_OM_REP_ASSGN_BATCH_HIST_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_OM_REP_ASSGN_BATCH_HIST_T FOR XXDO.XXD_OM_REP_ASSGN_BATCH_HIST_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_OM_REP_ASSGN_BATCH_HIST_T TO SOA_INT
/
