--
-- XXD_PPM_CRITERIA_CURRENT_T  (Table) 
--
CREATE TABLE XXDO.XXD_PPM_CRITERIA_CURRENT_T
(
  STRUCTURE_NAME     VARCHAR2(10 BYTE)          NOT NULL,
  FATHER_CODE        VARCHAR2(10 BYTE)          NOT NULL,
  RESOURCE_CODE      VARCHAR2(10 BYTE)          NOT NULL,
  PLACE              NUMBER,
  EFFICIENCY         NUMBER,
  PRIMARY_VALUE_IND  VARCHAR2(1 BYTE),
  LAST_UPDATED_BY    VARCHAR2(10 BYTE),
  LAST_UPDATED_ON    DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
