--
-- XXD_GL_CCID_JE_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_CCID_JE_T
(
  CCID                NUMBER,
  SUMARIZE_SUBLEDGER  VARCHAR2(100 BYTE),
  SUMMARIZE_MANUAL    VARCHAR2(100 BYTE),
  SUMMERIZE_REVE      VARCHAR2(100 BYTE),
  OPEN_BALANCE_TYPE   VARCHAR2(100 BYTE),
  SEC_SUM_SUBLEDGER   VARCHAR2(100 BYTE),
  SEC_SUM_MANUAL      VARCHAR2(100 BYTE),
  SEC_SUMM_REVE       VARCHAR2(100 BYTE),
  SEC_OPEN_BAL_TYP    VARCHAR2(100 BYTE),
  FILE_PATH           VARCHAR2(100 BYTE),
  STATUARY_LEDGER     VARCHAR2(100 BYTE),
  FY_ELIGIBLE         VARCHAR2(10 BYTE),
  SEC_CY_ELIGIBLE     VARCHAR2(10 BYTE),
  SEC_FY_ELIGIBLE     VARCHAR2(10 BYTE),
  CREATION_DATE       DATE,
  FILE_PATH_NA        VARCHAR2(4000 BYTE),
  FILE_PATH_EMEA      VARCHAR2(4000 BYTE),
  FILE_PATH_APAC      VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
