--
-- XXD_AP_INV_ERRORS_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_AP_INV_ERRORS_GT
(
  INVOICE_ID        NUMBER,
  INVOICE_NUMBER    VARCHAR2(50 BYTE),
  INVOICE_DATE      DATE,
  ERROR_CODE        VARCHAR2(30 BYTE),
  ERROR_MESSAGE     VARCHAR2(500 BYTE),
  CREATION_DATE     DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER,
  REQUEST_ID        NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
