--
-- XXDOPO_MOQ_SURCHARGE_STG  (Table) 
--
CREATE TABLE XXDO.XXDOPO_MOQ_SURCHARGE_STG
(
  VENDOR_NAME           VARCHAR2(100 BYTE),
  PO_RCV_DATE           DATE,
  PO_NO                 VARCHAR2(100 BYTE),
  SHIP_LOC_ID           NUMBER,
  STYLE_NO              VARCHAR2(100 BYTE),
  STYLE_NAME            VARCHAR2(100 BYTE),
  COLOR                 VARCHAR2(100 BYTE),
  EX_FACT_DATE          DATE,
  CONF_EX_FACT          VARCHAR2(100 BYTE),
  PROMISED_DATE         DATE,
  DEST                  VARCHAR2(100 BYTE),
  BRAND                 VARCHAR2(100 BYTE),
  PO_QTY                NUMBER,
  UNIT_PRICE_FOB        NUMBER,
  GLOBAL_SURCHARGE      NUMBER,
  SHIP_TO_ID_SURCHARGE  NUMBER,
  BLENDED_FOB           NUMBER,
  BUY_MONTH             VARCHAR2(100 BYTE),
  BUY_SEASON            VARCHAR2(100 BYTE),
  FACILITY_SITE         VARCHAR2(100 BYTE),
  ETD_PORT              VARCHAR2(100 BYTE),
  SNO                   NUMBER,
  STATUS                VARCHAR2(10 BYTE),
  ORGANIZATION_ID       NUMBER,
  ORGANIZATION_CODE     VARCHAR2(100 BYTE),
  ERROR_MESSAGE         VARCHAR2(3000 BYTE),
  REQUEST_ID            NUMBER,
  FILE_NAME             VARCHAR2(240 BYTE),
  CREATION_DATE         DATE                    NOT NULL,
  CREATED_BY            NUMBER                  NOT NULL,
  LAST_UPDATED_BY       NUMBER                  NOT NULL,
  LAST_UPDATE_DATE      DATE                    NOT NULL,
  LAST_UPDATE_LOGIN     NUMBER,
  P_SEQ_NO              NUMBER,
  SIZE_NO               VARCHAR2(40 BYTE),
  PO_LINE_ID            NUMBER,
  ITEM_ID               NUMBER,
  SHIPMENT_NUM          NUMBER,
  NEED_BY_DATE          DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- SNO_UNIQUE  (Index) 
--
--  Dependencies: 
--   XXDOPO_MOQ_SURCHARGE_STG (Table)
--
CREATE UNIQUE INDEX XXDO.SNO_UNIQUE ON XXDO.XXDOPO_MOQ_SURCHARGE_STG
(SNO)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXDOPO_MOQ_SURCHARGE_STG ADD (
  CONSTRAINT SNO_UNIQUE
  UNIQUE (SNO)
  USING INDEX XXDO.SNO_UNIQUE
  ENABLE VALIDATE)
/


--
-- XXDOPO_MOQ_SURCHARGE_STG_N1  (Index) 
--
--  Dependencies: 
--   XXDOPO_MOQ_SURCHARGE_STG (Table)
--
CREATE INDEX XXDO.XXDOPO_MOQ_SURCHARGE_STG_N1 ON XXDO.XXDOPO_MOQ_SURCHARGE_STG
(P_SEQ_NO)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOPO_MOQ_SURCHARGE_STG_N2  (Index) 
--
--  Dependencies: 
--   XXDOPO_MOQ_SURCHARGE_STG (Table)
--
CREATE INDEX XXDO.XXDOPO_MOQ_SURCHARGE_STG_N2 ON XXDO.XXDOPO_MOQ_SURCHARGE_STG
(PO_LINE_ID, REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOPO_MOQ_SURCHARGE_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOPO_MOQ_SURCHARGE_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOPO_MOQ_SURCHARGE_STG FOR XXDO.XXDOPO_MOQ_SURCHARGE_STG
/


--
-- XXDOPO_MOQ_SURCHARGE_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOPO_MOQ_SURCHARGE_STG (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOPO_MOQ_SURCHARGE_STG FOR XXDO.XXDOPO_MOQ_SURCHARGE_STG
/


GRANT SELECT ON XXDO.XXDOPO_MOQ_SURCHARGE_STG TO APPS
/

GRANT SELECT ON XXDO.XXDOPO_MOQ_SURCHARGE_STG TO APPSRO
/
