--
-- XXD_INTERCOM_ERROR_TBL  (Table) 
--
CREATE TABLE XXDO.XXD_INTERCOM_ERROR_TBL
(
  LINE_ID         NUMBER,
  FUNCTION_NAME   VARCHAR2(100 BYTE),
  FROM_OU         VARCHAR2(100 BYTE),
  TO_OU           VARCHAR2(100 BYTE),
  FROM_INV_ORG    VARCHAR2(100 BYTE),
  TO_INV_ORG      VARCHAR2(100 BYTE),
  BRAND           VARCHAR2(100 BYTE),
  ORDER_TYPE      VARCHAR2(100 BYTE),
  ORDER_CURRENCY  VARCHAR2(10 BYTE),
  SOURCE_FACTORY  VARCHAR2(10 BYTE),
  ERROR_MESSAGE   VARCHAR2(3000 BYTE),
  CREATION_DATE   DATE,
  CREATED_BY      NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_INTERCOM_ERROR_TBL  (Synonym) 
--
--  Dependencies: 
--   XXD_INTERCOM_ERROR_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_INTERCOM_ERROR_TBL FOR XXDO.XXD_INTERCOM_ERROR_TBL
/
