--
-- XXDO_AR_PS_AUDIT_TBL  (Table) 
--
CREATE TABLE XXDO.XXDO_AR_PS_AUDIT_TBL
(
  CUSTOMER_TRX_ID          NUMBER,
  OLD_PAYMENT_TERM_ID      NUMBER,
  NEW_PAYMENT_TERM_ID      NUMBER,
  OLD_DUE_DATE             DATE,
  NEW_DUE_DATE             DATE,
  UPDATED_BY               NUMBER,
  UPDATE_DATE              DATE,
  ERROR_MESSAGE            VARCHAR2(2000 BYTE),
  DISCREPANCY_TYPE         VARCHAR2(100 BYTE),
  UPDATED_USER             VARCHAR2(100 BYTE),
  OLD_PAYMENT_SCHEDULE_ID  NUMBER,
  NEW_PAYMENT_SCHEDULE_ID  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
