--
-- XXD_PPM_PLAN_ENTITY_CURRENT_T  (Table) 
--
CREATE TABLE XXDO.XXD_PPM_PLAN_ENTITY_CURRENT_T
(
  PLANNING_CODE  VARCHAR2(10 BYTE)              NOT NULL,
  CODE5          VARCHAR2(10 BYTE),
  PPL_CODE       VARCHAR2(10 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
