--
-- XXD_GL_CC_FILE_UPLOAD_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_CC_FILE_UPLOAD_T
(
  CONCATENATED_SEGMENTS  VARCHAR2(250 BYTE),
  REQUESTED_BY           VARCHAR2(100 BYTE),
  DESCRIPTION            VARCHAR2(500 BYTE),
  ENABLE_DISABLE         VARCHAR2(10 BYTE),
  PRESERVED_FLAG         VARCHAR2(10 BYTE),
  ENABLED_FLAG           VARCHAR2(10 BYTE),
  DISABLED_FLAG          VARCHAR2(10 BYTE),
  FILE_NAME              VARCHAR2(500 BYTE),
  FILE_PROCESSED_DATE    DATE,
  STATUS                 VARCHAR2(100 BYTE),
  ERROR_CODE             VARCHAR2(100 BYTE),
  ERROR_MSG              VARCHAR2(2000 BYTE),
  CREATION_DATE          DATE,
  CREATED_BY             NUMBER,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  CCID                   NUMBER,
  RECORD_TYPE            VARCHAR2(50 BYTE),
  REQUEST_ID             NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_GL_CC_FILE_UPL_REQID_IDX  (Index) 
--
--  Dependencies: 
--   XXD_GL_CC_FILE_UPLOAD_T (Table)
--
CREATE INDEX XXDO.XXD_GL_CC_FILE_UPL_REQID_IDX ON XXDO.XXD_GL_CC_FILE_UPLOAD_T
(REQUEST_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_CC_FILE_UPLOAD_T  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_CC_FILE_UPLOAD_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_CC_FILE_UPLOAD_T FOR XXDO.XXD_GL_CC_FILE_UPLOAD_T
/
