--
-- XXDOOM_SANUK_CRDCONFIRM_STG  (Table) 
--
CREATE TABLE XXDO.XXDOOM_SANUK_CRDCONFIRM_STG
(
  FORMAT_TYPE             VARCHAR2(2 BYTE),
  GROUP_CLIENT_NUMBER     VARCHAR2(4 BYTE),
  CLIENT_NUMBER           VARCHAR2(4 BYTE),
  JULIAN_DATE             NUMBER,
  HOUR_OF_EXTRACTION      NUMBER(2),
  RECORD_TYPE             NUMBER(2),
  CIT_CUSTOMER_NUMBER     NUMBER(7),
  CLIENT_CUSTOMER_NUMBER  VARCHAR2(15 BYTE),
  CUSTOMER_NAME           VARCHAR2(30 BYTE),
  CLIENT_ORDER_NUMBER     VARCHAR2(22 BYTE),
  CIT_REFERENCE_NUMBER    VARCHAR2(10 BYTE),
  ORDER_AMOUNT            VARCHAR2(8 BYTE),
  APPROVED_AMOUNT         NUMBER(8),
  ACTION_CODE             VARCHAR2(2 BYTE),
  REASON_CODE1            VARCHAR2(2 BYTE),
  REASON_CODE2            VARCHAR2(2 BYTE),
  REASON_CODE3            VARCHAR2(2 BYTE),
  REASON_CODE4            VARCHAR2(2 BYTE),
  REASON_CODE5            VARCHAR2(2 BYTE),
  ORDER_RECEIPT_DATE      NUMBER,
  START_SHIP_DATE         NUMBER,
  COMPLETION_SHIP_DATE    NUMBER,
  TERMS_DAYS              NUMBER(3),
  CREDIT_LINE_AMOUNT      NUMBER(9),
  CREDIT_LINE_TYPE        NUMBER(1),
  CREDIT_APPROVER_NUMBER  NUMBER(3),
  FUTURE_USE              VARCHAR2(62 BYTE),
  PROCESS_FLAG            VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOOM_SANUK_CRDCONFIRM_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOOM_SANUK_CRDCONFIRM_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOOM_SANUK_CRDCONFIRM_STG FOR XXDO.XXDOOM_SANUK_CRDCONFIRM_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOOM_SANUK_CRDCONFIRM_STG TO APPS
/

GRANT SELECT ON XXDO.XXDOOM_SANUK_CRDCONFIRM_STG TO APPSRO WITH GRANT OPTION
/
