--
-- XXD_ONT_CUST_ORD_LINE_DTLS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_CUST_ORD_LINE_DTLS_T
(
  ORIG_SYS_DOCUMENT_REF         VARCHAR2(50 BYTE) NOT NULL,
  ORIG_SYS_LINE_REF             VARCHAR2(50 BYTE) NOT NULL,
  ORG_ID                        NUMBER,
  INVENTORY_ITEM_ID             NUMBER,
  CUSTOMER_PO_NUMBER            VARCHAR2(50 BYTE),
  CUSTOMER_ITEM_PRICE           NUMBER,
  CUSTOMER_ITEM_DISCOUNT        NUMBER,
  CREATED_BY                    NUMBER,
  CREATION_DATE                 DATE,
  LAST_UPDATE_BY                NUMBER,
  LAST_UPDATE_DATE              DATE,
  ATTRIBUTE1                    VARCHAR2(240 BYTE),
  ATTRIBUTE2                    VARCHAR2(240 BYTE),
  ATTRIBUTE3                    VARCHAR2(240 BYTE),
  ATTRIBUTE4                    VARCHAR2(240 BYTE),
  ATTRIBUTE5                    VARCHAR2(240 BYTE),
  ATTRIBUTE6                    VARCHAR2(240 BYTE),
  ATTRIBUTE7                    VARCHAR2(240 BYTE),
  ATTRIBUTE8                    VARCHAR2(240 BYTE),
  ATTRIBUTE9                    VARCHAR2(240 BYTE),
  ATTRIBUTE10                   VARCHAR2(240 BYTE),
  ATTRIBUTE11                   VARCHAR2(240 BYTE),
  ATTRIBUTE12                   VARCHAR2(240 BYTE),
  ATTRIBUTE13                   VARCHAR2(240 BYTE),
  ATTRIBUTE14                   VARCHAR2(240 BYTE),
  ATTRIBUTE15                   VARCHAR2(240 BYTE),
  ATTRIBUTE16                   VARCHAR2(240 BYTE),
  ATTRIBUTE17                   VARCHAR2(240 BYTE),
  ATTRIBUTE18                   VARCHAR2(240 BYTE),
  ATTRIBUTE19                   VARCHAR2(240 BYTE),
  ATTRIBUTE20                   VARCHAR2(240 BYTE),
  DATE_ATTRIBUTE1               DATE,
  DATE_ATTRIBUTE2               DATE,
  DATE_ATTRIBUTE3               DATE,
  DATE_ATTRIBUTE4               DATE,
  DATE_ATTRIBUTE5               DATE,
  DATE_ATTRIBUTE6               DATE,
  DATE_ATTRIBUTE7               DATE,
  DATE_ATTRIBUTE8               DATE,
  DATE_ATTRIBUTE9               DATE,
  DATE_ATTRIBUTE10              DATE,
  DATE_ATTRIBUTE11              DATE,
  DATE_ATTRIBUTE12              DATE,
  DATE_ATTRIBUTE13              DATE,
  DATE_ATTRIBUTE14              DATE,
  DATE_ATTRIBUTE15              DATE,
  DATE_ATTRIBUTE16              DATE,
  DATE_ATTRIBUTE17              DATE,
  DATE_ATTRIBUTE18              DATE,
  DATE_ATTRIBUTE19              DATE,
  DATE_ATTRIBUTE20              DATE,
  NUMBER_ATTRIBUTE1             NUMBER,
  NUMBER_ATTRIBUTE2             NUMBER,
  NUMBER_ATTRIBUTE3             NUMBER,
  NUMBER_ATTRIBUTE4             NUMBER,
  NUMBER_ATTRIBUTE5             NUMBER,
  NUMBER_ATTRIBUTE6             NUMBER,
  NUMBER_ATTRIBUTE7             NUMBER,
  NUMBER_ATTRIBUTE8             NUMBER,
  NUMBER_ATTRIBUTE9             NUMBER,
  NUMBER_ATTRIBUTE10            NUMBER,
  NUMBER_ATTRIBUTE11            NUMBER,
  NUMBER_ATTRIBUTE12            NUMBER,
  NUMBER_ATTRIBUTE13            NUMBER,
  NUMBER_ATTRIBUTE14            NUMBER,
  NUMBER_ATTRIBUTE15            NUMBER,
  NUMBER_ATTRIBUTE16            NUMBER,
  NUMBER_ATTRIBUTE17            NUMBER,
  NUMBER_ATTRIBUTE18            NUMBER,
  NUMBER_ATTRIBUTE19            NUMBER,
  NUMBER_ATTRIBUTE20            NUMBER,
  VARCHAR_ATTRIBUTE1            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE2            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE3            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE4            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE5            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE6            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE7            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE8            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE9            VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE10           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE11           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE12           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE13           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE14           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE15           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE16           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE17           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE18           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE19           VARCHAR2(240 BYTE),
  VARCHAR_ATTRIBUTE20           VARCHAR2(240 BYTE),
  CUSTOMER_GENDER_CODE          VARCHAR2(30 BYTE),
  CUSTOMER_MAJOR_CLASS          VARCHAR2(100 BYTE),
  CUSTOMER_SUB_CLASS            VARCHAR2(100 BYTE),
  CUSTOMER_BOX_ID               VARCHAR2(100 BYTE),
  CUSTOMER_DEPARTMENT           VARCHAR2(100 BYTE),
  CUSTOMER_VENDOR_STYLE_NUMBER  VARCHAR2(100 BYTE),
  SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_ONT_CUST_ORD_LINE_DTLS_T TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_ONT_CUST_ORD_LINE_DTLS_T TO SOA_INT
/
