--
-- XXD_ONT_CALLOFF_ORDERS_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_CALLOFF_ORDERS_T
(
  CALLOFF_ID                      NUMBER,
  ORG_ID                          NUMBER,
  CALLOFF_HEADER_ID               NUMBER,
  CALLOFF_ORDER_NUMBER            NUMBER,
  CALLOFF_SOLD_TO_ORG_ID          NUMBER,
  CALLOFF_CUST_PO_NUMBER          VARCHAR2(50 BYTE),
  CALLOFF_REQUEST_DATE            DATE,
  CALLOFF_ORDER_BRAND             VARCHAR2(50 BYTE),
  CALLOFF_LINE_ID                 NUMBER,
  CALLOFF_LINE_NUMBER             NUMBER,
  CALLOFF_SHIPMENT_NUMBER         NUMBER,
  CALLOFF_ORDERED_ITEM            VARCHAR2(2000 BYTE),
  CALLOFF_INVENTORY_ITEM_ID       NUMBER,
  CALLOFF_ORDERED_QUANTITY        NUMBER,
  CALLOFF_LINE_REQUEST_DATE       DATE,
  CALLOFF_SCHEDULE_SHIP_DATE      DATE,
  CALLOFF_LATEST_ACCEPTABLE_DATE  DATE,
  CALLOFF_LINE_DEMAND_CLASS_CODE  VARCHAR2(30 BYTE),
  BULK_ID                         NUMBER,
  BULK_HEADER_ID                  NUMBER,
  BULK_ORDER_NUMBER               NUMBER,
  BULK_SOLD_TO_ORG_ID             NUMBER,
  BULK_CUST_PO_NUMBER             VARCHAR2(50 BYTE),
  BULK_REQUEST_DATE               DATE,
  BULK_ORDER_BRAND                VARCHAR2(50 BYTE),
  BULK_LINE_ID                    NUMBER,
  BULK_LINE_NUMBER                NUMBER,
  BULK_SHIPMENT_NUMBER            NUMBER,
  BULK_ORDERED_ITEM               VARCHAR2(2000 BYTE),
  BULK_INVENTORY_ITEM_ID          NUMBER,
  BULK_ORDERED_QUANTITY           NUMBER,
  BULK_LINE_REQUEST_DATE          DATE,
  BULK_SCHEDULE_SHIP_DATE         DATE,
  BULK_LATEST_ACCEPTABLE_DATE     DATE,
  BULK_LINE_DEMAND_CLASS_CODE     VARCHAR2(30 BYTE),
  ORIGINAL_LINKED_QTY             NUMBER,
  CALLOFF_REDUCED_QTY             NUMBER,
  NEW_LINKED_QTY                  NUMBER,
  PARENT_REQUEST_ID               NUMBER,
  REQUEST_ID                      NUMBER,
  CUSTOMER_BATCH_ID               NUMBER,
  BULK_BATCH_ID                   NUMBER,
  STATUS                          VARCHAR2(1 BYTE),
  ERROR_MESSAGE                   VARCHAR2(2000 BYTE),
  CREATION_DATE                   DATE,
  CREATED_BY                      NUMBER,
  LAST_UPDATE_DATE                DATE,
  LAST_UPDATED_BY                 NUMBER,
  LAST_UPDATE_LOGIN               NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_CALLOFF_ORDERS_N1  (Index) 
--
--  Dependencies: 
--   XXD_ONT_CALLOFF_ORDERS_T (Table)
--
CREATE INDEX XXDO.XXD_ONT_CALLOFF_ORDERS_N1 ON XXDO.XXD_ONT_CALLOFF_ORDERS_T
(PARENT_REQUEST_ID, CUSTOMER_BATCH_ID, BULK_HEADER_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_ONT_CALLOFF_ORDERS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_CALLOFF_ORDERS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_CALLOFF_ORDERS_T FOR XXDO.XXD_ONT_CALLOFF_ORDERS_T
/
