--
-- XXDOEC_UNAPPLIED_CASH_R  (Table) 
--
CREATE TABLE XXDO.XXDOEC_UNAPPLIED_CASH_R
(
  ORG_ID           NUMBER(15),
  RECEIPT_NUMBER   VARCHAR2(30 BYTE),
  RECEIPT_DATE     DATE                         NOT NULL,
  COMMENTS         VARCHAR2(2000 BYTE),
  RECEIPT_AMOUNT   NUMBER                       NOT NULL,
  CURRENCY_CODE    VARCHAR2(15 BYTE)            NOT NULL,
  CUSTOMER_NUMBER  VARCHAR2(30 BYTE),
  CUSTOMER_NAME    VARCHAR2(90 BYTE),
  APPLIED_AMOUNT   NUMBER,
  BALANCE          NUMBER,
  SITE_USE_ID      NUMBER(15),
  SITE             VARCHAR2(16 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_UNAPPLIED_CASH_R  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_UNAPPLIED_CASH_R (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_UNAPPLIED_CASH_R FOR XXDO.XXDOEC_UNAPPLIED_CASH_R
/
