--
-- XXD_PARTNER_RET_TRAFFIC_STG  (Table) 
--
CREATE TABLE XXDO.XXD_PARTNER_RET_TRAFFIC_STG
(
  STORE_CODE          VARCHAR2(20 BYTE),
  STORE_NAME          VARCHAR2(100 BYTE),
  RECORD_DATE         VARCHAR2(100 BYTE),
  TRAFFIC             NUMBER,
  STORE_STATUS        VARCHAR2(1 BYTE),
  RECORDDATE_STATUS   VARCHAR2(1 BYTE),
  TRAFFIC_STATUS      VARCHAR2(1 BYTE),
  OVERALL_STATUS      VARCHAR2(1 BYTE),
  FILE_NAME           VARCHAR2(100 BYTE),
  BATCH_ID            NUMBER,
  CUSTOMER_NAME       VARCHAR2(100 BYTE),
  CITY_NAME           VARCHAR2(100 BYTE),
  PROVINCE_NAME       VARCHAR2(100 BYTE),
  BRAND               VARCHAR2(100 BYTE),
  REGION              VARCHAR2(100 BYTE),
  CHANNEL             VARCHAR2(100 BYTE),
  UPDATE_DATE         DATE,
  UPDATE_BY           NUMBER,
  CREATION_DATE       DATE,
  CREATED_BY          NUMBER,
  BRAND_STATUS        VARCHAR2(1 BYTE),
  ERROR_MESSAGE       VARCHAR2(2000 BYTE),
  FILE_FORMAT_STATUS  VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_IDX_PRTNR_TRFC_BATCH_ID_N1  (Index) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_TRAFFIC_STG (Table)
--
CREATE INDEX XXDO.XXD_IDX_PRTNR_TRFC_BATCH_ID_N1 ON XXDO.XXD_PARTNER_RET_TRAFFIC_STG
(BATCH_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_IDX_PRTNR_TRFC_CRE_DATE_N2  (Index) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_TRAFFIC_STG (Table)
--
CREATE INDEX XXDO.XXD_IDX_PRTNR_TRFC_CRE_DATE_N2 ON XXDO.XXD_PARTNER_RET_TRAFFIC_STG
(CREATION_DATE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PARTNER_RET_TRAFFIC_STG  (Synonym) 
--
--  Dependencies: 
--   XXD_PARTNER_RET_TRAFFIC_STG (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_PARTNER_RET_TRAFFIC_STG FOR XXDO.XXD_PARTNER_RET_TRAFFIC_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_PARTNER_RET_TRAFFIC_STG TO SOA_INT
/
