--
-- XXD_CST_DUTY_CORRECT_TR_T  (Table) 
--
CREATE TABLE XXDO.XXD_CST_DUTY_CORRECT_TR_T
(
  ORGANIZATION_CODE       VARCHAR2(100 BYTE),
  STYLE                   VARCHAR2(50 BYTE),
  COLOR                   VARCHAR2(50 BYTE),
  ITEM_NUMBER             VARCHAR2(100 BYTE),
  TRANSACTION_DATE        VARCHAR2(100 BYTE),
  TRANSACTION_TYPE        VARCHAR2(100 BYTE),
  TRANSACTION_ACCOUNT     VARCHAR2(100 BYTE),
  AVG_COST                NUMBER,
  AVG_PERCENT_CHANGE      NUMBER,
  MAT_AVG_COST            NUMBER,
  MAT_AVG_PERCENT_CHANGE  NUMBER,
  MAT_OH_COST             NUMBER,
  MAT_OH_PERCENT_CHANGE   NUMBER,
  DUTY                    NUMBER,
  OH_DUTY                 NUMBER,
  OH_NON_DUTY             NUMBER,
  FREIGHT_DUTY            NUMBER,
  FREIGHT                 NUMBER,
  FUTURE_COL1             VARCHAR2(100 BYTE),
  FUTURE_COL2             VARCHAR2(100 BYTE),
  FUTURE_COL3             VARCHAR2(100 BYTE),
  FUTURE_COL4             VARCHAR2(100 BYTE),
  FUTURE_COL5             VARCHAR2(100 BYTE),
  FUTURE_COL6             VARCHAR2(100 BYTE),
  FUTURE_COL7             VARCHAR2(100 BYTE),
  FUTURE_COL8             VARCHAR2(100 BYTE),
  FUTURE_COL9             VARCHAR2(100 BYTE),
  FUTURE_COL10            VARCHAR2(100 BYTE),
  REQUEST_ID              NUMBER,
  FILE_NAME               VARCHAR2(500 BYTE),
  STATUS                  VARCHAR2(10 BYTE),
  ERROR_MSG               VARCHAR2(4000 BYTE),
  CREATION_DATE           DATE,
  CREATED_BY              NUMBER,
  LAST_UPDATE_DATE        DATE,
  LAST_UPDATED_BY         NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_CST_DUTY_CORRECT_TR_T  (Synonym) 
--
--  Dependencies: 
--   XXD_CST_DUTY_CORRECT_TR_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_CST_DUTY_CORRECT_TR_T FOR XXDO.XXD_CST_DUTY_CORRECT_TR_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_CST_DUTY_CORRECT_TR_T TO APPS
/
