--
-- XXD_CE_CASHFLOW_STMT_EXT_T  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_CE_CASHFLOW_STMT_EXT_T
(
  BANK_ACCOUNT_NUM        VARCHAR2(100 BYTE),
  STATEMENT_NUMBER        VARCHAR2(100 BYTE),
  CASHFLOW_NUMBER         NUMBER,
  CASHFLOW_DIRECTION      VARCHAR2(100 BYTE),
  CASHFLOW_CURRENCY_CODE  VARCHAR2(20 BYTE),
  CASHFLOW_DATE           VARCHAR2(100 BYTE),
  CASHFLOW_AMOUNT         NUMBER,
  CASHFLOW_DESCRIPTION    VARCHAR2(500 BYTE),
  LINE_NUMBER             NUMBER,
  MEANING                 VARCHAR2(100 BYTE),
  TRX_CODE                VARCHAR2(100 BYTE),
  BANK_TRX_NUMBER         VARCHAR2(240 BYTE),
  TRX_DATE                VARCHAR2(100 BYTE),
  VALUE_DATE              VARCHAR2(100 BYTE),
  AMOUNT                  NUMBER,
  STATUS                  VARCHAR2(100 BYTE),
  CURRENCY_CODE           VARCHAR2(30 BYTE),
  EXCHANGE_RATE_TYPE      VARCHAR2(100 BYTE),
  EXCHANGE_RATE           NUMBER,
  EXCHANGE_RATE_DATE      DATE,
  AGENT                   VARCHAR2(100 BYTE),
  AGENT_BANK_ACCOUNT      VARCHAR2(150 BYTE),
  INVOICE                 VARCHAR2(150 BYTE),
  TRX_TEXT                VARCHAR2(500 BYTE),
  BANK_ACCOUNT_ID         NUMBER,
  STATEMENT_HEADER_ID     NUMBER,
  STATEMENT_LINE_ID       NUMBER,
  CASHFLOW_ID             NUMBER,
  TRX_CODE_ID             NUMBER,
  STATEMENT_DATE          DATE,
  CREATION_DATE           DATE,
  GL_DATE                 DATE,
  BANK_ACCT_OWNER_ORG_ID  NUMBER,
  W_LAST_UPDATE_DATE      DATE,
  W_LAST_UPDATED_BY       NUMBER,
  W_CREATION_DATE         DATE,
  W_CREATED_BY            NUMBER,
  W_LAST_UPDATE_LOGIN     NUMBER,
  REQUEST_ID              NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
