--
-- XXD_WMS_SHIP_CONFIRM_T  (Table) 
--
CREATE TABLE XXDO.XXD_WMS_SHIP_CONFIRM_T
(
  DELIVERY_ID        NUMBER,
  BILL_OF_LADING     VARCHAR2(50 BYTE),
  CONTAINER_NUMBER   VARCHAR2(50 BYTE),
  ORDER_NUMBER       NUMBER,
  ACCOUNT_NUMBER     VARCHAR2(35 BYTE),
  SHIPMENT_NUMBER    VARCHAR2(60 BYTE),
  SHIPMENT_STATUS    VARCHAR2(1 BYTE),
  ERROR_MESSAGE      VARCHAR2(4000 BYTE),
  CREATED_BY         NUMBER,
  CREATION_DATE      DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_DATE   DATE,
  REQUEST_ID         NUMBER,
  ORGANIZAITON_CODE  VARCHAR2(100 BYTE),
  MILESTONE_EVENT    VARCHAR2(200 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_WMS_SHIP_CONFIRM_T  (Synonym) 
--
--  Dependencies: 
--   XXD_WMS_SHIP_CONFIRM_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_WMS_SHIP_CONFIRM_T FOR XXDO.XXD_WMS_SHIP_CONFIRM_T
/
