--
-- XXD_ONT_DTC_ROLLOVER_RUN_T  (Table) 
--
CREATE TABLE XXDO.XXD_ONT_DTC_ROLLOVER_RUN_T
(
  GROUP_ID             NUMBER,
  OPERATION_MODE       VARCHAR2(240 BYTE),
  BRAND                VARCHAR2(240 BYTE),
  ORG_ID               NUMBER,
  CHANNEL              VARCHAR2(240 BYTE),
  ORDER_TYPE_ID        NUMBER,
  INV_ORG_ID           NUMBER,
  DEPARTMENT           VARCHAR2(240 BYTE),
  REQUEST_DATE_FROM    DATE,
  REQUEST_DATE_TO      DATE,
  PERIOD_NAME          VARCHAR2(240 BYTE),
  REGION               VARCHAR2(240 BYTE),
  NEW_REQUEST_DATE     DATE,
  NEW_CANCEL_LAD_DATE  DATE,
  EXECUTION_MODE       VARCHAR2(240 BYTE),
  STATUS               VARCHAR2(240 BYTE),
  ERROR_MESSAGE        VARCHAR2(4000 BYTE),
  REQUEST_ID           NUMBER,
  ATTRIBUTE1           VARCHAR2(240 BYTE),
  ATTRIBUTE2           VARCHAR2(240 BYTE),
  ATTRIBUTE3           VARCHAR2(240 BYTE),
  ATTRIBUTE4           VARCHAR2(240 BYTE),
  ATTRIBUTE5           VARCHAR2(240 BYTE),
  ATTRIBUTE6           VARCHAR2(240 BYTE),
  ATTRIBUTE7           VARCHAR2(240 BYTE),
  ATTRIBUTE8           VARCHAR2(240 BYTE),
  ATTRIBUTE9           VARCHAR2(240 BYTE),
  ATTRIBUTE10          VARCHAR2(240 BYTE),
  ATTRIBUTE11          VARCHAR2(240 BYTE),
  ATTRIBUTE12          VARCHAR2(240 BYTE),
  ATTRIBUTE13          VARCHAR2(240 BYTE),
  ATTRIBUTE14          VARCHAR2(240 BYTE),
  ATTRIBUTE15          VARCHAR2(240 BYTE),
  PROGRAM_START_TIME   DATE,
  PROGRAM_END_TIME     DATE,
  CREATED_BY           NUMBER,
  CREATION_DATE        DATE,
  LAST_UPDATED_BY      NUMBER,
  LAST_UPDATE_DATE     DATE,
  LAST_UPDATE_LOGIN    NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ONT_DTC_ROLLOVER_RUN_T  (Synonym) 
--
--  Dependencies: 
--   XXD_ONT_DTC_ROLLOVER_RUN_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_ONT_DTC_ROLLOVER_RUN_T FOR XXDO.XXD_ONT_DTC_ROLLOVER_RUN_T
/
