--
-- XXD_AR_TRX_ERRORS_GT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_AR_TRX_ERRORS_GT
(
  TRX_ID            NUMBER,
  TRX_NUMBER        VARCHAR2(20 BYTE),
  TRX_DATE          DATE,
  ERROR_CODE        VARCHAR2(30 BYTE),
  ERROR_MESSAGE     VARCHAR2(500 BYTE),
  CREATION_DATE     DATE,
  CREATED_BY        NUMBER,
  LAST_UPDATE_DATE  DATE,
  LAST_UPDATED_BY   NUMBER,
  REQUEST_ID        NUMBER
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
