--
-- XXD_GL_ARCHIVE_LINES  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ARCHIVE_LINES
(
  JE_HEADER_ID                  NUMBER(15)      NOT NULL,
  JE_LINE_NUM                   NUMBER(15)      NOT NULL,
  LAST_UPDATE_DATE              DATE            NOT NULL,
  LAST_UPDATED_BY               NUMBER(15)      NOT NULL,
  LEDGER_ID                     NUMBER(15)      NOT NULL,
  CODE_COMBINATION_ID           NUMBER(15)      NOT NULL,
  PERIOD_NAME                   VARCHAR2(15 BYTE) NOT NULL,
  EFFECTIVE_DATE                DATE            NOT NULL,
  STATUS                        VARCHAR2(1 BYTE) NOT NULL,
  CREATION_DATE                 DATE,
  CREATED_BY                    NUMBER(15),
  LAST_UPDATE_LOGIN             NUMBER(15),
  ENTERED_DR                    NUMBER,
  ENTERED_CR                    NUMBER,
  ACCOUNTED_DR                  NUMBER,
  ACCOUNTED_CR                  NUMBER,
  DESCRIPTION                   VARCHAR2(240 BYTE),
  REFERENCE_1                   VARCHAR2(240 BYTE),
  REFERENCE_2                   VARCHAR2(240 BYTE),
  REFERENCE_3                   VARCHAR2(240 BYTE),
  REFERENCE_4                   VARCHAR2(240 BYTE),
  REFERENCE_5                   VARCHAR2(240 BYTE),
  REFERENCE_6                   VARCHAR2(240 BYTE),
  REFERENCE_7                   VARCHAR2(240 BYTE),
  REFERENCE_8                   VARCHAR2(240 BYTE),
  REFERENCE_9                   VARCHAR2(240 BYTE),
  REFERENCE_10                  VARCHAR2(240 BYTE),
  ATTRIBUTE1                    VARCHAR2(150 BYTE),
  ATTRIBUTE2                    VARCHAR2(150 BYTE),
  ATTRIBUTE3                    VARCHAR2(150 BYTE),
  ATTRIBUTE4                    VARCHAR2(150 BYTE),
  ATTRIBUTE5                    VARCHAR2(150 BYTE),
  ATTRIBUTE6                    VARCHAR2(150 BYTE),
  ATTRIBUTE7                    VARCHAR2(150 BYTE),
  ATTRIBUTE8                    VARCHAR2(150 BYTE),
  ATTRIBUTE9                    VARCHAR2(150 BYTE),
  ATTRIBUTE10                   VARCHAR2(150 BYTE),
  ATTRIBUTE11                   VARCHAR2(150 BYTE),
  ATTRIBUTE12                   VARCHAR2(150 BYTE),
  ATTRIBUTE13                   VARCHAR2(150 BYTE),
  ATTRIBUTE14                   VARCHAR2(150 BYTE),
  ATTRIBUTE15                   VARCHAR2(150 BYTE),
  ATTRIBUTE16                   VARCHAR2(150 BYTE),
  ATTRIBUTE17                   VARCHAR2(150 BYTE),
  ATTRIBUTE18                   VARCHAR2(150 BYTE),
  ATTRIBUTE19                   VARCHAR2(150 BYTE),
  ATTRIBUTE20                   VARCHAR2(150 BYTE),
  CONTEXT                       VARCHAR2(150 BYTE),
  CONTEXT2                      VARCHAR2(150 BYTE),
  CONTEXT3                      VARCHAR2(150 BYTE),
  CONTEXT4                      VARCHAR2(150 BYTE),
  INVOICE_DATE                  DATE,
  TAX_CODE                      VARCHAR2(15 BYTE),
  INVOICE_IDENTIFIER            VARCHAR2(20 BYTE),
  INVOICE_AMOUNT                NUMBER,
  USSGL_TRANSACTION_CODE        VARCHAR2(30 BYTE),
  SUBLEDGER_DOC_SEQUENCE_ID     NUMBER,
  SUBLEDGER_DOC_SEQUENCE_VALUE  NUMBER,
  GL_SL_LINK_ID                 NUMBER,
  GL_SL_LINK_TABLE              VARCHAR2(30 BYTE),
  LINE_TYPE_CODE                VARCHAR2(20 BYTE),
  NO1                           VARCHAR2(150 BYTE),
  STAT_AMOUNT                   NUMBER,
  IGNORE_RATE_FLAG              VARCHAR2(1 BYTE),
  JGZZ_RECON_STATUS             VARCHAR2(1 BYTE),
  JGZZ_RECON_DATE               DATE,
  JGZZ_RECON_ID                 NUMBER,
  JGZZ_RECON_REF                VARCHAR2(240 BYTE),
  JGZZ_RECON_CONTEXT            VARCHAR2(30 BYTE),
  GLOBAL_ATTRIBUTE_CATEGORY     VARCHAR2(30 BYTE),
  GLOBAL_ATTRIBUTE1             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE2             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE3             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE4             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE5             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE6             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE7             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE8             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE9             VARCHAR2(150 BYTE),
  GLOBAL_ATTRIBUTE10            VARCHAR2(150 BYTE),
  TAXABLE_LINE_FLAG             VARCHAR2(1 BYTE),
  TAX_TYPE_CODE                 VARCHAR2(1 BYTE),
  TAX_CODE_ID                   NUMBER(15),
  TAX_ROUNDING_RULE_CODE        VARCHAR2(1 BYTE),
  AMOUNT_INCLUDES_TAX_FLAG      VARCHAR2(1 BYTE),
  TAX_DOCUMENT_IDENTIFIER       VARCHAR2(50 BYTE),
  TAX_DOCUMENT_DATE             DATE,
  TAX_CUSTOMER_NAME             VARCHAR2(240 BYTE),
  TAX_CUSTOMER_REFERENCE        VARCHAR2(240 BYTE),
  TAX_REGISTRATION_NUMBER       VARCHAR2(50 BYTE),
  TAX_LINE_FLAG                 VARCHAR2(1 BYTE),
  TAX_GROUP_ID                  NUMBER(15),
  CO_THIRD_PARTY                VARCHAR2(14 BYTE),
  CO_PROCESSED_FLAG             VARCHAR2(1 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    1
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2000K
            NEXT             2000K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
COMPRESS FOR QUERY HIGH
NOCACHE
/


--
-- XXD_GL_ARCHIVE_LINES_N1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_LINES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_LINES_N1 ON XXDO.XXD_GL_ARCHIVE_LINES
(CODE_COMBINATION_ID, PERIOD_NAME)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_LINES_N3  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_LINES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_LINES_N3 ON XXDO.XXD_GL_ARCHIVE_LINES
(SUBLEDGER_DOC_SEQUENCE_VALUE, SUBLEDGER_DOC_SEQUENCE_ID)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_LINES_U1  (Index) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_LINES (Table)
--
CREATE INDEX XXDO.XXD_GL_ARCHIVE_LINES_U1 ON XXDO.XXD_GL_ARCHIVE_LINES
(JE_HEADER_ID, JE_LINE_NUM)
LOGGING
TABLESPACE APPS_TS_TX_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_GL_ARCHIVE_LINES  (Synonym) 
--
--  Dependencies: 
--   XXD_GL_ARCHIVE_LINES (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_GL_ARCHIVE_LINES FOR XXDO.XXD_GL_ARCHIVE_LINES
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_GL_ARCHIVE_LINES TO APPS WITH GRANT OPTION
/
