--
-- XXDOAR_STATEMENTS_STG  (Table) 
--
CREATE TABLE XXDO.XXDOAR_STATEMENTS_STG
(
  CUSTOMER_NAME           VARCHAR2(360 BYTE),
  CUSTOMER_NUMBER         VARCHAR2(30 BYTE),
  CLASS                   VARCHAR2(30 BYTE),
  CONTACT_SITE_ID         NUMBER,
  CUSTOMER_STATE          VARCHAR2(120 BYTE),
  CUSTOMER_CITY           VARCHAR2(120 BYTE),
  CUSTOMER_ID             NUMBER,
  PAYMENT_SCHED_ID        NUMBER,
  DUE_DATE                DATE,
  AMT_DUE_REMAINING       NUMBER,
  TRX_NUMBER              VARCHAR2(50 BYTE),
  DAYS_PAST_DUE           NUMBER,
  AMOUNT_ADJUSTED         NUMBER,
  AMOUNT_APPLIED          NUMBER,
  AMOUNT_CREDITED         NUMBER,
  GL_DATE                 DATE,
  B0_INV                  NUMBER,
  B1_INV                  NUMBER,
  B2_INV                  NUMBER,
  B3_INV                  NUMBER,
  B4_INV                  NUMBER,
  B5_INV                  NUMBER,
  B6_INV                  NUMBER,
  COMPANY                 VARCHAR2(360 BYTE),
  INVOICE_TYPE            VARCHAR2(120 BYTE),
  CONS_BILLING_NUMBER     VARCHAR2(120 BYTE),
  PROCESS_FLAG            VARCHAR2(1 BYTE),
  CONCURRENT_REQUEST_ID   NUMBER,
  FILE_DATE_TIME          VARCHAR2(30 BYTE),
  ORG_ID                  NUMBER,
  REMIT_ADDRESS1          VARCHAR2(240 BYTE),
  REMIT_ADDRESS2          VARCHAR2(240 BYTE),
  REMIT_ADDRESS3          VARCHAR2(240 BYTE),
  REMIT_ADDRESS4          VARCHAR2(240 BYTE),
  REMIT_CITY              VARCHAR2(60 BYTE),
  REMIT_STATE             VARCHAR2(60 BYTE),
  REMIT_PROVINCE          VARCHAR2(60 BYTE),
  REMIT_ZIP               VARCHAR2(60 BYTE),
  REMIT_COUNTRY           VARCHAR2(60 BYTE),
  BILL_TO_ADDRESS1        VARCHAR2(240 BYTE),
  BILL_TO_ADDRESS2        VARCHAR2(240 BYTE),
  BILL_TO_ADDRESS3        VARCHAR2(240 BYTE),
  BILL_TO_ADDRESS4        VARCHAR2(240 BYTE),
  BILL_TO_CITY            VARCHAR2(60 BYTE),
  BILL_TO_STATE           VARCHAR2(60 BYTE),
  BILL_TO_PROVINCE        VARCHAR2(60 BYTE),
  BILL_TO_ZIP             VARCHAR2(60 BYTE),
  BILL_TO_COUNTRY         VARCHAR2(60 BYTE),
  BILL_TO_PARTY           VARCHAR2(360 BYTE),
  REMIT_CONTACT_NUMBER    VARCHAR2(150 BYTE),
  REMIT_ADDRESSEE         VARCHAR2(240 BYTE),
  COLLECTOR_NAME          VARCHAR2(150 BYTE),
  COLLECTOR_PHONE         VARCHAR2(150 BYTE),
  COLLECTOR_EMAIL         VARCHAR2(240 BYTE),
  PARENT_CUSTOMER_NUMBER  VARCHAR2(30 BYTE),
  BUYING_GROUP_NUMBER     VARCHAR2(150 BYTE),
  SOLD_BY_LEGAL_ENTITY    VARCHAR2(150 BYTE),
  REPROCESS_FLAG          VARCHAR2(1 BYTE),
  HEADER_COMMENTS1        VARCHAR2(2000 BYTE),
  HEADER_COMMENTS2        VARCHAR2(2000 BYTE),
  HEADER_COMMENTS3        VARCHAR2(2000 BYTE),
  HEADER_COMMENTS4        VARCHAR2(2000 BYTE),
  HEADER_COMMENTS5        VARCHAR2(360 BYTE),
  HEADER_COMMENTS6        VARCHAR2(360 BYTE),
  HEADER_COMMENTS7        VARCHAR2(360 BYTE),
  HEADER_COMMENTS8        VARCHAR2(360 BYTE),
  HEADER_COMMENTS9        VARCHAR2(360 BYTE),
  HEADER_COMMENTS10       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER1       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER2       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER3       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER4       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER5       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER6       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER7       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER8       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER9       VARCHAR2(360 BYTE),
  LINE_PLACEHOLDER10      VARCHAR2(360 BYTE),
  BUCKET0_NAME            VARCHAR2(60 BYTE),
  BUCKET1_NAME            VARCHAR2(60 BYTE),
  BUCKET2_NAME            VARCHAR2(60 BYTE),
  BUCKET3_NAME            VARCHAR2(60 BYTE),
  BUCKET4_NAME            VARCHAR2(60 BYTE),
  BUCKET5_NAME            VARCHAR2(60 BYTE),
  BUCKET6_NAME            VARCHAR2(60 BYTE),
  BUCKET0_VALUE           NUMBER,
  BUCKET1_VALUE           NUMBER,
  BUCKET2_VALUE           NUMBER,
  BUCKET3_VALUE           NUMBER,
  BUCKET4_VALUE           NUMBER,
  BUCKET5_VALUE           NUMBER,
  BUCKET6_VALUE           NUMBER,
  TOTAL_AMOUNT            NUMBER,
  BRAND_PHONE_NUMBER      VARCHAR2(240 BYTE),
  BILLING_PHONE           VARCHAR2(240 BYTE),
  FOOTER_NOTES1           VARCHAR2(2000 BYTE),
  FOOTER_NOTES2           VARCHAR2(2000 BYTE),
  FOOTER_NOTES3           VARCHAR2(2000 BYTE),
  FOOTER_NOTES4           VARCHAR2(2000 BYTE),
  FOOTER_NOTES5           VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS1        VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS2        VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS3        VARCHAR2(2000 BYTE),
  FOOTER_COMMENTS4        VARCHAR2(2000 BYTE),
  OPERATING_UNIT          VARCHAR2(240 BYTE),
  BRAND_NAME              VARCHAR2(30 BYTE),
  DOC_LANGUAGE            VARCHAR2(30 BYTE),
  TO_EMAIL_ADDRESS        VARCHAR2(360 BYTE),
  FROM_EMAIL_ADDRESS      VARCHAR2(240 BYTE),
  PRINT_FLAG              VARCHAR2(1 BYTE),
  EMAIL_FLAG              VARCHAR2(1 BYTE),
  STATEMENT_NUMBER        VARCHAR2(30 BYTE),
  STATEMENT_DATE          DATE,
  CURRENCY_CODE           VARCHAR2(30 BYTE),
  REFERENCE               VARCHAR2(60 BYTE),
  AMOUNT_DUE_ORIGINAL     NUMBER,
  BILL_TO_COUNTRY_NAME    VARCHAR2(150 BYTE),
  REMIT_TO_COUNTRY_NAME   VARCHAR2(150 BYTE),
  ERROR_MESSAGE           VARCHAR2(4000 BYTE),
  CONSOLIDATED_FLAG       VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAR_STATEMENTS_U1  (Index) 
--
--  Dependencies: 
--   XXDOAR_STATEMENTS_STG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOAR_STATEMENTS_U1 ON XXDO.XXDOAR_STATEMENTS_STG
(CONCURRENT_REQUEST_ID, CUSTOMER_ID, ORG_ID, PAYMENT_SCHED_ID, CLASS, 
TRX_NUMBER, AMT_DUE_REMAINING)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_STATEMENTS_N1  (Index) 
--
--  Dependencies: 
--   XXDOAR_STATEMENTS_STG (Table)
--
CREATE INDEX XXDO.XXDOAR_STATEMENTS_N1 ON XXDO.XXDOAR_STATEMENTS_STG
(PROCESS_FLAG)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_STATEMENTS_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_STATEMENTS_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAR_STATEMENTS_STG FOR XXDO.XXDOAR_STATEMENTS_STG
/


--
-- XXDOAR_STATEMENTS_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_STATEMENTS_STG (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOAR_STATEMENTS_STG FOR XXDO.XXDOAR_STATEMENTS_STG
/
