--
-- XXDO_ORDER_RETURN_STATUS  (Table) 
--
CREATE TABLE XXDO.XXDO_ORDER_RETURN_STATUS
(
  STATUS   VARCHAR2(64 BYTE),
  MEANING  VARCHAR2(124 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_ORDER_RETURN_STATUS  (Synonym) 
--
--  Dependencies: 
--   XXDO_ORDER_RETURN_STATUS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_ORDER_RETURN_STATUS FOR XXDO.XXDO_ORDER_RETURN_STATUS
/
