--
-- XXDOAP_PRE_ACCRUAL  (Table) 
--
CREATE TABLE XXDO.XXDOAP_PRE_ACCRUAL
(
  BRAND            VARCHAR2(20 BYTE),
  VENDOR_ID        NUMBER                       NOT NULL,
  INVOICE_NUM      VARCHAR2(50 BYTE),
  VENDOR           VARCHAR2(240 BYTE)           NOT NULL,
  INVOICE_DATE     DATE,
  ACCOUNTING_DATE  DATE,
  INVOICE_AMOUNT   NUMBER,
  PAYMENT_DATE     DATE,
  AP_TYPE          VARCHAR2(20 BYTE),
  ORG_ID           NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAP_PRE_ACCRUAL  (Synonym) 
--
--  Dependencies: 
--   XXDOAP_PRE_ACCRUAL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAP_PRE_ACCRUAL FOR XXDO.XXDOAP_PRE_ACCRUAL
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOAP_PRE_ACCRUAL TO APPS
/

GRANT SELECT ON XXDO.XXDOAP_PRE_ACCRUAL TO APPSRO WITH GRANT OPTION
/
