--
-- XXDOEC_ORDER_RCNCL_STATUS_LOG  (Table) 
--
CREATE TABLE XXDO.XXDOEC_ORDER_RCNCL_STATUS_LOG
(
  ORDER_NUMBER     VARCHAR2(50 BYTE),
  CUSTOMER_NUMBER  VARCHAR2(25 BYTE),
  CALLED_WITH      VARCHAR2(500 BYTE),
  CREATEDATE       DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
