--
-- XXDO_BAM_860_ORDERS  (Table) 
--
CREATE TABLE XXDO.XXDO_BAM_860_ORDERS
(
  APP_TRANS_KEY          VARCHAR2(100 BYTE),
  ORDER_NUMBER           VARCHAR2(100 BYTE),
  PARTNER                VARCHAR2(100 BYTE),
  ISA                    VARCHAR2(100 BYTE),
  STATUS                 VARCHAR2(100 BYTE),
  MESSAGE_DATE           DATE,
  EXISTS_IN_INTERFACE    VARCHAR2(1 BYTE),
  NOTIFIED               VARCHAR2(1 BYTE),
  EXISTS_IN_EBS          VARCHAR2(1 BYTE),
  BLANKET_ORDER_CREATED  VARCHAR2(1 BYTE),
  ASSIGNEE               VARCHAR2(100 BYTE),
  SEND_INSTANCE_ID       VARCHAR2(100 BYTE),
  EBS_ORDER_NUMBER       VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_BAM_860_ORDERS  (Synonym) 
--
--  Dependencies: 
--   XXDO_BAM_860_ORDERS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_BAM_860_ORDERS FOR XXDO.XXDO_BAM_860_ORDERS
/


--
-- XXDO_BAM_860_ORDERS  (Synonym) 
--
--  Dependencies: 
--   XXDO_BAM_860_ORDERS (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXDO_BAM_860_ORDERS FOR XXDO.XXDO_BAM_860_ORDERS
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_BAM_860_ORDERS TO APPS
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_BAM_860_ORDERS TO SOA_INT
/
