--
-- XXD_RMS_CONCESSION_STORE_T  (Table) 
--
CREATE TABLE XXDO.XXD_RMS_CONCESSION_STORE_T
(
  RMS_STORE_ID    VARCHAR2(100 BYTE),
  PROCESS_STATUS  VARCHAR2(100 BYTE),
  NEW_RUN_DATE    DATE,
  LAST_RUN_DATE   DATE,
  CREATION_DATE   DATE,
  ATTRIBUTE1      VARCHAR2(100 BYTE),
  ATTRIBUTE2      VARCHAR2(100 BYTE),
  ATTRIBUTE3      VARCHAR2(100 BYTE),
  ATTRIBUTE4      VARCHAR2(100 BYTE),
  ATTRIBUTE5      VARCHAR2(3200 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
