--
-- XXDO_PO_ASN_RECEIPT_XML_STG  (Table) 
--
--  Dependencies: 
--   STANDARD (Package)
--   XMLTYPE (Type)
--
CREATE TABLE XXDO.XXDO_PO_ASN_RECEIPT_XML_STG
(
  PROCESS_STATUS    VARCHAR2(30 BYTE),
  XML_DOCUMENT      SYS.XMLTYPE,
  FILE_NAME         VARCHAR2(50 BYTE),
  ERROR_MESSAGE     VARCHAR2(2000 BYTE),
  REQUEST_ID        NUMBER                      NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        NUMBER                      NOT NULL,
  LAST_UPDATE_DATE  DATE                        NOT NULL,
  LAST_UPDATED_BY   NUMBER                      NOT NULL,
  ASN_XML_SEQ_ID    NUMBER
)
XMLTYPE XML_DOCUMENT STORE AS SECUREFILE BINARY XML (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
ALLOW NONSCHEMA
DISALLOW ANYSCHEMA
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_PO_ASN_RECEIPT_XML_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_PO_ASN_RECEIPT_XML_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_PO_ASN_RECEIPT_XML_STG FOR XXDO.XXDO_PO_ASN_RECEIPT_XML_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_PO_ASN_RECEIPT_XML_STG TO SOA_INT
/
