--
-- XXDOEC_CA_STLMNT_HEADERS  (Table) 
--
CREATE TABLE XXDO.XXDOEC_CA_STLMNT_HEADERS
(
  STLMNT_HEADER_ID   NUMBER,
  WEBSITE_ID         VARCHAR2(30 BYTE),
  SETTLEMENT_ID      VARCHAR2(40 BYTE),
  CURRENCY_CODE      VARCHAR2(10 BYTE),
  TOTAL_AMOUNT       NUMBER,
  DEPOSIT_DATE       DATE,
  TRANS_START_DATE   DATE,
  TRANS_END_DATE     DATE,
  RECEIPTS_BATCH_ID  NUMBER,
  INTERFACE_STATUS   VARCHAR2(1 BYTE),
  ERROR_MESSAGE      VARCHAR2(2000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_CA_STLMNT_HEADERS_U1  (Index) 
--
--  Dependencies: 
--   XXDOEC_CA_STLMNT_HEADERS (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOEC_CA_STLMNT_HEADERS_U1 ON XXDO.XXDOEC_CA_STLMNT_HEADERS
(STLMNT_HEADER_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
--
-- XXDOEC_CA_STLMNT_HEADERS_U2  (Index) 
--
--  Dependencies: 
--   XXDOEC_CA_STLMNT_HEADERS (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOEC_CA_STLMNT_HEADERS_U2 ON XXDO.XXDOEC_CA_STLMNT_HEADERS
(WEBSITE_ID, SETTLEMENT_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_CA_STLMNT_HEADERS  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_CA_STLMNT_HEADERS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_CA_STLMNT_HEADERS FOR XXDO.XXDOEC_CA_STLMNT_HEADERS
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDOEC_CA_STLMNT_HEADERS TO APPS
/
