--
-- XXDOAR_B2B_CASHAPP_STG  (Table) 
--
CREATE TABLE XXDO.XXDOAR_B2B_CASHAPP_STG
(
  EXPORTDETAILID             NUMBER,
  JOBID                      NUMBER,
  IMPORTID                   NUMBER,
  BATCHIMPORTDATE            DATE,
  LOCKBOX                    VARCHAR2(100 BYTE),
  EXPORTID                   NUMBER,
  OSBATCHID                  NUMBER,
  BANKBATCHID                NUMBER,
  DEPOSITDATE                DATE,
  PROCESSINGDATE             DATE,
  BATCHODIJOBID              VARCHAR2(50 BYTE),
  MACHINENAME                VARCHAR2(50 BYTE),
  BATCHTICKETMICR            VARCHAR2(100 BYTE),
  BATCHEXTERNALUID           VARCHAR2(100 BYTE),
  LOCATION_COL               VARCHAR2(100 BYTE),
  BATCHIDENTIFIER1           VARCHAR2(4000 BYTE),
  BATCHIDENTIFIER2           VARCHAR2(4000 BYTE),
  BATCHIDENTIFIER3           VARCHAR2(4000 BYTE),
  BATCHIDENTIFIER4           VARCHAR2(4000 BYTE),
  BATCHIDENTIFIER5           VARCHAR2(4000 BYTE),
  ENVELOPEID                 NUMBER,
  ENVELOPESEQ                NUMBER,
  BANKTRANSACTIONNUMBER      NUMBER,
  ENVELOPEIDENTIFIER1        VARCHAR2(4000 BYTE),
  ENVELOPEIDENTIFIER2        VARCHAR2(4000 BYTE),
  ENVELOPEIDENTIFIER3        VARCHAR2(4000 BYTE),
  ENVELOPEIDENTIFIER4        VARCHAR2(4000 BYTE),
  ENVELOPEIDENTIFIER5        VARCHAR2(4000 BYTE),
  EXPORTDATE                 DATE,
  ENVELOPENOTES              VARCHAR2(4000 BYTE),
  ABANUMBER                  VARCHAR2(50 BYTE),
  ACCOUNTNUMBER              VARCHAR2(50 BYTE),
  CHECKNO                    VARCHAR2(50 BYTE),
  CREDITACCOUNTANDCHECK_NO   VARCHAR2(100 BYTE),
  ISOCOUNTRY                 VARCHAR2(2 BYTE),
  CREDITUSFUNDSFLAG          VARCHAR2(1 BYTE),
  CHECKAMOUNT                NUMBER,
  CREDITORIGINALAMOUNT       NUMBER,
  CHECKDATE                  DATE,
  CREDITSIGNATURECOUNT       NUMBER,
  CREDITTYPECODE             VARCHAR2(5 BYTE),
  PAYORNAME                  VARCHAR2(100 BYTE),
  CREDITPAYORADDRESS         VARCHAR2(100 BYTE),
  PAYEENAME                  VARCHAR2(100 BYTE),
  CREDITPAYEEADDRESS         VARCHAR2(100 BYTE),
  CREDITIQARESULTS           NUMBER,
  CREDITIDENTIFIER1          VARCHAR2(4000 BYTE),
  CREDITIDENTIFIER2          VARCHAR2(4000 BYTE),
  CREDITIDENTIFIER3          VARCHAR2(4000 BYTE),
  CREDITIDENTIFIER4          VARCHAR2(4000 BYTE),
  CREDITIDENTIFIER5          VARCHAR2(4000 BYTE),
  DEPOSITBANKNAME            VARCHAR2(200 BYTE),
  DEPOSITBANKACCOUNT_NUMBER  VARCHAR2(200 BYTE),
  REMITPAGEID                NUMBER,
  PAGEEXCEPTIONNAME          VARCHAR2(100 BYTE),
  REMITPAGEIDENTIFIER1       VARCHAR2(4000 BYTE),
  REMITPAGEIDENTIFIER2       VARCHAR2(4000 BYTE),
  REMITPAGEIDENTIFIER3       VARCHAR2(4000 BYTE),
  REMITPAGEIDENTIFIER4       VARCHAR2(4000 BYTE),
  REMITPAGEIDENTIFIER5       VARCHAR2(4000 BYTE),
  LINEITEM                   NUMBER,
  SUSPENDED                  VARCHAR2(1 BYTE),
  INVOICENUMBER              VARCHAR2(100 BYTE),
  CUSTNO                     VARCHAR2(200 BYTE),
  PARENTCUSTNO               VARCHAR2(200 BYTE),
  CUSTNAME                   VARCHAR2(4000 BYTE),
  INVOICEAMOUNT              NUMBER,
  AMOUNTDUE                  NUMBER,
  AMOUNTBALANCE              NUMBER,
  TAX                        NUMBER,
  FREIGHT                    NUMBER,
  DISCOUNT                   NUMBER,
  INVOICEDATE                DATE,
  DISCOUNTDATE               DATE,
  DEDUCTIONCODE              VARCHAR2(4000 BYTE),
  DEDUCTIONAMT               NUMBER,
  REMITIDENTIFIER1           VARCHAR2(4000 BYTE),
  REMITIDENTIFIER2           VARCHAR2(4000 BYTE),
  SEARCH1                    VARCHAR2(4000 BYTE),
  SEARCH2                    VARCHAR2(4000 BYTE),
  REMITIDENTIFIER5           VARCHAR2(4000 BYTE),
  REMITIDENTIFIER6           VARCHAR2(4000 BYTE),
  REMITIDENTIFIER7           VARCHAR2(4000 BYTE),
  REMITIDENTIFIER8           VARCHAR2(4000 BYTE),
  REMITIDENTIFIER9           VARCHAR2(4000 BYTE),
  PONUMBER                   VARCHAR2(4000 BYTE),
  STATEMENTNO                VARCHAR2(4000 BYTE),
  CUSTOM1                    VARCHAR2(4000 BYTE),
  CUSTOM2                    VARCHAR2(4000 BYTE),
  CUSTOM3                    VARCHAR2(4000 BYTE),
  CUSTOM4                    VARCHAR2(4000 BYTE),
  REMITIDENTIFIER16          VARCHAR2(4000 BYTE),
  REMITIDENTIFIER17          VARCHAR2(4000 BYTE),
  REMITIDENTIFIER18          VARCHAR2(4000 BYTE),
  REMITIDENTIFIER19          VARCHAR2(4000 BYTE),
  REMITIDENTIFIER20          VARCHAR2(4000 BYTE),
  REMITINDEXIDENTIFIER1      VARCHAR2(4000 BYTE),
  REMITINDEXIDENTIFIER2      VARCHAR2(4000 BYTE),
  REMITINDEXIDENTIFIER3      VARCHAR2(4000 BYTE),
  REMITINDEXIDENTIFIER4      VARCHAR2(4000 BYTE),
  REMITINDEXIDENTIFIER5      VARCHAR2(4000 BYTE),
  STATEMENTAMT               NUMBER,
  LESSDISCOUNT               NUMBER,
  LESSFREIGHT                NUMBER,
  LESSTAX                    NUMBER,
  MONEY1                     NUMBER,
  MONEY2                     NUMBER,
  REMITMONEYIDENTIFIER7      NUMBER,
  REMITMONEYIDENTIFIER8      NUMBER,
  REMITMONEYIDENTIFIER9      NUMBER,
  REMITMONEYIDENTIFIER10     NUMBER,
  REMITMONEYIDENTIFIER11     NUMBER,
  REMITMONEYIDENTIFIER12     NUMBER,
  REMITMONEYIDENTIFIER13     NUMBER,
  REMITMONEYIDENTIFIER14     NUMBER,
  REMITMONEYIDENTIFIER15     NUMBER,
  REMITMONEYIDENTIFIER16     NUMBER,
  REMITDATEIDENTIFIER1       DATE,
  REMITDATEIDENTIFIER2       DATE,
  REMITDATEIDENTIFIER3       DATE,
  REMITNOTES                 VARCHAR2(4000 BYTE),
  REVIEWREASONSHORT          VARCHAR2(4000 BYTE),
  USERNAME                   VARCHAR2(50 BYTE),
  BLANK                      VARCHAR2(4000 BYTE),
  CREATION_DATE              DATE,
  CREATED_BY                 NUMBER,
  LAST_UPDATE_DATE           DATE,
  LAST_UPDATED_BY            NUMBER,
  INBOUND_FILENAME           VARCHAR2(240 BYTE),
  ORACLERECORDID             NUMBER,
  ORACLEREQUESTID            NUMBER,
  ORACLEPROCESSFLAG          VARCHAR2(1 BYTE),
  ORACLEERRORMESSAGE         VARCHAR2(4000 BYTE),
  ORG_ID                     NUMBER,
  CUSTOMER_ID                NUMBER,
  PARENT_CUSTOMER_ID         NUMBER,
  OU_REGION                  VARCHAR2(30 BYTE),
  USE_BRAND_CUST_FLAG        VARCHAR2(1 BYTE),
  DEFAULT_PAYMENT_TYPE       VARCHAR2(30 BYTE),
  DEFAULT_CURRENCY           VARCHAR2(30 BYTE),
  RECEIPT_SOURCE_ID          NUMBER,
  RECEIPT_METHOD_ID          NUMBER,
  RECEIPT_CLASS_ID           NUMBER,
  ORACLE_RECEIPT_NUM         VARCHAR2(60 BYTE),
  ORACLE_BANK_ID             NUMBER,
  ORACLE_BANK_BRANCH_ID      NUMBER,
  ORACLE_BANK_ACCOUNT_ID     NUMBER,
  RECEIPT_BATCH_TYPE         VARCHAR2(60 BYTE),
  ORACLE_BATCH_ID            NUMBER,
  ORACLE_BATCH_NAME          VARCHAR2(60 BYTE),
  ORACLE_RECEIPT_ID          NUMBER,
  CUSTOMER_TRX_ID            NUMBER,
  BILL_TO_SITE_USE_ID        NUMBER,
  SET_OF_BOOKS_ID            NUMBER,
  RECEIPT_WRITEOFF_ID        NUMBER,
  RECEIVABLE_APPLICATION_ID  NUMBER,
  INVOICE_BALANCE            NUMBER,
  OPEN_RECEIPT_NUMBER        VARCHAR2(60 BYTE),
  GRANDCUSTNO                VARCHAR2(60 BYTE),
  GRAND_CUSTOMER_ID          NUMBER,
  GRAND_BILLTO_SITE_USE_ID   NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAR_B2B_CASHAPP_U1  (Index) 
--
--  Dependencies: 
--   XXDOAR_B2B_CASHAPP_STG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOAR_B2B_CASHAPP_U1 ON XXDO.XXDOAR_B2B_CASHAPP_STG
(ORACLERECORDID, ORACLEREQUESTID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_B2B_CASHAPP_N1  (Index) 
--
--  Dependencies: 
--   XXDOAR_B2B_CASHAPP_STG (Table)
--
CREATE INDEX XXDO.XXDOAR_B2B_CASHAPP_N1 ON XXDO.XXDOAR_B2B_CASHAPP_STG
(ORACLEPROCESSFLAG)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_B2B_CASHAPP_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_B2B_CASHAPP_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAR_B2B_CASHAPP_STG FOR XXDO.XXDOAR_B2B_CASHAPP_STG
/
