--
-- XXDO_BK_BSA_ERRORS  (Table) 
--
CREATE TABLE XXDO.XXDO_BK_BSA_ERRORS
(
  ERROR_NUM       NUMBER,
  PACKAGE_NAME    VARCHAR2(150 BYTE),
  PROCEDURE_NAME  VARCHAR2(150 BYTE),
  CREATION_DATE   DATE                          DEFAULT SYSDATE,
  ERROR_MESSAGE   VARCHAR2(4000 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_BK_BSA_ERRORS TO APPS
/
