--
-- XXDO_ATR_INC  (Table) 
--
CREATE TABLE XXDO.XXDO_ATR_INC
(
  REFRESH_NUMBER     NUMBER,
  REFRESH_TIME       TIMESTAMP(6) WITH TIME ZONE,
  ORGANIZATION_ID    NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  ATR                NUMBER
)
NOCOMPRESS 
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            BUFFER_POOL      DEFAULT
           )
NOLOGGING
PARTITION BY HASH (ORGANIZATION_ID)
(  
  PARTITION P1
    TABLESPACE CUSTOM_TX_TS
)
NOCACHE
PARALLEL ( DEGREE 3 INSTANCES 2 )
/


--
-- XXDO_ATR_INC_N1  (Index) 
--
--  Dependencies: 
--   XXDO_ATR_INC (Table)
--
CREATE INDEX XXDO.XXDO_ATR_INC_N1 ON XXDO.XXDO_ATR_INC
(ORGANIZATION_ID, INVENTORY_ITEM_ID)
  TABLESPACE APPS_TS_TX_IDX
  PCTFREE    10
  INITRANS   2
  MAXTRANS   255
  STORAGE    (
              BUFFER_POOL      DEFAULT
             )
NOLOGGING
LOCAL (  
  PARTITION P1
    TABLESPACE APPS_TS_TX_IDX
)
PARALLEL ( DEGREE 3 INSTANCES 2 )
/
