--
-- XXD_EXP_CIP_TRANSFER  (Table) 
--
CREATE TABLE XXDO.XXD_EXP_CIP_TRANSFER
(
  TRANSFER_ID              NUMBER(15),
  TRANSFER_REF_NO          VARCHAR2(30 BYTE),
  TRANSFER_BY              VARCHAR2(15 BYTE),
  STATUS                   VARCHAR2(15 BYTE),
  ORIG_EXP_ITEM_ID         NUMBER(15),
  FROM_PROJECT_ID          NUMBER(15),
  FROM_TASK_ID             NUMBER(15),
  TO_PROJECT_ID            NUMBER(15),
  TO_TASK_ID               NUMBER(15),
  TO_EXPENDITURE_DATE      DATE,
  TO_EXPENDITURE_TYPE      VARCHAR2(30 BYTE),
  TO_ORG_ID                NUMBER(15),
  AMT_TO_TRANSFER_SRC_CUR  NUMBER,
  TO_CURRENCY              VARCHAR2(15 BYTE),
  AMT_TO_TRANSFER_TO_CUR   NUMBER,
  CAPITALIZABLE_FLAG       VARCHAR2(1 BYTE),
  ERROR_STAGE              VARCHAR2(30 BYTE),
  ERROR_MESSAGE            VARCHAR2(100 BYTE),
  COMMENTS                 VARCHAR2(100 BYTE),
  COL1                     VARCHAR2(100 BYTE),
  COL2                     VARCHAR2(100 BYTE),
  TO_EXPENDITURE_ORG_ID    NUMBER,
  TO_EXPENDITURE_ORG       VARCHAR2(240 BYTE),
  SRC_CURRENCY             VARCHAR2(15 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_EXP_CIP_TRANSFER  (Synonym) 
--
--  Dependencies: 
--   XXD_EXP_CIP_TRANSFER (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_EXP_CIP_TRANSFER FOR XXDO.XXD_EXP_CIP_TRANSFER
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_EXP_CIP_TRANSFER TO APPS
/
