--
-- XXDO_GL_REVAL_UPD_DETAILS  (Table) 
--
CREATE TABLE XXDO.XXDO_GL_REVAL_UPD_DETAILS
(
  REVALUATION_ID              NUMBER,
  OLD_REVALUATION             VARCHAR2(50 BYTE),
  NEW_REVALUATION             VARCHAR2(50 BYTE),
  OLD_DESCRIPTION             VARCHAR2(100 BYTE),
  NEW_DESCRIPTION             VARCHAR2(100 BYTE),
  OLD_AUTOPOST_REVALUATION    VARCHAR2(50 BYTE),
  NEW_AUTOPOST_REVALUATION    VARCHAR2(50 BYTE),
  OLD_ENABLE_SECURITY         VARCHAR2(50 BYTE),
  NEW_ENABLE_SECURITY         VARCHAR2(50 BYTE),
  OLD_FROM_CURRENCY_OPTION    VARCHAR2(10 BYTE),
  NEW_FROM_CURRENCY_OPTION    VARCHAR2(10 BYTE),
  OLD_FROM_CURRENCY           VARCHAR2(10 BYTE),
  NEW_FROM_CURRENCY           VARCHAR2(10 BYTE),
  OLD_CONVERSION_RATE_OPTION  VARCHAR2(20 BYTE),
  NEW_CONVERSION_RATE_OPTION  VARCHAR2(20 BYTE),
  OLD_CONVERSION_RATE_TYPE    VARCHAR2(50 BYTE),
  NEW_CONVERSION_RATE_TYPE    VARCHAR2(50 BYTE),
  OLD_REVALUATION_RATE        VARCHAR2(50 BYTE),
  NEW_REVALUATION_RATE        VARCHAR2(50 BYTE),
  OLD_UNREALIZED_GAIN         VARCHAR2(50 BYTE),
  NEW_UNREALIZED_GAIN         VARCHAR2(50 BYTE),
  OLD_UNREALIZED_LOSS         VARCHAR2(50 BYTE),
  NEW_UNREALIZED_LOSS         VARCHAR2(50 BYTE),
  OLD_LAST_UPDATED_BY         VARCHAR2(50 BYTE),
  NEW_LAST_UPDATED_BY         VARCHAR2(50 BYTE),
  OLD_LAST_UPDATE_DATE        DATE,
  NEW_LAST_UPDATE_DATE        DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_GL_REVAL_UPD_DETAILS  (Synonym) 
--
--  Dependencies: 
--   XXDO_GL_REVAL_UPD_DETAILS (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_GL_REVAL_UPD_DETAILS FOR XXDO.XXDO_GL_REVAL_UPD_DETAILS
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_GL_REVAL_UPD_DETAILS TO APPS
/
