--
-- XXDO_INV_SYNC_SERIAL_STG_LOG  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_SYNC_SERIAL_STG_LOG
(
  WH_ID               VARCHAR2(10 BYTE)         NOT NULL,
  ITEM_NUMBER         VARCHAR2(30 BYTE)         NOT NULL,
  HOST_SUBINVENTORY   VARCHAR2(50 BYTE),
  SERIAL_NUMBER       VARCHAR2(30 BYTE)         NOT NULL,
  SERIAL_SEQ_ID       NUMBER,
  SNAPSHOT_DATETIME   DATE,
  WMS_QTY             FLOAT(126),
  UOM                 VARCHAR2(10 BYTE),
  CREATION_DATE       DATE                      NOT NULL,
  CREATED_BY          NUMBER                    NOT NULL,
  LAST_UPDATE_DATE    DATE                      NOT NULL,
  LAST_UPDATED_BY     NUMBER                    NOT NULL,
  LAST_UPDATE_LOGIN   NUMBER                    NOT NULL,
  PROCESS_STATUS      VARCHAR2(20 BYTE)         NOT NULL,
  ERROR_MESSAGE       VARCHAR2(1000 BYTE),
  REQUEST_ID          NUMBER                    NOT NULL,
  SOURCE_TYPE         VARCHAR2(20 BYTE),
  ATTRIBUTE1          VARCHAR2(50 BYTE),
  ATTRIBUTE2          VARCHAR2(50 BYTE),
  ATTRIBUTE3          VARCHAR2(50 BYTE),
  ATTRIBUTE4          VARCHAR2(50 BYTE),
  ATTRIBUTE5          VARCHAR2(50 BYTE),
  ATTRIBUTE6          VARCHAR2(50 BYTE),
  ATTRIBUTE7          VARCHAR2(50 BYTE),
  ATTRIBUTE8          VARCHAR2(50 BYTE),
  ATTRIBUTE9          VARCHAR2(50 BYTE),
  ATTRIBUTE10         VARCHAR2(50 BYTE),
  ATTRIBUTE11         VARCHAR2(50 BYTE),
  ATTRIBUTE12         VARCHAR2(50 BYTE),
  ATTRIBUTE13         VARCHAR2(50 BYTE),
  ATTRIBUTE14         VARCHAR2(50 BYTE),
  ATTRIBUTE15         VARCHAR2(50 BYTE),
  ATTRIBUTE16         VARCHAR2(50 BYTE),
  ATTRIBUTE17         VARCHAR2(50 BYTE),
  ATTRIBUTE18         VARCHAR2(50 BYTE),
  ATTRIBUTE19         VARCHAR2(50 BYTE),
  ATTRIBUTE20         VARCHAR2(50 BYTE),
  SOURCE              VARCHAR2(20 BYTE),
  DESTINATION         VARCHAR2(20 BYTE),
  RECORD_TYPE         VARCHAR2(20 BYTE),
  EBS_ONHAND_QTY      NUMBER,
  ORGANIZATION_ID     NUMBER,
  INVENTORY_ITEM_ID   NUMBER,
  RESULT              VARCHAR2(50 BYTE),
  EBS_SHIP_PEND_QTY   NUMBER,
  EBS_SHIP_ERR_QTY    NUMBER,
  EBS_RMA_PEND_QTY    NUMBER,
  EBS_RMA_ERR_QTY     NUMBER,
  EBS_ASN_PEND_QTY    NUMBER,
  EBS_ASN_ERR_QTY     NUMBER,
  EBS_ADJ_PEND_QTY    NUMBER,
  EBS_ADJ_ERR_QTY     NUMBER,
  EBS_HOST_PEND_QTY   NUMBER,
  EBS_HOST_ERR_QTY    NUMBER,
  LOCATOR_ID          NUMBER,
  SNAPSHOT_ID         NUMBER,
  RECORD_ID           NUMBER,
  LOCATOR             VARCHAR2(200 BYTE),
  ARCHIVE_DATE        DATE,
  ARCHIVE_REQUEST_ID  NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_SYNC_SERIAL_STG_LOG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_SYNC_SERIAL_STG_LOG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INV_SYNC_SERIAL_STG_LOG FOR XXDO.XXDO_INV_SYNC_SERIAL_STG_LOG
/
