--
-- XXDO_PLM_STAGING  (Table) 
--
CREATE TABLE XXDO.XXDO_PLM_STAGING
(
  RECORD_ID                  NUMBER             NOT NULL,
  STYLE                      VARCHAR2(2000 BYTE),
  COLORWAY                   VARCHAR2(2000 BYTE),
  SIZING                     VARCHAR2(2000 BYTE),
  STYLE_DESCRIPTION          VARCHAR2(2000 BYTE),
  COLOR_DESCRIPTION          VARCHAR2(2000 BYTE),
  BRAND                      VARCHAR2(2000 BYTE),
  PRODUCT_GROUP              VARCHAR2(2000 BYTE),
  DIVISION                   VARCHAR2(2000 BYTE),
  SUB_GROUP                  VARCHAR2(2000 BYTE),
  CURRENT_SEASON             VARCHAR2(2000 BYTE),
  UOM                        VARCHAR2(2000 BYTE),
  WHOLESALE_PRICE            NUMBER,
  RETAIL_PRICE               NUMBER,
  PROJECTED_COST             NUMBER,
  SOURCING_RULE              VARCHAR2(2000 BYTE),
  COUNTRY_OF_ORIGIN          VARCHAR2(2000 BYTE),
  TARIFF_CODE                VARCHAR2(2000 BYTE),
  REGION                     VARCHAR2(2000 BYTE),
  DATE_CREATED               DATE               DEFAULT sysdate,
  DATE_UPDATED               DATE,
  STATUS                     VARCHAR2(2000 BYTE),
  SMU                        VARCHAR2(2000 BYTE),
  BATCH_ID                   VARCHAR2(2000 BYTE),
  FREIGHT_COST               NUMBER,
  PLM_STATUS                 VARCHAR2(2000 BYTE),
  ROW_ID                     VARCHAR2(2000 BYTE),
  SOURCING_FACTORY           VARCHAR2(2000 BYTE),
  COLORWAY_STATUS            VARCHAR2(200 BYTE),
  COLORWAY_STATE             VARCHAR2(200 BYTE),
  CLASS                      VARCHAR2(2000 BYTE),
  COLOR_CODE                 VARCHAR2(2000 BYTE),
  STYLE_NO                   VARCHAR2(2000 BYTE),
  STYLE_NAME                 VARCHAR2(2000 BYTE),
  SUB_CLASS                  VARCHAR2(2000 BYTE),
  MASTER_STYLE               VARCHAR2(2000 BYTE),
  COLLECTION                 VARCHAR2(2000 BYTE),
  COLLECTION_STATUS          VARCHAR2(2000 BYTE),
  ITEM_TYPE                  VARCHAR2(2000 BYTE),
  INVENTORY_TYPE             VARCHAR2(2000 BYTE),
  UPC                        VARCHAR2(2000 BYTE),
  PURCHASE_COST              VARCHAR2(2000 BYTE),
  RANK                       VARCHAR2(2000 BYTE),
  INTRO_DATE                 VARCHAR2(2000 BYTE),
  LEAD_TIME                  VARCHAR2(2000 BYTE),
  LANDED_COST                VARCHAR2(2000 BYTE),
  PRODUCTION_LINE            VARCHAR2(2000 BYTE),
  CLASSIFICATION             VARCHAR2(2000 BYTE),
  SUPPLIER                   VARCHAR2(2000 BYTE),
  BEGIN_DATE                 VARCHAR2(2000 BYTE),
  END_DATE                   VARCHAR2(2000 BYTE),
  MAJOR_CATEGORY             VARCHAR2(2000 BYTE),
  MINOR_CATEGORY             VARCHAR2(2000 BYTE),
  PROJECT_TYPE               VARCHAR2(2000 BYTE),
  BENEFIT                    VARCHAR2(2000 BYTE),
  PLANNING_MATERIAL_1        VARCHAR2(2000 BYTE),
  PLANNING_MATERIAL_2        VARCHAR2(2000 BYTE),
  PLANNING_MATERIAL_3        VARCHAR2(2000 BYTE),
  FOOTWEAR_WIDTHS            VARCHAR2(2000 BYTE),
  PLM_FUNCTION               VARCHAR2(2000 BYTE),
  HEEL_HEIGHT                VARCHAR2(2000 BYTE),
  HEEL_TYPE                  VARCHAR2(2000 BYTE),
  LIFECYCLE                  VARCHAR2(2000 BYTE),
  PRIMARY_CONSTRUCTION       VARCHAR2(2000 BYTE),
  CUSTOMER_POSITIONING       VARCHAR2(2000 BYTE),
  MARKETING_INITIATIVES      VARCHAR2(2000 BYTE),
  PROJECTED_NO_OF_COLORWAYS  VARCHAR2(2000 BYTE),
  DETAIL_SILHOUETTE          VARCHAR2(2000 BYTE),
  SUB_DIVISION               VARCHAR2(2000 BYTE),
  ORACLE_STATUS              VARCHAR2(2000 BYTE) DEFAULT 'N',
  ITEM_ID                    NUMBER,
  RECORD_STATUS              VARCHAR2(200 BYTE),
  COST_TYPE                  VARCHAR2(100 BYTE),
  REQUEST_ID                 NUMBER,
  ORACLE_ERROR_MESSAGE       VARCHAR2(4000 BYTE),
  ATTRIBUTE1                 VARCHAR2(2000 BYTE),
  ATTRIBUTE2                 VARCHAR2(2000 BYTE),
  ATTRIBUTE3                 VARCHAR2(2000 BYTE),
  ATTRIBUTE4                 VARCHAR2(2000 BYTE),
  ATTRIBUTE5                 VARCHAR2(2000 BYTE),
  ATTRIBUTE6                 VARCHAR2(2000 BYTE),
  ATTRIBUTE7                 VARCHAR2(2000 BYTE),
  ATTRIBUTE8                 VARCHAR2(2000 BYTE),
  ATTRIBUTE9                 VARCHAR2(2000 BYTE),
  ATTRIBUTE10                VARCHAR2(2000 BYTE),
  PURCHASING_START_DATE      VARCHAR2(2000 BYTE),
  PURCHASING_END_DATE        VARCHAR2(2000 BYTE),
  COLORWAY_LIFECYCLE         VARCHAR2(2000 BYTE),
  TARIFF_COUNTRY_CODE        VARCHAR2(2000 BYTE),
  NRF_COLOR_CODE             VARCHAR2(2000 BYTE),
  NRF_DESCRIPTION            VARCHAR2(2000 BYTE),
  SUPPLEMENTAL LOG GROUP GGS_3155014 (RECORD_ID) ALWAYS,
  SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
  SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS,
  SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


ALTER TABLE XXDO.XXDO_PLM_STAGING ADD (
  PRIMARY KEY
  (RECORD_ID)
  USING INDEX
    TABLESPACE CUSTOM_TX_TS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE)
/


--  There is no statement for index XXDO.SYS_C00282920.
--  The object is created when the parent object is created.

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_STAGING TO APPS
/

GRANT SELECT ON XXDO.XXDO_PLM_STAGING TO APPSRO
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_STAGING TO SOA_INT
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXDO_PLM_STAGING TO XXDO_PLM
/
