--
-- XXD_DIR_LIST_TBL  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE XXDO.XXD_DIR_LIST_TBL
(
  FILENAME  VARCHAR2(240 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


--
-- XXD_DIR_LIST_TBL_SYN  (Synonym) 
--
--  Dependencies: 
--   XXD_DIR_LIST_TBL (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_DIR_LIST_TBL_SYN FOR XXDO.XXD_DIR_LIST_TBL
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXD_DIR_LIST_TBL TO APPS
/
