--
-- XXD_PPM_CUSTOM_DATA_CURRENT_T  (Table) 
--
CREATE TABLE XXDO.XXD_PPM_CUSTOM_DATA_CURRENT_T
(
  PLANNING_CODE         VARCHAR2(10 BYTE)       NOT NULL,
  PPM_IDEA_ID           VARCHAR2(50 BYTE),
  PPM_IDEA_MOD_DATE     DATE,
  PPM_CAMPAIGN_ID       VARCHAR2(50 BYTE),
  PPM_CAMPAIGN_NAME     VARCHAR2(50 BYTE),
  PPM_PROP_ID           VARCHAR2(50 BYTE),
  PPM_PROP_CREATE_DT    DATE,
  SCORE1                NUMBER,
  SCORE2                NUMBER,
  GATE_0_DATE           DATE,
  GATE_1_DATE           DATE,
  GATE_2_DATE           DATE,
  GATE_3_DATE           DATE,
  GATE_4_DATE           DATE,
  GATE_5_DATE           DATE,
  GATE_6_DATE           DATE,
  PP_PCT_DONE_MILESTON  NUMBER,
  PP_PCT_DONE_CARDS     NUMBER,
  PP_PCT_DONE_ACTIVITY  NUMBER,
  PP_ACTIVITY_PCT_DONE  NUMBER,
  PP_TOTAL_BUDGET       NUMBER,
  PP_LINK               VARCHAR2(20 BYTE),
  T_EA_ALIGNMENT_SCORE  VARCHAR2(100 BYTE),
  T_CAP_IMPORTANCE      NUMBER,
  JIRA_ISSUE_ID         VARCHAR2(20 BYTE),
  JIRA_PRIORITY         VARCHAR2(50 BYTE),
  JIRA_FIX_VERSION      VARCHAR2(50 BYTE),
  ELT_SPONSOR           VARCHAR2(20 BYTE),
  BUSINESS_OWNER        VARCHAR2(40 BYTE),
  DECK_TASK_OWNER       VARCHAR2(50 BYTE),
  DECK_STATUS_START     DATE,
  DECK_STATUS_END       DATE,
  DECK_PROJECT_SPONSOR  VARCHAR2(40 BYTE),
  DECK_PRODUCT_OWNER    VARCHAR2(40 BYTE),
  DECK_REQUEST_BY       VARCHAR2(50 BYTE),
  DECK_PRJ_TIME_COMP    DATE,
  DECK_ACT_TIME_COMP    DATE,
  DECK_PRJ_TOT_COST     NUMBER,
  DECK_ACT_TOT_COST     NUMBER,
  DECK_VALUE_OWNER      VARCHAR2(50 BYTE),
  DECK_IDORACLE         VARCHAR2(10 BYTE),
  DECK_BENEFIT_DATE     VARCHAR2(10 BYTE),
  DECK_TOTAL_HRS        VARCHAR2(10 BYTE),
  LK_SYNC_WORK          VARCHAR2(1 BYTE),
  LK_SYNC_CHILDREN      VARCHAR2(1 BYTE),
  LK_PRIORITY           VARCHAR2(50 BYTE),
  LK_TOP_LANE           VARCHAR2(255 BYTE),
  LK_LANE_CLASS         VARCHAR2(50 BYTE),
  LK_CARD_TYPE          VARCHAR2(64 BYTE),
  LK_PLANNED_START      DATE,
  LK_PLANNED_FINISH     DATE,
  LK_ACTUAL_START       DATE,
  LK_ACTUAL_FINISH      DATE,
  LK_IS_BLOCKED         VARCHAR2(50 BYTE),
  LK_CRDS_TOTAL         NUMBER,
  LK_CRDS_COMPLETE      NUMBER,
  LK_CRDS_PCT_CMPLT     NUMBER,
  LK_CRDS_IN_PROGRESS   NUMBER,
  LK_CRDS_NOT_STARTED   NUMBER,
  LK_CRDS_BLOCKED       NUMBER,
  LK_CRDS_MISSED_START  NUMBER,
  LK_CRDS_MISSED_FIN    NUMBER,
  LK_EARLIEST_PLN_STRT  DATE,
  LK_LATEST_PLN_FINISH  DATE,
  LK_EARLIEST_ACT_STRT  DATE,
  LK_LATEST_ACT_FINISH  DATE,
  LK_CRDS_EXCEPTIONS    NUMBER,
  LK_CRDS_EXCEPT_PCT    NUMBER,
  LK_CARD_LINK_URL      VARCHAR2(4000 BYTE),
  LK_CARD_LINK_TXT      VARCHAR2(100 BYTE),
  LK_PRJCTD_FIN_DATE    DATE,
  LK_CARD_SIZE          NUMBER,
  PP_CNT_CARDS_OPEN     NUMBER,
  PP_CNT_CARDS_CMPLT    NUMBER,
  PP_COMPLETION_DATE    DATE,
  PP_BOARD_LINK_URL     VARCHAR2(4000 BYTE),
  PP_BOARD_LINK_TXT     VARCHAR2(100 BYTE),
  DECK_QTR_START        VARCHAR2(10 BYTE),
  DECK_QTR_FINISH       VARCHAR2(10 BYTE),
  DECK_FISCAL_YR        VARCHAR2(15 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/
