--
-- XXDO_INVVAL_DUTY_COST  (Table) 
--
CREATE TABLE XXDO.XXDO_INVVAL_DUTY_COST
(
  OPERATING_UNIT     NUMBER,
  COUNTRY_OF_ORIGIN  VARCHAR2(150 BYTE),
  PRIMARY_DUTY_FLAG  VARCHAR2(1 BYTE),
  OH_DUTY            NUMBER,
  OH_NONDUTY         NUMBER,
  ADDITIONAL_DUTY    NUMBER,
  INVENTORY_ORG      NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  DUTY               NUMBER,
  DUTY_START_DATE    DATE,
  DUTY_END_DATE      DATE,
  STYLE_COLOR        VARCHAR2(150 BYTE),
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    VARCHAR2(150 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  FREIGHT            NUMBER,
  FREIGHT_DUTY       NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INVVAL_DUTY_COST_N1  (Index) 
--
--  Dependencies: 
--   XXDO_INVVAL_DUTY_COST (Table)
--
CREATE INDEX XXDO.XXDO_INVVAL_DUTY_COST_N1 ON XXDO.XXDO_INVVAL_DUTY_COST
(DUTY_END_DATE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_INVVAL_DUTY_COST_N2  (Index) 
--
--  Dependencies: 
--   XXDO_INVVAL_DUTY_COST (Table)
--
CREATE INDEX XXDO.XXDO_INVVAL_DUTY_COST_N2 ON XXDO.XXDO_INVVAL_DUTY_COST
(INVENTORY_ITEM_ID, INVENTORY_ORG)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_INVVAL_DUTY_COST  (Synonym) 
--
--  Dependencies: 
--   XXDO_INVVAL_DUTY_COST (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INVVAL_DUTY_COST FOR XXDO.XXDO_INVVAL_DUTY_COST
/


--
-- XXDO_INVVAL_DUTY_COST  (Synonym) 
--
--  Dependencies: 
--   XXDO_INVVAL_DUTY_COST (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDO_INVVAL_DUTY_COST FOR XXDO.XXDO_INVVAL_DUTY_COST
/
