--
-- XXD_PO_RCV_MASS_UPD_ASN_T  (Table) 
--
CREATE TABLE XXDO.XXD_PO_RCV_MASS_UPD_ASN_T
(
  BRAND                 VARCHAR2(30 BYTE),
  SHIP_TO_ORG_CODE      VARCHAR2(3 BYTE),
  INVOICE_NUM           VARCHAR2(25 BYTE),
  CONTAINER_NUM         VARCHAR2(35 BYTE),
  ASN_NUMBER            VARCHAR2(30 BYTE),
  EXP_RECEIPT_DATE      DATE,
  NEW_EXP_RECEIPT_DATE  DATE,
  SEQ_ID                NUMBER,
  STATUS                VARCHAR2(1 BYTE),
  ERROR_MESSAGE         VARCHAR2(4000 BYTE),
  REQUEST_ID            NUMBER,
  OPR_MODE              VARCHAR2(10 BYTE),
  CREATION_DATE         DATE,
  CREATED_BY            NUMBER,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATE_LOGIN     NUMBER,
  SOURCE_ORG_ID         NUMBER,
  DEST_ORG_ID           NUMBER,
  SHIPMENT_HEADER_ID    NUMBER,
  VENDOR_ID             NUMBER,
  VENDOR_SITE_ID        NUMBER,
  VENDOR_NAME           VARCHAR2(240 BYTE),
  VENDOR_SITE_CODE      VARCHAR2(15 BYTE),
  RECEIPT_SOURCE_CODE   VARCHAR2(25 BYTE),
  NUM_ATTRIBUTE1        NUMBER,
  NUM_ATTRIBUTE2        NUMBER,
  NUM_ATTRIBUTE3        NUMBER,
  NUM_ATTRIBUTE4        NUMBER,
  NUM_ATTRIBUTE5        NUMBER,
  CHR_ATTRIBUTE1        VARCHAR2(150 BYTE),
  CHR_ATTRIBUTE2        VARCHAR2(150 BYTE),
  CHR_ATTRIBUTE3        VARCHAR2(150 BYTE),
  CHR_ATTRIBUTE4        VARCHAR2(150 BYTE),
  CHR_ATTRIBUTE5        VARCHAR2(150 BYTE),
  DT_ATTRIBUTE1         DATE,
  DT_ATTRIBUTE2         DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- SEQ_PK  (Index) 
--
--  Dependencies: 
--   XXD_PO_RCV_MASS_UPD_ASN_T (Table)
--
CREATE UNIQUE INDEX XXDO.SEQ_PK ON XXDO.XXD_PO_RCV_MASS_UPD_ASN_T
(SEQ_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

ALTER TABLE XXDO.XXD_PO_RCV_MASS_UPD_ASN_T ADD (
  CONSTRAINT SEQ_PK
  PRIMARY KEY
  (SEQ_ID)
  USING INDEX XXDO.SEQ_PK
  ENABLE VALIDATE)
/


--
-- XXD_PO_RCV_MASS_UPD_ASN_N1  (Index) 
--
--  Dependencies: 
--   XXD_PO_RCV_MASS_UPD_ASN_T (Table)
--
CREATE INDEX XXDO.XXD_PO_RCV_MASS_UPD_ASN_N1 ON XXDO.XXD_PO_RCV_MASS_UPD_ASN_T
(ASN_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PO_RCV_MASS_UPD_ASN_N2  (Index) 
--
--  Dependencies: 
--   XXD_PO_RCV_MASS_UPD_ASN_T (Table)
--
CREATE INDEX XXDO.XXD_PO_RCV_MASS_UPD_ASN_N2 ON XXDO.XXD_PO_RCV_MASS_UPD_ASN_T
(SHIP_TO_ORG_CODE, ASN_NUMBER)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_PO_RCV_MASS_UPD_ASN_T  (Synonym) 
--
--  Dependencies: 
--   XXD_PO_RCV_MASS_UPD_ASN_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_PO_RCV_MASS_UPD_ASN_T FOR XXDO.XXD_PO_RCV_MASS_UPD_ASN_T
/
