--
-- XXDO_INV_CONV_ONHAND_STG  (Table) 
--
CREATE TABLE XXDO.XXDO_INV_CONV_ONHAND_STG
(
  SOURCE_ORGANIZATION       VARCHAR2(30 BYTE),
  SOURCE_ORG_ID             NUMBER,
  SOURCE_SUBINVENTORY       VARCHAR2(30 BYTE),
  SOURCE_LOCATOR            VARCHAR2(30 BYTE),
  DESTINATION_ORGANIZATION  VARCHAR2(30 BYTE),
  DESTINATION_ORG_ID        NUMBER,
  DESTINATION_SUBINVENTORY  VARCHAR2(30 BYTE),
  ITEM_NUMBER               VARCHAR2(150 BYTE),
  INVENTORY_ITEM_ID         NUMBER,
  ITEM_DESCRIPTION          VARCHAR2(150 BYTE),
  UOM                       VARCHAR2(30 BYTE),
  ITEM_UNIT_COST            NUMBER,
  LPN                       VARCHAR2(150 BYTE),
  PALLET_LPN                VARCHAR2(150 BYTE),
  QUANTITY                  NUMBER,
  BRAND                     VARCHAR2(40 BYTE),
  CREATION_DATE             DATE,
  CREATED_BY                NUMBER,
  LAST_UPDATE_DATE          DATE,
  LAST_UPDATED_BY           NUMBER,
  REQUEST_ID                NUMBER,
  ATTRIBUTE1                VARCHAR2(150 BYTE),
  ATTRIBUTE2                VARCHAR2(150 BYTE),
  ATTRIBUTE3                VARCHAR2(150 BYTE),
  ATTRIBUTE4                VARCHAR2(150 BYTE),
  ATTRIBUTE5                VARCHAR2(150 BYTE),
  ATTRIBUTE6                VARCHAR2(150 BYTE),
  ATTRIBUTE7                VARCHAR2(150 BYTE),
  ATTRIBUTE8                VARCHAR2(150 BYTE),
  ATTRIBUTE9                VARCHAR2(150 BYTE),
  ATTRIBUTE10               VARCHAR2(150 BYTE),
  ATTRIBUTE11               VARCHAR2(150 BYTE),
  ATTRIBUTE12               VARCHAR2(150 BYTE),
  ATTRIBUTE13               VARCHAR2(150 BYTE),
  ATTRIBUTE14               VARCHAR2(150 BYTE),
  ATTRIBUTE15               VARCHAR2(150 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_INV_CONV_ONHAND_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_CONV_ONHAND_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_INV_CONV_ONHAND_STG FOR XXDO.XXDO_INV_CONV_ONHAND_STG
/


--
-- XXDO_INV_CONV_ONHAND_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_INV_CONV_ONHAND_STG (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDO_INV_CONV_ONHAND_STG FOR XXDO.XXDO_INV_CONV_ONHAND_STG
/
