--
-- XXDOAR_B2B_BILLING_LIN_STG  (Table) 
--
CREATE TABLE XXDO.XXDOAR_B2B_BILLING_LIN_STG
(
  CONCURRENT_REQUEST_ID     NUMBER,
  CUSTOMER_TRX_ID           NUMBER,
  CUSTOMER_TRX_LINE_ID      NUMBER,
  LINE_DESCRIPTION          VARCHAR2(240 BYTE),
  ITEM_STYLE                VARCHAR2(60 BYTE),
  ITEM_COLOR                VARCHAR2(60 BYTE),
  STYLE_DESCRIPTION         VARCHAR2(120 BYTE),
  COLOR_DESCRIPTION         VARCHAR2(120 BYTE),
  ITEM_SIZE                 VARCHAR2(60 BYTE),
  QUANTITY                  NUMBER,
  PRICE                     NUMBER,
  DISCOUNT_PERCENT          NUMBER,
  LINE_AMOUNT               NUMBER,
  TAX_CODE                  VARCHAR2(30 BYTE),
  STATE_TAX                 NUMBER,
  PARISH_TAX                NUMBER,
  COUNTY_TAX                NUMBER,
  TRANSIT_DISTRICT_TAX      NUMBER,
  US_SALES_TAX_101          NUMBER,
  SPECIAL_PURPOSE_DIST_TAX  NUMBER,
  TERRITORY_TAX             NUMBER,
  COUNTRY_TAX               NUMBER,
  GST_AMOUNT                NUMBER,
  HST_AMOUNT                NUMBER,
  QST_AMOUNT                NUMBER,
  PST_AMOUNT                NUMBER,
  TAX_EXEMPT_LINE_AMT       NUMBER,
  NON_TAX_EXT_LINE_AMT      NUMBER,
  LINE_PLACEHOLDER1         VARCHAR2(2000 BYTE),
  LINE_PLACEHOLDER2         VARCHAR2(2000 BYTE),
  LINE_PLACEHOLDER3         VARCHAR2(2000 BYTE),
  LINE_PLACEHOLDER4         VARCHAR2(2000 BYTE),
  LINE_PLACEHOLDER5         VARCHAR2(2000 BYTE),
  CITY_TAX                  NUMBER,
  DISTRICT_TAX              NUMBER,
  SELLING_PRICE             NUMBER,
  COUNTRY_OF_ORIGIN         VARCHAR2(60 BYTE),
  ITEM_CODE                 VARCHAR2(60 BYTE),
  TAX_AMOUNT                NUMBER
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOAR_B2B_BILLING_LIN_U1  (Index) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_LIN_STG (Table)
--
CREATE UNIQUE INDEX XXDO.XXDOAR_B2B_BILLING_LIN_U1 ON XXDO.XXDOAR_B2B_BILLING_LIN_STG
(CONCURRENT_REQUEST_ID, CUSTOMER_TRX_ID, CUSTOMER_TRX_LINE_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOAR_B2B_BILLING_LIN_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_LIN_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOAR_B2B_BILLING_LIN_STG FOR XXDO.XXDOAR_B2B_BILLING_LIN_STG
/


--
-- XXDOAR_B2B_BILLING_LIN_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOAR_B2B_BILLING_LIN_STG (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDOAR_B2B_BILLING_LIN_STG FOR XXDO.XXDOAR_B2B_BILLING_LIN_STG
/
