--
-- XXD_INV_PLM_SIZE_DEFINITIONS_T  (Table) 
--
CREATE TABLE XXDO.XXD_INV_PLM_SIZE_DEFINITIONS_T
(
  SIZE_CHART_CODE    NUMBER,
  SIZE_CHART_DESC    VARCHAR2(250 BYTE),
  SIZE_CHART_VALUES  VARCHAR2(250 BYTE),
  CREATION_DATE      DATE,
  CREATED_BY         NUMBER,
  LAST_UPDATE_DATE   DATE,
  LAST_UPDATED_BY    NUMBER,
  LAST_UPDATE_LOGIN  NUMBER,
  ENABLED_FLAG       VARCHAR2(1 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_INV_PLM_SIZE_CODE_IDX1  (Index) 
--
--  Dependencies: 
--   XXD_INV_PLM_SIZE_DEFINITIONS_T (Table)
--
CREATE INDEX XXDO.XXD_INV_PLM_SIZE_CODE_IDX1 ON XXDO.XXD_INV_PLM_SIZE_DEFINITIONS_T
(SIZE_CHART_CODE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_INV_PLM_SIZE_DEFINITIONS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_INV_PLM_SIZE_DEFINITIONS_T (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXD_INV_PLM_SIZE_DEFINITIONS_T FOR XXDO.XXD_INV_PLM_SIZE_DEFINITIONS_T
/


--
-- XXD_INV_PLM_SIZE_DEFINITIONS_T  (Synonym) 
--
--  Dependencies: 
--   XXD_INV_PLM_SIZE_DEFINITIONS_T (Table)
--
CREATE OR REPLACE SYNONYM SOA_INT.XXD_INV_PLM_SIZE_DEFINITIONS_T FOR XXDO.XXD_INV_PLM_SIZE_DEFINITIONS_T
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_INV_PLM_SIZE_DEFINITIONS_T TO SOA_INT
/
