--
-- XXDOEC_SFS_SHIPMENT_DTLS_STG  (Table) 
--
CREATE TABLE XXDO.XXDOEC_SFS_SHIPMENT_DTLS_STG
(
  SFS_SHIPMENT_ID      NUMBER,
  WEB_ORDER_NUMBER     VARCHAR2(30 BYTE),
  LINE_ID              NUMBER,
  ITEM_CODE            VARCHAR2(40 BYTE),
  STATUS               VARCHAR2(30 BYTE),
  STORE_NUMBER         VARCHAR2(30 BYTE),
  SHIPPED_DATE         DATE,
  SHIPPED_QUANTITY     NUMBER,
  UNIT_PRICE           NUMBER,
  SHIP_METHOD_CODE     VARCHAR2(30 BYTE),
  WAYBILL              VARCHAR2(120 BYTE),
  TRACKING_NUMBER      VARCHAR2(120 BYTE),
  PROCESS_FLAG         VARCHAR2(1 BYTE),
  ERROR_MESSAGE        VARCHAR2(2000 BYTE),
  PO_LINE_LOCATION_ID  NUMBER,
  CREATION_DATE        DATE,
  LAST_UPDATE_DATE     DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDOEC_SFS_SHIPMENT_DTLS_U1  (Index) 
--
--  Dependencies: 
--   XXDOEC_SFS_SHIPMENT_DTLS_STG (Table)
--
CREATE UNIQUE INDEX APPS.XXDOEC_SFS_SHIPMENT_DTLS_U1 ON XXDO.XXDOEC_SFS_SHIPMENT_DTLS_STG
(SFS_SHIPMENT_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_SFS_SHIPMENT_DTLS_N1  (Index) 
--
--  Dependencies: 
--   XXDOEC_SFS_SHIPMENT_DTLS_STG (Table)
--
CREATE INDEX APPS.XXDOEC_SFS_SHIPMENT_DTLS_N1 ON XXDO.XXDOEC_SFS_SHIPMENT_DTLS_STG
(LINE_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_SFS_SHIPMENT_DTLS_N2  (Index) 
--
--  Dependencies: 
--   XXDOEC_SFS_SHIPMENT_DTLS_STG (Table)
--
CREATE INDEX APPS.XXDOEC_SFS_SHIPMENT_DTLS_N2 ON XXDO.XXDOEC_SFS_SHIPMENT_DTLS_STG
(PROCESS_FLAG)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDOEC_SFS_SHIPMENT_DTLS_STG  (Synonym) 
--
--  Dependencies: 
--   XXDOEC_SFS_SHIPMENT_DTLS_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDOEC_SFS_SHIPMENT_DTLS_STG FOR XXDO.XXDOEC_SFS_SHIPMENT_DTLS_STG
/
