--
-- XXD_GL_ACCOUNT_BALANCE_T  (Table) 
--
CREATE TABLE XXDO.XXD_GL_ACCOUNT_BALANCE_T
(
  REQUEST_ID                NUMBER,
  FILE_NAME                 VARCHAR2(240 BYTE),
  ENTITY_UNIQUE_IDENTIFIER  VARCHAR2(240 BYTE),
  ACCOUNT_NUMBER            VARCHAR2(240 BYTE),
  BRAND                     VARCHAR2(240 BYTE),
  GEO                       VARCHAR2(240 BYTE),
  CHANNEL                   VARCHAR2(240 BYTE),
  COSTCENTER                VARCHAR2(240 BYTE),
  INTERCOMPANY              VARCHAR2(240 BYTE),
  STATUARY_LEDGER           VARCHAR2(240 BYTE),
  KEY9                      VARCHAR2(240 BYTE),
  KEY10                     VARCHAR2(240 BYTE),
  ACCOUNT_DESC              VARCHAR2(240 BYTE),
  ACCOUNT_REFERENCE1        VARCHAR2(240 BYTE),
  FINANCIAL_STATEMENT       VARCHAR2(240 BYTE),
  ACCOUNT_TYPE              VARCHAR2(240 BYTE),
  ACITVE_ACCOUNT            VARCHAR2(240 BYTE),
  ACTIVITY_IN_PERIOD        VARCHAR2(240 BYTE),
  ALT_CURRENCY              VARCHAR2(240 BYTE),
  ACCOUNT_CURRENCY          VARCHAR2(240 BYTE),
  PERIOD_END_DATE           VARCHAR2(240 BYTE),
  GL_REPORTING_BALANCE      VARCHAR2(240 BYTE),
  GL_ALT_BALANCE            VARCHAR2(240 BYTE),
  GL_ACCOUNT_BALANCE        VARCHAR2(240 BYTE),
  ACCOUNT_REFERENCE_2       VARCHAR2(240 BYTE),
  ACCOUNT_REFERENCE_3       VARCHAR2(240 BYTE),
  ACCOUNT_REFERENCE_4       VARCHAR2(240 BYTE),
  ACCOUNT_REFERENCE_5       VARCHAR2(240 BYTE),
  ACCOUNT_REFERENCE_6       VARCHAR2(240 BYTE),
  ATTRIBUTE1                VARCHAR2(240 BYTE),
  ATTRIBUTE2                VARCHAR2(240 BYTE),
  ATTRIBUTE3                VARCHAR2(240 BYTE),
  ATTRIBUTE4                VARCHAR2(240 BYTE),
  ATTRIBUTE5                VARCHAR2(240 BYTE),
  ATTRIBUTE6                VARCHAR2(240 BYTE),
  ATTRIBUTE7                VARCHAR2(240 BYTE),
  ATTRIBUTE8                VARCHAR2(240 BYTE),
  ATTRIBUTE9                VARCHAR2(240 BYTE),
  ATTRIBUTE10               VARCHAR2(240 BYTE),
  CREATED_BY                NUMBER,
  CREATION_DATE             DATE,
  CODE_COMBINATION_ID       NUMBER,
  STAT_LEDGER_FLAG          VARCHAR2(100 BYTE)
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_ACC_BAL_CC_IDX  (Index) 
--
--  Dependencies: 
--   XXD_GL_ACCOUNT_BALANCE_T (Table)
--
CREATE INDEX XXDO.XXD_ACC_BAL_CC_IDX ON XXDO.XXD_GL_ACCOUNT_BALANCE_T
(CODE_COMBINATION_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXD_ACC_BAL_PD_IDX  (Index) 
--
--  Dependencies: 
--   XXD_GL_ACCOUNT_BALANCE_T (Table)
--
CREATE INDEX XXDO.XXD_ACC_BAL_PD_IDX ON XXDO.XXD_GL_ACCOUNT_BALANCE_T
(PERIOD_END_DATE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON XXDO.XXD_GL_ACCOUNT_BALANCE_T TO APPS
/
