--
-- XXD_VT_CONSOLIDATED_EXT_T  (Table) 
--
CREATE TABLE XXDO.XXD_VT_CONSOLIDATED_EXT_T
(
  VT_SOURCE                     VARCHAR2(50 BYTE),
  INVOICE_NUMBER                VARCHAR2(100 BYTE),
  VT_TRANSACTION_REF            VARCHAR2(100 BYTE),
  ORACLE_REF                    VARCHAR2(100 BYTE),
  SOLD_BY_OU_CODE               VARCHAR2(250 BYTE),
  SOLD_TO_OU_CODE               VARCHAR2(250 BYTE),
  VAT_SELLER                    VARCHAR2(250 BYTE),
  VAT_BUYER                     VARCHAR2(250 BYTE),
  ORDER_TYPE_USER_CATEGORY      VARCHAR2(100 BYTE),
  CUSTOMER_VENDOR_NUMBER        VARCHAR2(50 BYTE),
  CUSTOMER_VENDOR_NAME          VARCHAR2(250 BYTE),
  INVOICE_DATE                  DATE,
  LINE_NUMBER                   NUMBER,
  INVENTORY_ITEM_ID             NUMBER,
  ORDERED_ITEM                  VARCHAR2(250 BYTE),
  VT_TRANSACTION_DATE           DATE,
  VT_TRANSACTION_ID             NUMBER,
  ACTUAL_COST                   NUMBER,
  BILL_TO_ADDRESS_LINE1         VARCHAR2(240 BYTE),
  BILL_TO_ADDRESS_LINE2         VARCHAR2(240 BYTE),
  BILL_TO_CITY                  VARCHAR2(60 BYTE),
  BILL_TO_STATE                 VARCHAR2(60 BYTE),
  BILL_TO_COUNTRY               VARCHAR2(60 BYTE),
  BILL_TO_ADDRESS_KEY           VARCHAR2(500 BYTE),
  SHIP_TO_ADDRESS_LINE1         VARCHAR2(240 BYTE),
  SHIP_TO_ADDRESS_LINE2         VARCHAR2(240 BYTE),
  SHIP_TO_CITY                  VARCHAR2(60 BYTE),
  SHIP_TO_STATE                 VARCHAR2(60 BYTE),
  SHIP_TO_COUNTRY               VARCHAR2(60 BYTE),
  SHIP_TO_ADDRESS_KEY           VARCHAR2(500 BYTE),
  WAREHOUSE_NAME                VARCHAR2(240 BYTE),
  IC_UNIT_PRICE                 NUMBER,
  QUANTITY                      NUMBER,
  IC_CURRENCY_CODE              VARCHAR2(15 BYTE),
  SELLER_VAT_CODE               VARCHAR2(100 BYTE),
  SELLER_VAT_ACCOUNT_CODE       VARCHAR2(500 BYTE),
  SELLER_VAT_RATE               VARCHAR2(100 BYTE),
  BUYER_VAT_CODE                VARCHAR2(100 BYTE),
  BUYER_VAT_ACCCOUNT_CODE       VARCHAR2(500 BYTE),
  BUYER_VAT_RATE                VARCHAR2(100 BYTE),
  REV_BUYER_PAY_VAT_RATE        VARCHAR2(100 BYTE),
  REV_BUYER_REC_VAT_ACCT_CODE   VARCHAR2(500 BYTE),
  REV_BUYER_REC_VAT_RATE        VARCHAR2(100 BYTE),
  INVOICE_TOTAL_GBP             NUMBER,
  SELLER_OUTPUT_VAT_AMOUNT_GBP  NUMBER,
  BUYER_INPUT_VAT_AMOUNT_GBP    NUMBER,
  BUYER_OUTPUT_VAT_AMOUNT_GBP   NUMBER,
  INVOICE_TOTAL_EUR             NUMBER,
  SELLER_OUTPUT_VAT_AMOUNT_EUR  NUMBER,
  BUYER_INPUT_VAT_AMOUNT_EUR    NUMBER,
  BUYER_OUTPUT_VAT_AMOUNT_EUR   NUMBER,
  INVOICE_TOTAL_USD             NUMBER,
  SELLER_OUTPUT_VAT_AMOUNT_USD  NUMBER,
  BUYER_INPUT_VAT_AMOUNT_USD    NUMBER,
  BUYER_OUTPUT_VAT_AMOUNT_USD   NUMBER,
  SHIPMENT_LANDED_COST_GBP      NUMBER,
  SHIPMENT_LANDED_COST_EUR      NUMBER,
  SHIPMENT_LANDED_COST_USD      NUMBER,
  COMMODITY_CODE                VARCHAR2(50 BYTE),
  UNIT_WEIGHT                   NUMBER,
  STYLE                         VARCHAR2(150 BYTE),
  COLOR                         VARCHAR2(150 BYTE),
  PRODUCT_GROUP                 VARCHAR2(40 BYTE),
  GENDER                        VARCHAR2(40 BYTE),
  SHIP_TO_ZIP                   VARCHAR2(60 BYTE),
  SELLER_REVENUE_ACCOUNT        VARCHAR2(500 BYTE),
  BUYER_EXPENSE_ACCOUNT         VARCHAR2(500 BYTE),
  NUM_ATTRIBUTE1                NUMBER,
  NUM_ATTRIBUTE2                NUMBER,
  CHAR_ATTRIBUTE1               VARCHAR2(250 BYTE),
  CHAR_ATTRIBUTE2               VARCHAR2(250 BYTE),
  DATE_ATTRIBUTE1               DATE,
  CREATION_DATE                 DATE,
  CREATED_BY                    NUMBER,
  LAST_UPDATE_DATE              DATE,
  LAST_UPDATED_BY               NUMBER,
  REQUEST_ID                    NUMBER,
  INVOICE_TOTAL                 NUMBER,
  SELLER_OUTPUT_VAT_AMOUNT      NUMBER,
  BUYER_INPUT_VAT_AMOUNT        NUMBER,
  BUYER_OUTPUT_VAT_AMOUNT       NUMBER,
  SOLD_TO_ORG_ID                NUMBER,
  INVOICE_TO_ORG_ID             NUMBER,
  SHIP_TO_ORG_ID                NUMBER,
  SHIPMENT_LANDED_COST          NUMBER,
  ACCOUNTING_DATE               DATE
)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXD_VT_CONSOLIDATED_REQID_IDX  (Index) 
--
--  Dependencies: 
--   XXD_VT_CONSOLIDATED_EXT_T (Table)
--
CREATE INDEX XXDO.XXD_VT_CONSOLIDATED_REQID_IDX ON XXDO.XXD_VT_CONSOLIDATED_EXT_T
(REQUEST_ID, VT_SOURCE)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
