--
-- XXDO_007_SHIP_INT_STG  (Table) 
--
--  Dependencies: 
--   STANDARD (Package)
--   XMLTYPE (Type)
--
CREATE TABLE XXDO.XXDO_007_SHIP_INT_STG
(
  SEQ_NUMBER          NUMBER,
  TO_LOCATION_ID      NUMBER,
  FROM_LOCATION_ID    NUMBER,
  BOL_NBR             VARCHAR2(240 BYTE),
  SHIPMENT_DATE       VARCHAR2(240 BYTE),
  CONTAINER_QTY       NUMBER,
  SHIP_TO_ADDRESS1    VARCHAR2(240 BYTE),
  SHIP_TO_ADDRESS2    VARCHAR2(240 BYTE),
  SHIP_TO_ADDRESS3    VARCHAR2(240 BYTE),
  SHIP_TO_ADDRESS4    VARCHAR2(240 BYTE),
  CITY                VARCHAR2(240 BYTE),
  STATE               VARCHAR2(240 BYTE),
  POSTAL_CODE         NUMBER,
  COUNTRY             VARCHAR2(240 BYTE),
  ORDER_NUMBER        NUMBER,
  DISTRO_DOC_TYPE     VARCHAR2(10 BYTE),
  TRAILER_NBR         VARCHAR2(240 BYTE),
  CARRIER_NODE        VARCHAR2(240 BYTE),
  NET_WEIGHT          NUMBER,
  WEIGHT_UOM_CODE     VARCHAR2(240 BYTE),
  CUST_ORDER_NBR      VARCHAR2(240 BYTE),
  CONTAINER_ID        NUMBER,
  ITEM_ID             NUMBER,
  SHIPPED_QTY         NUMBER,
  ORDERED_QTY         NUMBER,
  NET_QTY             NUMBER,
  LINE_NUMBER         NUMBER,
  ORDER_SOURCE        VARCHAR2(240 BYTE),
  DELIVERY_ID         NUMBER,
  DELIVERY_NAME       VARCHAR2(240 BYTE),
  VIRTUAL_WAREHOUSE   VARCHAR2(240 BYTE),
  STATUS              VARCHAR2(100 BYTE),
  PROCESSING_MESSAGE  VARCHAR2(240 BYTE),
  CREATED_BY          NUMBER,
  CREATION_DATE       DATE,
  LAST_UPDATE_BY      NUMBER,
  LAST_UPDATE_DATE    DATE,
  PROCESSED_FLAG      VARCHAR2(10 BYTE),
  TRANSMISSION_DATE   DATE,
  ERRORCODE           VARCHAR2(240 BYTE),
  XMLDATA             CLOB,
  RETVAL              CLOB,
  XMLDATA1            SYS.XMLTYPE,
  CONTAINER_NAME      VARCHAR2(200 BYTE),
  LPN_ID              VARCHAR2(100 BYTE),
  POST_CODE           VARCHAR2(100 BYTE),
  UNIT_COST           NUMBER
)
LOB (RETVAL) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
XMLTYPE XMLDATA1 STORE AS SECUREFILE BINARY XML (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          104K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
ALLOW NONSCHEMA
DISALLOW ANYSCHEMA
LOB (XMLDATA) STORE AS BASICFILE (
  TABLESPACE  CUSTOM_TX_TS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
  STORAGE    (
              INITIAL          64K
              NEXT             1M
              MINEXTENTS       1
              MAXEXTENTS       UNLIMITED
              PCTINCREASE      0
              BUFFER_POOL      DEFAULT
             ))
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
/


--
-- XXDO_007_SHIP_INT_IDX  (Index) 
--
--  Dependencies: 
--   XXDO_007_SHIP_INT_STG (Table)
--
CREATE INDEX XXDO.XXDO_007_SHIP_INT_IDX ON XXDO.XXDO_007_SHIP_INT_STG
(DELIVERY_NAME, STATUS, PROCESSED_FLAG)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_007_SHIP_INT_STG_IDX  (Index) 
--
--  Dependencies: 
--   XXDO_007_SHIP_INT_STG (Table)
--
CREATE INDEX XXDO.XXDO_007_SHIP_INT_STG_IDX ON XXDO.XXDO_007_SHIP_INT_STG
(DELIVERY_ID, ITEM_ID, LPN_ID)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/

--
-- XXDO_007_SHIP_INT_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_007_SHIP_INT_STG (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_007_SHIP_INT_STG FOR XXDO.XXDO_007_SHIP_INT_STG
/


--
-- XXDO_007_SHIP_INT_STG  (Synonym) 
--
--  Dependencies: 
--   XXDO_007_SHIP_INT_STG (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDO_007_SHIP_INT_STG FOR XXDO.XXDO_007_SHIP_INT_STG
/


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDO.XXDO_007_SHIP_INT_STG TO SOA_INT
/
