--
-- XXDO_DO_REP_CUST_DUP_PKG  (Package) 
--
--  Dependencies: 
--   DO_REP_CUST_ASSIGNMENT_TBLTYPE (Type)
--   STANDARD (Package)
--
/* Formatted on 4/26/2023 4:15:47 PM (QP5 v5.362) */
CREATE OR REPLACE PACKAGE APPS."XXDO_DO_REP_CUST_DUP_PKG"
IS
    PROCEDURE XXDO_DO_REP_CUST_DUP_ACT_REC (SALESREPROW DO_CUSTOM.DO_REP_CUST_ASSIGNMENT_TBLTYPE, STATUS OUT VARCHAR2, ERROR_MESSAGE OUT VARCHAR2);
END XXDO_DO_REP_CUST_DUP_PKG;
/
