--
-- XXD_WMS_LOCATOR_LOAD_X_PKG  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
/* Formatted on 4/26/2023 4:26:07 PM (QP5 v5.362) */
CREATE OR REPLACE PACKAGE APPS."XXD_WMS_LOCATOR_LOAD_X_PKG"
    AUTHID DEFINER
IS
    PROCEDURE LOAD_STAGING_TABLE (errbuf OUT VARCHAR2, retcode OUT NUMBER);
END XXD_WMS_LOCATOR_LOAD_X_PKG;
/
