--
-- XXD_WMS_LOCATOR_UTILS_X_PKG  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
/* Formatted on 4/26/2023 4:26:09 PM (QP5 v5.362) */
CREATE OR REPLACE PACKAGE APPS."XXD_WMS_LOCATOR_UTILS_X_PKG"
    AUTHID DEFINER
IS
    PROCEDURE CREATE_STOCK_LOCATORS (errbuf OUT VARCHAR2, retcode OUT NUMBER);
END XXD_WMS_LOCATOR_UTILS_X_PKG;
/
