--
-- XXD_WMS_GENERATE_LPN_PKG  (Package) 
--
--  Dependencies: 
--   STANDARD (Package)
--
/* Formatted on 4/26/2023 4:26:00 PM (QP5 v5.362) */
CREATE OR REPLACE PACKAGE APPS."XXD_WMS_GENERATE_LPN_PKG"
AS
    PROCEDURE CREATE_CASE_LPNS (errbuf OUT VARCHAR2, retcode OUT NUMBER);
END XXD_WMS_GENERATE_LPN_PKG;
/
