--
-- XXDO_RMS_ITEM_MASTER_MV  (Materialized View) 
--
--  Dependencies: 
--   V_20230114_1822 ()
--
CREATE MATERIALIZED VIEW XXDO.XXDO_RMS_ITEM_MASTER_MV 
    (ITEM,ITEM_NUMBER_TYPE,FORMAT_ID,PREFIX,ITEM_PARENT,
     ITEM_GRANDPARENT,PACK_IND,ITEM_LEVEL,TRAN_LEVEL,ITEM_AGGREGATE_IND,
     DIFF_1,DIFF_1_AGGREGATE_IND,DIFF_2,DIFF_2_AGGREGATE_IND,DIFF_3,
     DIFF_3_AGGREGATE_IND,DIFF_4,DIFF_4_AGGREGATE_IND,DEPT,CLASS,
     SUBCLASS,STATUS,ITEM_DESC,ITEM_DESC_SECONDARY,SHORT_DESC,
     DESC_UP,PRIMARY_REF_ITEM_IND,RETAIL_ZONE_GROUP_ID,COST_ZONE_GROUP_ID,STANDARD_UOM,
     UOM_CONV_FACTOR,PACKAGE_SIZE,PACKAGE_UOM,MERCHANDISE_IND,STORE_ORD_MULT,
     FORECAST_IND,ORIGINAL_RETAIL,MFG_REC_RETAIL,RETAIL_LABEL_TYPE,RETAIL_LABEL_VALUE,
     HANDLING_TEMP,HANDLING_SENSITIVITY,CATCH_WEIGHT_IND,WASTE_TYPE,WASTE_PCT,
     DEFAULT_WASTE_PCT,CONST_DIMEN_IND,SIMPLE_PACK_IND,CONTAINS_INNER_IND,SELLABLE_IND,
     ORDERABLE_IND,PACK_TYPE,ORDER_AS_TYPE,COMMENTS,ITEM_SERVICE_LEVEL,
     GIFT_WRAP_IND,SHIP_ALONE_IND,CREATE_DATETIME,LAST_UPDATE_ID,LAST_UPDATE_DATETIME,
     CHECK_UDA_IND,ITEM_XFORM_IND,INVENTORY_IND,ORDER_TYPE,SALE_TYPE,
     DEPOSIT_ITEM_TYPE,CONTAINER_ITEM,DEPOSIT_IN_PRICE_PER_UOM,AIP_CASE_TYPE,BANDED_ITEM_IND,
     CATCH_WEIGHT_TYPE,PERISHABLE_IND,SOH_INQUIRY_AT_PACK_IND,NOTIONAL_PACK_IND,CATCH_WEIGHT_UOM)
TABLESPACE CUSTOM_TX_TS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
NOLOGGING
NOCOMPRESS
BUILD IMMEDIATE
USING INDEX
            TABLESPACE CUSTOM_TX_TS
            PCTFREE    10
            INITRANS   2
            MAXTRANS   255
            STORAGE    (
                        INITIAL          64K
                        NEXT             1M
                        MINEXTENTS       1
                        MAXEXTENTS       UNLIMITED
                        PCTINCREASE      0
                        BUFFER_POOL      DEFAULT
                       )
REFRESH FORCE ON DEMAND
WITH PRIMARY KEY
EVALUATE USING EDITION V_20230114_1822
AS 
/* Formatted on 4/26/2023 4:09:44 PM (QP5 v5.362) */
SELECT ITEM, ITEM_NUMBER_TYPE, FORMAT_ID,
       PREFIX, ITEM_PARENT, ITEM_GRANDPARENT,
       PACK_IND, ITEM_LEVEL, TRAN_LEVEL,
       ITEM_AGGREGATE_IND, DIFF_1, DIFF_1_AGGREGATE_IND,
       DIFF_2, DIFF_2_AGGREGATE_IND, DIFF_3,
       DIFF_3_AGGREGATE_IND, DIFF_4, DIFF_4_AGGREGATE_IND,
       DEPT, CLASS, SUBCLASS,
       STATUS, ITEM_DESC, ITEM_DESC_SECONDARY,
       SHORT_DESC, DESC_UP, PRIMARY_REF_ITEM_IND,
       RETAIL_ZONE_GROUP_ID, COST_ZONE_GROUP_ID, STANDARD_UOM,
       UOM_CONV_FACTOR, PACKAGE_SIZE, PACKAGE_UOM,
       MERCHANDISE_IND, STORE_ORD_MULT, FORECAST_IND,
       ORIGINAL_RETAIL, MFG_REC_RETAIL, RETAIL_LABEL_TYPE,
       RETAIL_LABEL_VALUE, HANDLING_TEMP, HANDLING_SENSITIVITY,
       CATCH_WEIGHT_IND, WASTE_TYPE, WASTE_PCT,
       DEFAULT_WASTE_PCT, CONST_DIMEN_IND, SIMPLE_PACK_IND,
       CONTAINS_INNER_IND, SELLABLE_IND, ORDERABLE_IND,
       PACK_TYPE, ORDER_AS_TYPE, COMMENTS,
       ITEM_SERVICE_LEVEL, GIFT_WRAP_IND, SHIP_ALONE_IND,
       CREATE_DATETIME, LAST_UPDATE_ID, LAST_UPDATE_DATETIME,
       CHECK_UDA_IND, ITEM_XFORM_IND, INVENTORY_IND,
       ORDER_TYPE, SALE_TYPE, DEPOSIT_ITEM_TYPE,
       CONTAINER_ITEM, DEPOSIT_IN_PRICE_PER_UOM, AIP_CASE_TYPE,
       BANDED_ITEM_IND, CATCH_WEIGHT_TYPE, PERISHABLE_IND,
       SOH_INQUIRY_AT_PACK_IND, NOTIONAL_PACK_IND, CATCH_WEIGHT_UOM
  FROM item_master@XXDO_RETAIL_RMS
/


COMMENT ON MATERIALIZED VIEW XXDO.XXDO_RMS_ITEM_MASTER_MV IS 'snapshot table for snapshot XXDO.XXDO_RMS_ITEM_MASTER_MV'
/

--
-- XXDO_RMS_ITEM_MASTER_MV  (Synonym) 
--
--  Dependencies: 
--   XXDO_RMS_ITEM_MASTER_MV (Table)
--
CREATE OR REPLACE SYNONYM APPS.XXDO_RMS_ITEM_MASTER_MV FOR XXDO.XXDO_RMS_ITEM_MASTER_MV
/

--
-- XXDO_RMS_ITEM_MASTER_MV  (Synonym) 
--
--  Dependencies: 
--   XXDO_RMS_ITEM_MASTER_MV (Table)
--
CREATE OR REPLACE SYNONYM APPSRO.XXDO_RMS_ITEM_MASTER_MV FOR XXDO.XXDO_RMS_ITEM_MASTER_MV
/

--
-- PK_ITEM_MASTER  (Index) 
--
--  Dependencies: 
--   XXDO_RMS_ITEM_MASTER_MV (Table)
--   XXDO_RMS_ITEM_MASTER_MV (Materialized View)
--
CREATE UNIQUE INDEX XXDO.PK_ITEM_MASTER ON XXDO.XXDO_RMS_ITEM_MASTER_MV
(ITEM)
LOGGING
TABLESPACE CUSTOM_TX_TS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
/
